### ISSUE TITLE
How to handle Neovim busy state?

### ISSUE THREAD

**Issue by equalsraf** [equalsraf/neovim-qt#10]
I've just pushed support for busy_start and busy_stop GUI events, e.g. when Neovim blocks running a shell command the GUI knows about it. Currently it only changes the mouse cursor.

It might be useful to consider other things to do on busy_start:
1. Other types of visual feedback
2. Prevent user from sending keyboard input to Neovim, while it is busy (maybe not see next point)
3. (_hypothetical_) The user can cancel shell commands with ctrl-c, should we provide other means to send ctrl-c
4. how do we repaint the widget while busy? resize events wont be handled, etc (which takes us back to 1.)

**Comment by equalsraf** [comment]
Funny thing happened after I pushed this. I called `:terminal` and the mouse cursor turned into a busy cursor, which was not what I was expecting to happen.

![qtbug6](https://cloud.githubusercontent.com/assets/715238/7316670/d6aa4b06-ea70-11e4-9634-95ddc8893a1e.png)

So it turns out that `:terminal` calls busy_start, which makes some sense but doesn't look very good on the GUI.

**Comment by tarruda** [comment]
This is a hack I added because `:terminal` uses an artificial cursor. I guess we need a separate API notification to hide the cursor after all.

**Comment by YorickPeterse** [comment]
@equalsraf I noticed this as well when using `:term`. Is there any workaround/solution for this today? https://github.com/daa84/neovim-gtk does not suffer from this problem, suggesting there may be a solution to this problem. The only mention of `busy_start` in neovim-gtk that I could find lead to the commit that added support for it: https://github.com/daa84/neovim-gtk/commit/057fad0e8728612efb1bf6fa65e357bef5d3c4c8

**Comment by dboy591** [comment]
I don't know if this is helpful but:  With GuiMousehide set to 1 the busy cursor is hidden on any key press and if you move the cursor it appears again and is no longer in a busy state.  However when GuiMousehide is set to 0 the cursor stays busy even after a key press.

**Comment by jgehrig** [comment]
This behaves as-designed, `busy_start` and `busy_stop` work. The mouse cursor displays a pinwheel while busy. Resize appears to work in `:terminal` and `busy` modes.

As mentioned above, mouse hide (on by default) should cause the cursor to disappear when the user starts typing.

Please file a new bug if you have a suggestions for `:terminal` or `busy. Marking as closed.
