### ISSUE TITLE
Hyper_L inserts `v`

### ISSUE THREAD

**Issue by tastytea** [equalsraf/neovim-qt#1008]
I have bound my caps lock key to “Hyper_L” in my `.xmodmaprc` like this:

```
clear Lock
keysym Caps_Lock = Hyper_L
```

In insert-mode, it inserts `v` when i press it. There is no log message when i run neovim-qt from a terminal. I don't have this problem with other (Qt-)applications.

<details><summary>xev output</summary>

```
KeyPress event, serial 35, synthetic NO, window 0x6c00001,
    root 0x29f, subw 0x0, time 321666642, (197,-4), root:(829,427),
    state 0x0, keycode 66 (keysym 0xffed, Hyper_L), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyRelease event, serial 35, synthetic NO, window 0x6c00001,
    root 0x29f, subw 0x0, time 321666778, (197,-4), root:(829,427),
    state 0x40, keycode 66 (keysym 0xffed, Hyper_L), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False
```

</details>

neovim-qt version: NVIM-QT v0.2.17.0  
neovim version: 0.7.2  
Qt Version: 5.15.5  
OS: Gentoo Linux

**Comment by jgehrig** [comment]
Can you do a Debug build with the following lines un-commented:
https://github.com/equalsraf/neovim-qt/blob/7b230767dd04d921ca5c2c31ad46ffd00111aed2/src/gui/shell.cpp#L1367-L1370

The `QKeyEvent` is very helpful in resolving these types of input issues. Once we understand the event being sent by Qt, these issues are usually easy to correct.

**Comment by tastytea** [comment]
Here it is:

```
QKeyEvent ev: QKeyEvent(KeyPress, Key_Hyper_L)
   "v"
```

**Comment by jgehrig** [comment]
Interesting... I'm not very familiar with the `Hyper_L` key. Looks fixable though!

What is this key? What do we expect the behavior to be here?

**Comment by tastytea** [comment]
The Hyper key is a meta key like the Super/windows logo key. It is not present on normal keyboards, so no application uses it. That makes it perfect for controlling my window manager.

I expected that neovim-qt just ignores it. It looks like it is not mappable in nvim, but that might be a limitation of my terminal.

**Comment by jgehrig** [comment]
@tastytea 

I've created a Pull Request, it sounds like it is safe to ignore these key events.

Out of curiosity, what happens when you combine `Hyper_L` with other keys. Does this behave as expected on you machine?

Does it behave as expected in the Linux AppImage builds here:
https://github.com/equalsraf/neovim-qt/actions/runs/2834837131

**Comment by tastytea** [comment]
> Out of curiosity, what happens when you combine Hyper_L with other keys. Does this behave as expected on you machine?

The expected command is run, but the `v` is still inserted.

> Does it behave as expected in the Linux AppImage

Yes, that fixes it! :sparkling_heart:

**Comment by jgehrig** [comment]
Sorry for the delay -- Pull Request merged, marking as closed.

Please let me know if you see any further issues with the Hyper Key.
