### ISSUE TITLE
connecting to docker neovim

### ISSUE THREAD

**Issue by kitcarson3official** [equalsraf/neovim-qt#1015]
Hi, i'm trying to connect to a remote neovim server but i get a 
    "the remote host closed the connection"
reply.
the step to reproduce it are:
(in the host)
``` bash
docker pull alpine
docker run -it -p 80:80 alpine sh
```

(inside docker container)
``` bash
apk update
apk add neovim
nvim --listen 127.0.0.1:80

```

(in the host)
```bash
nvim-qt --server 127.0.0.1:80
```

**Comment by jgehrig** [comment]
@kitcarson3official 

Have you tried a port other than 80?

That is a common port and it could be busy. The commands above fail on my local machine (even without Docker).

Changing the port to something like `127.0.0.1:1234` does work:
```
export NVIM_LISTEN_ADDRESS=127.0.0.1:1234
nvim --headless ~/.vimrc &
nvim-qt --server $NVIM_LISTEN_ADDRESS
```

**Comment by jgehrig** [comment]
Making as closed.

From testing, remote connections do not work on port 80 and selecting a different port such as 1234 may resolve the issue.

If this still does not work feel free to continue the discussion or re-open the issue.
