### ISSUE TITLE
has('gui_running') returns 0

### ISSUE THREAD

**Issue by lambdalisue** [equalsraf/neovim-qt#102]
Hi. First of all, thanks for this wonderful implementation. This works almost perfect in my Ubuntu.

However, it seems `has('gui_running')` returns `0`. While this is a GUI version, I assumed it returns 1 so could you please confirm this?

Thanks.

#### Environment

OS: Ubuntu Gnome Desktop 15.04
neovim-qt: https://github.com/equalsraf/neovim-qt/commit/c2912f4045f11d73be2a4c362660b9babdca5380

**Comment by justinmk** [comment]
`has('gui_running')` is not meaningful for neovim, because a non-GUI terminal client may be connected to the same nvim server.

**Comment by lambdalisue** [comment]
Then what is a correct way to separate codes for `nvim` and `nvim-qt`.

**Comment by equalsraf** [comment]
At the moment there is none, see here https://github.com/equalsraf/neovim-qt/issues/94#issuecomment-186702667 for a discussion on the issue and possibilities. I'm closing this but we can keep discussing this in #94.

**Comment by lambdalisue** [comment]
Thanks :-)
