### ISSUE TITLE
Binary built from source using MSVC seems to require debug dlls

### ISSUE THREAD

**Issue by comiluv** [equalsraf/neovim-qt#1045]
* Description
I tried compiling from source following instructions in https://github.com/equalsraf/neovim-qt/wiki/Build-Instructions#windows-10-and-visual-studio-2019
After compiling the binary and copying it over to ```windeployqt``` directory if I run the executable error messages pop up that:
It requires ```Qt5Guid.dll, Qt5Svgd.dll, Qt5Widgetsd.dll, Qt5Networkd.dll```
If I copy ```Qt5Guid.dll, Qt5Svgd.dll, Qt5Widgetsd.dll, Qt5Networkd.dll, Qt5cored.dll``` to  ```windeployqt``` directory then this error message will show:
<img width="310" alt="2023-02-05 001547" src="https://user-images.githubusercontent.com/19642705/216775078-1bd2bfcc-f47f-4e01-b524-5ac671033557.png">

* Steps to reproduce:
Basically follow what's outlined in https://github.com/equalsraf/neovim-qt/wiki/Build-Instructions#windows-10-and-visual-studio-2019
1. Install neovim
2. Install Visual Studio 2022 with C++ development kit selected
3. Install Qt5 with options Qt 5.15.2 MSVC 2019 64-bit, Qt Creator 9.0.1, and CMake 3.24.2 selected
4. Run following powershell script in Developer Powershell for VS 2022:
```powershell
git clone https://github.com/equalsraf/neovim-qt
cd neovim-qt
mkdir build
cd build
$CMAKE_PATH = "C:\Qt\Tools\CMake_64\bin\"
$QT_PATH = "C:\Qt\5.15.2\msvc2019_64\bin\"
$NVIM_PATH = "C:\tools\neovim\nvim-win64\bin\"
$env:Path += ";$CMAKE_PATH;$QT_PATH;$NVIM_PATH;"
cmake -DCMAKE_PREFIX_PATH="C:\Qt\5.15.2\msvc2019_64\lib\cmake" -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release ..
cmake --build . 
```
Note: NVIM_PATH is where nvim.exe installed from step 1 is
5. Copy the binary nvim-qt.exe to ../windeployqt
6. Run nvim-qt.exe from the windeployqt directory and see error

* Environment
Windows 11 22H2 22621.1105
Visual Studio 2022
Qt 5.15.2

**Comment by comiluv** [comment]
Also for side note AppVeyor build is automatically deleted for being older than one month

**Comment by jgehrig** [comment]
Thanks for reporting your findings her @comiluv!

This looks related to the tooling provided by Qt on Windows. Since we have a workaround -- I'm going to mark this as closed. If you feel there is something that still needs to be addressed, do speak up.

**Comment by comiluv** [comment]
[I updated the cmake command line of the instruction in the wiki which fixes this issue](https://github.com/equalsraf/neovim-qt/wiki/Build-Instructions#windows-10-and-visual-studio-2019)
