### ISSUE TITLE
E492: Not an editor command: GuiWindowOpacity

### ISSUE THREAD

**Issue by nkta3m** [equalsraf/neovim-qt#1047]
![2023-02-07 09_14_16-Window](https://user-images.githubusercontent.com/13484700/217123071-3d65c7e5-ef7a-4b01-9340-bbd35fd2c1b0.png)
![2023-02-07 09_15_15-nvim-qt](https://user-images.githubusercontent.com/13484700/217123084-440c3701-0c04-4e1b-9aa2-044c69e73b60.png)

**Comment by jgehrig** [comment]
Marking as closed -- this is a local configuration issue. However, let's still work to get your issue solved!

I'd guess there is a 'runtime' issue here, the `:Gui...` commands require a plugin to load at startup.

How did you install neovim-qt?

Do other commands like `:GuiFont` work?

Does `nvim-qt --version` report a runtime? Are there files present at that location?

This was captured on Linux, but you should see something similar in the Windows MessageBox:
```
VIM-QT v0.2.17.9999
Build type: Release
Compilation:-march=native -O2 -pipe -Wall -Wextra -Wno-unused-parameter -Wunused-variable -std=c++11
Qt Version: 5.15.2
Environment: 
  nvim: nvim
  args: --cmd let &rtp.=',/usr/bin/../share/nvim-qt/runtime' --cmd set termguicolors
  runtime: /usr/bin/../share/nvim-qt/runtime <== SEE HERE
```

Please ensure that [these files](https://github.com/equalsraf/neovim-qt/tree/master/src/gui/runtime) are loaded on startup.

**Comment by nkta3m** [comment]
1. i install neovim-qt from scoop
2. `:GuiFont` not work
3. 
![2023-02-17 08_22_41-Window](https://user-images.githubusercontent.com/13484700/219518025-eb38b59b-ad60-4f33-873e-a84e3023563d.png)

**Comment by jgehrig** [comment]
2 - This indicates the runtime is not loading correctly.
3 - Are [these files](https://github.com/equalsraf/neovim-qt/tree/master/src/gui/runtime) present at `C:\Users\Leslie\scoop\apps\neovim\current\share\nvim-qt\runtime`?

**Comment by nkta3m** [comment]
`runtime\plugin\nvim_gui_shim.vim`

**Comment by nkta3m** [comment]
I copy `C:\Users\Leslie\scoop\apps\neovim\current\share\nvim-qt\runtime\plugin\nvim_gui_shim.vim` to `C:\Users\Leslie\scoop\apps\neovim\current\share\nvim\runtime\plugin\`, it is work. i guess is my rtp has error. thank you.

**Comment by jgehrig** [comment]
I'm glad we could get the issue resolved! :+1:
