### ISSUE TITLE
Incorrect exit status when using `:cq`

### ISSUE THREAD

**Issue by davvid** [equalsraf/neovim-qt#1048]
* Exiting `vim` with `:cq` exits with exit code 1.
* Exiting `nvim` with `:cq` exits with exit code 1.
* Exiting `gvim --nofork` with `:cq` exits with exit code 1.
* Exiting `nvim-qt --nofork` with `:cq` exits with exit code 0.

I believe the correct behavior is that `nvim-qt --nofork` should use exit code 1 when exiting with `:cq`.

If y'all agree that this should be improved then I can start looking into forwarding nvim's exit code. Let me know if there's anything I'm missing.

Thanks again for neovim-qt!

**Comment by davvid** [comment]
Sorry for the noise. I was using an older distro-provided version. The current version in Git already has this fixed.

**Comment by zdm** [comment]
It doesn't work for Windows.
