### ISSUE TITLE
Spawn new window on mac

### ISSUE THREAD

**Issue by dvcrn** [equalsraf/neovim-qt#105]
I am currently spawning neovim-qt with this command:

```
gnvim () {
        open -a ~/src/neovim-qt/build/bin/nvim-qt --args ${1:+"$@"}
}
```

it works really good with the only exception that once the app is open, it will not spawn a new window or update the existing one. 

Is there currently a way to either open a new window or use the existing window for the new buffer? With the command above, the args are getting ignored if the app is open and the window just shifts into foreground. 

I'm using the latest HEAD on Mac

**Comment by equalsraf** [comment]
I don't have a Mac to test so this might be hard to check.

> With the command above, the args are getting ignored if the app is open and the window just shifts into foreground

To open a new instance does [open -n](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/open.1.html) work?

Maybe this can be made easier, using a context menu or something similar in the UI. Patches are always welcome.

To open in an existing instance you can use like https://github.com/mhinz/neovim-remote this is independent of neovim-qt, just works for neovim in general, but you might have to do some extra work setting up the proper NVIM_LISTEN_ADDRESS.

Hope this helps

**Comment by dvcrn** [comment]
let me give that a try. I will report back as soon as I'm back at my pc!

**Comment by dvcrn** [comment]
This seems to work. Sometimes neovim-qt can't connect to neovim when opening another window but in most cases it works. 

Here are the commands I am using
```
# zsh
gnvim () {
	FILE=$1
	ABSOLUTEPATH="$(realpath $FILE)"
	open -n -a ~/src/neovim-qt/build/bin/nvim-qt --args $ABSOLUTEPATH
}
```

```
# fish
function gnvim
  set FILE $argv[1]
  set ABSOLUTEPATH (realpath $FILE)
  open -n -a ~/src/neovim-qt/build/bin/nvim-qt --args $ABSOLUTEPATH
end
```

**Comment by equalsraf** [comment]
Nice, thanks for sharing the snippets.

**Comment by alex-shamshurin** [comment]
Is it possible to make normal gui option like 'new window'

**Comment by equalsraf** [comment]
@alex-shamshurin you could, but it would likely open up a new instance of neovim-qt, without any relation to the previous one.

**Comment by alex-shamshurin** [comment]
Yes, this is what I want - new independent instance of neovim-qt. And I still don't know how to open it.
