### ISSUE TITLE
Feature Request: Option to automatically close neovim-qt on disconnect

### ISSUE THREAD

**Issue by sevenc-nanashi** [equalsraf/neovim-qt#1057]
I use headless neovim and listen-mode neovim-qt for my WSL development, like this:
```bash
function nvim-qt() {
    true
    while [ $? -ne 1 ]; do
        RANDOM_PORT=$(( ( RANDOM % 10000 ) + 50000 ))
        nc -z 127.0.0.1 $RANDOM_PORT
    done
    echo "Using port $RANDOM_PORT"
    cat - <<CMD | parallel
      nvim-qt.exe --server "127.0.0.1:$RANDOM_PORT"
      nvim --listen "127.0.0.1:$RANDOM_PORT" --headless "$@"
CMD
}
```

But, When I do `:wq`, it doesn't close nvim-qt.

![image](https://user-images.githubusercontent.com/59691627/227746849-4168bb2e-5dd4-4bbc-93cc-9315ddf97439.png)

So, I would like some option to close when remote connection was disconnected.

**Comment by equalsraf** [comment]
This should already happen, provided the gui shim plugin is installed on the remote side (from https://github.com/equalsraf/neovim-gui-shim/blob/master/plugin/nvim_gui_shim.vim#L30)

Install this plugin on the remote neovim

https://github.com/equalsraf/neovim-gui-shim

**Comment by sevenc-nanashi** [comment]
It worked like a charm, thanks!

**Comment by mikew** [comment]
I have `neovim-gui-shim` installed, it seems to be loaded but I'm still seeing this error:


https://github.com/user-attachments/assets/1d611048-ad86-4143-b273-36c7f25e304c
