### ISSUE TITLE
cmake fails to detect msgpack-6.0.0

### ISSUE THREAD

**Issue by berndf** [equalsraf/neovim-qt#1061]
This corresponds to upstream https://github.com/neovim/neovim/commit/46c4cbced567f5f05f2c95b91cd90084ea8b5528 and can be fixed by:

```
Index: neovim-qt-0.2.17/cmake/FindMsgpack.cmake
===================================================================
--- neovim-qt-0.2.17.orig/cmake/FindMsgpack.cmake
+++ neovim-qt-0.2.17/cmake/FindMsgpack.cmake
@@ -5,8 +5,8 @@ find_path(MSGPACK_INCLUDE_DIR
 )
 
 find_library(MSGPACK_LIBRARY
-    NAMES msgpack msgpackc libmsgpack.a libmsgpackc.a
-)
+    NAMES msgpack msgpackc msgpackc_import msgpack-c
+    NAMES_PER_DIR)
 
 mark_as_advanced(MSGPACK_INCLUDE_DIR MSGPACK_LIBRARY)
 set(MSGPACK_LIBRARIES ${MSGPACK_LIBRARY})
```

**Comment by equalsraf** [comment]
A recent change to master https://github.com/equalsraf/neovim-qt/commit/c6ae9709237b6a55a705687afe4103646f34ac60 should already cover this.

**Comment by amano-kenji** [comment]
You better release a new version soon. Gentoo Linux already moved to msgpack 6.

**Comment by tastytea** [comment]
> You better release a new version soon. Gentoo Linux already moved to msgpack 6. I can't build it on gentoo linux.

please report Gentoo bugs to Gentoo. 😉 (in this case, [it is reported](https://bugs.gentoo.org/903963) and i'm on it)

**Comment by berndf** [comment]
Well, I'm on gentoo as well, and my suggestion above fixes it ;-)

**Comment by equalsraf** [comment]
Fair enough. If you are blocked by this for a private build you can also use an older downloaded version with -DUSE_SYSTEM_MSGPACK=OFF
