### ISSUE TITLE
Cursor highlight not work

### ISSUE THREAD

**Issue by karriszou** [equalsraf/neovim-qt#1069]
I use nvim-qt on windows 10, and I set the cursor highlight color by:

**set guicursor=n-v-c-sm:block-Cursor/Cursor
highlight Cursor guifg=Red guibg=Green
highlight iCursor guifg=Red guibg=Green**

but it not work, how do I set cursor color ?

Thanks advance!!

**Comment by jgehrig** [comment]
I'd guess `ext_linegrid` is not enabled.

Without that option, Neovim does not provide us with enough information to render cursor color.

You can try setting the following registry key:
```
HKEY_CURRENT_USER\Software\nvim-qt\nvim-qt
ext_linegrid=true
```

Similar option, but with a different name from this comment:
https://github.com/equalsraf/neovim-qt/issues/589#issuecomment-532760074

**Comment by karriszou** [comment]
> I'd guess `ext_linegrid` is not enabled.
> 
> Without that option, Neovim does not provide us with enough information to render cursor color.
> 
> You can try setting the following registry key:
> 
> ```
> HKEY_CURRENT_USER\Software\nvim-qt\nvim-qt
> ext_linegrid=true
> ```
> 
> Similar option, but with a different name from this comment: [#589 (comment)](https://github.com/equalsraf/neovim-qt/issues/589#issuecomment-532760074)

Oh my god, it works! Thanks for your alsome replay!!
