### ISSUE TITLE
Latest Windows nightly build doesn't have nvim-qt.exe

### ISSUE THREAD

**Issue by drazde** [equalsraf/neovim-qt#1071]
It's correct that the latest nightly build packages for windows doesn't have the executable file nvim-qt.exe?

**Comment by justinmk** [comment]
If you are looking at https://github.com/neovim/neovim/releases (not neovimt-qt), then yes, Nvim intentionally removed nvim-qt from its builds. https://github.com/neovim/neovim/pull/23668
