### ISSUE TITLE
folder icon not showing

### ISSUE THREAD

**Issue by ogios** [equalsraf/neovim-qt#1077]
![image](https://github.com/equalsraf/neovim-qt/assets/96933655/a260418b-8a1c-4e23-bfc3-a416c4f8c89c)

![image](https://github.com/equalsraf/neovim-qt/assets/96933655/58acf9c3-5ebd-4128-a253-5c023bdaf3ed)

using `JetBrainsMonoNL Nerd Font Mono` 
What could possibly cause this, the same config works fine with `windows terminal` connecting to my Linux server:

![image](https://github.com/equalsraf/neovim-qt/assets/96933655/609bdffa-4e56-44af-a7ab-f60529249bb0)

**Comment by jgehrig** [comment]
@ogios

More information is required to determine what is going on here.

Where are these icons coming from? Are you using a plugin? Are you using `:GuiTreeView`?

It would be helpful to provide a minimal config (nvim-qt -- -u config.vim) that reproduces the issue.

**Comment by ogios** [comment]
@jgehrig 
oh, i'm really sorry, i find that it's just my jetbrains nerd font is out of date, install the lastest version fixed this problem.
i forgot to close the issue, really sorry.
