### ISSUE TITLE
cannot drag-n-drop to open file from some software

### ISSUE THREAD

**Issue by xarthurx** [equalsraf/neovim-qt#1078]
I use "Everything" to search files and open by drag-and-drop, which is a quite convenient process. But I cannot do it to open it in nvim-qt.

Similar issues described here:
https://www.voidtools.com/forum/viewtopic.php?t=7122

Here are the observed behavior for different `nvim` GUI on Windows:

| From Software | To Software | Success |
| :---------------:| :-------------:| :-------:|
| Windows Explorer | Fvim | Y |
| Windows Explorer |  Neovide | Y |
| Windows Explorer | nvim-qt | Y |
| Windows Explorer | notepad | Y |
| Everything | Fvim | N |
| Everything |  Neovide | Y |
| Everything | nvim-qt | N |
| Everything | notepad | Y |

It might be caused by: https://stackoverflow.com/questions/39612616/drag-and-drop-from-32-to-64-bit

But I'm wondering how `neovide` handle it so that the bug doesn't not occur -- and if nvim-qt can do the same.

**Comment by comiluv** [comment]
I can drag&drop from everything on to neovim-qt window just fine.
Are you using lazy.nvim? Then it might be related to folke/lazy.nvim#403

**Comment by xarthurx** [comment]
With the recent update of Neovim, it seems `Everything` is working now.

(by `everything`, I was referring the `voidtools Everthing` software.
