### ISSUE TITLE
How should window resizing behave?

### ISSUE THREAD

**Issue by equalsraf** [equalsraf/neovim-qt#108]
More on this in a PR that should pop up in a bit, we need to discuss how resizing should behave to address #106, #83, #84(indirectly, resizes in layouts), and #4.

Resizes can arrive from multiple sources
1. Neovim itself may trigger a resize, e.g. `set lines`
2. User interaction i.e. user resizes the window
3. Window manager or widget layout changes, something in the window changed e.g. the layout of other widgets, that caused the Shell widget to be resized as a consequence

Neovim resizing works as follows 
1. The GUI calls neovim for a resize - see `ui_try_resize()`
2. Neovim (eventually) triggers the correct event (followed up by a redraw), but there may be other events in the pipeline
3. (I think) if the GUI triggers multiple resizes simultaneously (without waiting for completion) the following requests are dropped, very common when resizing a window

A few cases that need to be considered
1. The shell widget might be a window (maximized or not)
2. In some systems there is the notion of full screen mode (MacVim, Vim-Qt) it usually behaves very differently from maximized window
3. The shell widget might be part of another widget
4. Not all GUIs behave the same, check out vim-gtk, vim-qt, MacVim

The important bit to understand here is that a resize can trigger another resize and sometimes this is racy e.g.
- Some users drop a set lines/cols in init.vim, should that work for the GUI?
- If the windows is maximized and Neovim triggers a resize (e.g. plugin or set lines) should the window leave the maximized state and be resized - I feel this breaks user expectations - for e.g. vim-qt resized vim back to its previous size
- If Neovim is actually an embeded widget then resizes are likely not possible, but races can occur - Neovim resizes, the layout resize back 
- When resizing a window (depending on the window manager) the resize is progressive, i.e. one bit at a time, this is terribly inefficient.
- For a non-maximized window should we allow resizes larger than the current screen/workspace (e.g. set lines=2000)?
- Not all window managers respond to these events in the same way, e.g. KWin might allow you to resize the window, i3 will not

Ping #106, #83, #4. TLDR; need to agree on what is the expected behaviour for resizes, and need to write unit tests that check the correct behaviour (upcoming PR should help).

**Comment by kierun** [comment]
Just adding another fly in the ointment: Some window managers ([awesome](http://awesome.naquadah.org/) for one) allow you to maximise a window vertically and/or horizontally and back again. This is a feature I use a lot as I tend to have many instances of (neo)vim open at once.

In more general terms, you might hit Parkinson's [bike shed](http://www.millingtons.eclipse.co.uk/glyn/bikeshed.html) asking for this. Personally, I do not care what the behaviour is as long as it is clearly documented.

**Comment by equalsraf** [comment]
> In more general terms, you might hit Parkinson's bike shed asking for this. Personally, I do not care what the behaviour is as long as it is clearly documented.

True. Likely I'll just implement whatever comes to mind and call it the `de facto` behaviour :D. But the point is also to identify what can't be done (some things work fine on my window manager but not yours, etc).

**Comment by equalsraf** [comment]
So far in #109, two distinct cases apply

#### A. Neovim is a top level widget (window)

This is NOT the default behaviour for the builds, unless you define NEOVIMQT_GUI_WIDGET in src/gui/main.cpp.

1. When neovim calls for a resize, **if the window is maximized/fullscreen**, we NEVER resize the widget instead we try to resize to Neovim to the maximum available size. **Pitfall:** can this trigger a loop where Neovim and the GUI keep calling each other for resizes?
2. When neovim calls for a resize, and **the window is NOT maximized/fullscreen**, the window is resized to whatever Neovim tells it to i.e. set lines works for changing the window size. Currently there is no enforcement of maximum size. **This will trigger 3.**
3. When the Shell widget is resized (user interaction, or not), if the current size does not match the Neovim size a call is made to Neovim to do resize (**may trigger 2.**); otherwise nothing happens.

#### B. Neovim is an embeded widget

Right now this is what happens in the default builds, the widget is inside a QMainWindow. 

1. When neovim calls for a resize, **if the window is maximized/fullscreen**, nothing happens, this causes unexpected behaviour for the user - set lines can cause the shell to be smaller or larger than your actual widget.
2. Should be identical to **A.2**, resizes to sizeHint() i.e. the window should be large enough to hold all the contents.
3. Is identical to **A.3**

**Comment by equalsraf** [comment]
Turns out resizing the widget is a really bad idea specially in window managers where Qt fails to detect if the window is maximized. So instead we just resize Neovim to always have the same size as the widget. The downside is that `set lines` does not work at all.

**Comment by with0out** [comment]
Excuse me, so...is there a way to automaticly set window size upon start yet?
(unrelated, but since we can't use winpos, can we still position the window upon startup?)
Thanks!

**Comment by kierun** [comment]
@with0out Yes, there is a way to set the window size upon start up: add `alias gvim='nvim-qt --geometry 500x320 --'` in your shell rc file. Clearly, the number might need to change depending on what you want/need.

Window position _is not_ something that `nvim-qt` should ever do. That is the job of your window manager.

**Comment by with0out** [comment]
@kierun I'm in windows 7, just tried `O:\Neovim\nvim-qt.exe --geometry 800x600` in cmd, and similarly in cygwin shell, it's size didn't seem to change...
(I'm using latest neovim-qt and neovim release)

**Comment by kierun** [comment]
@with0out I have no idea whatsoever about Windows.

**Comment by paulburlumi** [comment]
@with0out On Windows 7 I found using `-qwindowgeometry 800x600` instead of `--geometry 800x600` worked for me.

**Comment by xelra** [comment]
I think it's important that the window actually saves its state and then when you open Neovim-Qt again, it will appear at the same coordinates with the same size as when you quit.

Of course there are exceptions. For example when you pull the window to the far right, you get it maximized to half of the screen. Now if a second Neovim-Qt window should be opened, it shouldn't be above that window, but instead occupy exactly the other half of the screen.

**Comment by kevincox** [comment]
It seems like the default should be to just let the window manager decide where you should go. I'm not against an option to be explicit but I if anyone is saving the state it should be the WM because that is it's job.

**Comment by kierun** [comment]
> I think it's important that the window actually saves its state and then when you open Neovim-Qt again, it will appear at the same coordinates with the same size as when you quit.

Please do not do that: *it is the job of your window manager to do that!*

There are far too many edge cases that it will break -- for example tilling window managers.

**Comment by xelra** [comment]
What I'm suggesting is to actually leave it to the window manager.

**Comment by equalsraf** [comment]
> I think it's important that the window actually saves its state and then when you open Neovim-Qt again, it will appear at the same coordinates with the same size as when you quit.

This one is tricky if you need a way to command the GUI into a specific size I certainly don't mind adding a command to do it.

The tricky part is to store state and to know when to resize it (or when not to). Honestly I prefer to just add the command and let people script the behavior that makes sense for them or their WM, Vimscript does that well enough. More than that will likely clash into someone's setup.

**Comment by dumblob** [comment]
Is there any way how to start neovim on Windows 10 with a reasonably sized window (not 1x10 or so by default) without passing any arguments to it? Neither `set lines` nor `set columns` work. I need it to make NeoVim the default text editor.

**Comment by equalsraf** [comment]
@dumblob windows seems to have specific issue when the windows sometimes gets smaller than it should https://github.com/equalsraf/neovim-qt/issues/251

**Comment by kylemacfarlane** [comment]
On Windows it seems like setting a shortcut with arguments doesn't work as a default app. The arguments are just ignored.

So to set the startup width and size you can regedit `Computer\HKEY_CLASSES_ROOT\Applications\nvim-qt.exe\shell\open\command` and change it to something like `"C:\Program Files\nvim\bin\nvim-qt.exe" "%1" -qwindowgeometry 800x600`

**Comment by kierun** [comment]
@kylemacfarlane Sadly, the registry hack did not work for me. Should I reboot or something?

**Comment by jdhao** [comment]
Setting `-qwindowgeometry` works for me.
