### ISSUE TITLE
I can't open nvim in vs2022

### ISSUE THREAD

**Issue by Penguin-SAMA** [equalsraf/neovim-qt#1098]
if i click to open  nvim-qt.exe, it's work
![image](https://github.com/equalsraf/neovim-qt/assets/50973632/810b5e63-44e8-4b5d-ae12-bdb4a141dcdc)
but if i use 'open in neovim' plugin in vs2022, it will display error
![image](https://github.com/equalsraf/neovim-qt/assets/50973632/6d9ec87f-e47f-4d37-88ce-3ba162689fa4)

**Comment by jgehrig** [comment]
We'll need more specific repro steps to help.

Can you elaborate on ` but if i use 'open in neovim' plugin in vs2022, it will display error`?

**Comment by Penguin-SAMA** [comment]
Through my testing, it seems that using the nightly version causes nvim-qt.exe to be unable to start, while everything works fine with the stable version.
