### ISSUE TITLE
Emoji support on OSX

### ISSUE THREAD

**Issue by dvcrn** [equalsraf/neovim-qt#110]
Not a big issue but definitely nice to have. The current version of neovim-qt does not seem to render emojis:

<img width="732" alt="screen shot 2016-03-13 at 1 31 22 pm" src="https://cloud.githubusercontent.com/assets/688326/13726929/20018b8a-e920-11e5-8652-45c8a5c22e20.png">

**Comment by equalsraf** [comment]
How does this work? AFAIK this uses unicode chars, and should work provided that fonts support them. and as far as Neovim is concerned if the font is monospaced and these chars are considered to be wide (not sure if they are, surprisingly it seems [are not](https://news.ycombinator.com/item?id=10206380)).

A strange issue with your screenshot is that even the substitution char seems to rendered incorrectly, maybe a bug on our part.

Also tried to use these in my terminal (konsole) and got mixed results, sometimes they worked, but not when the cursor was over them, which suggests it does not consider them to be wide chars.

Sidenote: We use konsole's implementation of [wcwidth](https://github.com/equalsraf/neovim-qt/blob/master/third-party/konsole_wcwidth.cpp#L98) to detect the width of a character. Not sure what other terminals do, [iterm2 seems to do some funky magic](https://wiki.dequis.org/notes/emoji/)

**Comment by dvcrn** [comment]
I am not sure to be honest. I think the emojis on mac are provided by the OS and not by the font. Both screenshots, terminal (iterm2) and qt, are using the same font (Hack). 

Besides in ui elements, the same happens when opening a document that has emojis or trying to paste a emoji into a new document. 

Also not sure if this helps but Neovim.app renders emojis correctly

**Comment by equalsraf** [comment]
Can any one check if https://github.com/equalsraf/neovim-qt/pull/141 fixes this issue? You might need to use the neovim from master instead of 0.1.4.

**Comment by dvcrn** [comment]
@equalsraf looks like it's fixing it! Emojis are now rendered correctly

**Comment by dvcrn** [comment]
There are occasionally visual glitches with the width of emojis though. 
<img width="179" alt="2016-07-16 9 44 37" src="https://cloud.githubusercontent.com/assets/688326/16891747/f79f66ae-4b39-11e6-9031-e2b74514bc89.png">

**Comment by equalsraf** [comment]
@dvcrn thanks for checking, the visual glitches are not completely unexpected. Neovim and Neovim-qt can have disagreements about character width, I need to figure out how to deal with those cases.

**Comment by jgehrig** [comment]
This is an old issue, marking as closed. Please file a new bug if you still see issues.

Tested with `v0.2.16` on MacOS X, and emojis now render.

There are some clipping issues, but this should be solvable with `guifontwide` in pending release `v0.2.17` or `master`.
