### ISSUE TITLE
Neovim 0.10 Windows release doesn't include Neovim Qt

### ISSUE THREAD

**Issue by bybor** [equalsraf/neovim-qt#1108]
Could you tell why if you know why this happened?

Thank you!

**Comment by bybor** [comment]
I installed Neovim-Qt by using scoop (from `extras` bucket). I still don't know why it was removed with 0.10 - after it was added as the default windows GUI back in 2018.

Anyway, thank you for Neovim-Qt

**Comment by davea1** [comment]
Explanation: https://github.com/neovim/neovim/pull/23668
