### ISSUE TITLE
Copy and paste under awesome WM.

### ISSUE THREAD

**Issue by kierun** [equalsraf/neovim-qt#111]
I am not sure Awesome is at fault here but it could be... It could be something wrong with the way Fedora/CentOS7 sets up QT.

I cannot copy and paste using neovim-qt at all. The highlight works fine and neovim enters visual mode as expected. However, the X11 buffer is empty.

Am I missing something obvious?

**Comment by equalsraf** [comment]
Can you do it in regular Neovim from the console?

Copy/pasting should still be handled by the Neovim clipboard provider, this requires something like xclip to be installed.

**Comment by kierun** [comment]
Yes, it works fine in a console, I use [st](http://st.suckless.org/), but it works in xterm too.

I do not have xclip installed.

**Comment by equalsraf** [comment]
xsel works too, but if its is working in a terminal there really should be no issue. What commands are you using to copy/paste? Do you have any clipboard specific settings for Neovim?

**Comment by kierun** [comment]
I have installed xsel, made no difference.

I generally highlight something with my mouse, move to a different window, and press middle-mouse. Kinda old school.

The only things I think *might* influence this are these, but really they should not...

```
let mapleader=','

" Copy and paste.
set clipboard+=unmappedplus

" Copy to clipboard
vnoremap  <leader>y  "+y
nnoremap  <leader>Y  "+yg_
nnoremap  <leader>y  "+y
nnoremap  <leader>yy  "+yy

" Paste from clipboard
nnoremap <leader>p "+p
nnoremap <leader>P "+P
vnoremap <leader>p "+p
vnoremap <leader>P "+P
```

**Comment by equalsraf** [comment]
Tested here and confirm its not working.

> I generally highlight something with my mouse, move to a different window, and press middle-mouse. Kinda old school.

Ah. that makes a bit more sense. If you are copy/pasting by selection and middle mouse you are using the X11 selection clipboard. So maybe its not Neovim thats setting that for you but rather the terminal emulator i.e. selected text does not go automatically into the `*` register.

**Comment by guyzmo** [comment]
just a thought on this: maybe if there was (is?) a way to catch and define actions for mouse buttons, could we map middle click to `"*p`, or even better `:set paste<CR>"*p:set nopaste<CR>` :)

**Comment by equalsraf** [comment]
@guyzmo I dont think the problem is the middle click action, Neovim should already map that. I think the selection text is never copied to the clipboard.

**Comment by equalsraf** [comment]
See neovim/neovim#2325

**Comment by kierun** [comment]
Just so there is a record here as well...

Using `vmap <LeftRelease> "*ygv` did work for me with neovim-qt with `xsel`.
