### ISSUE TITLE
Inclusion of CMAKE_CXX_FLAGS in "About" dialog prevents build from being reproducible

### ISSUE THREAD

**Issue by jamessan** [equalsraf/neovim-qt#1111]
https://github.com/equalsraf/neovim-qt/blob/442abfba5399303cda8d8c6e9eaf7ed4227f4820/src/gui/app.cpp#L449

Since CMAKE_CXX_FLAGS can contain things like references to the build path, this prevents the builds of neovim-qt from being full reproducible.  This can be seen in the results of the [Reproducible Builds](https://reproducible-builds.org/) project's test for [neovim-qt](https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/neovim-qt.html).

Would removing this from the about dialog be acceptable?

**Comment by equalsraf** [comment]
Sounds good, at the very list I can make it conditional on an a build option.

**Comment by equalsraf** [comment]
Merged, on by default.
