### ISSUE TITLE
Open files from stdin input.

### ISSUE THREAD

**Issue by ivegotasthma** [equalsraf/neovim-qt#112]
Suppose I have a file called `test-file` with some arbitrary text. In vim I can open file with with: `$ vim test-file` but in nvim-qt the file isn't opened but a blank screen is displayed.

**Comment by equalsraf** [comment]
`nvim-qt filename` should work.

> but in nvim-qt the file isn't opened but a blank screen is displayed.

Blank screen, like a white screen? Can you post a screenshot?

**Comment by ivegotasthma** [comment]
Here's a [screencast](https://i.imgur.com/M1Yn8qa.webm)

**Comment by equalsraf** [comment]
Which version are you using?  From the master branch or from #109?

If its from #109, try `nvim-qt -- filename`

**Comment by fuelen** [comment]
[out-1.ogv.zip](https://github.com/equalsraf/neovim-qt/files/176949/out-1.ogv.zip)
and I am again...
There are white random markers when navigate in document

**Comment by ivegotasthma** [comment]
@equalsraf Built the branch with the reimplementation. 

Using `nvim-qt -- filename` fixes it.

**Comment by equalsraf** [comment]
#109 was merged this is now the default behaviour in the master branch

**Comment by SalmanPK** [comment]
@equalsraf This is bizarre. Why do we need those two extra hyphens to open a file?

**Comment by equalsraf** [comment]
Its just a way to separate arguments that are handled by nvim-qt and arguments that are handled by nvim i.e. all arguments after `--` are passed directly to nvim

**Comment by SalmanPK** [comment]
@equalsraf Thanks for the reply. Is there a list of the command line arguments that can be passed directly to `nvim-qt.exe` somewhere then? Since `nvim-qt filename` does not work (which is weird).. which argument can be used to open a file?

**Comment by equalsraf** [comment]
See `--help`

```
$ nvim-qt --help
Usage: /home/raf/Code/neovim-qt/build/bin/nvim-qt [options] [-- ...]

Options:
  --embed                Communicate with Neovim over stdin/out
  --server <addr>        Connect to existing Neovim instance
  --geometry <geometry>  Initial window geometry
  --maximized            Maximize the window on startup
  --fullscreen           Open the window in fullscreen on startup
  -h, --help             Displays this help.

Arguments:
  ...                    Additional arguments are fowarded to Neovim
```

For arguments following `--` check `nvim --help`
