### ISSUE TITLE
Could we have new binaries

### ISSUE THREAD

**Issue by eyalk11** [equalsraf/neovim-qt#1127]
I don't want to install build reqs to build it. 
The retension period in [AppVeyor](https://github.com/equalsraf/neovim-qt/wiki/Windows-AppVeyor-Builds)  for binaries is 1 month so it seems none exists at this time. Could it be increased? 

Also, publishing a new version seems reasonable .

**Comment by jgehrig** [comment]
@eyalk11 

I'll bump the binary version shortly

Maybe we can come up with a more robust solution, like a `latest` tag that has a longer retention time...

**Comment by jgehrig** [comment]
https://github.com/equalsraf/neovim-qt/actions/runs/11652428661
