### ISSUE TITLE
After update don't work color theme!!

### ISSUE THREAD

**Issue by scientistnik** [equalsraf/neovim-qt#113]
I use ArchLinux and use color theme solorized. After updated (30.03.2016) this color theme don't work.

Use: neovim-git 0.1.0.r44.g632408a-1

**Comment by equalsraf** [comment]
@scientistnik where did you get your theme? What happens exactly can you post a screenshot?

**Comment by scientistnik** [comment]
Theme: https://github.com/altercation/vim-colors-solarized
if I use `nvim-qt` command:
![white_screen](https://cloud.githubusercontent.com/assets/3358263/14200496/f4c9505a-f7f3-11e5-9ac9-4a33c74bebc3.png)

If I use `nvim` command:
![black_screen](https://cloud.githubusercontent.com/assets/3358263/14200491/f04928ac-f7f3-11e5-8f5f-9fff16dc7728.png)

**Comment by velovix** [comment]
I think this is an issue with solarized, not neovim-qt. I've found that using this fork fixes the problem. It looks like the original maintainer of solarized has gone silent.

https://github.com/frankier/neovim-colors-solarized-truecolor-only

**Comment by thuandt** [comment]
@velovix I tried with solarized in your link but seem don't works.

**Comment by jgehrig** [comment]
I haven't seen any issues with `colorscheme` and this is an old issue. Marking as closed.

If you still experience this issue, please file a new bug.
