### ISSUE TITLE
Startup errors

### ISSUE THREAD

**Issue by kurkale6ka** [equalsraf/neovim-qt#115]
I just compiled (on Arch linux) the gui and I get these at startup:

```
% /usr/local/src/neovim-qt/build/bin/nvim-qt                                                                                                            
Unknown Neovim function "Integer buffer_add_highlight(Buffer buffer, Integer src_id, String hl_group, Integer line, Integer col_start, Integer col_end) !fail"
Unknown Neovim function "void buffer_clear_highlight(Buffer buffer, Integer src_id, Integer line_start, Integer line_end) !fail"
Unknown Neovim function "Object vim_call_function(String fname, Array args) !fail"
Unknown Neovim function "Dictionary vim_get_color_map()"
Unknown Neovim function "Array vim_get_api_info()"
```

Later on, I get incomplete syntax highlighting...

**Comment by equalsraf** [comment]
The errors should be harmless, they just mean we need to update the bindings to support those functions, but they are not being used anyway. And those messages should only be visible in Debug builds.

> Later on, I get incomplete syntax highlighting...

What do you mean?

**Comment by kurkale6ka** [comment]
This is what I see when I open my zshrc:

![screenshot_2016-04-05_15-31-57](https://cloud.githubusercontent.com/assets/52182/14285478/9c6cc010-fb43-11e5-861f-fa90c4440e3b.png)

**Comment by equalsraf** [comment]
Some of the highlight groups don't seem to be working at all. What colorscheme is this?

I'm using wombat256 here and it looks ok.

**Comment by kurkale6ka** [comment]
It's a modified version of desertEx but using the original I get a similar output

**Comment by kurkale6ka** [comment]
For info: I remember having the same issue using pynvim

**Comment by equalsraf** [comment]
Try the following
- `set bg=dark` after loading the file
- export NVIM_TUI_ENABLE_TRUE_COLOR=1 before calling nvim-qt

**Comment by kurkale6ka** [comment]
Did both. No visible change

**Comment by kurkale6ka** [comment]
I found the issue.
My theme used many named colors such as `guifg=salmon` vs `guifg=#fa8072`
Used hex values everywhere and now it renders ok

**Comment by justinmk** [comment]
@kurkale6ka what `nvim --version` ? There were commits recently related to that.

**Comment by kurkale6ka** [comment]
@justinmk:
```
NVIM v0.1.5-611-gdcbd1c7
Build type: Dev
Compilation: /usr/bin/cc -march=native -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -Wconversion -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/usr/local/src/neovim-git/src/neovim-git/build/config -I/usr/local/src/neovim-git/src/neovim-git/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/local/src/neovim-git/src/neovim-git/build/src/nvim/auto -I/usr/local/src/neovim-git/src/neovim-git/build/include
Compiled by mitko@andromeda.galaxy

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by justinmk** [comment]
Ok, hmm. Never mind then.
