### ISSUE TITLE
Zsh alias.

### ISSUE THREAD

**Issue by kierun** [equalsraf/neovim-qt#116]
Okay, this is a really weird one. 

If I set `alias nvim-qt='nvim-qt --geometry 500x320'` in a zsh shell and run `gvim ook eek`, a window opens with two tabs one with the file `ook`, the other with the file `eek`. This is the expected behaviour.

However,  if I set `alias gvim='nvim-qt --geometry 500x320'` and run `nvim-qt ook eek`, a window opens but there is only an empty instance of nvim. Just one. No files opened. It does not matter how many other arguments I put after `nvim-qt`, no files is ever opened.

**Comment by equalsraf** [comment]
@kierun try it like this `alias gvim='nvim-qt --geometry 500x320 --` when #109 was merged the command line changed a bit `--` acts as a separator for the argument that are passed to nvim

**Comment by kierun** [comment]
Yup, that worked fine. Thank you.
