### ISSUE TITLE
Try to map windows key

### ISSUE THREAD

**Issue by teto** [equalsraf/neovim-qt#117]
Using neovim 8d12e28d946b259811a8827aa6fbf1dca34c11da and neovim-qt 04c73f16359c68050e724a6856959b1d235521ea (the latest HEADs as of today), I would like to replace "]" by super_R since ] is hard to reach on my azerty keyboard.
I made a test `map <D-a> :echom "Hello world"` to check that super_L modifier was catchad as advertised in neovim 1.3. Sadly it doesn't.

I run i3 (i3wm.org) on Ubuntu with an azerty (French) keyboard where I run xmodmap to switch ESC and CAPS LOCK
```
remove Lock = Caps_Lock
keysym Caps_Lock = Escape
add Lock = Caps_Lock
```
Here is nvim-qt log
```
Unknown Neovim function "ArrayOf(String) buffer_get_lines(Buffer buffer, Integer start, Integer end, Boolean strict_indexing) !fail"
Unknown Neovim function "void buffer_set_lines(Buffer buffer, Integer start, Integer end, Boolean strict_indexing, ArrayOf(String) replacement) !fail"
Unknown Neovim function "Object buffer_del_var(Buffer buffer, String name) !fail"
Unknown Neovim function "Integer buffer_add_highlight(Buffer buffer, Integer src_id, String hl_group, Integer line, Integer col_start, Integer col_end) !fail"
Unknown Neovim function "void buffer_clear_highlight(Buffer buffer, Integer src_id, Integer line_start, Integer line_end) !fail"
Unknown Neovim function "Object tabpage_del_var(Tabpage tabpage, String name) !fail"
Unknown Neovim function "Object vim_call_function(String fname, Array args) !fail"
Unknown Neovim function "Object vim_del_var(String name) !fail"
Unknown Neovim function "Dictionary vim_get_color_map()"
Unknown Neovim function "Array vim_get_api_info()"
Unknown Neovim function "Object window_del_var(Window window, String name) !fail"
```

**Comment by equalsraf** [comment]
@teto looking into it in https://github.com/equalsraf/neovim-qt/pull/118 with that branch I was able to map the D- modifier to Super_L.

The Qt docs only refer to the Windows key as being the Meta modifier, with no details about left or right super.

**Comment by Zardoz89** [comment]
This issue is similar to the incapacity of mapping windows key on KDE to open krunner :(

**Comment by equalsraf** [comment]
Merged into master.
