### ISSUE TITLE
Couldn't input on the nvim-qt

### ISSUE THREAD

**Issue by procuteboy** [equalsraf/neovim-qt#119]
when i build and run it on ArchLinux
and get that on the terminal

```
Unknown Neovim function "Object vim_call_function(String fname, Array args) !fail"
Unknown Neovim function "Dictionary vim_get_color_map()"
Unknown Neovim function "Array vim_get_api_info()"
```

It is similar to the [isssue](https://github.com/equalsraf/neovim-qt/issues/115)
but they are different. I can't input, or do something but look at the window
![_2016-04-21_10-31-19](https://cloud.githubusercontent.com/assets/6184552/14696281/395dab18-07ac-11e6-9c54-2a5bff8e5caf.png)
1. python vesion:3.5
2. qt vesion: 4.87
3. gcc version: 5.30

**Comment by equalsraf** [comment]
These messages are normal, and should not be related to this issue. This seems to be the same as #78, if Neovim is throwing an error on startup it will block.

**Comment by equalsraf** [comment]
Closing as a duplicate, in any case the behaviour of the GUI has changed, it now times out with an error.
