### ISSUE TITLE
Unknown functions after binding rebuild

### ISSUE THREAD

**Issue by blm768** [equalsraf/neovim-qt#120]
I've been trying to build neovim-qt from Git on Arch Linux, and I'm running into some issues. I did a debug build and updated the bindings (as per #115), but I'm still getting some "Unknown Neovim function" errors, and the GUI window comes up blank. I've tested with both Neovim 0.1.3 and the Git head.

```
$ nvim-qt 
Unknown Neovim function "Object vim_call_function(String fname, Array args) !fail"
Unknown Neovim function "Dictionary vim_get_color_map()"
Unknown Neovim function "Array vim_get_api_info()"
```

**Comment by equalsraf** [comment]
@blm768 the unknown functions should be ok, the bindings generator is unable to generate the bindings to more complex types, and then on runtime it displays debug messages for functions it does not know.

> and the GUI window comes up blank.

what happens if you start with `nvim-qt -- -u NONE`?

**Comment by blm768** [comment]
> what happens if you start with nvim-qt -- -u NONE?

I don't notice any difference when I try that.

**Comment by equalsraf** [comment]
When the GUI window comes up blank it usually means Neovim is blocked with an error message (#78).

**Comment by blm768** [comment]
> When the GUI window comes up blank it usually means Neovim is blocked with an error message (#78).

I saw that issue, but I'm not sure if that's the problem because as far as I can tell, Neovim starts normally (i.e without error messages) when I run it in a terminal. Are there any flags I should be passing to `nvim` to test whether it's getting stuck when it's run in a GUI context?

**Comment by equalsraf** [comment]
the purpose of `-u NONE` was to skip your local settings and have a clean startup. Lets try to narrow this down.

Is the environment variable VIMRUNTIME set?

When you start nvim-qt the nvim process should be visible in the process list (ps ax should show something like `nvim --cmd ... --headless`), can you try running the same command without '--embed --headless'.

You can also try to attach to a running Neovim instance just in case this is a bug on our part

1. export NVIM_LISTEN_ADDRESS=127.0.0.1:8888
2. nvim
3. nvim-qt --server 127.0.0.1:8888

**Comment by blm768** [comment]
Ha, found the problem. It turns out that it's completely unrelated to the "missing function" errors. My Arch installation didn't have a "monospace" font alias. Installing a monospace font fixed it. It might not be a bad idea to make neovim-qt produce an error message in that scenario, but I've never written any Qt-based code, so I have no idea whether it would be worth the effort, especially because any "non-minimal" distribution will have a monospace font alias by default.

**Comment by equalsraf** [comment]
Closing in favor of #130
