### ISSUE TITLE
Command line arguments are not passed to neovim on Windows

### ISSUE THREAD

**Issue by robinkjoy** [equalsraf/neovim-qt#125]
Tried release v0.2.0 and latest build from AppVeyor. File names or other options are not passed to neovim. In the case of options 'unknown option' pops up, persumably from nvim-qt, not nvim.

**Comment by equalsraf** [comment]
@robinkjoy see `nvim-qt --help`, to pass arguments to neovim put them after `--` e.g.

```
nvim-qt -- file1 file2 file3
```

**Comment by robinkjoy** [comment]
Oh right. Sorry, I didn't notice the space after --. Thank you!
