### ISSUE TITLE
When searching, matched string is not highlighted as I am typing (incsearch has been turned on)

### ISSUE THREAD

**Issue by JasonXJ** [equalsraf/neovim-qt#128]
With option "incsearch" being turned on, the matched string should be highlighted immediately as I am typing (before I type "enter" to finish the searching). This works in terminal neovim/vim or gvim, but not in nvim-qt.

Here is a screen shot of terminal neovim, gvim and nvim-qt when I typed "/world" (without "enter") in normal mode.

![selection_003](https://cloud.githubusercontent.com/assets/6949499/15528719/d5b0801a-2289-11e6-92ca-c0a11edc1778.png)

**Comment by JasonXJ** [comment]
It seems that nvim-qt also has problems with background highlight in neovim's terminal emulator. Here is how to reproduce the problem:

1. Run an instance of nvim-qt  /  Run neovim in a terminal
2. use command `:terminal<cr>` to open a terminal emulator
3. Type `man ls` in the emulator
4. Type `/ls<cr>` to search the keyword "ls"

In the case of "neovim in a terminal", the keyword "ls" is background highlighted. However, in the case of "nvim-qt", nothing happened. Here is the screen shot:

![selection_004](https://cloud.githubusercontent.com/assets/6949499/15530516/2f5d1f52-2298-11e6-8d83-29b32b433e50.png)

**Comment by equalsraf** [comment]
Confirmed here, this seems to be caused by our lack of support for the **reverse** attribute in the highlight_set event. Starting a PR shortly.
