### ISSUE TITLE
Why can't i change the font into Monaco??

### ISSUE THREAD

**Issue by OsmanthusTree** [equalsraf/neovim-qt#131]
![screenshot from 2016-05-31 20-25-30](https://cloud.githubusercontent.com/assets/16307070/15674081/71738866-276d-11e6-96a1-eab8386cbf52.png)
![screenshot from 2016-05-31 20-25-37](https://cloud.githubusercontent.com/assets/16307070/15674082/77b45264-276d-11e6-8354-5ac800fe107c.png)

**Comment by suy** [comment]
See #103. And note that there are better ways to report textual messages than screenshots. Your images are not searchable. However: [a search gives you the answer](https://github.com/equalsraf/neovim-qt/issues?utf8=✓&q=is+not+a+fixed+pitch+font+)

**Comment by deto** [comment]
I'm also having trouble with GuiFont - I'm getting "Not an editor command: GuiFont" when I try to run it.  Using the 0.2.0 release - which looks like its the most up-to-date?

**Comment by OsmanthusTree** [comment]
Thanks! I will remember that!
