### ISSUE TITLE
neovim-gui-shim not in release?

### ISSUE THREAD

**Issue by deto** [equalsraf/neovim-qt#132]
It looks like the neovim-gui-shim plugin is not in the release?  Took me a while to figure out why Guifont wasn't working for me.

If this is the desired behavior, I'd recommend putting a big note in the main ReadMe.txt so others don't also waste so much time (or just ditch neovim-qt altogether in frustration).  The FAQs make it sound like sourcing this plugin using a plugin manager is optional.

**Comment by equalsraf** [comment]
@deto no this is not desired behaviour. Its a bug with the appveyor config it is not bundling the runtime in the release.

**Comment by equalsraf** [comment]
Started a PR to fix this, but I cannot test right now, If you are in a hurry here is the artifact

https://ci.appveyor.com/project/equalsraf/neovim-qt/build/700/job/f7srg48aeb2qxcu7/artifacts

**Comment by deto** [comment]
Great!  And am I supposed to manually move the neovim-qt/share/nvim-qt/runtime folder contents into Neovim/share/nvim/runtime ? It looks like the former location is not automatically added to my &runtimepath.

**Comment by equalsraf** [comment]
No moving should be required, nvim-qt should set runtimepath if it exists. I'm still missing a few commits to make the whole thing more user friendly though.
