### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by gwerbin** [equalsraf/neovim-qt#135]
Hey there, just want to let you guys know that I wrote a Homebrew formula for Neovim-Qt.

It's located at https://github.com/gwerbin/homebrew-tap/blob/master/Formula/neovim-qt.rb, and you can install it as follows:

```
brew tap gwerbin/tap
brew install --HEAD gwerbin/tap/neovim-qt
```

**Comment by gwerbin** [comment]
FYI: there is now a versioned installation: `brew install gwerbin/tap/neovim-qt` will install the latest tagged release (v0.2.0 as of right now).

I can't guarantee I'll be able to keep it up to date but I will gladly accept pull requests for version bumps. And if someone else wants to copy the formula and take ownership, let me know so I can take mine down.

**Comment by equalsraf** [comment]
@gwerbin many thanks for this

**Comment by rkitover** [comment]
@gwerbin just a suggestion, perhaps you could put it in https://github.com/neovim/homebrew-neovim if the neovim maints agree, then it could be installed from the same tap as neovim itself.

If not then perhaps @equalsraf could create a neovim-qt github org.

In any case, a note in the README.md with install instructions would be good.

And yeah I haven't forgotten about creating an .app bundle at least entirely, I've been doing random other stuff and life has been difficult, sorry.

**Comment by justinmk** [comment]
>could put it in https://github.com/neovim/homebrew-neovim if the neovim maints agree, then it could be installed from the same tap 

👍

**Comment by wayneashleyberry** [comment]
I'm struggling with this on macOS Sierra.

```
~
△ brew install gwerbin/tap/neovim-qt
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
bash-git-prompt                          commandbox                               gtkextra

==> Tapping gwerbin/tap
Cloning into '/usr/local/Homebrew/Library/Taps/gwerbin/homebrew-tap'...
remote: Counting objects: 12, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 12 (delta 1), reused 10 (delta 1), pack-reused 0
Unpacking objects: 100% (12/12), done.
Tapped 3 formulae (42 files, 36.9K)
==> Installing neovim-qt from gwerbin/tap
==> Installing dependencies for gwerbin/tap/neovim-qt: qt5
==> Installing gwerbin/tap/neovim-qt dependency: qt5
==> Downloading https://homebrew.bintray.com/bottles/qt5-5.6.1-1.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring qt5-5.6.1-1.el_capitan.bottle.tar.gz
==> Using the sandbox
==> Caveats
We agreed to the Qt opensource license for you.
If this is unacceptable you should uninstall.

This formula is keg-only, which means it was not symlinked into /usr/local.

Qt 5 conflicts Qt 4

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/qt5/lib
    CPPFLAGS: -I/usr/local/opt/qt5/include
    PKG_CONFIG_PATH: /usr/local/opt/qt5/lib/pkgconfig


.app bundles were installed.
Run `brew linkapps qt5` to symlink these to /Applications.
==> Summary
🍺  /usr/local/Cellar/qt5/5.6.1-1: 7,494 files, 315.6M
==> Installing gwerbin/tap/neovim-qt
==> Downloading https://github.com/equalsraf/neovim-qt/archive/v0.2.2.tar.gz
==> Downloading from https://codeload.github.com/equalsraf/neovim-qt/tar.gz/v0.2.2
######################################################################## 100.0%
==> Building Neovim-Qt
==> cmake ..
==> make
Error: No such file or directory - bin/nvim-qt

```

**Comment by khalidchawtany** [comment]
See https://github.com/gwerbin/homebrew-tap/issues/2

**Comment by wayneashleyberry** [comment]
Ah, thanks @khalidchawtany

**Comment by gwerbin** [comment]
@wayneashleyberry fixed at long last -- https://github.com/gwerbin/homebrew-tap/pull/4

**Comment by amagura** [comment]
@gwerbin Do you know if you'll be updating your formula to v0.2.12 anytime soon?

**Comment by equalsraf** [comment]
@amagura here use mine https://github.com/equalsraf/homebrew-neovim-qt it should work with the default brew commands already.

**Comment by KnowsCount** [comment]
how to use yours? @equalsraf

**Comment by equalsraf** [comment]
Similar to the commands seen above
Start by adding the tap for my recipe

```
brew tap equalsraf/neovim-qt
```

To install the latest release, just use brew as usual

```
brew install neovim-qt
```

If you want to install from the latest development version

```
brew install --HEAD neovim-qt
```

**Comment by xukai92** [comment]
Thanks! That's helpful! Maybe helpful to have this installation guide for macOS in the README.md.

**Comment by jgehrig** [comment]
@xukai92 Pending :)

Pull Request #821
