### ISSUE TITLE
Support for "light" fonts/font weight

### ISSUE THREAD

**Issue by equalsraf** [equalsraf/neovim-qt#136]
From https://github.com/equalsraf/neovim-gui-shim/issues/2 we have no way to select different font family weights other than bold.

A patch to add the `l` attribute to GuiFont can be found in https://github.com/equalsraf/neovim-qt/commit/6e5672861b03cd4a12a446e582816b54fe343cfe but it fails to address cases where the font weight is not available. Also does it make sense to allow other font weights besides bold and light (http://doc.qt.io/qt-5/qfont.html#Weight-enum)?

ping @gwerbin

**Comment by equalsraf** [comment]
To make matters slightly more confusing the following two seem to result in the same font (there is no light variant for Courier)

```
GuiFont Courier:h18
GuiFont Courier:h18:l
```

Sadly I'm unable to detect this as an error, Qt reports the exact same weight that we requested.

**Comment by gwerbin** [comment]
Thanks for looking into this.

In general it seems that fonts can specify arbitrary "weights" like Extra Light or Semibold -- not sure if it makes sense to support them all, but maybe there's room for additional flexibility?

**Comment by equalsraf** [comment]
There's a PR for this (#153) I've only added the :l attribute and nothing else. The problem I described earlier remains - its possible to ask for a light font and get a regular font, presumably for fonts that have not light variant, but otherwise it should be ok.

**Comment by equalsraf** [comment]
Fixed in the master branch.
