### ISSUE TITLE
Cannot open new file by passing arguments in terminal

### ISSUE THREAD

**Issue by yhylord** [equalsraf/neovim-qt#139]
I can create a new file called a.cpp, for example, in terminal by `nvim a.cpp`.
Nevertheless, it seems that I can't have the same effect by `nvim-qt a.cpp`.

**Comment by equalsraf** [comment]
The syntax to forward arguments to nvim is to separate the arguments with `--` for example to open `filename`

```
nvim-qt -- filename
```

check nvim-qt --help

**Comment by yhylord** [comment]
Sorry for not checking the manual. So if I want to achieve such an effect, I have to manually create an alias?

**Comment by equalsraf** [comment]
Closing since #155 was merged. You can now use nvim-qt filename to open files.
