### ISSUE TITLE
powerline doesn't work.

### ISSUE THREAD

**Issue by turtleDev** [equalsraf/neovim-qt#147]
using powerline somehow screws things up. After a little inspection, I found that this exception is thrown by the python interpreter:
![bug](https://cloud.githubusercontent.com/assets/12575843/16329991/d087ff28-3a03-11e6-9ad8-3622d1e9668b.png)

**Comment by justinmk** [comment]
`bindeval()` is not supported in Neovim, 

https://neovim.io/doc/user/vim_diff.html#nvim-features-missing

and I doubt airline really needs to be using it. airline should check if bindeval is available (it's a Vim 7.4 feature).

**Comment by justinmk** [comment]
oops I read airline. This is a known issue with powerline https://github.com/neovim/neovim/issues/1898
