### ISSUE TITLE
Unable to change font size

### ISSUE THREAD

**Issue by lpan** [equalsraf/neovim-qt#157]
I have read the [wiki](https://github.com/equalsraf/neovim-qt/wiki/GUI) and have the following in `~/.config/nvim/ginit.vim`
```
set background=dark
colorscheme hybrid_reverse
Guifont Mono:h15
```
When I restart `nvim-qt`, the font size is not changed

**Comment by khalidchawtany** [comment]
See if *ginit.vim* is sourced using `:scriptnames` command.  In my case the *ginit.vim* line is located towards the bottom of the output, as it is sourced after *init.vim* (I think 😄 )

**Comment by lpan** [comment]
@khalidchawtany it is located at the very bottom of the list :stuck_out_tongue: btw does changing font size work on your system?

**Comment by khalidchawtany** [comment]
Yep, it works flawlessly. Wha if you change the font using `:Guifont Mono:h15<cr>`, does it work this way? If yes, then you can use VimEnter autocommand to set it.

**Comment by equalsraf** [comment]
Hi @lpan lets see if we can narrow the problem down a bit:

- Does :messages show any error message?
- Does changing the font work using the command by hand :Guifont Mono:h15
- Does it work with other fonts?

**Comment by lpan** [comment]
Hi @khalidchawtany @equalsraf , thank you so much for your help! Here are the outputs

`:messages`
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
```

`:Guifont Mono:h15`
```
E492: Not an editor command: Guifont Mono:h15
```

All the other fonts I tried also print `not an editor command: xxx`

**Comment by equalsraf** [comment]
> E492: Not an editor command: Guifont Mono:h15

Ok this helps. The shim plugin is not loading at all, so none of the Gui commands are working

In a nutshell nvim-qt does two things at startup 

1. Sets runtimepath to point to its own runtime folder and sources nvim_gui_shim.vim
2. Runs ginit.vim

Step 1. seems to be failing. Can you share a bit more about your setup?

- Is this Linux or Mac?
- Did you install nvim-qt using `make install` or are you running off the source folder

As a last resort you can try adding this plugin by hand to init.vim

```Vim
" Load GUI commands (vim-plug)
Plug 'equalsraf/neovim-gui-shim'
```

**Comment by lpan** [comment]
@equalsraf I am on Linux. it turned out I installed it with `make install` instead of `sudo make install`. Thanks a lot for the help
