### ISSUE TITLE
A << mapping does not work

### ISSUE THREAD

**Issue by lambdalisue** [equalsraf/neovim-qt#160]
```vim
function! s:test()
  echo "Hello"
endfunction

nmap <silent><nowait> << :<C-u>call <SID>test()<CR>
nmap <silent><nowait> >> :<C-u>call <SID>test()<CR>
```

source the vim script file above define `<<` and `>>` mapping but `<<` mapping seems not work only on neovim-qt (works on vim/GVim/nvim but neovim-qt).

![](https://i.gyazo.com/969bd87be09ece6ec088dc506f982326.png)

I confirmed that `<<` is mapping to `s:test()` correctly by `:nmap`.

![selection_001](https://cloud.githubusercontent.com/assets/546312/16976677/7d8e1d60-4e8b-11e6-9411-012e25a4b515.png)

I'm not really sure if it is my environment issue or bug. Could you try with the script above?

**Comment by equalsraf** [comment]
The script works here, but maybe this is the same issue as https://github.com/equalsraf/neovim-qt/issues/134, where `<` gets translates into the wrong key. Can you try adding the following debug line to see what is being passed onto neovim.

```diff
diff --git a/src/gui/shell.cpp b/src/gui/shell.cpp
index a2e5096..1c771be 100644
--- a/src/gui/shell.cpp
+++ b/src/gui/shell.cpp
@@ -567,6 +567,7 @@ void Shell::keyPressEvent(QKeyEvent *ev)
                return;
        }
 
+       qDebug() << ev->text() << ev->key() << ev->modifiers() << inp;
        m_nvim->neovimObject()->vim_input(m_nvim->encode(inp));
        // FIXME: bytes might not be written, and need to be buffered
 }
```

**Comment by lambdalisue** [comment]
```
"<" 60 QFlags<Qt::KeyboardModifiers>(ShiftModifier) "<S-lt>"
"<" 60 QFlags<Qt::KeyboardModifiers>(ShiftModifier) "<S-lt>"
```

I close this and write additional informations to #134 while it seems same issue.
