### ISSUE TITLE
[Windows 10 x64] Neovim-qt needs an extra input to close

### ISSUE THREAD

**Issue by rgoliveira** [equalsraf/neovim-qt#165]
*[I'm not sure how to verify my Neovim-qt version. Apparently there's no `--version` flag? Let me know If it's possible. But I downloaded it today, so it's probably [the last `staging` release](https://github.com/equalsraf/neovim-qt/releases/tag/staging).]*

Whenever I try to close Neovim-qt, either from `:q` or using the GUI, it needs another input. It can be a keystroke or a click, but it won't close until the next input.

Is this expected behavior as of this version?

**Comment by equalsraf** [comment]
Its a bug already reported in https://github.com/equalsraf/neovim-qt/issues/53, and https://github.com/neovim/neovim/issues/4703.

**Comment by rgoliveira** [comment]
My bad, I search for `windows` in the title and couldn't find it.

**Comment by equalsraf** [comment]
No problem, closing this.
