### ISSUE TITLE
ligatures font support

### ISSUE THREAD

**Issue by idealist1508** [equalsraf/neovim-qt#166]
It would be fantastic that NeoVim could support some ligatures programming font like [FiraCode](https://github.com/tonsky/FiraCode).

There exists a [patch to VIM](https://groups.google.com/forum/#!topic/vim_dev/0sETSAwe5Wo) to enable this.

**Comment by equalsraf** [comment]
That is something that would have to be done upstream see https://github.com/neovim/neovim/issues/1408

**Comment by idealist1508** [comment]
I thought it is something that could be implemeted only in client gui. 
See https://github.com/neovim/neovim/issues/1408#issuecomment-223696580

**Comment by equalsraf** [comment]
Possible. But would require some large changes in drawing. Need to check further.

- http://doc.qt.io/qt-5/qglyphrun.html

**Comment by zovt** [comment]
This weekend I'll try to take a look at this and see if I can figure something out

**Comment by equalsraf** [comment]
@zovt you might want to start from https://github.com/equalsraf/neovim-qt/pull/141 instead of master

One aspect that is not clear to me is how to determine if two chars form a ligature, or if the fonts support it.

**Comment by razor-x** [comment]
I'd love is this could be a thing. I switch to neovim-gtk for a couple months simply for this feature, but I'm about to abandon that project due to UI lag, flickering, slowness, and general breakage of mappings. Never had any of those issues with neovim-qt.

Is there anyway you can use whatever ligature logic they have from that project and adapt it here?

**Comment by unclechu** [comment]
@razor-x It's probably **offtopic**, about flickering in *neovim-gtk* (I'm using this GUI for about half a year), it have been fixed in master branch, see [this issue](https://github.com/daa84/neovim-gtk/issues/57) by enabling double-buffering with environment variable `NVIM_GTK_DOUBLE_BUFFER` set to `1`.

**Comment by razor-x** [comment]
Thanks for the update. I may have been a bit harsh with my feedback on neovim-gtk. Some issues were plugin related I think. I also noticed a lag when writing with one of my keybinds, but now I suspect this is a lower-level issue unrelated to the GUIs (`nnoremap <silent> <Leader>s :<C-U>update<CR>`).

I did end up switching back to qt out of eventual frustration. The key factor was speed for me: neovim-qt just feels faster for my day to day work.

**Comment by kierun** [comment]
Any update on this one?…

**Comment by equalsraf** [comment]
None on my end.

**Comment by concatime** [comment]
`qTerminal` is based on Qt and [does support](//github.com/lxqt/qterminal/pull/368) font ligature. Maybe you could take at look for inspiration?

**Comment by osa1** [comment]
:+1: this would be great.

**Comment by Nuclearo** [comment]
It seems like sending multiple characters at once to QPainter::drawText will automatically draw the ligatures. I managed to get them to show up, but there are still a couple of glitches. For example, the colon in airline (bottom right):
![image](https://user-images.githubusercontent.com/4747118/45929699-023a3400-bf5e-11e8-9d35-b855425a4407.png)

**Comment by jgehrig** [comment]
Ligatures are now available in `master`, run `:GuiRenderLigatures 1`.

The feature should be available for release `0.2.17`. Marking as closed.

**Comment by kierun** [comment]
I tried this:

```
√ (master|…56); git log | head -1
commit 5038ad11d27100889a69b079f1c0c2515687565a
√ (master|…56); lsd -l bin/nvim-qt
.rwxrwxr-x yann yann 4.4 MB Thu Oct  1 11:17:59 2020  nvim-qt
√ (master|…56); gvim ook
```

But got that:

![screenshot](https://user-images.githubusercontent.com/3079575/94797664-5a6f6080-03d8-11eb-93c1-1c3ed65b3763.png)

*What am I doing wrong here?*

**Comment by jgehrig** [comment]
@kierun 

From your commit hash, it looks like you have the required changes. I would guess the shim is not loading properly. There is a plugin that need to load for all of the `Gui...` commands to work.

You can where the runtime is loaded from in the `--version` command:
```
$ nvim-qt --version
NVIM-QT v0.2.17.9999
Build type: Release
Compilation:-march=native -O2 -pipe -Wall -Wextra -Wno-unused-parameter -std=c++11 -Wfatal-errors
Qt Version: 5.14.2
Environment: 
  nvim: nvim
  args: --cmd let &rtp.=',/usr/share/nvim-qt/runtime' --cmd set termguicolors
  runtime: /usr/share/nvim-qt/runtime  <-- RUNTIME HERE
```

If you are compiling `nvim-qt` from source you need the latest `master` shim changes:
`NVIM_QT_RUNTIME_PATH=src/gui/runtime build/bin/nvim-qt`

If you are connecting to a remote instance of `nvim` you need:
`Plugin 'equalsraf/neovim-gui-shim'`

*NOTE:* As of writing this, I haven't added the changes to the plugin above. They will be added soon...

**Comment by kierun** [comment]
Ah, I see. The runtime was wrong, installed and I can see ligatures.

![screenshot](https://user-images.githubusercontent.com/3079575/94821846-ef368600-03f9-11eb-9e3a-875165329c71.png)

I mean, they are horribly broken but that could be my font.

![screenshot1](https://user-images.githubusercontent.com/3079575/94822033-24db6f00-03fa-11eb-8411-4438361ea4cd.png)

Which it is.

However, using the mouse now causes `neovim` to crash… Should I open a new bug for that?

**Comment by unclechu** [comment]
I have also a couple of rendering issues, will open an issue later.

**Comment by Himujjal** [comment]
> If you are compiling `nvim-qt` from source you need the latest `master` shim changes:
> `NVIM_QT_RUNTIME_PATH=src/gui/runtime build/bin/nvim-qt`

These are my logs:
```sh
$ echo NVIM_QT_RUNTIME_PATH
/home/himu/programs/neovim-qt/src/gui/runtime
$ ./build/bin/nvim-qt --version                                                
NVIM-QT v0.2.17.9999
Build type: Release
Compilation: -Wall -Wextra -Wno-unused-parameter -Wunused-variable -std=c++11
Qt Version: 5.15.2
Environment: 
  nvim: nvim
  args: --cmd set termguicolors
  runtime: 

NVIM v0.4.3
....
```

**Comment by Djedouas** [comment]
Hi,

I installed neovim-qt using the Ubuntu package repository with `sudo apt install neovim-qt`.

The command `GuiRenderLigatures` was not available.

I added the function and command found [here](https://github.com/equalsraf/neovim-gui-shim/blob/668188542345e682addfc816af38b7073d376a64/plugin/nvim_gui_shim.vim#L260) in my config.

Using the font [JetBrains Mono](https://www.jetbrains.com/fr-fr/lp/mono/) I opened neovim-qt and typed `GuiRenderLigatures 1` which resulted in no change in my opened file.

**Comment by jgehrig** [comment]
@Djedouas 

Font ligatures are only supported in not-yet released builds.

See:
https://github.com/equalsraf/neovim-qt/issues/823#issuecomment-786725622
https://github.com/equalsraf/neovim-qt/wiki/Windows-AppVeyor-Builds
