### ISSUE TITLE
unable to change geometry durning startup on MacOS

### ISSUE THREAD

**Issue by ray-x** [equalsraf/neovim-qt#167]
I am trying to set the size of vim window durning startup using  --geometry 500x640. But seems no matter what size I used in geometry, it always ended up with same size. And I got some warnings for ui_try_resize : 

Unknown Neovim function "ArrayOf(String) buffer_get_lines(Buffer buffer, Integer start, Integer end, Boolean strict_indexing) !fail"
Unknown Neovim function "void buffer_set_lines(Buffer buffer, Integer start, Integer end, Boolean strict_indexing, ArrayOf(String) replacement) !fail"
Unknown Neovim function "Object buffer_del_var(Buffer buffer, String name) !fail"
Unknown Neovim function "Integer buffer_add_highlight(Buffer buffer, Integer src_id, String hl_group, Integer line, Integer col_start, Integer col_end) !fail"
Unknown Neovim function "void buffer_clear_highlight(Buffer buffer, Integer src_id, Integer line_start, Integer line_end) !fail"
Unknown Neovim function "Object tabpage_del_var(Tabpage tabpage, String name) !fail"
Unknown Neovim function "void ui_attach(Integer width, Integer height, Boolean enable_rgb) !fail"
Unknown Neovim function "void ui_detach() !fail"
Unknown Neovim function "Object ui_try_resize(Integer width, Integer height) !fail"
Unknown Neovim function "Object vim_call_function(String fname, Array args) !fail"
Unknown Neovim function "Object vim_del_var(String name) !fail"
Unknown Neovim function "Dictionary vim_get_color_map()"
Unknown Neovim function "Array vim_get_api_info()"
Unknown Neovim function "Object window_del_var(Window window, String name) !fail"

It seems some of the commands was not corrected send to neovim.
The neovim i am using is NVIM v0.1.5-718-g67062d2 (master build from github) neovim-qt also master build from github. And I am running on MacOS.  

Is there special setup need to pay attention to?

**Comment by equalsraf** [comment]
Not really.

Other than the startup size, is it working correctly?

The messages you are seeing in the console are only displayed in debug builds, if there was an issue attaching to neovim, an error message should appear in the window.

**Comment by ray-x** [comment]
After the QT windows showed up. I can use mouse to change the windows size. It behaved normal.

**Comment by equalsraf** [comment]
Confirmed on Mac OS X. The `--geometry` option is handled internally by Qt, but it only works for X11. In Mac OS X using `-qwindowgeometry` should produce the same effect ([docs](http://doc.qt.io/qt-5/qguiapplication.html))

**Hypothesis** maybe it would work to replace `--geometry` with `-qwindowgeometry` in argv.

**Comment by ray-x** [comment]
Confirmed --qwindowgeometry is working on my mac with latest master (nvim-qt --qwindowgeometry 300x200) .

**Comment by equalsraf** [comment]
Continues in https://github.com/equalsraf/neovim-qt/issues/434
