### ISSUE TITLE
Forward nvim arguments transparently

### ISSUE THREAD

**Issue by koppa** [equalsraf/neovim-qt#172]
It would be nice to pass the all arguments to neovim directly without the `--` flag.
It should be no problem.
Currently only the `--embed` and `--help` flags are used by neovim and neovim-qt.

For example I often use the diff mode (-f).

**Comment by justinmk** [comment]
See https://github.com/equalsraf/neovim-qt/issues/148

**Comment by equalsraf** [comment]
#148 only addresses filenames. Flags such as `-f` still require using `--`.

**Comment by jgehrig** [comment]
Related #449.

**Comment by equalsraf** [comment]
Closing as a duplicate of https://github.com/equalsraf/neovim-qt/issues/449
