### ISSUE TITLE
":q"  causes "E173: 1 more file to edit" even when there is not extra file.

### ISSUE THREAD

**Issue by kierun** [equalsraf/neovim-qt#174]
If I edit a file with `nvim`, the `:q` command works as expected. However, in `neovim-qt`, if I type `:q` then I get the `E173: 1 more file to edit` warning even though there is no other file open in this neovim session. The screen shot tries to illustrate this: A simple file (with the date) got open and when I tried to close it via `:q` I got this:

![untitled](https://cloud.githubusercontent.com/assets/3079575/17891354/13761f8c-6933-11e6-9329-bbb09b75e4f7.png)

Typing `:q!` does work fine.

I run the latest master (`commit 407e7f35c150aeb942e646b1adfd6e2cb799a25e`).

**Comment by justinmk** [comment]
What does `:args` say?

**Comment by kierun** [comment]
`:args` says `[ook] ook`.

**Comment by equalsraf** [comment]
I see it, `nvim-qt -- TEST` causes `[TEST] TEST` but `nvim-qt TEST` works.

**Comment by kierun** [comment]
Dammit! I apologies. I should have included the line that I use to start `neovim-qt`.  I use `zsh` and I have this function defined which sets the size of the window and allows for other options to be passed.

```
function gvim {
    nvim-qt --geometry 500x320 -- "$@" &
}

```

**Comment by equalsraf** [comment]
@kierun no problem, this patch should fix it, I'm just waiting on CI to push it https://github.com/equalsraf/neovim-qt/commit/1bb92ad88c636a99ab29e41fad4ec587f3ac55ba

**Comment by kierun** [comment]
Thanks. I do hate wasting your time since you are super helpful in answering all my weird issues. ;)

**Comment by equalsraf** [comment]
Merged.

**Comment by kierun** [comment]
I can confirm your fix works for me.

Many thanks indeed.
