### ISSUE TITLE
Rendering issues in Windows 10

### ISSUE THREAD

**Issue by equalsraf** [equalsraf/neovim-qt#175]
@thebergamo reported this in https://github.com/neovim/neovim/issues/5271#issue-174019045

> I install neovim-qt and after open a file, neovim shows a blank screen, when I try arrow down or up, sometimes the content of file are showed, but not entire just some pieces. This behaviour are followed in normal and edit mode.

![](https://camo.githubusercontent.com/5efa61f449c9f26541d83ddacef09966fc50259e/68747470733a2f2f7075752e73682f7154506c762f633164616533346466632e706e67)

![](https://camo.githubusercontent.com/8e547e587fbc1f582f881b0da2d014e569288a9e/68747470733a2f2f7075752e73682f7154506e6e2f626232396634656235372e706e67)

Seems to be a rendering issue. Like the paint events are not triggered and the screen never gets updated.

**Comment by equalsraf** [comment]
I could use some more details about your setup

- Where did you get neovim-qt, did you build it? did you downloaded it from the releases page?
- What graphics card do you have

**Comment by thebergamo** [comment]
@equalsraf 

* I downloaded the neovim-qt direct from the release page.
* I got a Intel HD Graphics 5500 && AMD Radeon R7 M260
* Resezing or change the windows not affect the behaviour described above.

**Comment by equalsraf** [comment]
> I got a Intel HD Graphics 5500 && AMD Radeon R7 M260

An hybrid graphics system? I would be inclined to think this is either a driver issue, or some sort of bug in Qt.

I'll try to update the Qt version being used for the build, to see if helps.

**Comment by equalsraf** [comment]
Ok I've updated Qt, can you try with this release https://github.com/equalsraf/neovim-qt/releases/tag/staging?

**Comment by thebergamo** [comment]
Same issue, command line where I try to open an file the `:` at begin when I write that are hide and depending folder or file I try to autocomplete with `tab` have the same behaviour. 

About the graphics, I have an i7 so, the intel graphic card are presented, but the "external" graphic card are a Radeon in my Notebook.

**Comment by jgehrig** [comment]
Marking old bug as closed.

If you still see this issue, please file a new bug.
