### ISSUE TITLE
Guifont Invalid font height

### ISSUE THREAD

**Issue by Valdsonjr** [equalsraf/neovim-qt#176]
Since nvim_gui_shim.vim is not being loaded for me I installed it as a plugin:
`Plug 'equalsraf/neovim-gui-shim'`

and put this into ginit.vim:
`Guifont(DejaVu Sans Mono:h13)
GuiWindowMaximized(1)
GuiWindowFullScreen(1)`

but then i get:
`Invalid font height` for Guifont and
`E492: Not an editor command` for the other two.

It seems that nvim_gui_shim is being loaded since nvim now recognizes Guifont but what about the other two? And why is (DejaVu Sans Mono:h13) not working for Guifont?

**Comment by khalidchawtany** [comment]
The first one is a command. The other two are functions.
`:GuiFont DejaVu Sans Mono:h13`
`:call GuiWindowMaximized(1)`
`:call GuiWindowFullScreen(1)`

**Comment by Valdsonjr** [comment]
Oh of course, silly me! Thanks!
