### ISSUE TITLE
neovim-qt doesn't compile with MinGW

### ISSUE THREAD

**Issue by andalou** [equalsraf/neovim-qt#179]
I'm trying to compile neovim-qt on Windows 7 with MinGW, but I'm
getting:

--------------------
[...]
[ 44%] Built target nvim-qt
[ 46%] Preparing Qt runtime dependencies
Unknown option 'compiler-runtime'.

src\gui\CMakeFiles\windeployqt.dir\build.make:56: recipe for target 'src/gui/CMakeFiles/windeployqt' failed
mingw32-make.exe[2]: *** [src/gui/CMakeFiles/windeployqt] Error 1
CMakeFiles\Makefile2:1738: recipe for target 'src/gui/CMakeFiles/windeployqt.dir/all' failed
mingw32-make.exe[1]: *** [src/gui/CMakeFiles/windeployqt.dir/all] Error 2
Makefile:159: recipe for target 'all' failed
mingw32-make.exe: *** [all] Error 2
--------------------

Many thanks in advance,

-- 
Cesar

**Comment by equalsraf** [comment]
Cheers

- Which version of mingw are you using? Is this regular old MinGW or MinGW-w64.
- Can you post a log with `make VERBOSE=1`?

We build releases with MinGW-w64, here is a log

    https://ci.appveyor.com/project/equalsraf/neovim-qt/branch/master/job/31223afroak2qf8s

**Comment by andalou** [comment]
I'm using MinGW-w64, gcc 5.3.0, 32-bit.
I followed the instructions for compiling neovim-qt, according to the
README.md:

mkdir build
cd build

cmake -G "MinGW Makefiles" -DCMAKE_INSTALL_PREFIX:PATH=C:/progs/nvim -DCMAKE_PREFIX_PATH=C:/Qt/5.2.1/mingw48_32/ ..
[log.txt](https://github.com/equalsraf/neovim-qt/files/451068/log.txt)

cmake --build .
[log2.txt](https://github.com/equalsraf/neovim-qt/files/451069/log2.txt)

**Comment by equalsraf** [comment]
Seems to be a problem with the version of `windeployqt` not accepting the `--compiler-runtime`, maybe Qt 5.2 does not have that flag.

Quick fix is to remove the `COMPILER_RUNTIME` option when calling windeployqt

```diff
diff --git a/src/gui/CMakeLists.txt b/src/gui/CMakeLists.txt
index 8500ef9..bbce4f6 100644
--- a/src/gui/CMakeLists.txt
+++ b/src/gui/CMakeLists.txt
@@ -56,7 +56,7 @@ endif()
 
 if(WIN32 AND NOT CMAKE_CROSSCOMPILING)
        include(WinDeployQt)
-       WinDeployQt(TARGET nvim-qt COMPILER_RUNTIME INCLUDE_MODULES ${QTLIBS} EXCLUDE_MODULES webkit webkit2)
+       WinDeployQt(TARGET nvim-qt INCLUDE_MODULES ${QTLIBS} EXCLUDE_MODULES webkit webkit2)
        install(DIRECTORY ${PROJECT_BINARY_DIR}/windeployqt/
                DESTINATION ${CMAKE_INSTALL_BINDIR})
 endif()
```

Apparently I need to add a version check to that option.

**Comment by equalsraf** [comment]
Just a side note, there were some performance issues reported for Qt version before 5.5.

**Comment by equalsraf** [comment]
I create a branch with a fix, but I don't have Qt 5.2 to test with. Can you test using the branch tb-windeploy-fix?

**Comment by andalou** [comment]
I did the test using the tb-windeploy-fix branch, but I get another
error:
[log2.txt](https://github.com/equalsraf/neovim-qt/files/452783/log2.txt)

In the meantime I installed Qt 5.7.0, mingw53_32 version, and it
compiles fine.

**Comment by equalsraf** [comment]
Ah, it seems this is a know issue with windeplyqt in 5.2, https://forum.qt.io/topic/40061/the-windeployqt-tool-that-comes-with-qt-5-2/5

I don't think we can get fixes for such an old version. I've just disabled windeployqt for 5.2.

**Comment by equalsraf** [comment]
Fixed in master 0536fb9861fe7947e7aaae9956185d9ff0f6efd3, closing.

**Comment by andalou** [comment]
For installing, I suppose the next step is running:
mingw32-make install

When I do this, and I try to running nvim-qt.exe, it pops up an error
window with the message:

--------------------
The procedure entry point _Z21qRegisterResourceDataiPKhS0_S0_ could
not be located in the dynamic link library Qt5Core.dll.
--------------------

The install command has copied the following files on the installation
directory:
Qt5Cored.dll
Qt5Guid.dll
Qt5Networkd.dll
Qt5Svgd.dll
Qt5Widgetsd.dll

I think, they should be:
Qt5Core.dll
Qt5Gui.dll
Qt5Network.dll
Qt5Svg.dll
Qt5Widgets.dll

If I copy these, then nvim-qt starts without problem.

**Comment by equalsraf** [comment]
Can you restart using

cmake -DCMAKE_BUILD_TYPE=Release ,,,

its probably best to remove the build folder and start fresh

**Comment by andalou** [comment]
Thanks, it works, but now I have another problem: When I start neovim-qt
and I want to type a single quote, it won't  type it.

Only if I press twice the single quote key, it'll print two single
quotes, and then I have to remove the extra single quote, to have one
single quote.

The same problem happens with the double quotes key.

**Comment by equalsraf** [comment]
> The same problem happens with the double quotes key.

I have a similar issue with `~`, but it also happens in gVim on windows. What keyboard layout are you using? Are these dead keys in you layout?

**Comment by andalou** [comment]
I'm using a US keyboard with "United States-International" layout, and
on gVim I don't have that problem.
With a dead key, you're supposed to press the key plus a space and you
get the character printed. If you use a US keyboard with "US" layout,
you don't have dead keys.

For example, if I wanted to have a ~, I press the ~ key plus a space and
then I get the ~ character. The same happens with ` ' ", but on
neovim-qt, if I press one of these keys: ~ ` ' " and then a space I
don't get anything, only a space. I have to press twice those keys, but
then I get those characters twice printed.

**Comment by andalou** [comment]
It seems that Qt has some problems in Windows with dead keys:
http://stackoverflow.com/questions/3872085/dead-keys-dont-arrive-at-keypressedevent
