### ISSUE TITLE
Not able to change Gui font (Mac OS X)

### ISSUE THREAD

**Issue by Valdsonjr** [equalsraf/neovim-qt#180]
Using `:GuiFont  <fontname:h<fontsize>>` does not change anything nor shows any error message.

OS: Mac OS X El Capitan 10.11.6
Neovim: both 0.1.5 and 0.1.6-dev
Neovim-QT: brewed from [this formula](https://github.com/ourobourbon/homebrew-tap/blob/master/Formula/neovim-qt.rb)

Tried some common fonts (and variations):
```
:GuiFont Courier New:h16
:GuiFont Courier\ New:h16
:GuiFont courier new:h16
:GuiFont! Arial:h14
:GuiFont! arial:h14
:GuiFont AnyNonExistentFont:h13
```

but got no response.

`:echo exists("g:GuiLoaded")` and `:echo exists("g:GuiFont")` both return 1

**Comment by equalsraf** [comment]
Cheers, can you provide some more details?

- Does `:messages` show anything useful?
- Does `g:GuiFont` get updated when you call the command?

That brew recipe uses 0.2, and there have been some fixes since then. `GuiFont!` was only added after 0.2. Ping @ourobourbon

**Comment by ourobourbon** [comment]
@equalsraf Thanks for the heads up. I confess I switched back to terminal Neovim so I haven't been keeping up with changes. If you wanna make a PR whwn you release a new version I'll be happy to merge it. I'll do the change for this one when I get off mobile, and leave instructions for what to put in PRs in the future. I'll also put in a PR with the Neovim tap

**Comment by gwerbin** [comment]
Also FYI I changed my username back to gwerbin because it was causing issues when I forgot to update remote tracking branches. Sorry for the confusion!

**Comment by gwerbin** [comment]
Change is pushed! https://github.com/gwerbin/homebrew-tap/blob/master/Formula/neovim-qt.rb

For future reference all you need to do is change the URL on [line 4](https://github.com/gwerbin/homebrew-tap/blob/master/Formula/neovim-qt.rb#L4) and update the SHA256 for the ZIPped release on [line 5](https://github.com/gwerbin/homebrew-tap/blob/master/Formula/neovim-qt.rb#L5) by `shasum -a 256 neovim-qt-<version>.zip`. Just make a PR for it whenever you release a new version and I'll merge.

**Comment by equalsraf** [comment]
thanks @gwerbin

**Comment by Valdsonjr** [comment]
>Does :messages show anything useful?
Does g:GuiFont get updated when you call the command?

`:messages` shows nothing 
`g:GuiFont` is never updated

I'm currently trying to update/reinstall nvim-qt but failing with `Error: no such file or directory - bin/nvim-qt`, probably something wrong with my homebrew.

**Comment by equalsraf** [comment]
> I'm currently trying to update/reinstall nvim-qt but failing with Error: no such file or directory - bin/nvim-qt, probably something wrong with my homebrew.

mmm, maybe something changed and the recipe needs additional updaet. I don't have an OS X to test right away. Maybe its easier to build from source and go from there?

**Comment by khalidchawtany** [comment]
@equalsraf @Valdsonjr  @gwerbin  the **neovim-qt** formula is incorrect. Since it tries to install `build/bin/nvim-qt` executable and it does not exist on a Mac OS X. On Mac OS X an application bundle is created instead. I have opened an [issue](https://github.com/gwerbin/homebrew-tap/issues/2).

**Comment by Valdsonjr** [comment]
Updated to 0.2.2, everything seems fine now.
