### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by fuelen** [equalsraf/neovim-qt#183]
![07 09 16-23 36 03-940211659](https://cloud.githubusercontent.com/assets/588762/18327571/dd9af4aa-7553-11e6-8ac9-40994709019b.png)
version from git
Arch linux.
The same result is in KDE

**Comment by equalsraf** [comment]
Maybe a duplicate of https://github.com/equalsraf/neovim-qt/issues/130#issuecomment-233861925 what happens if you install a font like inconsolata.

**Comment by fuelen** [comment]
@equalsraf nothing happens

**Comment by fuelen** [comment]
@equalsraf I installed also 
`ttf-dejavu ttf-freefont ttf-droid ttf-liberation`
and it works

**Comment by fuelen** [comment]
I don't know what package solves issue
