### ISSUE TITLE
Lots of Unsupported function attribute… calls

### ISSUE THREAD

**Issue by kierun** [equalsraf/neovim-qt#184]
When I run`nvim-qt`, I get lots of `Unsupported function attribute…` warning but `neovim-qt` seems to run just fine. This is on a CentOS 7 machine. Here is the fuill log: [log.txt](https://github.com/equalsraf/neovim-qt/files/472097/log.txt)

Do you need anything else for me?

**Comment by equalsraf** [comment]
> When I runnvim-qt, I get lots of Unsupported function attribute… warning but neovim-qt seems to run just fine. This is on a CentOS 7 machine.

Those messages only appear in debug builds, and are a reminder that some functions or attributes are not handled by the bindings, but they harmless. If you build in release mode they should not appear.

The increase in messages happened because of recent changes in the Neovim API, but there was no compatibility issues so it still runs as intended. We should probably fix all these before Neovim 0.1.6 comes out.

> Do you need anything else for me?

Nope, thanks anyway.

**Comment by kierun** [comment]
Hum, I thought I was building in release mode or at least I am doing what the `README.rst` file says.  Is there something else I should be doing?

**Comment by equalsraf** [comment]
Remove the build/ folder and restart with `cmake -DCMAKE_BUILD_TYPE=Release ..`

**Comment by kierun** [comment]
Did that (`cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$HOME ..`) but I still get the warnings.

```
(master|✓); rm -rf ./build 
(master|✓); mkdir build
(master|✓); cd build 
(master|✓); cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$HOME ..
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Downloading Msgpack...
-- Found GTest: /usr/lib64/libgtest.so  
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7") 
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Performing Test MSGPACK_ENABLE_GCC_CXX_ATOMIC
-- Performing Test MSGPACK_ENABLE_GCC_CXX_ATOMIC - Failed
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.5") 
-- Found PythonInterp: /usr/bin/python (found version "2.7.5") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/usr/src/neovim-qt/build
(master|✓); make -j 5
[…]
(master|✓); ./bin/nvim-qt 
[… All the warning …]
```

**Comment by equalsraf** [comment]
Ok I see, the unknown function messages are debug, but the unknown attribute messages are warnings. I'll get a PR going.

**Comment by JasonXJ** [comment]
It would be very nice to mention the release build in README.md.

**Comment by equalsraf** [comment]
Updated README.md
