### ISSUE TITLE
0xc000007b under x64 win10 with installed Visual Studio 2015 C++ redistributable

### ISSUE THREAD

**Issue by iamkarlson** [equalsraf/neovim-qt#186]
Unable to start app due to this error. I googled it and found that I should reinstall redistributables, but no luck, still the same. Dependency walker showed too many errors:

![image](https://cloud.githubusercontent.com/assets/4534374/18815065/19aec788-8336-11e6-8948-c7ba58458e66.png)

**Comment by equalsraf** [comment]
Strange, the only thing that comes to mind really is the redistributables.

Did you get the build from the releases page? Or from appveyor? The release binaries are 32bit so the redistributables must also be the 32bit package.

**Comment by iamkarlson** [comment]
I took it from releases on github. 
![image](https://cloud.githubusercontent.com/assets/4534374/18823010/a68bba18-83c6-11e6-9033-934a4c9e81a2.png)

It's a list of all redistributables, they are coming with visual studio (2010,2015)

**Comment by iamkarlson** [comment]
@equalsraf do you know any possibility to find out what is a cause?

**Comment by equalsraf** [comment]
Honestly no idea where to go from here, you already did what I would do in the same situation. There is a long thread discussing a similar issue in SO

    http://stackoverflow.com/questions/17023419/win-7-64-bit-dll-problems

I suppose you could try the MSVC based build instead, from here

    https://ci.appveyor.com/project/equalsraf/neovim-qt/build/934/job/qsuufh1fgdhc2f5b/artifacts

**Comment by iamkarlson** [comment]
Just unpacked MSVC build and that's it. Thanks
