### ISSUE TITLE
"nvim-qt --help" requires connecting to an X display

### ISSUE THREAD

**Issue by jamessan** [equalsraf/neovim-qt#189]
I'm using `nvim-qt --help` to generate a man page for the Debian packaging.  During the build, there's no access to X, so nvim-qt aborts.  This can readily be reproduced by clearing the environment:

``` sh
$ env -i ./bin/nvim-qt --help
QXcbConnection: Could not connect to display 
zsh: abort      env -i ./bin/nvim-qt --help
$ echo $?
134 
```

This is inherited from Qt since QApplication is what performs the argument parsing, however there is a suggestion in their [docs](https://doc.qt.io/qt-5/qapplication.html#details) on using QCoreApplication when specific switches are present.

---

That being said, we've been able to work around this in the context of building the package by running `nvim-qt --help` under xvfb-run (which is already available to run the tests).  However, I thought I'd raise the issue in case it's something you think is worth addressing generally.

**Comment by equalsraf** [comment]
Already fixed in master.

**Comment by jamessan** [comment]
Actually, it isn't.  It's just in the fix-189 branch.

**Comment by equalsraf** [comment]
?? the following works fine here

```
$ unset DISPLAY
$ nvim-qt --help
```

That commit was not cherry picked but the corresponding behaviour ended up changing when we introduced --nofork. For example the following does not work

```
$ unset DISPLAY
$ nvim-qt --nofork --help
QXcbConnection: Could not connect to display 
Abort
```
