### ISSUE TITLE
Neovim fatal error "API methods mismatch…

### ISSUE THREAD

**Issue by kierun** [equalsraf/neovim-qt#191]
I updated neovim (v0.1.6-167-g22dfe69) and neovim-qt today (2831d3f41355e20291b1af82de07e26f891a6fc8) and upon running neovim-qt, I got: `Neovim fatal error "API methods mismatch: Cannot connect to this instance of Neovim, its version is likely too old, or the API has changed"`.

Do you need any more information from me?

Yes, I am more than happy to test new branches/fixes.

**Comment by kierun** [comment]
I reverted `neovim` to before the `Merge pull request #5357 from jbradaric/vim-7.4.1671`, recompiled, and installed it. Then I recompiled `neovim-qt` and it works again. So, the API changes are in that smallish change set.

**Comment by equalsraf** [comment]
There was a breaking change in 0.1.6 (fixed in https://github.com/neovim/neovim/pull/5389) and some other changes upstream, PR https://github.com/equalsraf/neovim-qt/pull/188 should fix it

**Comment by Mathiasb17** [comment]
Just to say, i had the same problem and last merge indeed fixed this. Thanks !
