### ISSUE TITLE
Open new files in new tabs

### ISSUE THREAD

**Issue by whitebyte** [equalsraf/neovim-qt#192]
Sorry for the possiby dumb question, but I can't figure out how to avoid opening new nvim-qt instance for every file. It seems that `--remote-tab-silent` used in gVim not working with nim-qt. Thoughts?

Linux.

**Comment by equalsraf** [comment]
Have you seen this https://github.com/mhinz/neovim-remote?

It should provide a replacement for --remote, it works Neovim with or without the GUI.

**Comment by whitebyte** [comment]
Thanks for the direction, will take a look.
