### ISSUE TITLE
Sign column icons cut off

### ISSUE THREAD

**Issue by bronzehedwick** [equalsraf/neovim-qt#195]
I have an issue where the signs in my sign column are cut off in the middle (screenshot below).

![screen shot 2016-10-03 at 2 37 39 pm](https://cloud.githubusercontent.com/assets/637174/19053345/9086725e-8988-11e6-9c5a-81ddc0bc4a51.png)

Changing the `Guifont` or the font size doesn't seem to matter. It looks fine in terminal neovim.

I am using neovim 0.1.5 on macOS 10.10.5.

**Comment by equalsraf** [comment]
I have not checked yet, but it could be related to https://github.com/equalsraf/neovim-qt/pull/141

**Comment by bronzehedwick** [comment]
Ah, that would make sense. I'll try testing that branch, and see if it fixes my issue.

**Comment by equalsraf** [comment]
Ok, what are the settings for the sign? e.g. `:sign list`

**Comment by bronzehedwick** [comment]
Here's a screenshot of the output from `:sign list`:

<img width="634" alt="screen shot 2016-10-05 at 11 12 59 am" src="https://cloud.githubusercontent.com/assets/637174/19119139/ca57acae-8aec-11e6-84b2-74f5c1f3c15f.png">

**Comment by equalsraf** [comment]
> Here's a screenshot of the output from :sign list:

This should help getting the output from a command, and appending it to the current buffer

    :call append(line('$'), split(execute('sign list'), "\n"))

I took a look at Neomake, it does set a sign with the char ✖, which seems to be causing your issue, e.g.

    sign define dummy4 text=✖ texthl=WarningMsg
    sign place 1 line=1 name=dummy4 buffer=1

In my Linux  system it does render as a single column char

![screenshot](https://cloud.githubusercontent.com/assets/715238/19123507/d28093de-8b26-11e6-8ffe-f1ed3e4d28d7.png)

What system are you on and what fonts are you using?

**Comment by bronzehedwick** [comment]
Thanks for the sign appending tip! Much easier to debug. I am using the Inconsolata for Powerline Mod font.

**Comment by bronzehedwick** [comment]
I also tested with Monaco, with similar results.

![screen shot 2016-10-06 at 4 16 25 pm](https://cloud.githubusercontent.com/assets/637174/19168925/42d473da-8be0-11e6-9c9b-68c79148d404.png)

**Comment by jgehrig** [comment]
Tested as working with `v0.2.16`.

Wide characters, and emojis will display in the sign coloumn without truncation.
![image](https://user-images.githubusercontent.com/11207308/91796157-8044f200-ebed-11ea-9b3b-6e9833aabca8.png)

Marking as closed.

**Comment by lgeo3** [comment]
I am still observing the issue, if I am on the line where I insert the sign when I insert the sign

Here is a screenshot where we see that the sign column is truncated


![Capture d’écran 2022-01-12 à 16 30 38](https://user-images.githubusercontent.com/2479539/149170767-3bc0167d-aab1-4d2f-b258-758e5e11733d.png)

When editing the sign in my init.vim I observe the same issue (i.e sign is truncated)
![Capture d’écran 2022-01-12 à 16 32 47](https://user-images.githubusercontent.com/2479539/149170971-c46ec8ad-2972-4749-8576-7b3e7295f2b1.png)

After a refresh (for example pressing escape to return to normal mode when editing the init.vim) get me the character not truncated.

![Capture d’écran 2022-01-12 à 16 34 36](https://user-images.githubusercontent.com/2479539/149171281-395cfd5b-aa79-4f95-9498-4e87e2a58918.png)


My Guifont: Fantasque Sans Mono:h16
the sign used is U+274C

(I am currious about the sign you use in your screen @jgehrig  it looks nice for breakpoint)
