### ISSUE TITLE
Building with MSVC 2015

### ISSUE THREAD

**Issue by Herz3h** [equalsraf/neovim-qt#196]
I can't manage to build this project with QT 5.7 x86 and MSVC 2015 Community, i get a lot of unreferenced errors to QT functions such as toUtf8 etc...

I have Qt in my env PATH.

Followed the instructions on the README for Windows x64.

**Comment by equalsraf** [comment]
@Herz3h  can you provide some more details, like an error log.

We do build with MSVC regularly in appveyor, here is the [build script](https://github.com/equalsraf/neovim-qt/blob/master/contrib/appveyor-msvc.bat), and the [build log](https://ci.appveyor.com/project/equalsraf/neovim-qt/branch/master/job/my2mtblokm4j81c0)

**Comment by Herz3h** [comment]
Well using that build script, all worked, would be nice to mention that in the README i think. Thanks @equalsraf
