### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by RedX2501** [equalsraf/neovim-qt#20]
Trying to compile this under windows but it is failing.

Cmake aborts with the following message:

    By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
      has asked CMake to find a package configuration file provided by
      "Qt5Widgets", but CMake did not find one.

      Could not find a package configuration file provided by "Qt5Widgets" with
      any of the following names:

        Qt5WidgetsConfig.cmake
        qt5widgets-config.cmake

      Add the installation prefix of "Qt5Widgets" to CMAKE_PREFIX_PATH or set
      "Qt5Widgets_DIR" to a directory containing one of the above files.  If
      "Qt5Widgets" provides a separate development package or SDK, be sure it has
      been installed.

I guess i need the Qt5 sources? Is it not possible to just use the windows binaries for Qt?

It would be nice if windows compilation instructions could be added.

**Comment by equalsraf** [comment]
> I guess i need the Qt5 sources? Is it not possible to just use the windows binaries for Qt?

CMake seems to be failing to find your Qt installation. Are running CMake a regular cmd console or the Qt shell? If you are running from a normal console did you run qtenv2.bat?

**Comment by RedX2501** [comment]
I'm using cmake-bin from my windows installation. I have installed qt-opensource-windows-x86-msvc2013-5.4.1 binaries. Do i need the source code distribution?

**Comment by equalsraf** [comment]
No you don't need the source, but if you are in the console you need to initialize the Qt environment otherwise CMake cant find it.

1. If you start cmake from the Qt command prompt it should work
1. Or from a regular cmd console you need to run qtenv2.bat (yours should be a bit different e.g. C:\Qt\Qt5.3.0\5.3\mingw482_32\bin\qtenv2.bat) and vcvarsall.bat
1. Alternatively you can try using Qt creator to import the CMake project (I have not tried this)

**Comment by RedX2501** [comment]
Using the 'VS2013 x86 Native Tools-Eingabeaufforderung' and executing the qtenv2.bat and using the command line provided with the appveyor.yml i was able to build it. I also did the first party initalizing third-party libs.

It seems to have build. I am using the version form appveyor directly now.
