### ISSUE TITLE
Process does not get "backgrounded" when launched from terminal

### ISSUE THREAD

**Issue by StuntsPT** [equalsraf/neovim-qt#200]
This is more of a wishlist item than a bug, but here it is:

When I launch `gvim` from the terminal, I can use it to edit files, but it will automatically "background" itself and I can keep using the shell and `gvim` will continue to run, even if I close the terminal.
This currently does not happen with `nvim-qt`, which when launched from the terminal will "hog" the prompt. Furthermore, if the terminal window is closed, the `nvim-qt` process is also killed.
It would be really awesome if `nvim-qt` could behave like `gvim` in this regard.

**Comment by rdnetto** [comment]
For wisdom of the ancient purposes, one workaround is `alias nvim-qt='nohup nvim-qt'`.

**Comment by StuntsPT** [comment]
While I appreciate the suggestion, doing that a second time will result in a white window instead of having nvim-qt display the contents of the file...

Just for the record I am currently using another "wisdom of the ancients" workaround, which is:

```bash
function qvim {
    nvim-qt --geometry 800x600 -- "$@" &
}

alias qvim=qvim
```

It allows me to open a file and keep working on the terminal, but closing the shell will also kill nvim-qt, so it's not yet a perfect solution.

**Comment by equalsraf** [comment]
If you are running the latest version from master the process should go into the background.

If for some reason you want to keep in the foreground use '--nofork'.

**Comment by StuntsPT** [comment]
Just tested this and works great! Thank you!
