### ISSUE TITLE
Default window size is too small

### ISSUE THREAD

**Issue by ctuffli** [equalsraf/neovim-qt#201]
Running either latest from github or the v0.2.3, the application opens a 200x100 window. This didn't happen in the previous version (v0.2.2). Is this the expected behavior running ```nvim-qt filename```?

System specifics:
OS: FreeBSD 12.0-CURRENT
Xorg 1.18.4
QT 5.6.1
neovim 0.1.4

**Comment by icaroperseo** [comment]
The following code:

```call GuiWindowMaximized(1)```

within of `~/.config/nvim/ginit.vim` does not the trick for you?

**Comment by equalsraf** [comment]
> Is this the expected behavior running

No I don't expect it is, unless you have a very small screen. The default window size should be 0.66*screensize, minus some rouding adjustments.

The window manager can override this, what WM are you using?

**Comment by DavidWhit** [comment]
Doesn't qt support -qwindowgeometry wxh+leftoffset_topoffset? This at least worked for me.

**Comment by MattMS** [comment]
Can confirm similar issue on Windows 10, but only on first execution.
Running the application again gives the standard Vim window size.

**Comment by ctuffli** [comment]
This is using the Lumina desktop (https://lumina-desktop.org/) on FreeBSD.

**Comment by istinkatruby** [comment]
I have encountered this recently as well on KDE Neon.  I've noticed that commenting out my Guifont line in my init.vim starts the window at a more reasonable size. 

Here's the two sizes I'm dealing with, the tiny window has Guifont set:

![screenshot](https://cloud.githubusercontent.com/assets/300517/19795392/15511948-9ca9-11e6-832c-863321db7915.png)

**Comment by ctuffli** [comment]
Couple of updates:
- Regarding @icaroperseo comment, adding that line does open a full screen sized window, but I was hoping for something closer to the 0.66*screensize described by @equalsraf 
- Built the app in debug mode, but the output doesn't seem relevant
```
[ctuffli@chuck-laptop] ~/dev/neovim-qt/build% ./bin/nvim-qt
Unknown Neovim function "Dictionary vim_get_color_map()"
Unknown Neovim function "Array vim_get_api_info()"
```

**Comment by ctuffli** [comment]
Updated to the latest version of Lumina (1.1.1) and the issue has gone away.
