### ISSUE TITLE
Command line parameter for forking the gui process

### ISSUE THREAD

**Issue by osa1** [equalsraf/neovim-qt#203]
`qvim` by default forks the process so I can run it in a terminal and then close the terminal without closing `qvim`. Doing the same thing in `neovim-qt` would be great.

I tried adding a `--fork` parameter and then

``` cpp
    if (parser.isSet("fork")) {
        if (fork()) return 0;
    }
```

but it failed, probably because it's not possible to create a Qt context in one process and then use it in another. I'm a noob in C++/Qt so I may be talking nonsense though ...

**Comment by justinmk** [comment]
Why not do this by default?

**Comment by osa1** [comment]
That'd work fine for me.. I just thought that there may be a reason why this is not default by now and did not want to break existing workflows.

**Comment by justinmk** [comment]
`:help gui-fork` in gvim gives an example of why non-forking would be used: when spawned from some program that wants to wait (e.g. `git commit`).

```
                                                        gui-fork
When the GUI is started, it does a fork() and exits the current process.
When gvim was started from a shell this makes the shell accept further
commands.  If you don't want this (e.g. when using gvim for a mail program
that waits for gvim to exit), start gvim with "gvim -f", "vim -gf" or use
...
"gvim --nofork" does the same as "gvim -f".
```

gvim forks by default and provides `--nofork`. Maybe that is best.

**Comment by equalsraf** [comment]
Qt is not very helpful when it comes to forking into the background. A simple fork when using QApplication can crash the child. I see a couple ways to go about it

1. quickly check for --nofork, fork() immediately,  and have the child inherit stdout. Easy, but not very hygienic when it comes to terminal output.
1. Check CLI args for correctness, re-execute the nvim-qt binary with --nofork in argv. But we need to do CLI argument parsing twice.

Note that in windows, and Mac OS the process is already sent to background.

**Comment by suy** [comment]
Not something that I use often, buy why implement this in a GUI app? What does it give you that `nohup app &` doesn't?

**Comment by equalsraf** [comment]
This is fixed in the latest release. Forks by default in UNIX, use --nofork to override.

**Comment by zoresvit** [comment]
@equalsraf is there a way to achieve the same in MacOS? I'd like it to detach from the terminal when I launch nvim-qt in specific directory.

PS: Thanks for nvim-qt and homebrew formula for MacOS!

**Comment by equalsraf** [comment]
> @equalsraf is there a way to achieve the same in MacOS? I'd like it to detach from the terminal when I launch nvim-qt in specific directory.

Not entirely sure if it is safe to change [this](https://github.com/equalsraf/neovim-qt/blob/master/src/gui/main.cpp#L62). In think in Mac OS X the system launcher expects it to stay in the foreground - no harm in testing though.

Worst case scenario, either add a --fork or find a way to check if are being launched from a terminal.

**Comment by equalsraf** [comment]
Cleaning up, moved to https://github.com/equalsraf/neovim-qt/issues/731

**Comment by BatmanAoD** [comment]
Does the Windows binary not include this? When I pass `--nofork` to `nvim-qt.exe`, I get a pop-up saying `Unknown option: 'nofork'.`

I'm using v0.2.16.1 installed with Scoop.

**Comment by equalsraf** [comment]
@BatmanAoD there is no `fork` api in windows, which is why the option never existed there.

> The current behavior is that PowerShell forks nvim-qt while Git Bash and cmd.exe do not.

That is surprising. I know powershell has commands to start processes, but I was not expecting it to do it by default, and i dont know how it determines how to start the process.
