### ISSUE TITLE
Broken mapping in visual mode

### ISSUE THREAD

**Issue by ferranpm** [equalsraf/neovim-qt#204]
```
vnoremap > >gv
vnoremap < <gv
```

I have these mappings to indent/unindent multiple times without having to reselect the region. The first one works fine. The second one unindents the region but then the visual selections breaks. It works fine in the console.

This is in Archlinux with a US keyboard.
I've installed neovim-qt from the package in AUR
Qt version 5.7.0
Using this version: v0.2.2

**Comment by amagee** [comment]
Same issue here:

Ubuntu 16.10
Qt 5.6.1
Nvim 0.2.0-dev
Neovim-qt from source: revision 4015d8cc5b75b56ffa758be115ea3309c58058b6
