### ISSUE TITLE
Cursor and CursorLineNr highlighting not working

### ISSUE THREAD

**Issue by sprout42** [equalsraf/neovim-qt#207]
When using neovim-qt, the Cursor and CursorLineNr highlighting does not match standard (GTK) gvim.  When using terminal neovim the highlighting matches standard terminal vim.

![image](https://cloud.githubusercontent.com/assets/493589/19972274/d65eff98-a1b7-11e6-8b9c-c6d11695dc65.png)

Here are the cursor highlight rules in my colorscheme:
```
hi Cursor cterm=reverse gui=reverse ctermbg=NONE guibg=NONE ctermfg=NONE guifg=NONE
hi CursorLine term=underline cterm=underline guibg=#282828
hi CursorLineNr term=underline cterm=underline guifg=Grey guibg=#282828
```

**Comment by Cypress-the-Kinaesthetician** [comment]
Any updates on this. I haven't found a way to change the cursor. I just want default vim functionality where it's like inverted from the color beneath it. Literally the only thing that bothers me about neovim-qt.

**Comment by jgehrig** [comment]
See Pull #520, this is likely fixed. Will test.

**Comment by jgehrig** [comment]
The `guicursor` option is available as of `v0.2.16`.

Color behavior is slightly different with Neovim, you need to explicitly specify the highlight group. For example:
`n-v-c-sm:block-Cursor/Cursor`.

Marking as closed.

**Comment by MIvanchev** [comment]
I am still having this issue in self-compiled v0.2.16.1, it is not fixed.

**Comment by MIvanchev** [comment]
OK, so I took a quick look at the code, I think neovim-qt has to trigger an update (redraw) to the line number cells whenever the cursor position is updated.

**Comment by MIvanchev** [comment]
My mistake, `:set cursorline` disappeared from my config... everything works.
