### ISSUE TITLE
It'd be nice to be able to configure the cursor appearance.

### ISSUE THREAD

**Issue by sprout42** [equalsraf/neovim-qt#208]
In normal gvim you can configure the blink rate and appearance of the cursor with the `guicursor` setting.  This of course does not work in neovim.

It would be nice to be able to make the cursor blink in neovim-qt.

**Comment by maxigaz** [comment]
Any progress on this? I read that guicursor "works in the TUI (and sends info to UIs)" in the release notes of neovim v0.2.0. I wonder if this allows neovim-qt to have blinking enabled.

**Comment by sprout42** [comment]
I hadn't checked on the cursor behavior in quite a while. `guicursor` does work for me in neovim.  The original reason I made this issue was due to the fact that the neovim-qt cursor colors were not behavior as specified in my theme.

But as I haven't used neovim-qt in quite a while due to a platform change, I don't know if this is still the case.

**Comment by zdm** [comment]
Hi,
no progress with this issue?

**Comment by sez11a** [comment]
I'm interested in this issue as well. I like my cursor to blink in insert mode, which works in regular Neovim, but not in Neovim-qt.

**Comment by jgehrig** [comment]
See Pull Request #623

`set guicursor` is not supported by neovim-qt.

**Comment by justinmk** [comment]
> `set guicursor` is not supported by neovim-qt.

Do you mean "now" instead of "not" ?
