### ISSUE TITLE
How to disable touchpad?

### ISSUE THREAD

**Issue by yashamon** [equalsraf/neovim-qt#209]
How does one completely disable touchpad input, clicking and scrolling. (all modes)
set mouse=
does nothing. Is this not implemented?

**Comment by equalsraf** [comment]
Currently not implemented i.e. all mouse events are forwarded to Neovim. 'mouse' is not being respected. The GUI does receive the necessary Neovim events mouse_on/_off, this can be implemented in shell.cpp.

**Comment by Leandros** [comment]
Push?

**Comment by equalsraf** [comment]
I've opened #461 for this. Anyone up for testing this?

**Comment by equalsraf** [comment]
Merged #512 into master, have a look and let me know if i missed something.

**Comment by equalsraf** [comment]
#512 was merged, let me know if i need to reopen this.
