### ISSUE TITLE
Window startup size

### ISSUE THREAD

**Issue by RedX2501** [equalsraf/neovim-qt#21]
When i startup the window is quite small, about 210x130 px. Is there a way to configure the startup size?

The greates problem is that i cannot see the error messages, just some gibberish pixels:

![2015-05-28_14-13-54](https://cloud.githubusercontent.com/assets/929932/7859728/cf89de0c-0543-11e5-9775-0f8f97d4847b.png)

This is also the startup size.

**Comment by equalsraf** [comment]
For the moment no, this bug is a consequence of #4.
