### ISSUE TITLE
Key mapping not working

### ISSUE THREAD

**Issue by carl0m** [equalsraf/neovim-qt#210]
I have the following mapping which works in neovim, but not in neovim-qt.  This is for typing in latex.

inoremap <buffer> `< \leq

**Comment by HeLiBloks** [comment]
I have a mapping issue as well works in nvim but not in nvim-qt:
this persists on Windows and Linux 
nmap Ä {

**Comment by jgehrig** [comment]
This looks like was caused by incorrectly encoding `<` as `<S-lt>`. See Issue #607 and Pull #612.

The fix should be available as of `v0.2.16`. Marking the issue as closed.
