### ISSUE TITLE
Command notification

### ISSUE THREAD

**Issue by ferranpm** [equalsraf/neovim-qt#211]
Hi, 

I'm trying to implement a project tree view. So far I can change the neovim working directory and open files from the tree but I'm having trouble changing the directory from the command line inside neovim.

Is there a way to detect when the user has finished a command? Or even better, when the directory inside the neovim instance has changed?

I've tried with some of the signals like `on_vim_change_directory`, `on_nvim_set_current_directory`, `on_(n)vim_command` `on_nvim_command_output` but none of them seem to be called when I perform a `:cd /whatever/directory` from within neovim.

Thanks

**Comment by equalsraf** [comment]
The signals on_vim... ate triggered after a corresponding call to the API function, only. So they do not get called when you do a :cd.

Writing this kind of extensions is the same as writing a regular Neovim plugin. You can see a simple example in src/gui/runtime, it notifies the GUI when the user calls the Gui related commands. Usually rpcnotify() is called in Neovim, and the UI code calls vim_subscribe() before it can receive events and listens on the Neovim::neovimNotification signal.

I'm unsure about the best way to track the current directory, I dont think there is an autocommand group for that. Also the current directory may change per tab too (:h tcd), so you might want to update the tree view when swiitching the current buffer/tab too.

**Comment by justinmk** [comment]
@equalsraf Adding a `DirChanged` autocmd is on the todo list for nvim core, it's also needed for the ruby provider.

**Comment by equalsraf** [comment]
@ferranpm a DirChanged event added to the master branch of neovim, https://github.com/neovim/neovim/pull/5961 it should help you with your problem.

I'm closing this issue since this seems to be covered.
