### ISSUE TITLE
Font don`t change by GuiFont if it called from ~/.config/nvim/init.vim

### ISSUE THREAD

**Issue by BjornMelgaard** [equalsraf/neovim-qt#213]
If I set font when nvim-qt already loaded by `:GuiFont DejaVu Sans Mono for Powerline:h10` - it will change, but if I do the same from init.vim - it will not
P.S. [RenatoUtsch/dotnvim](https://github.com/RenatoUtsch/dotnvim) distribudion
```
let g:settings = {}
let g:settings.version = 1
let g:settings.colorscheme = 'base16-railscasts'
source ~/.config/nvim/dotnvim/init.vim
GuiFont DejaVu Sans Mono for Powerline:h10
```

**Comment by BjornMelgaard** [comment]
And can you give me a cue, how can I set `GuiFont DejaVu Sans Mono for Powerline:h10` only when neovim-qt running? 
I searched myself and fave not found clear answer: `has("gui_running")` dont work

**Comment by justinmk** [comment]
It has to be in ginit.vim. There are other issues discussing this.

has("gui_running") is a known issue, we'll address it in nvim core.

**Comment by BjornMelgaard** [comment]
@justinmk it's beautiful, thnks)
