### ISSUE TITLE
PGP git commit signing fails

### ISSUE THREAD

**Issue by bronzehedwick** [equalsraf/neovim-qt#214]
First of all, thanks so much for the wonderful app!

I noticed an issue with git commit signing. I have my git commits automatically signed via `.gitconfig`, and use fugitive to use git from neovim. However, in neovim-qt, it fails, with an error like: `gpg failed`. This doesn't happen with regular, terminal neovim.

Thanks so much!

**Comment by xelra** [comment]
@bronzehedwick GPG needs the signee to own the tty. For example, you can't login as user a and then su to user b and sign commits as user b, because the tty is still owned by user a. Maybe that applies to your specific problem.

**Comment by bronzehedwick** [comment]
This was indeed the issue. Closing, thanks.
