### ISSUE TITLE
Copy/paste using Ctrl-Shift-c, Ctrl-Shift-v

### ISSUE THREAD

**Issue by danihodovic** [equalsraf/neovim-qt#215]
I regularly copy and paste using Ctrl-Shift-c, Ctrl-Shift-v into the vim command window (`:Here`). This works fine in terminal neovim, but fails in nvim-qt. Instead it generates a caret symbol `^`.

Is it possible to enable/map this functionality somehow?

**Comment by equalsraf** [comment]
This is bug. Actually a duplicate #170.

**Comment by danihodovic** [comment]
Since it's a duplicate I'll close this.
