### ISSUE TITLE
Received unexpected redraw arguments, expecting list QVariant(QByteArray, "redraw")

### ISSUE THREAD

**Issue by kierun** [equalsraf/neovim-qt#216]
Since updating the latest neovim (NVIM v0.2.0-144-g02a9824), I am getting this error at random times:

```
Received unexpected redraw arguments, expecting list QVariant(QByteArray, "redraw")
Received unexpected redraw arguments, expecting list QVariant(QByteArray, "redraw")
```

It seems to happen when there is an error in neovim -- in the latest case, a `vim-airline` one.

Do you need more information?

Any idea what could be causing this?

**Comment by kierun** [comment]
Neovim master branch commit [75c18b6aaa](https://github.com/neovim/neovim/commit/75c18b6aaa8430596fa10466dc7918047b13ff2b) is a last safe commit. Apparently, everything after that introduced bugs -- [Source](https://github.com/neovim/neovim/issues/5774#issuecomment-267239861). This might be a cause of instability.

**Comment by equalsraf** [comment]
The error message comes from https://github.com/equalsraf/neovim-qt/blob/master/src/gui/shell.cpp#L530 it expects the redraw op arguments to be a list. But for some reason it gets byte array "redraw", seems strange, could be an issue on our part.

**Comment by jgehrig** [comment]
Fixed, marking as closed.

**Comment by kierun** [comment]
It is back. I am getting a fair few of these, generally in pairs:

```bash
Received unexpected redraw arguments, expecting list QVariant(QByteArray, "redraw")
Received unexpected redraw arguments, expecting list QVariant(QByteArray, "Gui")
```

And some debug information:

```
√ ; nvim-qt --version
NVIM-QT v0.2.18.9999
Build type: Release
Compilation: -Wall -Wextra -Wno-unused-parameter -Wunused-variable -std=c++11
Qt Version: 5.15.6
Environment:
  nvim: nvim
  args: --cmd let &rtp.=',/home/yann/bin/../share/nvim-qt/runtime' --cmd set termguicolors
  runtime: /home/yann/bin/../share/nvim-qt/runtime

NVIM v0.8.0-v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by yann@nightwatch.neverness.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/yann/nvim/share/nvim"

Run :checkhealth for more info
```

Anything else I can do to help?
