### ISSUE TITLE
GUI options not working

### ISSUE THREAD

**Issue by felixendres** [equalsraf/neovim-qt#217]
Hi,
I just tried neovim (from ubuntu pacakge) and neovim-qt (cloned master). Looks nice, feels snappy. 
However I ran into two problems:
 - has('gui_running') doesn't seem to work.
- The following function says "E684 list index out of range: -1" and  "invalid expression `l:font[-1] +1`"
```
function! EnlargeFont()
    let l:font=split( &guifont )
    let l:font[-1] = l:font[-1] + 1
    let &guifont=join( l:font, ' ' )
endfunction

```
The second problem is actually the same in "console" nvim, but since that doesn't control the font, I guess this is the right place to report it. 
I copied that function from somewhere and am quite happy with it. Is there a way I can achieve the same 
thing in neovim-qt. Preferrably without breaking vim-gtk?

**Comment by suy** [comment]
Both are known facts, are and not bugs, but features. When the "core" starts, it is spawned by a GUI, yes, but the GUI has not attached yet to that core, so there is no possibility to know that a GUI will attach later. At least not in the current design. Also, the guifont feature is removed from neovim, but (probably by oversight) the documentation is not updated.

But you probably raise a valid point with respect to the discoverability of certain things.

**Comment by felixendres** [comment]
Thanks, maybe the gui then needs to reparse the vimrc to apply the gui related settings.
