### ISSUE TITLE
Gui detect when has('gui_running') equals 0

### ISSUE THREAD

**Issue by iamkarlson** [equalsraf/neovim-qt#219]
I'm aware of #50 and #83, and many many more. But still, is there is any way to run my gui settings in neovim-qt? There is no any information in docs or wiki that's implemented or not, I tried a lot of. What did I try:

```
has('gui_runnning')
exists('g:Gui')

~\.config\nvim\ginit.vim
~\.gvimrc
```

I'm using windows and my :version is v.0.2.0-15-g0e1c406
Kindly give me any information what I can try else, cause it's too difficult to find proper info for nvim-qt exactly

**Comment by suy** [comment]
There is no wiki page or readme file about this, but yes. Check other issues. Or even #158.

**Comment by iamkarlson** [comment]
Already check, without success. #158 result:

```
:echo has('nvim')
1
:echo exists('g:GuiLoaded')
0
```

**Comment by equalsraf** [comment]
This one should work, as a command  or from ginit.vim

```vim
:echo exists('g:GuiLoaded')
```

Are you building from source or using one of the packages?

**Comment by iamkarlson** [comment]
@equalsraf yes, it works, but only after loading vimrc. I tried script like mentioned in #158 but no success

**Comment by equalsraf** [comment]
> @equalsraf yes, it works, but only after loading vimrc

This is to be expected, the GUI only opens AFTER init.vim has been processed, so it cannot handle the font change in init.vim.

Instead put those commands in .config/nvim/ginit.vim - all GUI related options and commands should work there.

**Comment by iamkarlson** [comment]
Yes! Thank you! it works.
