### ISSUE TITLE
"Invalid font height" error on non-integer font heights

### ISSUE THREAD

**Issue by whitelynx** [equalsraf/neovim-qt#221]
Running the following command in neovim-qt (on `master` from a few minutes ago) gives an "Invalid font height" error:
```vim
GuiFont Input Mono:h10.5
```

----

According to the `guifont` help in `options.txt`:
```
	- takes these options in the font name:
		hXX - height is XX (points, can be floating-point)
```

However, according to the help for the `GuiFont` command in `neovim_gui_shim.txt`:
```
		The following attributes are available

			hXX - height is XX in points
```
with no mention of whether or not it may be floating-point.

----

The reason I need floating-point sizes is because this is setting the font size with _points_, not _pixels_. In order to match what my terminal is set to (14 pixels high), I need something between 10 and 11 points, which I currently can't do.

**Comment by sliceofcode** [comment]
@whitelynx Here is a hacked-up patch that makes `h12` mean 12 pixels, not 12 points.

```patch
From 5f5ddd400084ab8d6e42b5000e4fe41aea639fb8 Mon Sep 17 00:00:00 2001
From: sliceofcode <cheesy.fried.bacon@gmail.com>
Date: Thu, 1 Dec 2016 23:05:23 -0800
Subject: [PATCH] Set font size using pixels instead of points

---
 src/gui/shellwidget/shellwidget.cpp | 5 +++--
 1 file changed, 3 insertions(+), 2 deletions(-)

diff --git a/src/gui/shellwidget/shellwidget.cpp b/src/gui/shellwidget/shellwidget.cpp
index c444f15..17431d8 100644
--- a/src/gui/shellwidget/shellwidget.cpp
+++ b/src/gui/shellwidget/shellwidget.cpp
@@ -34,9 +34,10 @@ void ShellWidget::setDefaultFont()
 #endif
 }
 
-bool ShellWidget::setShellFont(const QString& family, int ptSize, int weight, bool italic, bool force)
+bool ShellWidget::setShellFont(const QString& family, int pxSize, int weight, bool italic, bool force)
 {
-	QFont f(family, ptSize, weight, italic);
+	QFont f(family, 0, weight, italic);
+	f.setPixelSize(pxSize);
 	f.setStyleHint(QFont::TypeWriter, QFont::StyleStrategy(QFont::PreferDefault | QFont::ForceIntegerMetrics));
 	f.setFixedPitch(true);
 	f.setKerning(false);
```

**Comment by equalsraf** [comment]
Indeed, the setGuiFont method parses the argument as an integer, not a float. setShellFont would also need to take a float as an argument in ptSize.

**Comment by equalsraf** [comment]
@sliceofcode the patch actually changes it use pixel sizes, which I dont think is the intended effect. I would still requiring changes to the setGuiFont function.

**Comment by whitelynx** [comment]
Actually, if it supported setting the font size in pixels as well as points, that would be ideal. Maybe have it recognize `p12` or `H12` or `x12` as 12 pixels?
