### ISSUE TITLE
neovim-qt does not support option "-S" or "-c"

### ISSUE THREAD

**Issue by xeyownt** [equalsraf/neovim-qt#224]
vim/gvim/nvim supports option `-S {file}` to specify a file that is sourced after the first file has been read. The same way they support option `-c {command}` to execute a command. One use case for this is to restore session file.

Currently neovim-qt does not support these options. Both give the error message `Unknown option '...'.`

**Comment by equalsraf** [comment]
nvim-qt simply calls the nvim command. You can forward additional arguments directly to nvim after "--" e.g.

    nvim-qt filename -- -S file.vim

which is the same as

    nvim-qt -- -S file.vim filename

internally this calls

    nvim -S file.vim filename

**Comment by xeyownt** [comment]
Ok, excellent. Rather obvious in fact. Tx for quick reply, I close the issue.
