### ISSUE TITLE
N nvim process spawned after clicking "Retry" N times

### ISSUE THREAD

**Issue by jamessan** [equalsraf/neovim-qt#227]
While testing out some nvim crashes, I noticed that nvim-qt lets you respawn after nvim crashes, so I tried that.  The fun part is that N nvim instances are spawned for the Nth time the "Retry" button is used.

0. Start nvim-qt
1. Make nvim crash
2. Click "Retry"
3. 1 nvim started
4. Make nvim crash
5. Click "Retry"
6. 2 nvims started
7. Make nvim crash (the other nvim is still running)
8. Click "Retry"
9. 3 nvims started (4 total running)
10. ...

**Comment by equalsraf** [comment]
Patching this. The reconnect signal was being connected again and again with each call to MainWindow::init() causing multiple signals to be emitted later.

While its clear why the process was being spawned multiple times, I still find it a bit surprising that the extra child processes remained alive. I expected the eventual desctructor call to kill the process as well.
