### ISSUE TITLE
Error when used together with typescript-tools plugin

### ISSUE THREAD

**Issue by danihodovic** [equalsraf/neovim-qt#23]
I'm not aware of how far this project has come, but I assume it should be handle plugins as the ones I've tried work decently. The Typescript plugin I use however fails to start. It communicates with a CLI server that provides syntax highlighting and autocomplete suggestions (clausreinke/typescript-tools.vim).

Error message when calling `:TSSstarthere`:

```
starting TSS...
['tss', 'stores.ts']

Error detected while processing function TSSstart..TSSshowErrors:
line   21:
TSS not running - start with :TSSstarthere on main file
```

I am not a vim expert, but it seems to point to `function! TSSstart(...)` at line 466 here: https://github.com/clausreinke/typescript-tools.vim/blob/master/ftplugin/typescript_tss.vim#L466

**Comment by equalsraf** [comment]
Does this also happen when running Neovim without the GUI?

**Comment by dani-h** [comment]
No, I've tried it in both the terminal and using the python client.

**Comment by equalsraf** [comment]
Cannot replicate, it just loads and runs the background tss process

```
"loaded /tmp/test.ts, TSS listening.."
```

I did however get a similar error if the typescript file was not saved yet (both with and without the GUI). 

Not sure where to go next with this
- Can you add the typescript file?
- Are you running on Windows or Linux?
- Can you add the typescript file here, or does it also happen with an empty file?

**Comment by dani-h** [comment]
It seems to occur if I run the executable nvim-qt in `build/bin` without specifying a file at start, e.g `./nvim-qt` and then editing `:e test.ts`.
If I however do `./nvim-qt test.ts` I have no issues and the server starts normally.

- Xubuntu 14.04 and Lubuntu 15.04
- tss installed globally (`npm install -g clausreinke/typescript-tools`)

**Comment by equalsraf** [comment]
Does it make a difference if you call :w to write the buffer before calling TSSstarthere?

**Comment by dani-h** [comment]
Nope

**Comment by danihodovic** [comment]
Closing since it's a two year old issue and I'm not using `clausreinke/typescript-tools` anymore.
