### ISSUE TITLE
drag and drop file

### ISSUE THREAD

**Issue by justinmk** [equalsraf/neovim-qt#235]
Drag and dropping a file onto nvim-qt seems to have no effect.

Tested on Windows 7 32-bit build.

**Comment by equalsraf** [comment]
I would guess them shim plugin did not load and the `GuiDrop()` is not available.

**Comment by justinmk** [comment]
Oh, that's possible. My setup is a bit messed up. 

I see that GuiLinespace() and GuiFont() exist because nvim doesn't raise UI events for those options (yet). A bit surprised that GuiDrop() would not be implemented internally to nvim-qt, but I see now it's discussed at https://github.com/equalsraf/neovim-qt/pull/169. 

I'll close this then.
