### ISSUE TITLE
neovim-qt doesn't start -- stuck on a gray screen

### ISSUE THREAD

**Issue by sliceofcode** [equalsraf/neovim-qt#239]
Built from source.

**Operating System:** Arch Linux
**Qt Version:** 5.8.0-1
**G++ Version:** 6.3.1

**Neovim Version:** *Latest from head*, 0.1.7.r598.g0e44916ff-1
**Nvim-qt Version:** *Latest from head*, 0d71bdcfd08d2dfff5f70fb3e44a96c49a3a8852

If I do `nvim-qt --fullscreen` it runs fullscreen but it's still stuck on a gray screen.

I have tried:
  - Running a composition manager, since I don't use one. Made no difference.
  - Removing `~/.config/nvim`/`init.vim` Made no difference.

**Comment by justinmk** [comment]
@sliceofcode Does CTRL-L fix the screen? Or resizing the window?

**Comment by equalsraf** [comment]
This sounds a lot like https://github.com/equalsraf/neovim-qt/issues/130

**Comment by sliceofcode** [comment]
@equalsraf Looks like it. I'll close this issue for now and attempt to debug when I have access to my PC.
