### ISSUE TITLE
Rendering/font issue with remote nvim and airline

### ISSUE THREAD

**Issue by xelra** [equalsraf/neovim-qt#246]
On the remote machine I've installed the Hack font and I'm loading `neovim-gui-shim` in the `init.vim`. Locally I've installed the Hack font. When running Neovim-Qt locally, everything is fine.

![untitled2](https://cloud.githubusercontent.com/assets/908568/23112228/0aa01824-f72f-11e6-96c9-3c1deba2f868.png)

When I'm connecting to a Neovim socket on a remote server (through ssh), there are rendering issues with the airline. The Hack font is loaded though. There are powerline glyphs visible in the screenshot too.

![untitled](https://cloud.githubusercontent.com/assets/908568/23112256/43895ae2-f72f-11e6-8567-d02fa479325e.png)

The remote machine is running Arch Linux, the local machine is running Windows 10.

**Comment by equalsraf** [comment]
Possibly related to 'set termguicolors'. For local spawned processes nvim-qt sets it, https://github.com/equalsraf/neovim-qt/pull/151 but for remote connections this is not possible. Does setting termguicolors in the remote init.vim fix this?

**Comment by xelra** [comment]
Adding
```
set termguicolors
```
explicitly to the remote `init.vim` fixed the issue. Thanks.
