### ISSUE TITLE
Quitting a remote session does not quit Neovim-Qt

### ISSUE THREAD

**Issue by xelra** [equalsraf/neovim-qt#247]
When quitting a remote nvim session, Neovim-Qt doesn't quit too. Instead the window stays open and it shows a retry button.

![untitled3](https://cloud.githubusercontent.com/assets/908568/23112419/7e823154-f730-11e6-8bfb-27e42f76ce85.png)

**Comment by equalsraf** [comment]
Yes this was done intentionally in case of a connection break. A possible way to improve this is to have the shim signal a clean shutdown (but the shim plugin is not always available on remote connections).

**Comment by xelra** [comment]
Detecting whether the connection was really lost or whether I locally sent a quit command would be a much appreciated feature.

**Comment by equalsraf** [comment]
#241 was merged, but the autocommand was implemented in the shim. So it does not satisfy this issue completely. We can do better and implement it as part of the GUI initialization in C++ - this removes the for the shim in the remote system.

Adding a couple reminders here for later

- [ ] setup an autocommand to call rpcnotify(0, 'Gui', 'Close') in Shell::setAttached
- [ ] Ideally avoid doing if the shim has loaded, to avoid getting two notifications
