### ISSUE TITLE
Include version/build number in nvim-qt.exe

### ISSUE THREAD

**Issue by christianrondeau** [equalsraf/neovim-qt#255]
A small detail but very useful, is to know the version number you are working with.

In Windows, right-click and properties on an executable and dll files supports embedded the "product version" and "file version" (using `AssemblyInfo` in the .NET world, I don't know about QT).

When built and deployed as a release, all dll and exe files should have the published version number (e.g. 0.2.6) so that we can easily know which version we currently have.

This might be another issue, but it would be nice to have a command within VIM to see it too.

**Comment by equalsraf** [comment]
Finally got some time on windows to work this out. #432 has been merged into master. Closing this.

As a side note it is also possible to get this information through nvim using nvim_get_chan_info(), but this depends on nvim 0.3 and also on nvim-qt from the master branch.
