### ISSUE TITLE
:version and thrown errors close when qt window loses focus

### ISSUE THREAD

**Issue by christianrondeau** [equalsraf/neovim-qt#256]
Replication:

1. Open nvim-qt (version 0.2.6)
2. Type in `:version`
3. Click on another window
4. The `version` window disappears

Same problem with `throw 'something'`.

This is very frustrating when you are trying to type some information in another window, since as soon as you switch to the other window, the message disappears :)

**Comment by justinmk** [comment]
This is a nvim bug, not nvim-qt. And it's already reported , fwiw

**Comment by christianrondeau** [comment]
Right, I found it: https://github.com/neovim/neovim/issues/4840 and https://github.com/neovim/neovim/issues/3416

Sorry about that, I was sure interaction with mouse was controlled by neovim-qt (it's hard to guess where to create issues, thanks for responding)
