### ISSUE TITLE
:GuiFont "Not an editor command: GuiFont"

### ISSUE THREAD

**Issue by mynameisdaniil** [equalsraf/neovim-qt#257]
`GuiFont` and variations are not recognized as editor command. How do I set gui font?
I'm using current muster 7b4bbbc53e0fe23b6ec606e7f17669b3918e5c5f, if it helps

**Comment by equalsraf** [comment]
It looks like the runtime vim scripts were not loaded. 

Usually nvim-qt loads the runtime scripts from /usr/share/nvim-qt/runtime (unix) or from a relative path in Windows. Or from a path in the environment var $NVIM_QT_RUNTIME_PATH.

- are you building from source or running a pkg
- what system are you using, windows, linux?
- can you share your nvim `&runtimepath`?

**Comment by mynameisdaniil** [comment]
Well. I though it is self-contained binary. There is nothing in the readme to indicate that I need to copy some files somewhere.
I'm using linux and I'm building from source (I haven't found PPA).

**Comment by equalsraf** [comment]
make install would place the files in the correct location. Concerning pkg there is an out of data pkg in [zesty](http://packages.ubuntu.com/search?keywords=neovim-qt&searchon=names) (also in debian).

**Comment by mynameisdaniil** [comment]
Ok, I've just copied contents of `runtime` into `$XDG_CONFIG_DIRS/nvim/` and it works. Thank you.
