### ISSUE TITLE
Window requires second input to close

### ISSUE THREAD

**Issue by cjmeyer** [equalsraf/neovim-qt#258]
With the latest version of NeoVim and NeoVim-Qt, on Windows 10, a second input is required to close the window when exiting using either :q! or clicking on the X.  Second input can be anything, including a key stroke.

I did find the related issues #53, and neovim/neovim#4703, however, they have been closed and seem to apply to a different combination of versions which I can't verify.

I see the issue on Windows 10, running the NeoVim nightly build v0.2.0-998-g93de182b (which I believe is build 1405) and the packaged NeoVim-Qt.  I also tried replacing the packaged NeoVim-Qt (and Qt libraries) with v0.2.6 from https://github.com/equalsraf/neovim-qt/releases/tag/v0.2.6.

**Comment by justinmk** [comment]
How are you starting nvim-qt? (exact command. or just double-clicking?)

What's the output of `:au VimLeave` ?

What's the output of `:verb func GuiClose` ?

**Comment by cjmeyer** [comment]
I am launching nvim-qt simply by double-clicking.

The output from `:au VimLeave` is:

    :au VimLeave
    --- Auto-Commands ---
    Press ENTER or type command to continue

The output from `:verb func GuiClose` is:

    :E123: Undefined function: GuiClose
    
I get this result with both the nightly of Neovim and the nightly of Neovim overwritten with Neovim-Qt v0.2.6.

**Comment by cjmeyer** [comment]
Oops, sorry, I didn't mean to close it...

**Comment by justinmk** [comment]
well, your runtimepath either is invalid or was modified. Did you follow [this steps](https://github.com/neovim/neovim/wiki/Installing-Neovim#windows) to "install"?

Does the issue occur if you run `nvim-qt.exe -- -u NORC` ?

**Comment by cjmeyer** [comment]
I followed those steps; I didn't perform the optional PATH update nor did I need to install the VCRUNTIME140.dll.

If I run `nvim-qt.exe -- -u NORC`, either from the Neovim bin directory, or from a different directy and specify the full path to `nvim-qt.exe`, it seems to work fine.

My `init.vim` is:

    set runtimepath=~/.vim,$RUNTIME

    call plug#begin('~/.vim/plugged')

    Plug 'equalsraf/neovim-gui-shim'

    call plug#end()

**Comment by justinmk** [comment]
`set runtimepath=~/.vim,$RUNTIME` obliterates the default runtimepath. Use `+=` instead.

**Comment by cjmeyer** [comment]
I made the suggested change; same issue.

If I comment out `plug#begin` and `plug#end` then it starts to work.

**Comment by justinmk** [comment]
Then something else is in your config is modifying the runtimepath.

**Comment by cjmeyer** [comment]
Is there a way to get information on what happens when `plug#begin` and `plug#end` are called?  Some sort of software trace/log output?
