### ISSUE TITLE
Dirty output when typing Shift together with non-character keys on terminal

### ISSUE THREAD

**Issue by hkupty** [equalsraf/neovim-qt#259]
I'm running nvim-qt on Arch Linux, built via the aur package.

Whenever I'm on terminal and accidentally press `<S-Space>` or `<S-Backspace>`, a dirty output is printed on the terminal. This doesn't happen on TUI.

![20170329174740](https://cloud.githubusercontent.com/assets/2695819/24476300/2a52db06-14a9-11e7-9d41-b472215b115e.png).

**Comment by hkupty** [comment]
:birthday: :cake:

**Comment by YorickPeterse** [comment]
A sort of hack you can use to work around this is the following:

```vim
tnoremap <S-Backspace> <Backspace>
tnoremap <S-Space> <Space>
tnoremap <C-Backspace> <Backspace>
tnoremap <C-Space> <Space>
```

**Comment by redbmk** [comment]
> 

This worked well for me, but I did end up noticing hitting `Enter` while still holding `Shift` (basically a race condition) caused  some weird characters too, so I added these:

```vim
  tnoremap <S-Enter> <Enter>
  tnoremap <C-Enter> <Enter>
```
