### ISSUE TITLE
GUI-specific config

### ISSUE THREAD

**Issue by Himura2la** [equalsraf/neovim-qt#262]
I need to add a GUI-specific init entity, how to do it for Nvim-Qt?
For example, this one

```vim
let g:airline_powerline_fonts = 1
```

It should be executed only in Nvim-Qt and ommitted in console

I know about the `ginit.vim`, but it seems that nothing except `GuiFont` works in this file... That's the main question - why? I can't even change the colorsheme from `ginit.vim`

I also heard about `if has('gui')`, but it does not seems to work in Nvim-Qt

**Comment by ferranpm** [comment]
If `GuiFont` works, everything else should. Have you tried `echo g:airline_powerline_fonts`? If the output is `1` maybe the problem is in the plugin?. Are you sure any other script is being sourced and overwriting the value? in `after/plugin` or something like that?

**Comment by Himura2la** [comment]
If I set this variable in init.vim, it works. The same for colorscheme. But in ginit - not. So you state that the ginit.vim executes in my case and it's syntax/purpose is exactly the same as init.vim, right?

**Comment by Himura2la** [comment]
umm, yes, I see 1. Strange, I'm really new to vim and I thought it should work.... Thank you
