### ISSUE TITLE
Incorrect cursor position when lines contains CJK characters.

### ISSUE THREAD

**Issue by qwfy** [equalsraf/neovim-qt#266]
when a lines contains Chinese characters, clicking on a character doesn't place the cursor on the clicked character.

in the attached image, if I click the "y" in the "blue sky", instead of placing the cursor on the "y", the cursor is placed on the "天" (indexed by `bc` on line 8).

![nvim-cjk](https://cloud.githubusercontent.com/assets/11158705/25122251/ce847b00-2456-11e7-9661-c94edcf57ae6.png)

OS: Archlinux
neovim-qt version: commit c208c1a1b5b4283dea130dbde589939f11245e3a, built using instructions in `README.md`
```
nvim --version
NVIM 0.1.7
Build type: Release
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.1.7/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by zhaozg** [comment]
@equalsraf Do you have solution, or give me any advice? 
I want to fix this issue.

**Comment by equalsraf** [comment]
Lets see, the mouse click handling is processed [here](https://github.com/equalsraf/neovim-qt/blob/master/src/gui/shell.cpp#L660). The position to cell calculation fails to take into account the presence of double width cells.

```c++
	QPoint pos(ev->x()/cellSize().width(), ev->y()/cellSize().height());
```

The actual cell contents (and double width information) are stored in `ShellContents`.

**Comment by justinmk** [comment]
possibly related: https://github.com/neovim/neovim/pull/5822

**Comment by zhaozg** [comment]
Maybe the chinese character should move to center and middle of CRect.

**Comment by jgehrig** [comment]
This issue no longer reproduces. Tested with nvim v0.4.3 and nvim-qt 0.2.16.

Marking as closed.
