### ISSUE TITLE
cursor shape changing does not work with nvim master

### ISSUE THREAD

**Issue by justinmk** [equalsraf/neovim-qt#267]
https://github.com/neovim/neovim/pull/6539 added a new field to the `mode_change` UI event. Is it possible that caused nvim-qt to ignore the event?

It looks like [this code](https://github.com/equalsraf/neovim-qt/blob/7b4bbbc53e0fe23b6ec606e7f17669b3918e5c5f/src/gui/shell.cpp#L407) expects the `mode_change` UI event to always have exactly 1 item. Why is that?

In `:help api-contract` we recently documented the expectations that clients should have of the API and vice versa. It will help a lot if nvim can add new items to UI events, so that we can start "externalizing" UI components such as popupmenu, tabline, etc., without have to make the event data "perfectly implemented" from the start.

**Comment by equalsraf** [comment]
👍 removed several similar checks to only require the minimum number of arguments in the notification, merged into master

**Comment by justinmk** [comment]
Thanks @equalsraf ! It works. Would you be able to post a release in the next couple days?
