### ISSUE TITLE
neovim-qt.zip for 0.2.7 is same as 0.2.6

### ISSUE THREAD

**Issue by justinmk** [equalsraf/neovim-qt#268]
The 0.2.7 zip on the releases page 

https://github.com/equalsraf/neovim-qt/releases/download/v0.2.7/neovim-qt.zip

appears to be identical to the 0.2.6 zip

https://github.com/equalsraf/neovim-qt/releases/download/v0.2.6/neovim-qt.zip

**Comment by equalsraf** [comment]
sha256sum shows distinct hashes for those two files.

b548f6e4045f16a10163b0e433f05b115b2f877cb47c4eacbf80eaad1a8429ab  neovim-qt(1).zip
90217351e9e51c81ef5bba39066f00d05e15ef1f881882c3c682e61cd446c211  neovim-qt.zip

**Comment by justinmk** [comment]
I'm seeing b548f6e4045f16a10163b0e433f05b115b2f877cb47c4eacbf80eaad1a8429ab now as well. Must have been a cache hiccup somewhere. Thanks!

**Comment by equalsraf** [comment]
that was scary :D
