### ISSUE TITLE
Problem with uppercase accented characters

### ISSUE THREAD

**Issue by einars** [equalsraf/neovim-qt#269]
It seems to be currently impossible to type uppercase (latvian) characters like Ā, Ē, Š — special characters that require shift to be pressed. Everything works just fine in nvim in a terminal (urxvt, arch linux).

To reproduce, you may switch to a latvian keyboard layout (setxkbmap lv) and type altgr-S (observe lower-case š) and altgr-shift-S (observe nothing, Š expected).

InputConv.convertKey builds a <S-Š> representation and that seems to be unsupported/mishandled by nvim.

I worked around the issue by patching input.cpp to prevent any out-of-ASCII-range ( > 127) keys to have shift modifier ever sent, if nvim doesn't seem to support it:

          // Remove SHIFT
    -     if (c.unicode() < 0x100 && !c.isLetterOrNumber() && c.isPrint()) {
    -         mod &= ~ShiftModifier;
    -     }
    +     if (c.unicode() >= 0x80) {
    +         mod &= ~ShiftModifier;
    +     }
          ...

and it seems to be working, but I'm not sure what new cans of worms does it open.

**Comment by einars** [comment]
My original suggestion is buggy and is having issues with some ASCII symbols (shift-' to get a quote stopped working). This one's better:

          // Remove SHIFT
    -     if (c.unicode() < 0x100 && !c.isLetterOrNumber() && c.isPrint()) {
    +     if (c.unicode() >= 0x80 || (!c.isLetterOrNumber() && c.isPrint())) {

**Comment by clason** [comment]
This also happens on a German keyboard with capital umlauts (ÜÖÄ), which don't require any modifier keys (apart from `shift`, of course). Your patch fixes this for me as well.

**Comment by koalefant** [comment]
It is not impossible to type uppercase cyrillic letters on X11 and Windows.

**Comment by MarcelHB** [comment]
Does that referenced commit fix this issue? This is showbreaking for writing Docs/TeXs in German. I greatly appreciate a bugfix release for this.

**Comment by diefans** [comment]
at least for me ÜÄÖ are working now...
