### ISSUE TITLE
Colors in neovim-qt are not as in vim

### ISSUE THREAD

**Issue by RedX2501** [equalsraf/neovim-qt#27]
I'm not sure if this is a problem wtih neovim-qt or neovim reporting the wrong colors.

What I see in neovim-qt is:
![2015-06-23_15-36-37](https://cloud.githubusercontent.com/assets/929932/8307323/5af05884-19be-11e5-90d4-d587ba579063.png)

What i expect to see is (this was taken from vim under cygwin:
![2015-06-23_15-42-29](https://cloud.githubusercontent.com/assets/929932/8307387/7a60ae80-19be-11e5-982e-65c4e1fda22d.png)

If this is a neovim problem i will gladly post it there.

**Comment by equalsraf** [comment]
@RedX2501 how did you get the different colors? are those tab chars being colorized?

**Comment by RedX2501** [comment]
@equalsraf  Oh sorry, I forgot to mention that those are being coloured by [vim-indent-guides](https://github.com/nathanaelkane/vim-indent-guides).

**Comment by equalsraf** [comment]
What settings are you using? I do get different colors in the term and in the gui, but I can adjust the GUI colors using guibg instead of ctermbg.

```
let g:indent_guides_auto_colors = 0
hi IndentGuidesOdd ctermbg=122 guibg=white
hi IndentGuidesEven ctermbg=088 guibg=blue
```

I do get some pretty bad colors for my colorscheme with the default settings, it seems to default to the theme background color.

**Comment by RedX2501** [comment]
Ok it seems the mistake was on my side, for some reason i had set guibg. Since i never use a gui version of vim i never noticed it.

I'm kind of wondering if neovim-qt qualifies as a gui version or if it should use the term colors...

**Comment by equalsraf** [comment]
Since the terminal UI is not running Neovim does not have access to the terminal settings, so we are definitely a GUI or at least `not a terminal`.
