### ISSUE TITLE
Italic Fonts Clipped

### ISSUE THREAD

**Issue by kdurant** [equalsraf/neovim-qt#271]
Font： Source Code Pro
Gvim display like below：
![gvim](https://cloud.githubusercontent.com/assets/2704364/25694032/0c9b7396-30df-11e7-8680-19bb42b1f1f9.png)
Neovim-Qt display like below：
![neovim](https://cloud.githubusercontent.com/assets/2704364/25694037/11e0d51c-30df-11e7-8e69-36689b78f4f4.png)

When the italic is displayed, the upper right corner shows that it is truncated

**Comment by prabirshrestha** [comment]
I have similar problems with sign column fonts too. (use ale for tslint)

Both on win10.

Gvim 8 :
![image](https://cloud.githubusercontent.com/assets/287744/25713775/af74fe6e-30aa-11e7-8c22-5ddb35913e3d.png)

Neovim-Qt:
![image](https://cloud.githubusercontent.com/assets/287744/25713809/c475ea26-30aa-11e7-9091-7ed31503a96b.png)

Font: ubuntu mono from nerd font.

```vim
let g:ale_sign_column_always = 1
let g:ale_sign_error = '✗'
```

**Comment by qwfy** [comment]
Same problem here, I'm using the font `Input`, italic font get chopped of at the top right corner.

**Comment by icaroperseo** [comment]
Same issue here. At some point stopped working, I had not had this situation before.

Previously I used: `Guifont FuraCode Nerd Font:h10`, currently use: `Guifont Inconsolata for Powerline:h11
`

_OS:_ Arch Linux / KDE
_Qt version:_ 5.8
_Neovim version:_ v0.20
_Neovim-qt version:_ 26a6b43

Build options:

```
  cmake .. \
    -G 'Unix Makefiles' \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DUSE_SYSTEM_MSGPACK=ON
    make ${MAKEFLAGS}
```

**Comment by khalidchawtany** [comment]
This could be the same issue https://github.com/equalsraf/neovim-qt/pull/171

**Comment by jgehrig** [comment]
Duplicate #154
