### ISSUE TITLE
Direct Write support?

### ISSUE THREAD

**Issue by harg** [equalsraf/neovim-qt#272]
Does Neovim-qt support Direct Write on Microsoft Windows?

![neovim_directwrite](https://cloud.githubusercontent.com/assets/34398/25696711/7ce4ee24-30b8-11e7-98c8-e167ab4c3c74.png)

**Comment by equalsraf** [comment]
AFAIK Qt does not enable directwrite by default. I think you would need to rebuild Qt to support it.

**Comment by justinmk** [comment]
We don't support windows xp, so should we not enable this by default? [this](http://stackoverflow.com/q/15569167/152142) and [this](http://blog.qt.io/blog/2011/03/14/hint-hint-nudge-nudge-say-no-more/) suggest Windows Vista and later will work.

**Comment by suy** [comment]
According to the changelog of 5.6.0: "DirectWrite support is now the default if available". I checked the latest source, and there is a command line option to disable it.

**Comment by harg** [comment]
Is there any chance that you provide windows build with direct write support in the future? Thanks

**Comment by suy** [comment]
@harg How do you confirm that DirectWrite is not enabled? The rendering output is not very relevant, given that neovim-qt uses it's own way to render text looping over the characters of the line. That will skip shaping features, as I understand it.

**Comment by harg** [comment]
Sorry, i thought that Direct Write was enabled based on the rendering. Is it possible to have the same rendering as Gvim on Windows?

**Comment by equalsraf** [comment]
We don't really have a path forward here. Closing. But feel free to open issues with good approaches that improve this.
