### ISSUE TITLE
Arrow keys broken while in normal mode (OSX)

### ISSUE THREAD

**Issue by coddingtonbear** [equalsraf/neovim-qt#274]
A quick bisect shows that this problem was introduced in c208c1a1b5b4283dea130dbde589939f11245e3a, but glancing at the commit, I can't imagine how.

Because the summary description might not be very descriptive, here are a couple videos showing how the problem exhibits itself:

Not working: https://www.youtube.com/watch?v=EC6gcJ-7aa4&feature=youtu.be
Working: https://www.youtube.com/watch?v=yQNXCi_f868&feature=youtu.be

**Comment by equalsraf** [comment]
Honestly I cant exactly figure out the exact problem from the video :D

Regardless lets have a look at it, with the following patch to track input. I don't have a Mac to test but hopefully someone can help out

```diff
diff --git a/src/gui/shell.cpp b/src/gui/shell.cpp
index f169276..a3a98cc 100644
--- a/src/gui/shell.cpp
+++ b/src/gui/shell.cpp
@@ -587,6 +587,7 @@ void Shell::keyPressEvent(QKeyEvent *ev)
                return;
        }
 
+       qDebug() << "vim_input" << inp;
        m_nvim->neovimObject()->vim_input(m_nvim->encode(inp));
        // FIXME: bytes might not be written, and need to be buffered
 }
```

Pressing the down arrow here prints out `vim_input "<Down>"`.

The commit you mention adds the keypad modifier 'K', wild assumption, maybe on OSX its sending `<K-Down>` which would definitely be invalid.

**Comment by coddingtonbear** [comment]
Ahh -- it looks like you're right -- when press the arrow keys while in normal mode, the logs print:

```
vim_input "<kUp>"
vim_input "<kUp>"
vim_input "<kUp>"
vim_input "<kUp>"
vim_input "<kUp>"
vim_input "<kUp>"
```

What I was trying to demonstrate in those videos, by the way, was that one can neither access previous commands from Normal mode by pressing the up arrow, nor could one scroll vertically/horizontally through options presented by tools like Ctrl+P using the up/down arrows.

**Comment by equalsraf** [comment]
Quick search found this issue that seems very similar http://gnuplot.10905.n7.nabble.com/Arrow-keys-not-working-on-qt-terminal-for-Mac-OS-X-td19090.html

> The KeypadModifier value will also be set when an arrow key is pressed as the arrow keys are considered part of the keypad.

This seems to be mac specific, but I guess it wouldnt hurt to be sure and whitelist the events that get the modifers - from the nvim docs

```vim
<kHome>		keypad home (upper left)	*keypad-home*
<kEnd>		keypad end (lower left)		*keypad-end*
<kPageUp>	keypad page-up (upper right)	*keypad-page-up*
<kPageDown>	keypad page-down (lower right)	*keypad-page-down*
<kPlus>		keypad +			*keypad-plus*
<kMinus>	keypad -			*keypad-minus*
<kMultiply>	keypad *			*keypad-multiply*
<kDivide>	keypad /			*keypad-divide*
<kEnter>	keypad Enter			*keypad-enter*
<kPoint>	keypad Decimal point		*keypad-point*
<k0> - <k9>	keypad 0 to 9			*keypad-0* *keypad-9*
```

**Comment by coddingtonbear** [comment]
Totally sounds reasonable to me.  Since that method appears to receive only the modifiers and this is (probably) OSX-specific, would you settle for my wrapping that in an `#ifndef Q_OS_MAC` block?
