### ISSUE TITLE
Cannot enter `.` (dot) using numpad

### ISSUE THREAD

**Issue by qwfy** [equalsraf/neovim-qt#277]
in insert mode, if you press the dot in the numpad, nothing happens.

expect: entering a `.` (dot)

I can enter the dot using numpad in `nvim`.

**Comment by equalsraf** [comment]
Likely related to the recent keypad input change https://github.com/equalsraf/neovim-qt/commit/c208c1a1b5b4283dea130dbde589939f11245e3a the keypad dot should actually be encoded as `<kPoint>`

**Comment by cdvv7788** [comment]
I cannot enter any symbol using the numpad (/, *, -, +, .). It works normally outside of nvim-qt.

**Comment by qwfy** [comment]
it now (3fd464624db1810ced546ac7e98d4c4483542167) works. other symbols (/*-+) also work. :+1:

**Comment by cdvv7788** [comment]
Awesome.
