### ISSUE TITLE
Nearly-empty screen after installation

### ISSUE THREAD

**Issue by eddow** [equalsraf/neovim-qt#278]
I just wanted to try as the screenshots looked nice, but I was unable to even see localy how DejaVue works
I end up with a screen containing two titles and a slider bar with a button "Resume App" appearing some times
![image](https://cloud.githubusercontent.com/assets/765511/25795540/70e586f0-33de-11e7-881c-14a45c579954.png)
Did I miss an installation part? Is it my configuration? ... ?

**Comment by equalsraf** [comment]
Errr ... what is DejaVue? And how does this relate to neovim-qt

**Comment by eddow** [comment]
Oops, typo - please remove this ... O.o  :-/

**Comment by equalsraf** [comment]
:D roger that
