### ISSUE TITLE
Can't noremap <S-F10> in nvim-qt on Windows 

### ISSUE THREAD

**Issue by equalsraf** [equalsraf/neovim-qt#279]
Original  report at https://github.com/neovim/neovim/issues/6706

**Comment by RedX2501** [comment]
I don't think this will ever work as Shift+F10 is the window key binding to open the context menu.

https://support.microsoft.com/en-us/help/126449/keyboard-shortcuts-for-windows

**Comment by jgehrig** [comment]
See above. Marking as closed.
