### ISSUE TITLE
GuiFont command non-functional with Spacevim

### ISSUE THREAD

**Issue by tidux** [equalsraf/neovim-qt#284]
It has absolutely no effect in ginit.vim and attempting to run `:GuiFont foo` at runtime throws the "not an editor command" error.

**Comment by equalsraf** [comment]
Will need some more details to figure out this one

- operating system
- whats your &runtimepath
- how are you running nvim-qt? any specifc arguments, etc
- does this happen when using SpaceVim but not when using regular Vim?

nvim-qt calls nvim with a modified runtimepath that includes the location of the gui shim scripts. If these scripts are not found then the Gui* commands are not available. In UNIX thy are installed under /usr/share/nvim-qt/runtime. You can override this at runtime using the environment variable `$NVIM_QT_RUNTIME_PATH`

**Comment by tidux** [comment]
Looks like this was an issue with not calling `make install` properly.  Everything works as expected now.

Arch Linux amd64, NeoVim 0.2.0, neovim-qt git master.
