### ISSUE TITLE
Extremly long exit time with youcompleteme plugin

### ISSUE THREAD

**Issue by bl4ckout31** [equalsraf/neovim-qt#286]
Starting from release 0.2.6 to latest commit, nvim-qt hangs for about 25 seconds (nvim doing a lot of i/o in the background) with youcompleteme activated. This doesn't happen with nvim alone.

OS: Archilnux
Compiler: gcc 6.3.1-2
Qt: 5.8.0-11

**Comment by justinmk** [comment]
sounds like https://github.com/neovim/neovim/issues/6695

**Comment by bl4ckout31** [comment]
Anyway I can get give more detail ?

**Comment by jgehrig** [comment]
Closing this old issue.

I have not observed any hangs with YCM in `master` lately.
