### ISSUE TITLE
Powerline fonts do not showup correctly

### ISSUE THREAD

**Issue by saumyajyoti** [equalsraf/neovim-qt#287]
The Power line characters show up in nvim terminal but not in neovim-qt.

**Comment by AnotherBugworm** [comment]
How it works for me. I'm using spacevim, some chars just cut off in neovim-qt. Here is example(top-left corner)
![screenshot_20170520_155023](https://cloud.githubusercontent.com/assets/7214361/26528781/38317d90-43bb-11e7-899a-3d16af5c81ce.png)
![screenshot_20170520_155031](https://cloud.githubusercontent.com/assets/7214361/26528782/38331222-43bb-11e7-9ccc-403476842c4a.png)

**Comment by AnotherBugworm** [comment]
I think this is it https://github.com/equalsraf/neovim-qt/issues/164

**Comment by saumyajyoti** [comment]
Yes, Using GuiFont solved the problem for me. Thanks for the pointer.
