### ISSUE TITLE
Is it possible to improve scrolling performance?

### ISSUE THREAD

**Issue by tarruda** [equalsraf/neovim-qt#29]
During some tests in a headless machine connected to a remote display server, I found scrolling to be pretty slow. Could this be a consequence of [copying](https://github.com/equalsraf/neovim-qt/blob/master/src/gui/shell.cpp#L307) the entire scroll region on every scroll notification? Note that if this copying is performed by Qt in memory then a lot of data is transferred between the X server and client.

I'm going to try a shot in the dark(not familiar with Qt), but perhaps this would be faster if you performed a coordinate translation using [setClipRect](http://doc.qt.io/qt-4.8/qpainter.html#setClipRect) and [translate](http://doc.qt.io/qt-4.8/qpainter.html#translate)? I think this kind of transformation can be directly mapped to the backend graphics engine(X11 in my case) APIs, and if so, it would be much more efficient.

Coordinate translation is what pynvim [does](https://github.com/neovim/python-client/blob/master/neovim/ui/gtk_ui.py#L191-L242), and the performance is pretty good despite the UI logic being implemented in python.

**Comment by equalsraf** [comment]
You are probably right about scroll. I've got some mixed results on this one, its always a compromise between doing it at the backend (which is good for copy/scrolling) and doing it in memory (which is generally faster at drawing).

vim-qt did everything in the backend as this was faster (Qt4), but for Qt5 I got mixed results when benchmarking, and there were some regressions in Qt (upstream - [39686](https://bugreports.qt.io/browse/QTBUG-39686)) that keep me from doing this exactly as before.

Another option would be to use OpenGL, but this is way outside of my area of expertise.

**Sidenote**: There is room for some optimization on text drawing too, if instead of drawing one char at a time we group drawing operations into chunks of chars (we already do this for the bg color). But this is usually where we start running into bugs involving poor Monospace fonts and clipping.

**Comment by equalsraf** [comment]
More to the point both QPixmap and QWidget have scroll() methods that can be used instead of translate.

**Comment by tarruda** [comment]
> Sidenote: There is room for some optimization on text drawing too, if instead of drawing one char at a time we group drawing operations into chunks of chars (we already do this for the bg color). But this is usually where we start running into bugs involving poor Monospace fonts and clipping.

It might be helpful if you see pynvim's [redraw_glitch_fix](https://github.com/neovim/python-client/blob/master/neovim/ui/gtk_ui.py#L528-L550) method, which works around the problem by always redrawing non-empty adjacent cells. This is possible because it stores a [representation](https://github.com/neovim/python-client/blob/master/neovim/ui/screen.py) of the screen/cells.

I agree that the performance will improve by buffering cell updates with the same attributes and row, it's what pynvim does in the [put handler](https://github.com/neovim/python-client/blob/master/neovim/ui/gtk_ui.py#L248). This is mostly achieved by the internal screen [iterator](https://github.com/neovim/python-client/blob/master/neovim/ui/screen.py#L105), which yields chunks of text with same row/attributes instead of individual cells(to minimize drawing API calls).

Eventually this buffering optimization optimization might be implemented in the UI protocol itself, which should simplify GUI implementation.

**Comment by equalsraf** [comment]
> It might be helpful if you see pynvim's redraw_glitch_fix method, which works around the problem by always redrawing non-empty adjacent cells. This is possible because it stores a representation of the screen/cells.

This is actually one of the things I was trying to avoid - but admittedly I cant fix #3 without keeping at least some screen state around.

In practice vim-qt did away with most of these by running heuristics when loading fonts, and refused to load fonts with flawed metrics - it wasn't perfect but worked for most cases (in practice font substitution means its always possible to have problems here). Redrawing adjacent cells will most likely also have some corner cases - maybe drawing italics get clipped? If the font is monospaced and kerning is disabled then we should be ok in either case.

**Comment by tarruda** [comment]
> This is actually one of the things I was trying to avoid - but admittedly I cant fix #3 without keeping at least some screen state around.

I don't think it's possible to implement a text widget correctly without storing the states of the cells. It's always possible that drawing one cell will clip another(unless you have absolute control over the order that the cells are updated, which is not the case here).

>  Redrawing adjacent cells will most likely also have some corner cases - maybe drawing italics get clipped? If the font is monospaced and kerning is disabled then we should be ok in either case.

This shouldn't happen with pynvim because every non-empty sequence of cells is redrawn as a single unit. It might be a problem with very strange fonts(such as one with italics crossing more than one cell boundary), but I never saw this.

**Comment by Pireax** [comment]
I currently have created a fork which has some openGL functionality working correctly, I would make a pull request but I think it would be better to create a seperate branch for this. I'm currently working on making the scrolling functionality use opengl but everything is working as it should.

**Comment by equalsraf** [comment]
@Pireax nice! Having a look right now.

BTW https://gitter.im/equalsraf/neovim-qt is up

**Comment by equalsraf** [comment]
#109 was merged this should be ok now.

**Comment by tarruda** [comment]
@equalsraf nice!
