### ISSUE TITLE
Devicons are cropped in neovim-qt

### ISSUE THREAD

**Issue by fuelen** [equalsraf/neovim-qt#297]
I don't know where should I put this issue, but everything is ok in guake terminal
![image](https://user-images.githubusercontent.com/588762/27369942-d93278d4-5662-11e7-9631-d0e85a3a4f46.png)
and not in neovim-qt
![image](https://user-images.githubusercontent.com/588762/27369971-ff3fa68c-5662-11e7-8fec-724a8689818e.png)

in init.vim:
```
autocmd FileType nerdtree setlocal nolist
let g:WebDevIconsNerdTreeAfterGlyphPadding = ' '
let g:WebDevIconsUnicodeGlyphDoubleWidth = 0
```
ginit.vim:
```
Guifont xos4\ Terminess\ Powerline:h10
```

Installed fonts
```
$ yaourt nerd-fonts | grep installed
3 aur/nerd-fonts-complete-mono-glyphs 1.0.0-1 [installed] (2) (0,87)
```
With `aur/nerd-fonts-complete` package I can see only half of icon, with `aur/nerd-fonts-complete-mono-glyphs` almost full.

**Comment by AnotherBugworm** [comment]
https://github.com/equalsraf/neovim-qt/issues/164

**Comment by fuelen** [comment]
Thanks, found this font 
```
Guifont! TerminessTTF Nerd Font:h10
```
and now I have blurred font
![image](https://user-images.githubusercontent.com/588762/27418885-895cd628-5726-11e7-80ed-669b12c68e08.png)
with h32
![image](https://user-images.githubusercontent.com/588762/27418936-c6d1b014-5726-11e7-9247-7161eb755b45.png)
so, it is a font issue, thanks.
