### ISSUE TITLE
neovim-qt does not support -V argument

### ISSUE THREAD

**Issue by RedX2501** [equalsraf/neovim-qt#299]
After installing youcompleteme `:q` stopped exiting neovim. Instead it prints `Press ENTER or type command to continue`. Since I'm sure this is an youcompleteme error but I cannot see the messages that are printed because typing anything leads to neovim quitting (as I told him to).

So to log I wanted to start neovim-qt with `nvim-qt -V9log.txt` but that only led to a message about unknown command line arguments.

Is there any other way of getting this behaviour?

**Comment by equalsraf** [comment]
You can pass arguments to the nvim process after the `--` separator, I assume what you want is

```
$ nvim-qt -- -V9log.txt
```

**Comment by RedX2501** [comment]
Thank you. I added this info to the wiki page. I hope that is ok.
