### ISSUE TITLE
Cursor for fullwidth characters

### ISSUE THREAD

**Issue by equalsraf** [equalsraf/neovim-qt#3]
(in the tb-remote-ui branch) the text cursor is painted over existing characters. However for fullwidth characters, since we assume the cursor width is one cell it only covers half of the char.

![snapshot-neovim-qt1](https://cloud.githubusercontent.com/assets/715238/5586546/eb58a97c-90c9-11e4-8a8a-d318d3d9d550.png)

**Comment by osa1** [comment]
This is a very annoying issue which old vim-qt also has. It happens even when you're using a monospace font, because italic characters sometimes go over character boundaries even if the font is monospace.

**Comment by equalsraf** [comment]
The cause here is a bit different though. In vim-qt it only happens because fonts fail to report metrics properly (or are broken, or not available).

In this case it happens because the gui doesn't know the cursor is standing over the wide character. This is something I assumed from Vim-qt, but it doesn't work the same way in the Neovim API.

If you look at the gui implemented in the python client it knows exactly which char is where - this is an assumption I was trying to avoid, but I either have to change strategy, or think about sending a PR to Neovim to change gui events.
