### ISSUE TITLE
Open files in existing neovim instance

### ISSUE THREAD

**Issue by RedX2501** [equalsraf/neovim-qt#300]
I'd really like to have an option to open files in an already open neovim-qt session as a new tab or buffer.

Is there any command-line way of doing this already?

**Comment by equalsraf** [comment]
Nothing specific to nvim-qt. I believe the most popular way is to use https://github.com/mhinz/neovim-remote.

Personally I use some script tricks with NVIM_LISTEN_ADDRESS.

**Comment by RedX2501** [comment]
Thank you for that tool.

What I have done now:

In `init.vim`

    if has('nvim')
      " some known address, this will lead to a message about the address already being taken on other instances
      call serverstart('\\.\pipe\nvim-123')
    endif

And a batch file:

```
@echo off

c:\Python3\Scripts\nvr.exe --servername \\.\pipe\nvim-123 --remote-silent %* > NUL

if ERRORLEVEL 1 (
	rem ok, returning an error means there was no neovim open
	pushd d:\Utilities\Neovim\bin 
	start nvim-qt.exe %*
	popd
)
```

And I use that file for the context menu.
