### ISSUE TITLE
Cannot inoremap <F13> <Esc> (probably the problem with all F13-F24 keys)

### ISSUE THREAD

**Issue by RIscRIpt** [equalsraf/neovim-qt#308]
The following mapping:
```
inoremap <F13> <ESC>
```

 - nvim-qt: Doesn't work on both windows and linux.
 - nvim: Works on linux, but doesn't work on windows, but I guess that's the problem of windows' cmd/powershell.

```
Windows version: NVIM v0.2.1-25-g2e3b78d1
Linux version:   NVIM v0.2.1-527-g702c94aac
```

So taking in to account only linux version, the mentioned mapping **doesn't work in nvim-qt**, but **does work in nvim**.

**Edit:**
I guess this can be fixed by adding F13-F24 keys to [this](https://github.com/equalsraf/neovim-qt/blob/master/src/gui/input.cpp#L18-L29) list. ~~Trying to setup the dev environment to build and test it.~~ Couldn't build because of the annoying `-Werror=implicit-fallthrough=` msgpack error-warning.

**Comment by equalsraf** [comment]
> I guess this can be fixed by adding F13-F24 keys

Presumably yes. But the vim docs dont mention keys above F12. The nvim keymap.h shows defines up to [F37](https://github.com/neovim/neovim/blob/master/src/nvim/keymap.h#L321), but Qt only supports up to [F35](http://doc.qt.io/qt-5/qt.html#Key-enum).

Started https://github.com/equalsraf/neovim-qt/pull/311 with F13-F24. Can you check if it works with modifier keys too?

> Couldn't build because of the annoying -Werror=implicit-fallthrough= msgpack error-warning.

Pushed fix into master.

**Comment by RIscRIpt** [comment]
Cool, thanks!
I'll do the check asap -- in 2 days.

**Comment by RIscRIpt** [comment]
I've done the following tests, and almost everything worked as expected:
```
nnoremap <S-F14> i
vnoremap <A-F15> x
inoremap <C-F16> "I pressed Ctrl + F16"
noremap <A-F24> <Esc>:up<CR>
```
I couldn't make the first mapping to work (`nnoremap <S-F14> i`), **but all the rest worked as expected**.

~~I also want to note that the last mapping `noremap <A-F24> <Esc>:up<CR>` doesn't work in the _insertion_ mode, but that's how `noremap` works with other keys.~~

As for the "shifted function keys"... I suppose that there's a problem in nvim, because the following mapping didn't work there: `map <S-F5> <Esc>:up<CR>` (whereas `map <F6> <Esc>:up<CR>` worked).

According to the (n)vim `:help` "shifted function keys" should work:
_quote from_ `:help map-which-keys`
> - Function keys < F2 >, < F3 >, etc..  Also the shifted function keys < S-F1 >,
>   < S-F2 >, etc.  Note that <F1> is already used for the help command.

But I think that's not so important, although it should be resolved (later, and in other issue) for _functional_ completeness :)

As the reported problem is resolved, I'm closing this issue.

**Comment by ellbur** [comment]
Just FYI for others coming across this page wondering why remapping `F13` to `F24` isn't working as expected in Linux, it may be because [your keyboard layout maps these keys to XF86Tools, XF86Launch5, and such](http://xahlee.info/linux/linux_xmodmap_tutorial.html). You can fix this by changing your keyboard layout using `xkb` or `xmodmap`.
