### ISSUE TITLE
Install location for runtime/ files

### ISSUE THREAD

**Issue by ctuffli** [equalsraf/neovim-qt#309]
I'm packaging neovim-qt for FreeBSD and wanted to know if the runtime files are intended to be copied into `${PREFIX}/share/nvim-qt/` or `${PREFIX}/share/nvim/`.

**Comment by justinmk** [comment]
@ctuffli They should go in `${PREFIX}/share/nvim/`.

**Comment by ctuffli** [comment]
@justinmk, thanks!

**Comment by equalsraf** [comment]
errr, I think @ctuffli  means the shim, and that usually goes into prefix/share/nvim-qt

**Comment by ctuffli** [comment]
Yes, specifically, setting `Guifont` in ginit.vim wasn't working because the runtimepath didn't include `${PREFIX}/share/nvim-qt/`. Copying the contents of the neovim-qt runtime directory into the nvim runtime directory fixed the problem for me, raising this question.

The wiki suggests if the directory isn't in runtimepath, it might be a bug. Did I goof when packaging neovim-qt?

OS is FreeBSD 12
nvim is 0.1.7
nvim-qt is 0.2.7

**Comment by equalsraf** [comment]
Usually what happens is that nvim-qt sets the runtimepath to include that directory on start.

You can check this with ps ax to see what arguments were passed to nvim to see which path is being used.

When building cmake defaults prefix to /usr/local. You can override this with `cmake -DCMAKE_PREFIX_PATH=/usr`. Can you share your pkg recipe?

**Comment by ctuffli** [comment]
Here's the ps output:
```
> ps ax | grep vim
10874  -  S      0:00.15 /usr/local/bin/nvim-qt --nofork
10875  -  I      0:00.06 nvim --cmd let &rtp.=',/usr/local/share/nvim-qt/runtime' --cmd set termguicolors --embed --headless
```

The full shar for the pkg is here [1], but there isn't much to it. Being that it is a FreeBSD package, the prefix is going to be `/usr/local/`

[1] https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=212187

**Comment by equalsraf** [comment]
> nvim --cmd let &rtp.=',/usr/local/share/nvim-qt/runtime'

So nvim-qt is convinced the runtime location is in the /usr/local prefix. If that was the intended prefix, and the files are there, then it should be fine to use GuiFont.

**Comment by ctuffli** [comment]
I get `E492: Not an editor command: GuiFont`. Also tried this with a more recent neovim (NVIM v0.2.1-535-g837037383), but still, no joy.

**Comment by ctuffli** [comment]
This maybe FreeBSD specific. Running the command `nvim --cmd "let &rtp.=',/usr/local/share/nvim-qt/runtime'"` on an Ubuntu 14.04 and FreeBSD 12.0 machine yields different results. On the Linux machine, running `:echo &rtp` shows the new path, but on FreeBSD, `:echo &rtp` does not show the new path.

**Comment by ctuffli** [comment]
Bah, this had nothing to do with the OS. There was something weird with the plugin manager on the misbehaving system. Nuking `~/.config/nvim/bundles` and starting over with that seems to have restored the expected behavior. Sorry for the noise.
