### ISSUE TITLE
Missing Error Message/Prompt When Closing Without Saving

### ISSUE THREAD

**Issue by lordmilko** [equalsraf/neovim-qt#310]
## Issue Description ##

When closing neovim-qt with an open window containing unsaved changes via one of the following methods

* Click the X on the window
* Alt+F4
* `:call GuiClose()`

neovim-qt will respond "Please ENTER or type a command to continue", without displaying an appropriate error message.

Typing `:q` returns the error message "E37: No write since last change (add ! to override)" as expected.

## Expected behavior ##

When closing neovim-qt with unsaved changes via any of the other methods above, neovim-qt should either

1. Display an appropriate error message similar to the error message displayed by `:q`
2. Prompt the user as to whether or not they would like to save their changes.

gVim uses option 2. When a single window is open with unsaved changes, gVim will ask whether or not to save changes to the document with Yes/No/Cancel. When multiple windows are open with unsaved changes, its options are Yes/No/Save All/Discard All/Cancel. I would propose that neovim-qt use a similar technique.

## Steps to Reproduce ##

1. Open neovim-qt
2. Enter some random text in insert mode
3. Hit Alt+F4, click the X on the window, or in normal mode execute `:call GuiClose()`

## System Information ##

* Windows 7 SP1
* 64-bit nvim v0.2.1 + neovim-qt from the latest [0.2.0 release](https://github.com/neovim/neovim/releases/download/v0.2.0/nvim-win64.zip)

**Comment by equalsraf** [comment]
Confirmed, it seems  calling `:q` manually does not produce the same result as calling `:qa` via `vim_command()`.

**Comment by equalsraf** [comment]
Added a patch for this in https://github.com/equalsraf/neovim-qt/pull/463
