### ISSUE TITLE
Arch Package fails to compile

### ISSUE THREAD

**Issue by asyncial** [equalsraf/neovim-qt#313]
I tried to install the AUR package of neovim-qt, but it fails with 

`[ 32%] Built target neovim-qt-gui_autogen
In file included from /tmp/makepkg/neovim-qt/src/neovim-qt-0.2.4/third-party/msgpack-c-cpp-1.4.0/src/unpack.c:268:0:
/tmp/makepkg/neovim-qt/src/neovim-qt-0.2.4/third-party/msgpack-c-cpp-1.4.0/include/msgpack/unpack_template.h: In Funktion »template_execute«:
/tmp/makepkg/neovim-qt/src/neovim-qt-0.2.4/third-party/msgpack-c-cpp-1.4.0/include/msgpack/unpack_template.h:250:17: Fehler: diese Anweisung könnte durchfallen [-Werror=implicit-fallthrough=]
                 ++p;
                 ^~~
/tmp/makepkg/neovim-qt/src/neovim-qt-0.2.4/third-party/msgpack-c-cpp-1.4.0/include/msgpack/unpack_template.h:252:13: Anmerkung: hier
             default:
             ^~~~~~~
cc1: Alle Warnungen werden als Fehler behandelt
make[2]: *** [third-party/msgpack-c-cpp-1.4.0/CMakeFiles/msgpackc-static.dir/build.make:63: third-party/msgpack-c-cpp-1.4.0/CMakeFiles/msgpackc-static.dir/src/unpack.c.o] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:174: third-party/msgpack-c-cpp-1.4.0/CMakeFiles/msgpackc-static.dir/all] Fehler 2
`

The [package](https://aur.archlinux.org/packages/neovim-qt/) is already flagged out of date since June 3rd

Is the package still maintainend, and if yes, can it be updated?

**Comment by ianks** [comment]
I am currently maintaining this but do not use neovim-qt at this moment. Would someone like to take the keys?

**Comment by ianks** [comment]
In the meantime, I have fixed to package to work with v0.2.7 now.

**Comment by asyncial** [comment]
Ah thanks for the fast response! If it's possible/allowed/needed I could maintain the AUR package.

**Comment by ianks** [comment]
@asyncial awesome! How would I transfer it to you (i.e. you aur username, steps, etc.)

**Comment by asyncial** [comment]
My username on the aur is the same as here.
In order for me to take the maintenance into my hands, you would have to flag your package as "orphaned", as far as I understand it. Just answer again here, if you've done so, so I can claim the package.

**Comment by jamessan** [comment]
Since this is related to the Arch packaging, not current neovim-qt code, the issue should probably be closed.
