### ISSUE TITLE
i have trouble building it on linux-mint

### ISSUE THREAD

**Issue by torpak** [equalsraf/neovim-qt#32]
[ 31%] Built target neovim-qt_automoc
Scanning dependencies of target neovim-qt
[ 33%] Building CXX object src/CMakeFiles/neovim-qt.dir/util.cpp.o
[ 35%] Building CXX object src/CMakeFiles/neovim-qt.dir/neovimconnector.cpp.o
In file included from /home/brix/neovim-qt/src/neovimconnector.cpp:1:
In file included from /home/brix/neovim-qt/src/neovimconnector.h:6:
In file included from /usr/include/qt5/QtCore/QProcess:1:
/usr/include/qt5/QtCore/qprocess.h:105:5: fatal error: 'metaObject' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
    Q_OBJECT
    ^
/usr/include/qt5/QtCore/qobjectdefs.h:150:32: note: expanded from macro 'Q_OBJECT'
    virtual const QMetaObject *metaObject() const; \
                               ^
/usr/include/qt5/QtCore/qiodevice.h:70:5: note: overridden virtual function is here
    Q_OBJECT
    ^
/usr/include/qt5/QtCore/qobjectdefs.h:150:32: note: expanded from macro 'Q_OBJECT'
    virtual const QMetaObject *metaObject() const; \
                               ^
1 error generated.
make[2]: *** [src/CMakeFiles/neovim-qt.dir/neovimconnector.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/neovim-qt.dir/all] Error 2
make: *** [all] Error 2

**Comment by equalsraf** [comment]
Thats strange, seems to be failing in a Qt header. @torpak what Qt and compiler versions are you using?

Maybe I'm being too pedantic with the compile flags. Can you try removing this line from CMakeLists.txt to see if it helps

```
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror -Wall -Wextra -Wno-unused-parameter -std=c++11 -Wfatal-errors")
```

**Comment by jalcine** [comment]
[**@equalsraf**](https://github.com/equalsraf) commented on [Aug 5, 2015, 1:38 PM EDT](https://github.com/equalsraf/neovim-qt/issues/32#issuecomment-128086233 "2015-08-05T17:38:16Z - Replied by Github Comment Enhancer"):
> Thats strange, seems to be failing in a Qt header. [@torpak](https://github.com/torpak) what Qt and compiler versions are you using?
> 
> Maybe I'm being too pedantic with the compile flags. Can you try removing this line from CMakeLists.txt to see if it helps
> 
>         set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror -Wall -Wextra -Wno-unused-parameter -std=c++11 -Wfatal-errors")

You only need to remove `-Wfatal-errors`; since the errors were just warnings elevated to an error. That's typically a flag you'd want running against a test executable, no?

**Comment by equalsraf** [comment]
@jalcine I was expecting `-Werror` or `-Wextra` to be the culprit here not `-Wfatal-errors`, but I can't verify right now. gcc manpage says

```
       -Wfatal-errors
           This option causes the compiler to abort compilation on the first error occurred rather than trying to keep
           going and printing further error messages.
```

**Comment by jalcine** [comment]
@equalsraf You're completely right: `-Werror` is _definitely_ the flag to elevate it:
```
   -Werror
           Make all warnings into errors.

       -Werror=
           Make the specified warning into an error.  The specifier for a
           warning is appended; for example -Werror=switch turns the warnings
           controlled by -Wswitch into errors.  This switch takes a negative
           form, to be used to negate -Werror for specific warnings; for
           example -Wno-error=switch makes -Wswitch warnings not be errors,
           even when -Werror is in effect.

           The warning message for each controllable warning includes the
           option that controls the warning.  That option can then be used
           with -Werror= and -Wno-error= as described above.  (Printing of the
           option in the warning message can be disabled using the
           -fno-diagnostics-show-option flag.)

           Note that specifying -Werror=foo automatically implies -Wfoo.
           However, -Wno-error=foo does not imply anything.
```

**Comment by equalsraf** [comment]
@torpak can you verify if removing  -Werror or -Wextra from CMakeLists.txt  (one or the other) fixes this?

    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror -Wall -Wextra -Wno-unused-parameter -std=c++11 -Wfatal-errors")

**Comment by torpak** [comment]
Hi, i'm on vacation at the moment. I will check as soon as i come home.

**Comment by torpak** [comment]
Without -Werror it builds (with the above warnings) :smile:

**Comment by equalsraf** [comment]
Just for completeness what compiler/system/Qt are are you using?

**Comment by torpak** [comment]
gcc 4.8.4, linux-mint kernel version: 3.13.0-24, QT 5.2.1

**Comment by equalsraf** [comment]
Merged into master.
