### ISSUE TITLE
TAB does not work in insert mode in windows8.1

### ISSUE THREAD

**Issue by yehuohan** [equalsraf/neovim-qt#321]
TAB does not work in insert mode in windows8.1.

**Comment by equalsraf** [comment]
It does nothing at all?

What about other modes? Can you create a mapping using TAB?

**Comment by yehuohan** [comment]
I try follow maps:

```
nnoremap <Tab> :echo 'Hello nq'
inoremap <Tab> <esc>:echo 'Hello nq'
```
and nnoremap worked but inoremap doesn't.

**Comment by yehuohan** [comment]
I found recently that 'tab' doesn't work in insert mode for neovim-qt in windows when the plugin SirVer/ultisnips is loaded. Maybe there're some conficts.

**Comment by equalsraf** [comment]
Seems to be a problem with that specific plugin. Closing this for now, please reopen if it is specific to nvim-qt.
