### ISSUE TITLE
Cannot type *(asterisk) in nvim-qt

### ISSUE THREAD

**Issue by MMDF** [equalsraf/neovim-qt#325]
nvim-qt doesn't recognize asterisk keypress. Analogous to  [neovim/neovim#6703](https://github.com/neovim/neovim/issues/6703)

**Comment by jamessan** [comment]
Sounds like a duplicate of #270.

**Comment by w1mb0r** [comment]
I had this issue on an older version of nvim-qt but it works fine on nvim-qt.exe dating 06/09/2017 17:58 with nvim v0.2.3-234-gb0e9132cf

**Comment by markstos** [comment]
In my case I found that the issue was that I was using a QMK-powered keyboard and my asterisk key was sending a "Numpad Asterisk". I updated the firmware to send a "Shifted Punctuation Asterisk" instead and that resolved the issue with Neovim 0.3.8.

**Comment by jgehrig** [comment]
Cannot reproduce anymore. Marking as closed.

The input layer has changed since this bug was filed. Please open a new bug if you still see input issues.

**Comment by Carlosmape** [comment]
Hi all, I am having the same issue but with '[' character. I tried to `call nvim_input('[')` as anyone sais to solve the trouble with the asterisk but it does not work for my case.
