### ISSUE TITLE
Select/copy/paste support?

### ISSUE THREAD

**Issue by frankie-loves-jesus** [equalsraf/neovim-qt#327]
Hi, is it possible or are there any plans to add select/copy/paste support (Windows 10)? Ie. being able to select text within nvim-qt.exe, ctrl+c/ctrl-v/mouse clicks etc.? gVim does this and it's helped me a lot!

Cheers!

Ref. [Windows 8.1] clipboard support? https://github.com/equalsraf/neovim-qt/issues/123

**Comment by justinmk** [comment]
:set mouse=a

**Comment by frankie-loves-jesus** [comment]
Thanks man, I didn't know I could do that! Still though I can't seem to copy or paste, whether it's with my keyboard or with my mouse.

**Comment by tindzk** [comment]
To replicate the regular copy-and-paste behaviour on Linux, I had to put the following settings in `ginit.vim`:

```vim
set mouse=a

" Paste with middle mouse click
vmap <LeftRelease> "*ygv

" Paste with <Shift> + <Insert>
imap <S-Insert> <C-R>*
```

**Comment by frankie-loves-jesus** [comment]
No dice on Windows :/

**Comment by equalsraf** [comment]
The mswin.vim example should enable Ctrl+c and Ctrl+v. Testing here with nvim from master and it is working with nvim-qt. It is also working in the terminal UI.

Maybe there is some other issue at play here. @frankie-loves-jesus is any kind of copy pasting to the system clipboard working for you?

**Comment by frankie-loves-jesus** [comment]
Thanks guys - I can confirm mswin.vim enables Ctrl+c and Ctrl+v 👍 

Copy/pasting with the mouse with `set mouse=a` however seems to be more challenging: https://stackoverflow.com/questions/4608161/copy-text-out-of-vim-with-set-mouse-a-enabled. Apparently it requires that you hold in Shift while selecting. Unfortunately this also requires that you press Ctrl+c / Ctrl+v multiple times. Nowhere near as smooth as in gVim. Thoughts?

**Comment by justinmk** [comment]
> Apparently it requires that you hold in Shift while selecting

No. That post is for _terminal_ Vim. Lots of confusion and misinformation flying around, because Vim is so inconsistent.

**Comment by equalsraf** [comment]
> @equalsraf Does nvim-qt handle mousemodel=popup[_setpos]? Is there something missing in Nvim for that?

We dont have any specific support for menus or the popup yet.

Is the popup supposed to work in the terminal, like the pum? I cant get it to trigger (quick side note menu.vim is not sourced by default, but this does not fix it)

**Comment by justinmk** [comment]
> Is the popup supposed to work in the terminal, like the pum? 

No, but it's something I've been thinking about.

**Comment by lihuelworks** [comment]
Is this going to be implemented anytime soon?

**Comment by justinmk** [comment]
@lihuelworks What is "this"? Did you try the suggestions above? What exactly did you try?

**Comment by eyalk5** [comment]
> ```
> :set mouse=a
> ```
> 
> > ctrl+c/ctrl-v
> 
> Those are just mappings. ~Try `:behave mswin`~ Try:
> 
> ```
> :source $VIMRUNTIME/mswin.vim
> ```

Interestingly, while similarly trying with macmap.vim, it didn't work. 
Until I have changed all the <D-x> to <D-X> where x stands for any char.

**Comment by predatorian3** [comment]
The
```vim
set mouse=a
source $VIMRUNTIME/mswin.vim
```

Did the trick for me. I included those in my `init.vim`.  I was able to use CTRL+c/CTRL+v to copy and paste from and to neovim. I was kind of expecting the same right-click menu like gVim has for Windows, but this works too.

**Comment by jgehrig** [comment]
> I was kind of expecting the same right-click menu like gVim has for Windows, but this works too.

Pull Request #539 adds support for a basic right-click context menu similar to gVim in recent versions. I need to add some documentation for the feature...

ginit.vim:
```
nnoremap <silent><RightMouse> :call GuiShowContextMenu()<CR>

inoremap <silent><RightMouse> <Esc>:call GuiShowContextMenu()<CR>

vnoremap <silent><RightMouse> :call GuiShowContextMenu()<CR>gv
```

**Comment by JR2Media** [comment]
> The
> 
> ```viml
> set mouse=a
> source $VIMRUNTIME/mswin.vim
> ```
> 
> Did the trick for me. I included those in my `init.vim`. I was able to use CTRL+c/CTRL+v to copy and paste from and to neovim. I was kind of expecting the same right-click menu like gVim has for Windows, but this works too.

Works for me too on Windows with NeoVim GUI.
