### ISSUE TITLE
nvim 0.2.1 removes <FocusGained> pseudokey

### ISSUE THREAD

**Issue by justinmk** [equalsraf/neovim-qt#329]
In https://github.com/neovim/neovim/pull/7221 the `<FocusGained>` and `<FocusLost>` pseudokeys were removed. Currently, the best suggestion for neovim-qt is to do what most other UIs do (probably because they didn't know about `<FocusGained>` pseudo key), something like this:

    nvim_command("if exists('#FocusGained') | doautocmd FocusGained | endif")

However, I've started working on another approach which might be better: add handlers for msgpack notifications to Nvim core. Not sure how that will turn out though.

The reason `<FocusGained>` was removed:

1. to move away from using input to control the eventloop
2. to fix things like https://github.com/equalsraf/neovim-qt/issues/256

**Comment by equalsraf** [comment]
This seems to be backward compatible with 0.2.0 so it should be easy to do. is FocusLost also being removed in the future? might as well change that too.

**Comment by justinmk** [comment]
Yes focuslost was removed too.

**Comment by equalsraf** [comment]
Merged in #330  thanks for the heads up.
