### ISSUE TITLE
Document the need to run `make install` for Gui commands to work in the Readme 

### ISSUE THREAD

**Issue by e00E** [equalsraf/neovim-qt#334]
I built `neovim-qt` from source on Linux like the Readme explains. However when running it from the built directory the `:GuiFont` and `:help nvim-gui-shim` commands would not work.

I ran `make install` and then ran the installed version of `neovim-qt` and the commands worked.

This should be documented in the Readme so other people can spend less time pondering this issue.

**Comment by equalsraf** [comment]
Closing after #337
