### ISSUE TITLE
Event focus-lost isn't triggering

### ISSUE THREAD

**Issue by noamcore** [equalsraf/neovim-qt#335]
Informations
---
Software | Version
-- | --
Operating System | Antergos Linux 17.8
Neovim-Qt | v0.2.8

Problem
---
I'm currently using this auto-command `autocmd FocusLost * silent! wa`, and it works as expected on the terminal, but not in the neovim-qt.

**Comment by khalidchawtany** [comment]
I am on **Mac OS 10.12.6** and running the latest version of each **neovim** and **neovim-qt** and it works as expected.

**Comment by justinmk** [comment]
@noamcore If you remove the `silent!`, does an error or message appear on focus?

**Comment by noamcore** [comment]
Nop, tried now with no success.

Tried changing tab, and opening another application.

**Comment by noamcore** [comment]
Curiosly, in gnome-terminal, nvim can save on focus lost, but urxvt can't. I might be a nvim issue, not this project.

**Comment by justinmk** [comment]
> Curiosly, in gnome-terminal, nvim can save on focus lost, but urxvt can't. I might be a nvim issue, not this project.

No, it's not a nvim issue. Are you certain your urxvt was built with focus-reporting feature?

**Comment by noamcore** [comment]
Not sure, and I don't know how to check. Any tip?

**Comment by equalsraf** [comment]
> Anyway, the question is on Neovim-Qt. Anything I can do to help debugging?

Does it work with other commands, simple print would suffice.

It is possible that the GUI is not actually detecting the focus event. What window manager are you using?

**Comment by noamcore** [comment]
Currently I’m using gnome-shell.

Abraços,
Iago Sousa

**Comment by equalsraf** [comment]
Boas,

Tested here with i3 and gnome, and I cannot reproduce.

For debugging this first thing we need is to figure out if the focus events are being triggered or not. The relevant code is https://github.com/equalsraf/neovim-qt/blob/master/src/gui/shell.cpp#L908 a qDebug statement or a gdb breakpoint in that line would be enough to figure out if it is being called or not.

**Comment by noamcore** [comment]
Hello, sorry for the late response. I needed to re-install my Arch Linux, and now it's all fine (now I'm using Plasma and i3). Maybe was a misconfiguration in my system? I can't say. But thanks for trying to figure out and sorry that I can't provide more information as now it is working as expected.

PS: The version I'm using now is 0.2.9.

**Comment by equalsraf** [comment]
Ok, thanks.
