### ISSUE TITLE
Users need a screenshot

### ISSUE THREAD

**Issue by Goddard** [equalsraf/neovim-qt#338]
It would be extremely helpful for new users just to have a visual reference of what this looks like without having to go through the trouble of building and finding out they do not like it.

Thanks

**Comment by kierun** [comment]
![screenshot](https://user-images.githubusercontent.com/3079575/31221526-d4af8c3c-a9bb-11e7-96ce-fda7ca5d6cf5.png)

Using [vim-airline](https://github.com/vim-airline/vim-airline)…

**Comment by jalcine** [comment]
![screenshot_20180103_214919](https://user-images.githubusercontent.com/452100/34551558-fc904268-f0cf-11e7-955c-8f51d395465f.png)

This is on Linux using [this configuration](https://github.com/jalcine/vimrc).
