### ISSUE TITLE
Can not type ÄÜÖ Umlauts in nvim-qt

### ISSUE THREAD

**Issue by getreu** [equalsraf/neovim-qt#339]
I am using a German keyboard layout and when I press *[Shift + ü]* no `Ü` appears. Same for `ÄÖ`. Surprisingly `äü` and `ö` are typed correctly. This bug does not appear neither in `nvim` run on the console nor with `GVim`.

# Workaround

Pressing `[Compose] ["] [ö]` prints `Ö`

# Tested versions

* OS: debian 9
* `NVIM v0.2.0`

**Comment by khalidchawtany** [comment]
This [patch](https://github.com/equalsraf/neovim-qt/files/1418178/FixUnicodeChars.txt) solves the issue for me. However, I am on **Mac  OS 10.12.6**

You can test if it solves the issue for you too.

**Comment by jgehrig** [comment]
The input layer has been improved in recent releases. A quick test of `v0.2.16` shows this scenario now works (ÄÖÜäöü).

If you still see input issues, please file a bug. I can add a test case and handling for specific keyboards, layouts, and characters.

Marking as closed.
