### ISSUE TITLE
nvim-qt takes a long time to quit and asks for user input when editing a python file with ropevim plugin.

### ISSUE THREAD

**Issue by bonderado** [equalsraf/neovim-qt#341]
When editing a python file, with the ropevim plugin enabled (https://github.com/python-rope/ropevim), issuing the :q command, after a delay of several seconds nvim-qt asks the user to "Enter RETURN or command to continue" (I am using a localized version, so the English message  may be inexact, the Italian one reads: "Premi INVIO o un comando per proseguire").
This also happen if editing a python file and a file of different type and the :qa command is issued from the pythn file buffer, but not if :qa is issued from the other buffer.

Steps to reproduce:

1. Start editing a python file with nvim-qt 
    nvim-qt test.py
2. quit nvim-qt
   :q
3. nvim-qt waits several seconds, tehn asks the user for input.

Expected result:
nvim-qt quits immediately.

Note:
The console version of neovim does not manifest the issue.

Configuration;
Linux  4.12.0-2-amd64 #1 SMP Debian 4.12.13-1 (2017-09-19) x86_64 GNU/Linux
neovim (0.2.0-3)
neovim-qt (0.2.8-1)
rope (0.10.5)
ropemode (0.4)
ropevim (0.7.0)

Sample init.vim:

set nocompatible
if has('nvim')
  let $VIMNAME='nvim'
else
  let $VIMNAME='vim'
endif

if empty($XDG_CACHE_HOME)
    let $XDG_CACHE_HOME=expand("$HOME/.cache")
endif
if empty($XDG_CONFIG_HOME)
    let $XDG_CONFIG_HOME=expand("$HOME/.config")
endif
if empty($XDG_DATA_HOME)
    let $XDG_DATA_HOME=expand("$HOME/.local/share")
endif

" Set Directory for plugins
let $XDG_VIM_PLUGINS=expand("$XDG_DATA_HOME/$VIMNAME/plugins")

set directory=$XDG_CACHE_HOME/$VIMNAME/swap//,~/,/tmp
if has('persistent_undo')
  set undofile
  set undodir=$XDG_CACHE_HOME/$VIMNAME/undo//,~/,/tmp
endif
set backupdir=$XDG_CACHE_HOME/$VIMNAME/backup//,~/,/tmp
set viminfo='100,n$XDG_CACHE_HOME/$VIMNAME/viminfo
set runtimepath+=$XDG_CONFIG_HOME/$VIMNAME
set runtimepath+=$XDG_CONFIG_HOME/$VIMNAME/after,$VIM,$VIMRUNTIME

let g:netrw_home=expand("$XDG_CACHE_HOME/$VIMNAME")"
let $PLUGIN_MANAGER=expand("$XDG_VIM_PLUGINS/repos/github.com/Shougo/dein.vim")

set runtimepath+=$PLUGIN_MANAGER

  call dein#begin($XDG_VIM_PLUGINS)
  call dein#add(expand('$PLUGIN_MANAGER'))
  call dein#add('python-rope/ropevim')
  """"""""""""""""
  call dein#end()
  call dein#save_state()

syntax enable
filetype on
filetype indent on
filetype plugin indent on

**Comment by qwfy** [comment]
Have the same problem, I don't use ropevim, it doesn't always happen though.

**Comment by bonderado** [comment]
possibly related to #394 .

**Comment by micbou** [comment]
After installing [the `ropevim` plugin](https://github.com/python-rope/ropevim/blob/master/ftplugin/python_ropevim.vim) and editing a Python file, `:autocmd VimLeave` returns:
```
--- Auto-Commands ---
VimLeave
    *         call GuiClose()
    *.py      call RopeExitingActions()
```
where `RopeExitingActions` is defined as:
```viml
function! RopeExitingActions()
  python ropevim.exiting_actions()
endfunction
```
so it's definitely the same issue as #394.

**Comment by micbou** [comment]
I would suggest to close this issue in favor of #394 as the test case is easier to reproduce.

**Comment by bonderado** [comment]
I second the motion,  I am closing this for the time being. I will reopen this if it still happens after bug #394 is fixed.
