### ISSUE TITLE
Default cursor width in insert mode is thicker

### ISSUE THREAD

**Issue by navxio** [equalsraf/neovim-qt#342]
As compared to neovim in the terminal!

**Comment by khalidchawtany** [comment]
Try [this patch.txt](https://github.com/equalsraf/neovim-qt/files/1418205/cursor_patch.txt)

I like the thicker cursor :)

**Comment by osa1** [comment]
In case you don't want to download the file in the comment above:

```patch
diff --git a/src/gui/shell.cpp b/src/gui/shell.cpp
index 428e90b..bc88139 100644
--- a/src/gui/shell.cpp
+++ b/src/gui/shell.cpp
@@ -559,7 +559,7 @@ void Shell::paintEvent(QPaintEvent *ev)
 		QRect cursorRect(neovimCursorTopLeft(), cellSize());
 
 		if (m_insertMode) {
-			cursorRect.setWidth(2);
+			cursorRect.setWidth(1);
 		} else if (wide) {
 			cursorRect.setWidth(cursorRect.width()*2);
 		}
```

**Comment by jgehrig** [comment]
As of `v0.2.16` there is support for `guicursor` and this option is configurable.

You can changed the cursor width with `ver{N}`. See `:set guicursor` and `:help guicursor` for more details.
