### ISSUE TITLE
Font commands completely broken? (latest nvim + neovim-qt)

### ISSUE THREAD

**Issue by osa1** [equalsraf/neovim-qt#343]
I'm looking at this wiki page: https://github.com/equalsraf/neovim-qt/wiki

It shows this example:

```
Guifont DejaVu Sans Mono:h13
```

I put that in `~/ginit.vim` and `~/.config/nvim/ginit.vim` (hopefully one of these is the correct locations -- I've been using vim for 5+ years and this is the first time I've heard about this file) -- but it has no effect. I still see default font with default size. When I check `let g:GuiFont` I see the default one.

**Comment by khalidchawtany** [comment]
I have the latest *neovim-qt* and *neovim* built from HEAD, and the `:Guifont` command works as expected.
I am on Mac OS 10.12.6 adnd I have placed the command in `~/.config/nvim/ginit.vim`.

Are sure the font is installed correctly?
You can try to execute the command `:Guifont DejaVu Sans Mono:h13` after neovim-qt has started and see if any error is shown.

**Comment by equalsraf** [comment]
> ~/.config/nvim/ginit.vim

this is the correct one. In Vim there is also a gvimrc for gvim.

@osa1 how did you install, are you using a package, did you built from source?

If you are building from source and running the binary from the build folder, remember that you need to pass the location of the runtime files

```
NVIM_QT_RUNTIME_PATH=../src/gui/runtime bin/nvim-qt
```

**Comment by osa1** [comment]
Sorry, this was my mistake. I failed at installing neovim-gui-shim.
