### ISSUE TITLE
<C-S-> appears as <C-Space> before I can type anything else

### ISSUE THREAD

**Issue by ZyX-II** [equalsraf/neovim-qt#344]
When running nvim-qt on Windows I wanted to check whether I can have `<C-S-smth>` mappings. But when I type `<C-v>` then *press* `<C-S-` `<C-Space>` immediately appears before I can press `smth` as well, thus removing the possibility of tying any `<C-S-smth>` mappings.

Note that I

1. Have custom programming dvorak layout, created by Microsoft Keyboard Layout Creator tool.
2. Used https://www.howtogeek.com/194705/how-to-disable-or-reassign-the-caps-lock-key-on-any-operating-system/ to place Control on CapsLock, Escape on Left Control and CapsLock on Escape.

   *Right* control still behaves the same way.

Neovim version:

```
NVIM v0.2.1-871-g6c9183ae8
Build type: RelWithDebInfo
Compilation: C:/msys64/mingw64/bin/gcc.exe -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -D__USE_MINGW_ANSI_STDIO -D_WIN32_WINNT=0x0600 -Wvla -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv -jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"
```

`nvim-qt` refuses to accept `--version`, but it is the one which came with [chocolatey package](https://chocolatey.org/packages/neovim/0.2.1.329-beta).

**Comment by einars** [comment]
Running programmers dvorak on archlinux, I'm seeing the same effect on ctrl-shift, it's being treated as ctrl-space. I'll take a closer look at the key handling code.
