### ISSUE TITLE
Feature request: Ability to detect/click to open links

### ISSUE THREAD

**Issue by jacobmischka** [equalsraf/neovim-qt#345]
It's possible this exists already and I just don't know how to do it, but it would be handy to be able to recognize a link and be able to open it in the browser. 

As an example of what I mean, in gnome-terminal you can <kbd>Ctrl</kbd>+click a link to open it, and the link is underlined and the mouse cursor changes to a pointer on hover.

![image](https://user-images.githubusercontent.com/3939997/32136527-a7796d7a-bbd4-11e7-8a43-d72c6f3eb70c.png)

Thanks for all your work!

**Comment by justinmk** [comment]
`gx` does this already. You can map ctrl-click to `gx`:

    nmap <c-leftmouse> gx

**Comment by jacobmischka** [comment]
Thanks!

**Comment by jacobmischka** [comment]
Hm, it seems like that binding will open the link underneath the cursor, but not underneath where I click. Is there a mouse setting that might help?

Thank you!
