### ISSUE TITLE
GUI: externalize cmdline?

### ISSUE THREAD

**Issue by equalsraf** [equalsraf/neovim-qt#347]
Opening this because @khalidchawtany pinged me earlier but I really have no idea what to do with the externalized cmdline yet :)

**Comment by teto** [comment]
having a cmdline popup in the middle of the window  would be cool. I dsilike the CLI cmdline at the bottom because I have to look down on it instead of looking at the text. I would vote for something like sublimetext palette.

**Comment by jgehrig** [comment]
Closing this issue. The work can be tracked via Pull #586.
