### ISSUE TITLE
NERDTree crashes on start

### ISSUE THREAD

**Issue by Lodin** [equalsraf/neovim-qt#35]
Using a fresh version of neovim and neovim-qt on Ubuntu 14.04. As a package manager using NeoBundle. Config for installing nerdtree looks like this: 
```vim
if has('vim_starting')
  if &compatible
    set nocompatible               " Be iMproved
  endif

  " Required:
  set runtimepath+=/home/lodin/.nvim/bundle/neobundle.vim/
endif

" Required:
call neobundle#begin(expand('/home/lodin/.nvim/bundle'))

" Let NeoBundle manage NeoBundle
" Required:
NeoBundleFetch 'Shougo/neobundle.vim'

" Add or remove your Bundles here:
NeoBundle 'scrooloose/nerdtree'

" Required:
call neobundle#end()

" Required:
filetype plugin indent on

" If there are uninstalled bundles found on startup,
" this will conveniently prompt you to install them.
NeoBundleCheck

" NERDTree config for opening nerdtree in every tab
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
```
Neovim-qt fails on start. Neovim console and `:NERDTree` command in Neovim-qt works fine.

**Comment by equalsraf** [comment]
Could this be the same as #34, which version of Neovim are you using?

**Comment by svenstaro** [comment]
I had the very same thing and it was indeed the same issue and fixed upstream.

**Comment by Lodin** [comment]
@equalsraf I used version before the last (0.0.0+git201508240835+1837+12~ubuntu14.04.1), and it crashed. Few minutes ago I have updated to a new version of neovim, and NERDTree starts now as it should. So I think my issue is solved.
