### ISSUE TITLE
Tabline and viewport size with maximized window

### ISSUE THREAD

**Issue by WolfgangMehner** [equalsraf/neovim-qt#352]
I noticed a problem with the new tabline. When I maximize the window, approx. two lines on the bottom are not visible anymore. (Meaning the Vim command-line is not visible.) If I do not maximize the window, even resizing it to take up the entire screen, everything looks OK.
I would assume that when the window is maximized, the size of the viewport is by mistake that of the whole window, while in the other case the size of the viewport is correctly calculated from the size of the widget which contains the viewport.

I have Ubuntu 16.04, with MATE desktop, and with
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5)
and Qt5 (5.5.1+dfsg-16ubuntu7.5) from Ubuntu packages

Neovim is build from source https://github.com/neovim/neovim/commit/54b79f19d7c63e5a7673264665d95dac335ede2c
Neovim-Qt is build from source https://github.com/equalsraf/neovim-qt/commit/0551ef29108ebcfad2f9bcaa8658317bf8ca886c

Maximized:
![nvim-qt-fullscreen](https://user-images.githubusercontent.com/2720024/32418891-cbf3af46-c271-11e7-8c2e-74cc14662bdf.png)
Resized to fill up the screen:
![nvim-qt-non-fullscreen](https://user-images.githubusercontent.com/2720024/32418892-cc0bf434-c271-11e7-9445-d11d373787ad.png)

**Comment by WolfgangMehner** [comment]
Same phenomenon with the standard Ubuntu Desktop

**Comment by equalsraf** [comment]
Does it help if we disable the auto hide of the tabline? patch in https://github.com/equalsraf/neovim-qt/pull/353

**Comment by equalsraf** [comment]
I cant reproduce in my window manager with a maximized window. But using fullscreen also works e.g. open with `nvim-qt --fullscreen` and then open a new tab.

**Comment by WolfgangMehner** [comment]
The patch does not help, sorry. Running with `--fullscreen` shows the same undesired behavior on my system.

**Comment by equalsraf** [comment]
Updated #352. Does this work for you now?

**Comment by WolfgangMehner** [comment]
This seems to fix it for me, I will also try your solution later:
https://gist.github.com/WolfgangMehner/ada83e664af5dc5c431dd933fe571a8e

**Comment by equalsraf** [comment]
@WolfgangMehner with that patch you probably would run into problems if you call `:set lines=`  with a value larger than the available space (while the window is maximized)

**Comment by WolfgangMehner** [comment]
For me, running `:set lines=XX` never has any effect, even if the window is not maximized.
(Comparing the documentation `:help 'lines'` that would even be sort of OK.)

I have the following hypothesis:

This line: https://github.com/equalsraf/neovim-qt/blob/4ecb532f865795b26535330ab809aca9c373cbc2/src/gui/mainwindow.cpp#L135 does not seem to be correct as soon as we have more than one widget in the main window.

According to the Qt documentation http://doc.qt.io/qt-5/qwidget.html#maximized-prop : 

> _Note:_ Due to limitations on some window systems, this does not always report the expected results (e.g., if the user on X11 maximizes the window via the window manager, Qt has no way of distinguishing this from any other resize). This is expected to improve as window manager protocols evolve.

Maybe your window manager is one of those, which would also explain the different behavior we observed. If I am correct, the above mentioned line would have never run on your system.

Grepping through the code, it seems that: https://github.com/equalsraf/neovim-qt/blob/4ecb532f865795b26535330ab809aca9c373cbc2/src/gui/mainwindow.cpp#L134 is the only time those properties from the QWidget class are queried. So this problem would only show up once we add more elements to the GUI, e.g. the tab bar, and not in any other part of the code.

Plus, this: https://github.com/equalsraf/neovim-qt/blob/174770cd6b162d61b9ad01f3ee93a3f5a28b14ea/src/gui/mainwindow.cpp#L140 will cause more problems once more elements are added, e.g. an externalized cmd.-line

**Comment by WolfgangMehner** [comment]
BTW. Thanks for this awesome project. I love the fact that I can --server to work with a nvim instance running on a different machine.

**Comment by equalsraf** [comment]
I agree with your assessment of the problem, and yes since my window manager is tilled a lot of the resizes do not happen the same way as in other WMs.

We used to respect `set lines` but I think we stopped doing it a while back. I've pushed a new commit that does the same thing in both cases

```
	m_shell->resizeNeovim(m_shell->size());
```

But I'm am unsure if this is correct -- :) need to leave right now, will continue testing later.

> BTW. Thanks for this awesome project. I love the fact that I can --server to work with a nvim instance running on a different machine.

This might be useful https://github.com/equalsraf/neovim-qt/issues/332

**Comment by qwfy** [comment]
62d3976cb3cd59786df5c733cf299f8c25366263 no longer:

>When I maximize the window, approx. two lines on the bottom are not visible anymore.

but it introduces higher command line, see the picture:

No tab, command line height is 1 line:
![no tab](https://user-images.githubusercontent.com/11158705/32695956-b316f05e-c7a4-11e7-8781-6bbcff820f55.png)

With tab, command line is higher than 1 line:
![with tab](https://user-images.githubusercontent.com/11158705/32695958-b9d2774c-c7a4-11e7-9883-ead80afd27c4.png)

**Comment by WolfgangMehner** [comment]
I think the 14 pixels at the bottom are actually empty, because they do not fit an additional row. In the first example the command line also seems to take slightly more space than the other rows.

The computation is essentially:
`number_of_rows = floor ( viewport_height / cell_height )`,
the additional pixels you see are the "remainder" of that operation:
`viewport_height / cell_height - floor ( viewport_height / cell_height )`
