### ISSUE TITLE
Honor 'tabline' and 'showtabline' settings?

### ISSUE THREAD

**Issue by davidsierradz** [equalsraf/neovim-qt#355]
Using the AUR package `neovim-qt-git` in `manjaro-i3`

I have [vim-airline](https://github.com/vim-airline/vim-airline/issues) installed, and using the tabline extension this is what `set tabline?` shows:

``` viml
tabline=%!airline#extensions#tabline#get()
```

Also, `set showtabline?`:

```viml
showtabline=2
```

But no tabline is displayed:

![2017-11-08-125203_1366x768_scrot](https://user-images.githubusercontent.com/9190258/32565038-f8bc2774-c483-11e7-9595-8a47c9c46925.png)

If I open a new tab:

![2017-11-08-125100_1366x768_scrot](https://user-images.githubusercontent.com/9190258/32564892-8c354afe-c483-11e7-9994-3c3790652354.png)

Any idea how to disable the new tabline and use the Airline one? thanks

**Comment by justinmk** [comment]
The externalized tabline is a bit basic, currently. To support real 'tabline' fully this PR is needed: https://github.com/neovim/neovim/pull/6607

Forgot about 'showtabline', maybe that's a bug with externalized tabline. Hmm.

**Comment by equalsraf** [comment]
showtabline should be fixed in the master branch.
