### ISSUE TITLE
Bottom gets chopped off when having tab and maximized

### ISSUE THREAD

**Issue by qwfy** [equalsraf/neovim-qt#356]
When nvim-qt window is maximized, and there are tabs (`:tab new`), the bottom of nvim-qt would go over the bottom screen. If the window is not maximized then there is no problem, see the picture

No tab, works ok:

![no tab](https://user-images.githubusercontent.com/11158705/32637500-1918d496-c5f5-11e7-8078-fb377f752f95.png)

With tab, bottom is chopped off:

![with tab, bottom is chopped](https://user-images.githubusercontent.com/11158705/32637501-195e5b88-c5f5-11e7-8808-3ff0a0c17830.png)

```
nvim: v0.2.1
nvim-qt: commit 0551ef29108ebcfad2f9bcaa8658317bf8ca886c
desktop env: plasma-desktop 5.11.3-1 with breeze theme
```

**Comment by justinmk** [comment]
https://github.com/equalsraf/neovim-qt/issues/352
