### ISSUE TITLE
Closing nvim-qt closes the headless nvim server running in TCP socket

### ISSUE THREAD

**Issue by Mariappan** [equalsraf/neovim-qt#36]
Hi
I have started neovim in headless mode in remote server and connect from local laptop using tcp/ip msgpack.

Everything is working fine. But when i close the neovim-qt (which i will do accidently most of the time), it closes the nvim server which is running in the server. I am expecting only the connection get closed so that I can connect to the same nvim server after sometime.

Can we change the behavior of close button to just disconnect the session without actually closing the nvim running in headless mode.

**Comment by equalsraf** [comment]
Maybe for TCP sessions, but certainly not for embedded Neovim processes.

The `:qa` command is issued when a [closeEvent](https://github.com/equalsraf/neovim-qt/blob/master/src/gui/mainwindow.cpp#L92) takes place. The type of connection is available through the [m_ctype](https://github.com/equalsraf/neovim-qt/blob/master/src/neovimconnector.h#L37) attribute (currently private).

My question here is, what would the default behavior?

1. If Neovim is launched via `spawn()` the current behavior remains unchanged
1. If its a TCP connection then skip the call to `:qa` as you suggest
1. If its a local socket/pipe (same as the TCP case for consistency)

Not ideal if the user actually expects the window close button to close a remote Neovim, but I currently don't have a way to customize this behavior. If the user really needs to exit he can call `:q`

A simple approach would be to expose `m_ctype` and add an if statement to [Shell::closeEvent](https://github.com/equalsraf/neovim-qt/blob/master/src/gui/shell.cpp#L637)

**Comment by Mariappan** [comment]
> If Neovim is launched via spawn() the current behavior remains unchanged
> If its a TCP connection then skip the call to :qa as you suggest
> If its a local socket/pipe (same as the TCP case for consistency)

Thats what i want exactly. You summarized it crystal clearly.

> Not ideal if the user actually expects the window close button to close a remote Neovim, but I currently don't have a way to customize this behavior.

I dont anticipate this will be a ideal case, since if the user starts nvim in socket or tcp connection (probably in server), he wants it to be alive just like any other server. If user wants to edit only local file, he/she could open with embed option which is much more convenient than opening the GUI specifying nvim listen address.

Last thing, thanks a lot for this wonderful GUI :+1: . Already started using it in my development setup with nvim in headless mode in server and nvim-qt acting as both ssh connection and tmux session :smile: .

**Comment by Mariappan** [comment]
Closing this Issue as the code changes are merged.
