### ISSUE TITLE
How to disable GUI tabline?

### ISSUE THREAD

**Issue by unclechu** [equalsraf/neovim-qt#361]
How to just use default text-based tabline?

I have `tabline` set as `%!airline#extensions#tabline#get()` but see GUI tabs, without any features provided by extension, no window titles, numbers, etc. Just current buffer, kinda `expand('%')`.

**Comment by equalsraf** [comment]
I dont have a method to disable it at the moment, but I'm willing to add something to configure this behaviour. Preferably in the form of an option in ginit.vim

**Comment by justinmk** [comment]
There is already a `showtabline` option. Instead of a new option, nvim-qt could listen for changes to that option, and also check it.

    au OptionSet showtabline ...

**Comment by equalsraf** [comment]
> There is already a showtabline option. Instead of a new option,

:+1 was the option supposed to work for the GUI events too, the docs suggest as much

> This is both for the GUI and non-GUI implementation of the tab pages

**Comment by unclechu** [comment]
@equalsraf for [neovim-gtk](https://github.com/daa84/neovim-gtk/) it's done by this command:
```viml
call rpcnotify(1, 'Gui', 'Option', 'Tabline', 0)
```

**Comment by equalsraf** [comment]
@unclechu cool I was not aware of that.

> Preferably in the form of an option in ginit.vim

I will have to correct myself on this one. UI attachment happens before ginit.vim is sourced i.e. the option in ginit.vim would be too late to have an effect.

**Comment by legendre6891** [comment]
Merry xmas/happy holidays! 

What is the status of #362 at the moment? It would be great if we could use the 'TUI' tabline instead of Qt's.

**Comment by justinmk** [comment]
showtabline and other UI related options are sent as UI events in Nvim 0.2.3. so no need for extra options.

**Comment by equalsraf** [comment]
> showtabline and other UI related options are sent as UI events in Nvim 0.2.3. so no need for extra options.

showtabline disables the tabline for both the external tabline and the TUI, but they want a way to use the internal TUI tabline in neovim-qt instead of the external one that was added recently.

**Comment by BoltsJ** [comment]
You can now use `GuiTabline 0` in `ginit.vim` to go back to the TUI tabline.

**Comment by equalsraf** [comment]
Closing this, thanks @BoltsJ

**Comment by justinmk** [comment]
The `option_set` UI redraw event publishes the `showtabline` option value whenever it is changed. Why not use that instead of adding another shim command? 

This is a lot of code and an unnecessary command, and it fractures what the user must learn ...

**Comment by equalsraf** [comment]
@justinmk the showtabline hides or shows the tabline completely. What they wanted was a way to use the tabline provided by neovim instead of the Qt gui widget tabline.

**Comment by justinmk** [comment]
My mistake, we would need support for 'guioptions' to satisfy my comment.
