### ISSUE TITLE
"nvim-qt +mak" is not responsive

### ISSUE THREAD

**Issue by shlomif** [equalsraf/neovim-qt#363]
"nvim-qt +mak" is not responsive and keeps saying:

```
Neovim fatal error "Neovim is taking too long to respond"
Neovim API version compatible with 0 supported 3
Request 1 timed out: 34
```

"nvim +mak" and "nvim-qt +echo" are fine. I am using it on xfce on Mageia v7 x86-64. I am using git commit 539522cf19633163f72a8c567960b06e133048da of neovim-qt and a recent commit of neovim.

**Comment by jgehrig** [comment]
This scenario works now. Marking as closed.
