### ISSUE TITLE
Buffer list not shown

### ISSUE THREAD

**Issue by tuxflo** [equalsraf/neovim-qt#366]
Some infos first:
Operating System: KDE Neon (Ubuntu 16.04)
Compiler version: g++ (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
QT version: 5.9 (qt5-default/xenial,now 5.9.3+dfsg-0neon+16.04+xenial+build41 amd64)
Build version: latest git version, commit 539522cf19633163f72a8c567960b06e133048da

Problem:
In the GUI version the buffer list (created by vim-airline) is not shown. Here are 2 screenshots to visualize the issue:
Nvim in Konsole:
![screenshot_20171227_172750](https://user-images.githubusercontent.com/2816893/34396729-1846b374-eb2c-11e7-930e-cc733e1c03a7.png)

Neovim-qt:
![screenshot_20171227_172832](https://user-images.githubusercontent.com/2816893/34396730-1c257d04-eb2c-11e7-94d7-d7b2f0aa587e.png)

I'm using lots of buffers and the list prevents me from getting lost :)

**Comment by shuhaowu** [comment]
I can confirm this issue.

**Comment by cristobaltapia** [comment]
I am having this problem, too.

**Comment by cristobaltapia** [comment]
That works, thanks! Is there an configuration that can be used instead of opening nvim-qt with that option? (in `ginit` or something like that?)

**Comment by BoltsJ** [comment]
No, there isn't currently. I'd recommend making a copy of nvim-qt.desktop in `~/.local/share/applications/` and changing the `Exec` line to `Exec=nvim-qt --no-ext-tabline -- %F` if you're on Linux.

**Comment by BoltsJ** [comment]
Now that #431 is merged, you can use `GuiTabline 0` in `ginit.vim` to disable the gui tabline.

**Comment by cristobaltapia** [comment]
Thanks @BoltsJ ! It works perfectly! :)

**Comment by equalsraf** [comment]
Closing this then.
