### ISSUE TITLE
FR: Please support qt5-static link.

### ISSUE THREAD

**Issue by zhaozg** [equalsraf/neovim-qt#376]
If yes, I'll make a PR.

**Comment by equalsraf** [comment]
I dont mind supporting static linking in the build scripts but this is usually hard to do in windows without a custom Qt build and some Qt plugins are always dynamic libraries.

@zhaozg what did you mean with `cut down depends`?

**Comment by zhaozg** [comment]
@equalsraf when static link QT, it has no depends, this is my mean.

**Comment by zhaozg** [comment]
The support for qt5-static not finished, but you can look a head from https://ci.appveyor.com/project/zhaozg/neovim-qt/build/0.2.8.11.
