### ISSUE TITLE
quit too slowly

### ISSUE THREAD

**Issue by zhaozg** [equalsraf/neovim-qt#377]
when type :q will wait a moment to quit on windows 10 pro, but nvim will quickly. Any others care about it?

**Comment by Leandros** [comment]
I'm experiencing the same, without the vimtex plugin, though.

**Comment by zhaozg** [comment]
@Leandros thanks.

**Comment by equalsraf** [comment]
Does `nvim-qt -- -i NONE` avoid the issue?

**Comment by zhaozg** [comment]
OK, I installed spacevim, maybe some plugins cause this iusser. 
`nvim-qt -- -u NORC` type `:q` will quit quickly.
but `nvim-qt -- -i NONE`  quick slowly too.

**Comment by equalsraf** [comment]
Ok thanks @zhaozg. So it is not the same problem as #373, and it does seem to be caused by some plugin.

@Leandros does `-- -u NORC` make any difference for you?

**Comment by Himura2la** [comment]
I experience the same. Windows 10 1709.
When I issue `:q` with the open file, the cursor starts flashing with the loading indicator.
Sometimes this does not reproduce.

**Comment by zhaozg** [comment]
Use head of neovim, the issue disappered, maybe fixed by https://github.com/neovim/neovim/commit/c6fe06bbc09c0adbb3ef30be9f5b238e802b5038
