### ISSUE TITLE
set background not working  in ginit.vim

### ISSUE THREAD

**Issue by feluxe** [equalsraf/neovim-qt#390]
Hi there!

I have this in `init.vim`:

     set background=dark

and this in `ginit.vim`:

    set background=light

I expected `nvim` (terminal) to run in dark mode and `nvim-qt` (gui) to run in light mode. Unfortunately `nvim-qt` does not switch to light mode.

I have this `Guifont DejaVu Sans Mono:h8` in `ginit.vim` as well, which works fine.

Any idea what this could be?

OS: Arch Linux. Installed nvim-qt from source. `cmake=3.10.1`, `GNU Make 4.2.1`, `Qt=5.10.0`

**Comment by jgehrig** [comment]
Working as of `v0.2.16`.

I think there are also changes in recent versions of `nvim` making this more likely to work on various frontends.
