### ISSUE TITLE
Slow or fail to exit when Python code is executed after GuiClose

### ISSUE THREAD

**Issue by micbou** [equalsraf/neovim-qt#394]
When Python code is executed after the `GuiClose` function, nvim-qt takes several seconds to exit or does not exit at all with the message `Press Enter or type command to continue` on the command line. Pressing the enter key twice will then exit Neovim.

Steps to reproduce:
 - `nvim-qt -- -u NORC`
 - `:autocmd VimLeave * python pass` (replace `python pass` with `python3 pass` if using Python 3)
 - `:q`

Here are [the logs](https://gist.github.com/micbou/c8576b8716bf41686d11ebcc1e39d340) from these steps with `set verbose=15`. Looks like Neovim gets into an infinite loop calling alternatively `GuiClose` and `python pass`.

Related issue: https://github.com/Valloric/YouCompleteMe/issues/2919.

Configuration:
 - Windows 7 64-bit;
 - [pre-built Neovim 64-bit from the Wiki](https://github.com/neovim/neovim/wiki/Installing-Neovim#pre-built-archives): `v0.2.3-711-g6c3dd51aa`;
 -  `neovim` Python package 0.2.1.

**Comment by bonderado** [comment]
Possibly related to #341.

**Comment by equalsraf** [comment]
Does https://github.com/equalsraf/neovim-qt/pull/435 fix this for you?

**Comment by micbou** [comment]
It does. Thanks!

**Comment by equalsraf** [comment]
Merged into master.
