### ISSUE TITLE
Cannot set default editor in osx

### ISSUE THREAD

**Issue by ta3pks** [equalsraf/neovim-qt#399]
when i try to set neovim-qt as the system-wide editor for any sort of file i get error message saying 
an error occured 
![2018-03-17 19_39_33](https://user-images.githubusercontent.com/9097437/37557223-f4ccb500-2a1a-11e8-903f-d2c6d083a5c4.gif)

**Comment by equalsraf** [comment]
Using Sierra here.

I installed nvim-qt using brew.and dragged the app from /usr/local/Cellar/... to Applications. From the **Open with -> Other** I was able to set **Always open with**. But as reported I cannot use the **Change All** button without getting an error.

The exact same issue is reported in apple https://discussions.apple.com/thread/1140217 there are some suggestions there but I cant follow through right now.

**Comment by equalsraf** [comment]
Does not seem to be something we can fix on our end.  Please reopen if we have a path forward.
