### ISSUE TITLE
WM_CLASS Should be neovim-qt

### ISSUE THREAD

**Issue by concatime** [equalsraf/neovim-qt#401]
Hi.
When using `xprop`, it detects neovimQt as `.nvim-qt-wrapped`, which is not clean. It should be `neovim-qt` (`WM_CLASS(STRING) = ".nvim-qt-wrapped", ".nvim-qt-wrapped"`).
For example, when I _xprop_ quteBrowser, it prints `qutebrowser` (`WM_CLASS(STRING) = ".qutebrowser-wrapped", "qutebrowser"`).
Thank you.

**Comment by equalsraf** [comment]
Perhaps this can be done as part of the desktop file using `StartupWMClass` - https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html





StartupWMClass
--

**Comment by equalsraf** [comment]
This seems to be set as `nvim-qt`` now. Maybe something changed in Qt upstream.

Closing for now.
