### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by ShalokShalom** [equalsraf/neovim-qt#402]
Hi, I am very happy to see that someone integrates an editor with Qt :D

I suggest to include a screenshot or two.

Thanks a lot ^-^

**Comment by equalsraf** [comment]
Duplicate https://github.com/equalsraf/neovim-qt/issues/47 - in short I'm not a fan of placing screenshots in the README, and github no longer supports this. I certainly dont mind if someone adds a couple of wiki entries ^^

**Comment by ShalokShalom** [comment]
I just saw one screenshot on other Github pages? How they are not supported anymore?
https://github.com/ramboxapp/community-edition#screenshot

**Comment by equalsraf** [comment]
In that particular case they just added a link inside the markdown ([raw markdow](https://raw.githubusercontent.com/ramboxapp/community-edition/master/README.md)), it works but is not very nice when you are actually reading the README file.

This is what mostly people do, either in the README, in the wiki or in the project pages.

> How they are not supported anymore?

I was under the impression that at some point in the past GH did support project images/screenshots of some kind. Maybe I am wrong and was just confusing GH with some other code hosting forge.

**Comment by equalsraf** [comment]
Any preference on what you would like to see on those screenshots?

**Comment by u2berggeist** [comment]
[veonim](https://github.com/veonim/veonim) has a ton (probably too many). [Oni](https://github.com/onivim/oni) does a good job of highlighting multiple features in a single screenshot.

Basically, one screenshot highlighting any special GUI item. As I kinda alluded to before, I haven't actually installed it, so I don't know what the specific GUI stuff would be pertinent 😅. It doesn't have to be nearly as extensive as veonim's (it honestly goes a bit overboard). 

But here's a list knowing absolutely nothing about neovim-qt. Screenshot with...
1. ...multiple splits (with one of the splits being the console if it's integrated GUI wise)
2. ...tab completion in there
3. ...hover information (if it's available)
4. ...multiple tabs
5. ...maybe one or two different color themes. Don't need to repeat the previous screenshots, just something to give a feel

These ideas could probably be combined into one or two screenshots similar to what Oni has, but I'm not sure if that'd work with neovim-qt.

**Comment by equalsraf** [comment]
Oni has a lot more going for it in terms of Gui elements. At first glance you might not even notice this is a GUI.

The following trigger Gui widgets for us

- tabs
- auto complete

![nvim-qt](https://user-images.githubusercontent.com/715238/49906185-b6b26a80-fe68-11e8-8a7b-e4fd5e4569ce.png)


Others are harder to demonstrate like font and tabline.
