### ISSUE TITLE
Neovim-Qt does not reload files modified by external programs

### ISSUE THREAD

**Issue by kdurant** [equalsraf/neovim-qt#404]
*  nvim --version:
    v0.2.2
    * (Vim (version: ) behaves differently?
    Gvim can reload files modified by external programs
    * Operating system/version:
    Win7

`Actual behaviour`

    open file with vim and neovim
    modified file by Gvim , neovim don't auto reload
    modified file by neovim , Gvim can auto reload

**Comment by equalsraf** [comment]
This seems like something that should be reported to the neovim repo. I dont think it is related to the GUI.

**Comment by equalsraf** [comment]
See https://github.com/neovim/neovim/issues/1936
