### ISSUE TITLE
[future request] I need to make neovim-qt window transparent, just like wimproved.vim.

### ISSUE THREAD

**Issue by augustblizzard** [equalsraf/neovim-qt#411]
I need a plugin or config to make neovim-qt window transparent just like wimproved.vim(just need WSetAlpha)

**Comment by adrianrocamora** [comment]
It would be nice to have

**Comment by sentavian** [comment]
It is possible to do this with third party apps / utilities / settings depending on your OS etc(although still nice to have built in). A missing killer feature, however, would be setting only the background as transparent or setting a background image.

**Comment by matheusfillipe** [comment]
> It is possible to do this with third party apps / utilities / settings depending on your OS etc(although still nice to have built in). A missing killer feature, however, would be setting only the background as transparent or setting a background image.

Do you mean it is posible to set true transparency and if so I would like to
know how, or do you mean managing the compositor and having both the background
and the text with opacity?

**Comment by augustblizzard** [comment]
![image](https://user-images.githubusercontent.com/11937856/90994780-71a67b80-e5ec-11ea-9acd-80c434cc7571.png)

just like image that I uploaded.

**Comment by equalsraf** [comment]
Opened a CR for this https://github.com/equalsraf/neovim-qt/pull/737, a GuiWindowOpacity command sets the opacity in the range 0.0 - 1.0. Can you test if it works for you?

**Comment by augustblizzard** [comment]
sure, I'll test when I'm free of work.

**Comment by Atharva-k** [comment]
does this work now ?

**Comment by jgehrig** [comment]
@Atharva-k 

Yes, this should work. However, it is only available in the `master` branch.

`:GuiWindowOpacity 0.7`

It will be added to the next release, `0.2.17`.

**Comment by matheusfillipe** [comment]
Btw this is not real transparency. Real transparency would be background only transparency. Having the text transparent is not ideal. I hope this can be addressed in the future, would be cool.

**Comment by jgehrig** [comment]
The request here was full window transparency, like `wimproved.vim` in the screenshot.

I agree, that would be a cool improvement. I'm not sure if it is (easily) possible with Qt. If anyone wants to take a look at implementing such a feature, `QGraphicsEffect` is probably a good starting point.

**Comment by thePHTest** [comment]
What is the cycle for new releases? I would love to have this available.
