### ISSUE TITLE
Devicons are cropped…

### ISSUE THREAD

**Issue by kierun** [equalsraf/neovim-qt#415]
Devicons as imported in a Nerd Font patched font are chopped:

![screenshot](https://user-images.githubusercontent.com/3079575/40836065-538f9960-658d-11e8-8304-f4e45f8cc14c.png)

I am on `commit 2cd39097caf9e9a44e1d79788e01b2e9f667aa59` and NVIM v0.2.0 if that helps.

What else would you need?

**Comment by kierun** [comment]
Same on `fcb99d684e8567a67e13be90d92596dabf40973a` with Nvim 0.3.0… ☺

**Comment by Mte90** [comment]
In my nvim-qt are 1/third cropped
![immagine](https://user-images.githubusercontent.com/403283/66475679-1c28b500-ea94-11e9-90c2-49912a45562f.png)

**Comment by kierun** [comment]
I can confirm it's a problem with the font. I messed with Nerd fonts and now this is what I see:

![screenshot](https://user-images.githubusercontent.com/3079575/66480812-58a9e000-ea97-11e9-990a-80c4ebcb7299.png)

The icons are smaller but hey-ho, they work.

**Comment by jgehrig** [comment]
Marking as closed, as per comments above.

Wide character support is now better with some changes in `neovim` and `neovim-qt`.
