### ISSUE TITLE
Windows 7: Opening file from command line fails with 0.3.0 release

### ISSUE THREAD

**Issue by tbttfox** [equalsraf/neovim-qt#416]
I grabbed the 0.3.0 release from neovim this morning, and my right-click "Open With Neovim" stopped working.  Neovim-qt still opens, but the file isn't loaded. Afterwards, I can drag/drop or :e files normally.
There are no errors reported anywhere that I can see.

I tried directly from the windows 7 command line with both relative and full filepaths, with and without quotes. Still no success.
`"C:\Program Files\Neovim\bin\nvim-qt.exe" <<filepath>> -- -u NORC`

Invoking neovim (not qt) directly from the command line works.

**Comment by justinmk** [comment]
Try putting the files after `--`

**Comment by tbttfox** [comment]
That works. Thanks.
Is that the intended usage now? If so, the nvim-qt help message should be updated.

**Comment by whitebyte** [comment]
This is not Windows-specific behaviour, I have the same issue on Linux

**Comment by kierun** [comment]
#417 duplicate?

**Comment by tbttfox** [comment]
Yep, same thing. Since equalsraf responded to that one, I'll just go ahead and close this one

**Comment by kierun** [comment]
My bad. I should have closed mine since yours was earlier. Apologies for high jacking it. ⍨

**Comment by Perry3D** [comment]
I think nvim-qt is loading the file. But also opens another empty buffer afterwards. Just close it
 `:bd`
and you see the the file. For a workaround you can also add this to the end of your init.vim.
