### ISSUE TITLE
Can't open file passed as argument

### ISSUE THREAD

**Issue by PhilT** [equalsraf/neovim-qt#422]
I've installed Neovim 0.3.0 from Chocolatey using `--pre` on Windows 10.

I've added `C:\Tools\neovim\Neovim\bin` to my path.

I can run `nvim file.txt` and it loads `file.txt` for editing.

However, if I run `nvim-qt file.txt` I get `[No Name]` and the file is not loaded.
I get the same response if I do `nvim-qt -- file.txt`. I've also tried specifying full paths to executable, the file to open, the nvim executable but the file still does not load.

I'm assuming it's an issue on my machine as others would no doubt have reported this already but I can't think what it could be.

I also tried installing 0.3.1 but I get an error saying it couldn't find the Qt platform plugin.

Any ideas?

**Comment by PhilT** [comment]
I solved the 0.3.1 platform plugin error by copying `qwindows.dll` to the `platforms` subfolder in `bin/`

**Comment by justinmk** [comment]
> solved the 0.3.1 platform plugin error by copying qwindows.dll to the platforms subfolder in bin/

@b-r-o-c-k ist seems like the new cmake script isn't copying to this subfolder.

**Comment by jamesvl** [comment]
I'm seeing the same issue with it not opening a file passed as an argument. 0.3.1-dev didn't solve the issue either - do you need any further debug information from us to help find a fix?

**Comment by justinmk** [comment]
@jamesvl yes, try the .zip from here: https://ci.appveyor.com/project/neovim/neovim/build/21318/job/jsnoyn9ho38hrw2l/artifacts

**Comment by PhilT** [comment]
This loads Neovim okay but still does not solve the main issue.

**Comment by justinmk** [comment]
@PhilT the main issue was addresed by https://github.com/equalsraf/neovim-qt/pull/419 but we've haven't pulled that into Nvim's builds yet.

**Comment by PhilT** [comment]
Aha! Great! Does it also not currently work when using the `--` syntax?

**Comment by ITSecMedia** [comment]
I fiddled 30 minutes trying to get nvim-qt open files via cli/cmd on windows until I found this thread.

**Comment by Raincode** [comment]
I have the same issue on windows. Neovim Qt runs fine, but when opening files associated with neovim-qt it simply opens an empty buffer in the directory and not the existing file.

**Comment by moshen** [comment]
To anyone else having this problem, version 0.3.1 on Chocolatey (the current version at this time) doesn't work.  You need to install the "--pre" version:

```
choco install neovim --pre
```

or

```
choco upgrade neovim --pre
```

If you already have it installed
