### ISSUE TITLE
Can't open files with nvim-qt when started from shell with neovim 0.3.0

### ISSUE THREAD

**Issue by riddochc** [equalsraf/neovim-qt#424]
I'm running the current opensuse leap, I built neovim-qt myself with gcc-7 at version 36fddb4 (committed Jan. 27), and would run a newer version, but most of the recent changes don't appear to be likely to affect its behavior for my uses.

I recently updated to neovim 0.3.0, and discovered that a change in neovim's behavior seems to have caused neovim-qt to be unable to open a file provided to it on the command-line.  When I run:

$ nvim-qt ~/.zshrc

I'm presented with an empty buffer.

I've bisected neovim and found that the commit introducing the change that causes this issue is https://github.com/neovim/neovim/commit/905d4d78fc4a702613b694d4ece984b69f5f2481

I may have a closer look sometime, but anyone already familiar with RPC between neovim and neovim-qt would have a huge head start on me.

Thanks for your time, and a great editor.

**Comment by riddochc** [comment]
Looking further, and remembering back to when I was first setting up neovim, I had the NVIM_LISTEN_ADDRESS variable set in my environment to point to a socket file in my filesystem.  This means that this issue isn't likely to affect anyone besides myself.  Unsetting the variable fixes the issue, as does setting it to anything like "127.0.0.1:30015," so I think it's something about specifically using a unix socket in this context.

I believe my reason for doing that in the first place was to make use of traditional file permissions to provide a little access control to which programs could connect to neovim and give it commands.  In retrospect, this was probably just setting myself to stumble over something exactly like what I'm reporting, rather than providing any actual security.  I'll accept "don't do that" as a response to this issue, even though the behavior changed.

**Comment by justinmk** [comment]
This was already addressed in about 5 other issues https://github.com/equalsraf/neovim-qt/issues/423#issuecomment-403269350

**Comment by riddochc** [comment]
Ah, you're right, and it does indeed work with the current tip of master. I think I even stared at the commit that fixed it on the neovim-qt side and decided I'd just look into the existing issues later - but should've just held off on filing this issue until at least doing that.

Sorry for the noise, and thanks again for all your work on neovim and neovim-qt.  I've come to rely on these, because it's been such a huge improvement for me overall.
