### ISSUE TITLE
after type key, can't shutdown nvim with `X` button

### ISSUE THREAD

**Issue by zgpio** [equalsraf/neovim-qt#425]
On windows, after I type `<c-w>`,  I can't shutdown nvim with `X` button immediately.
 
![default](https://user-images.githubusercontent.com/19503791/42791312-9a66ad7c-89a2-11e8-8fd2-fd3afa15f6ca.png)

**Comment by equalsraf** [comment]
Confirmed in Linux. To reproduce

1. Open nvim-qt
1. Type `<C-w>`
1. Attempt to close the window either with  the window close button or Altf+f4/etc

The window will not close. If you press `j` the window will then close.

It would seem we are blocked waiting for the rest of the `<C-w>` command, before the call to vim_command is handled.

**Comment by zgpio** [comment]
Although this button is not used often, this should indeed be fixed.

**Comment by equalsraf** [comment]
@zgpio started testing a fix for this in #462.
