### ISSUE TITLE
Add support for SpellBad and SpellCap highlighting

### ISSUE THREAD

**Issue by mkusher** [equalsraf/neovim-qt#43]
I mean thing like:
![snapshot424](https://cloud.githubusercontent.com/assets/523021/10005823/2863e9c6-60c2-11e5-9bb6-0a00b68976ba.png)

**Comment by equalsraf** [comment]
@mkusher I got started on the undercurl drawing. Its not clear to me at this point what Neovim is doing for the SpellCap case. I assumed the color would be different but I'll need to have a closer look.

**Comment by mkusher** [comment]
@equalsraf you're pretty fast :))

**Comment by equalsraf** [comment]
This should be fixed with #121
