### ISSUE TITLE
Document platform specific CLI args

### ISSUE THREAD

**Issue by equalsraf** [equalsraf/neovim-qt#434]
For example in linux we can use `--geometry` but in mac it is --qwindowgeometry (https://github.com/equalsraf/neovim-qt/issues/167)

- [ ] document these
- [ ] Add platform specific checks in https://github.com/equalsraf/neovim-qt/blob/master/src/gui/app.cpp#L135

**Comment by jgehrig** [comment]
Issue #565 is a duplicate of this work item.

The issue was fixed in Pull #590, and is available as of `v0.2.15`.

Marking the issue as closed.
