### ISSUE TITLE
nvim-qt generates weird keys in :terminal after '= 'and space fast

### ISSUE THREAD

**Issue by ghost** [equalsraf/neovim-qt#437]
nvim -v: 0.2.2

nvim-qt: was installed on ubuntu-18.04

I connected `nvim -u NORC` with `nvim-qt --server /tmp/nvim...` and when I write something like `f = ` it'll become `f =;2u`. It's reproducible 80% of the time, I tested it on two different machines(ubuntu was the same).

**Comment by JasonXJ** [comment]
This is also affecting me. I think it is actually triggered by typing `<shift>-<space>`, which happens frequently for me when I typing fast. With `nvim` in `gnome-terminal`, a normal space instead of `;2u` is inserted instead.

I am using nvim-qt 0.2.10 and nvim v0.3.1
