### ISSUE TITLE
does not show file content when double clicking on the file

### ISSUE THREAD

**Issue by jahanbani** [equalsraf/neovim-qt#440]
I am running neovim on windows 10 and when I double click to open a file, it just opens nvim-qt with no file showing. It is as if the file name is not passed to the nvim-qt to open the file. Any suggestions?

**Comment by whitebyte** [comment]
https://github.com/equalsraf/neovim-qt/issues/416
https://github.com/equalsraf/neovim-qt/issues/424
https://github.com/equalsraf/neovim-qt/issues/423

**Comment by equalsraf** [comment]
Closing, please reopen if this is not a duplicate.
