### ISSUE TITLE
Tracking issue for unsupported neovim features

### ISSUE THREAD

**Issue by equalsraf** [equalsraf/neovim-qt#445]
- [ ] default_colors_set
- [ ] mode_info_set
- [ ] arabicshape
- [ ] ambiwdith
- [ ] emoji
- [ ] ext_cmdline
- [ ] ext_cmdline
- [ ] ext_wildmenu
- [ ] ext_linegrid

**Comment by equalsraf** [comment]
Yeah we just had to set termguicolors the old days (we still set it actually). We still get the notification via **option_set**, should we do something with it.

**Comment by bfredl** [comment]
No, I meant `option_set('termguicolors', true/false)` is specifically for a remote TUI that wants to to support both cterm and rgb colors the same way as the builtin TUI does, a GUI has nothing to do with it.

> Yeah we just had to set termguicolors the old days (we still set it actually). 

This is a hack for some color schemes that check it, I presume?

**Comment by equalsraf** [comment]
> This is a hack for some color schemes that check it, I presume?

No. I just like to be able to run nvim 0.1.4 some times :D and I never removed the code that added that argument.

**Comment by bfredl** [comment]
Did nvim 0.1.4 have a bug that made it ignore `ui_attach(..., rgb=true)` if `termguicolors` was not set? `ui_attach` should be older than `termguicolors`...

**Comment by equalsraf** [comment]
I dont remember exactly but back them the GUI had to set the option for colorschemes to work correctly.

**Comment by bfredl** [comment]
That was exactly what I said before with "a hack for some color schemes that check it". Buggy color schemes have to be fixed (and some have over the time I presume), this is independent of the nvim version.

**Comment by jgehrig** [comment]
This issue has become stale. Marking as closed.

Several features have been implemented:
- ext_linegrid
- default_colors_set
- mode_info_set

One feature is still in progress:
- ext_cmdline

One feature has been superseded:
- ext_wildmenu
