### ISSUE TITLE
Fails to respond to resize or move after resizing to top of screen

### ISSUE THREAD

**Issue by PhilT** [equalsraf/neovim-qt#446]
Neovim itself seems okay but the window is unresponsive to move or resize commands after Windows 10 has resized the window to full height.

Minimise and maximise appear to still work.

**Comment by PhilT** [comment]
mouse dragging the top of the title bar border to the top of the screen. I think it may be when using dual monitors. Now that I've unplugged my laptop from my external monitor it's behaving correctly.

**Comment by jgehrig** [comment]
Resolved as per comments above. Please speak up if this is still an issue.

Marking as closed.
