### ISSUE TITLE
Build instructions, ubuntu

### ISSUE THREAD

**Issue by anderejd** [equalsraf/neovim-qt#451]
Hi there!

I'm just a user of this software and I wanted to get my hands on the latest bugfixes without waiting for the official ubuntu package to get updated, so I tried building from source.

One small snag, I was missing this library:

`sudo apt install qtbase5-dev`

Could be nice to add that info to the build instructions?

Thanks for this project btw! :+1:

**Comment by equalsraf** [comment]
hi @anderejd, thanks for the info

README files can get pretty rowdy with detailed build instructions and dependencies for all systems. But feel free to add content to the wiki. Any user can edit it, so you can just add a build page for ubuntu or any other information that is missing.
