### ISSUE TITLE
Add global sentinel variable to identify neovim-qt

### ISSUE THREAD

**Issue by legendre6891** [equalsraf/neovim-qt#456]
The idea is to introduce a variable (say, `g:NvimQt`) such that `g:NvimQt == 1` when neovim is launched with `nvim-qt`. This allows for `nvim-qt` specific customization.

See [this comment](https://github.com/equalsraf/neovim-qt/issues/452#issuecomment-417596005).

**Comment by equalsraf** [comment]
Set channel info in #458. I also added a GuiName function you can use in ginit.vim. Try something like this.

```vim
if GuiName() == 'nvim-qt'
	echom "Oh no ..."
endif
```

**Comment by equalsraf** [comment]
Closing this - it is now available with the latest version.
