### ISSUE TITLE
Solarized colorscheme displays wrong colors when loaded from .nvimrc

### ISSUE THREAD

**Issue by Marenz** [equalsraf/neovim-qt#46]
Just tried the current master (https://github.com/equalsraf/neovim-qt/commit/311070f44a40efb485b5ecf303b3c598dd071efc) with the current nvim package (`NVIM 0.0.0-alpha (compiled Sep 23 2015 21:21:47)`) and I am getting the following errors on the terminal:

```
QWidget::setMinimumSize: (/QDockWidget) Negative sizes (0,-1) are not possible
QWidget::setMaximumSize: (/QDockWidget) Negative sizes (0,-1) are not possible
Unknown Neovim function "Object vim_call_function(String fname, Array args) !fail" 
Unknown Neovim function "Dictionary vim_get_color_map()" 
Unknown Neovim function "Array vim_get_api_info()" 
```

The effect of this seems to be that it fails to render the colors that I configured. 

I am using https://github.com/altercation/vim-colors-solarized with pathogen.

**Comment by equalsraf** [comment]
@Marenz those messages should not be harmful unless the API has changed a lot, it only means that that the API bindings were generated with a version of Neovim that did not have those functions.

> The effect of this seems to be that it fails to render the colors that I configured.

What do you mean? can you share some screenshots/examples?

**Comment by Marenz** [comment]
And here you see vim-gtk

![vim-gtk](https://cloud.githubusercontent.com/assets/424752/10085594/54f95bb6-630a-11e5-9be3-01dd245d9e05.png)

Here you see nvim on the terminal:

![terminal](https://cloud.githubusercontent.com/assets/424752/10085588/4e8fdf98-630a-11e5-99e9-5f87cdbaa414.png)

Here you see nvim-qt:

![nvim-qt](https://cloud.githubusercontent.com/assets/424752/10085593/5204eaa6-630a-11e5-96e8-72773a82aac9.png)


I would have expected the colors to be at least similar to nvim :)

**Comment by equalsraf** [comment]
Does calling `:set bg` change this in any way?

**Comment by equalsraf** [comment]
**Correction**: `set bg=dark`

**Comment by Marenz** [comment]
Doing that yields the same colors as the gvim picture. So that seems to fix it

**Comment by Marenz** [comment]
Though I _do_ have `set background=dark` in my .vimrc.

**Comment by equalsraf** [comment]
According to the vim docs

> When a color scheme is loaded (the "g:colors_name" variable is set)
	setting 'background' will cause the color scheme to be reloaded.

And in fact forcing a reload with `:color solarized` has the same effect.

We are not getting some of the colors when using solarized. Reloading the color scheme forces Neovim to pass us the right colors. Its unclear if this is a bug on our part, but I've already verified that we never get the background color from Neovim (and default to white). Incidentally neovim/neovim#2953 looks a lot like this issue but the solution used there does not work us.

BTW the colors on your terminal screenshoot look like solarized is not using 256 colors on the terminal - you can force it with `let g:solarized_termcolors=256` but it would be best to figure out why.

**Comment by Marenz** [comment]
> BTW the colors on your terminal screenshoot look like solarized is not using 256 colors on the terminal - you can force it with let g:solarized_termcolors=256 but it would be best to figure out why.

I wasn't using the xdefaults they suggested on their website. I did that now and it looks quite alright now.

> ..

I'd write more about the issue but I have no idea what at this point :D

**Comment by equalsraf** [comment]
> I'd write more about the issue but I have no idea what at this point :D

No need, the [comment in 2953](https://github.com/neovim/neovim/issues/2953#issuecomment-122852800) is spot on, I've already hacked a test here and it works. Sadly I can't offer a workaround for you, other that using a different colorscheme.

I'll mark this as waiting until I hear back from that issue.

**Comment by equalsraf** [comment]
Closing, see https://github.com/neovim/neovim/issues/2953#issuecomment-179673780
