### ISSUE TITLE
Saving and switching buffers makes editor forget history

### ISSUE THREAD

**Issue by ptersilie** [equalsraf/neovim-qt#468]
The editor forgets the history after switching to a different buffer, meaning that undo and redo don't work anymore. To reproduce:

- Open two files
- Make edits in file: undo/redo works as expected
- Save changes and switch to the buffer of file2
- Switch back to file1: undo/redo don't work as the history has been wiped

**Comment by justinmk** [comment]
@ptersilie That's because you have `'nohidden'`. This is a (bad) "feature" of Vim. Use 

    :set hidden

 to fix it. And it isn't related to neovim-qt.

In Nvim core we are considering making `'hidden'` the default.

**Comment by ptersilie** [comment]
Oh you are right. I could have sworn I tested it with `nvim` first before I reported the "bug" and then it worked. But I checked again and now they both behave the same. So, thanks for the help!

I would agree, that making `hidden` the default is probably a good idea!
