### ISSUE TITLE
complete popup have wrong color

### ISSUE THREAD

**Issue by trlsmax** [equalsraf/neovim-qt#471]
Arch linux x64, neovim 0.3.1, neovim-qt compiled with the latest code. No matter what complete plugin I used, popup window have wrong color.
![screenshot_2018-10-02_21-11-55](https://user-images.githubusercontent.com/5501321/46350642-d7e82500-c687-11e8-9827-5dfdc332aadd.png)

**Comment by equalsraf** [comment]
The popup menu is provided by the GUI and it should be using the default Qt style for your system.
To disable the GUI popup you can use `:GuiPopupmenu 0` (you can also use this in ginit.vim).

Another strange issue with that menu is the line spacing between entries. Are you having similar issues in other Qt applications?

**Comment by trlsmax** [comment]
neovim said GuiPopupmenu is not an editor command and use it in ginit.vim still not work.

My other Qt applications are seems just fine.

**Comment by trlsmax** [comment]
Problem solved with disable plugin equalsraf/neovim-gui-shim and use :GuiPopupmenu 0 in ginit.vim
Thank you.
