### ISSUE TITLE
Output error messages that occur during startup instead of just blank window

### ISSUE THREAD

**Issue by svermeulen** [equalsraf/neovim-qt#472]
Often times, I find that I'll have errors in my config or a plugin will misbehave and there will be errors during startup.  In terminal neovim, this is fine because the errors get printed to the console and you can see what happened.  With nvim-qt, it's just a blank window.  Is there a way to get access to those errors or do I have to continue reverting to terminal vim in these cases?

**Comment by justinmk** [comment]
What nvim-qt and nvim versions? This is addressed by Nvim 0.3.2 (HEAD). See also https://github.com/equalsraf/neovim-qt/pull/462 and https://github.com/equalsraf/neovim-qt/pull/463

**Comment by svermeulen** [comment]
I was on Nvim 0.3.1 with whatever version of nvim-qt is bundled with that (when installed through chocolatey).  I just tried the nightly 0.3.2 release though and am getting a different problem where it shows a blank screen then times out with "Neovim is taking too long to respond" message

**Comment by svermeulen** [comment]
Here's a very simple way to reproduce it.  If I use this as my init.vim:

```
set nocompatible
call nonexistantautoload#method()
```

Then the problem occurs.  I'm in windows 10, nvim version 0.3.2-671-g384770556 obtained from releases page

**Comment by justinmk** [comment]
>  I just tried the nightly 0.3.2 release though and am getting a slightly different problem where it shows a blank screen then times out with "Neovim is taking too long to respond" message

You need to also use the latest verison of nvim-qt, IIRC.

**Comment by svermeulen** [comment]
Same issue occurs with the version of nvim-qt from releases section.  Do you mean latest directly from nvim-qt source?

**Comment by justinmk** [comment]
I don't know. But the behavior you described is discussed elsewhere in this tracker, and it was resolved. Might be easiest to just wait until there are new releases of both nvim-qt and nvim (could be a couple months).

**Comment by svermeulen** [comment]
Ok thanks

**Comment by svermeulen** [comment]
Just want to mention that after installing nvim qt from the latest appveyor build, the issue went away.  I can now get prompts for errors or messages during startup
