### ISSUE TITLE
Can't implement commands for font resizing

### ISSUE THREAD

**Issue by reygoch** [equalsraf/neovim-qt#475]
So, usually I'd have something like this:

```vimscript
command! -bar Bigger  :let &guifont = substitute(&guifont, '\d\+$', '\=submatch(0)+1', '')
command! -bar Smaller :let &guifont = substitute(&guifont, '\d\+$', '\=submatch(0)-1', '')
```

but `guifont` variable is empty even if I set my font with `Guifont Consolas:h10:b`.

How can I programatically extract and set my current font?

**Comment by reygoch** [comment]
Ok, I've figured out that there is actually a global `Guifont` variable which just contains current font settings, but changing it doesn't affect the gui font size. It is only useful for retrieving the current state but than `Guifont` command has to be called. Here is my solution for "zooming" in the font:

```vimscript
command! -bar FontPlus  :execute "Guifont " . substitute(g:GuiFont, '\d\+', '\=submatch(0)+1', '')
command! -bar FontMinus :execute "GuiFont " . substitute(g:GuiFont, '\d\+', '\=submatch(0)-1', '')
```

**Comment by equalsraf** [comment]
You can check the help for these commands, `:h GuiFont` or to see the help for all gui commands and options use `:h nvim-gui-shim`
