### ISSUE TITLE
Change GuiTabline interface style

### ISSUE THREAD

**Issue by larrytang1** [equalsraf/neovim-qt#478]
Is there any way to change the GuiTabline style ? In current Neovim implementation it looks like Windows 98/2000. Can we change it looks like a modern Operation System such as Windows 10 with flat UI.

**Comment by equalsraf** [comment]
@davidgaleano these days I'm not much of a windows user but all the usual methods that Qt5 uses for interface styling should be available. Usually Qt should apply the native style, but maybe qtconfig can change the default.

Can you post a screenshot of what it looks like?

In addition you can also use a qss stylesheet through the command line with `nvim-qt --stylesheet file.qss`

**Comment by davidgaleano** [comment]
@equalsraf I guess you meant to answer to @daviestang?

**Comment by daviestang** [comment]
![nvim](https://user-images.githubusercontent.com/10758075/49447107-a79c3e80-f810-11e8-93b5-7c7e05adf673.png)

**Comment by daviestang** [comment]
![gvim](https://user-images.githubusercontent.com/10758075/49447653-0dd59100-f812-11e8-88d5-93cd521cf482.png)

In gvim it's more like system UI styling. Is there any way to change nvim-qt gui tabline like this ?

**Comment by equalsraf** [comment]
@davidgaleano sorry about that - I blame it on auto-complete :)

@daviestang I think this is not normal (but I cant test this right now). Where did you install nvim-qt from? Which windows version are you using?

**Comment by kdurant** [comment]
Current GuiTabline are very ugly and difficult to use ！

**Comment by daviestang** [comment]
@equalsraf I installed the nvim-qt from Neovim pre-release package [NVIM 0.3.2-dev](https://github.com/neovim/neovim/releases), and using Windows 10 pro version.

**Comment by daviestang** [comment]
@equalsraf Hello, I checked in neovim-qt project latest release v0.2.11 today. This issue has been fixed. Many thanks!

**Comment by equalsraf** [comment]
errr ... I did nothing to fix this. I dont know the specifics in windows, but the Qt style can usually be changed - maybe something else was going on.

**Comment by teto** [comment]
That's the same style as notepad++. I don't think gvim UI is more system-like than notepad. Just tweak the Qt style.

**Comment by jgehrig** [comment]
It is now possible to override the styling with `:GuiAdaptiveStyle`. 

You can see all available styles on your system with `:GuiAdaptiveStyleList`.

Here is `:GuiAdaptiveStyle Fusion` and `:GuiAdaptiveColor 1` on Windows 10:
![image](https://user-images.githubusercontent.com/11207308/127783570-a8311494-6f57-494b-bdc9-c75905569d91.png)

This feature is available in `master`, and will be included in the next release.
