### ISSUE TITLE
Doesn't load vim config when used as git editor

### ISSUE THREAD

**Issue by moshen** [equalsraf/neovim-qt#481]
Platform: Windows 10 Pro
Version: v0.3.2.88-beta (Installed from `choco install neovim --pre`)

When I set my `core.editor` in git to `nvim-qt`, my vim configuration is not loaded when the editor is launched (during `git commit`, etc).

If I launch the editor normally, my configuration is loaded properly.

**Comment by moshen** [comment]
1. Yes, it appears so (didn't notice this before)
2. Inside cmd, using msysgit:
```
where git
C:\Program Files\Git\cmd\git.exe
```
3. `echo $MYVIMRC` returns nothing?

**Comment by moshen** [comment]
When starting neovim-qt via a shortcut, `echo $MYVIMRC` returns: `C:\Users\moshen\AppData\Local\nvim\init.vim`

**Comment by equalsraf** [comment]
msysgit probably means nvim considers its settings folder to be in some other location, you might want to check :h xdg and try to figure out where nvim is trying to find the config (or try to override this location).

It is probably best to move this issue to neovim/neovim.

**Comment by moshen** [comment]
`:h xdg` shows `~/AppData/Local/nvim` (even when launched as a git commit), I'll make a ticket in the neovim repository

**Comment by equalsraf** [comment]
What about `:echo expand('~')`, does it show the same path in both cases?

**Comment by moshen** [comment]
From my comment here: https://github.com/neovim/neovim/issues/9405

Through process of elimination I figured out that having `LC_CTYPE=C` set, would cause `nvim` to not load my init.  I wrapped launching Neovim from git in a script which unsets that environment variable and it works as expected.  All other environment is left unmodified.

My script looks like this:

nvim-launcher
```shell
#!/bin/bash

export LC_CTYPE=""
nvim-qt --maximized "$*"
```

And is referenced in my `.gitconfig` like so:
```
[core]
  editor = nvim-launcher
```

**Comment by equalsraf** [comment]
@moshen awesome, thanks for taking the time to fix this upstream.
