### ISSUE TITLE
Noto Color Emoji cropped

### ISSUE THREAD

**Issue by erlanger** [equalsraf/neovim-qt#482]
Hi,

   The 'Noto Color Emoji' font is being cropped. I think it is a problem with the Qt Terminal. This is what I  get:

### On lxterminal everything OK
![lxterminal_emoji](https://user-images.githubusercontent.com/8608855/50261370-3bbaf800-0404-11e9-861f-fc5f607a356e.png)

It looks fine. It also works fine with `nvim` inside lxterminal.

### On nvim-qt emojis are cropped/not found:
![nvim-qt_emoji](https://user-images.githubusercontent.com/8608855/50261441-791f8580-0404-11e9-8d5c-b35e94158ef2.png)

This is not a problem with font selection, since I am using exactly the same font:

lxterminal font:
![lxterminal_font](https://user-images.githubusercontent.com/8608855/50261462-8d638280-0404-11e9-90a3-76ad346c2d10.png)

nvim-qt font:
![nvim-qt_font](https://user-images.githubusercontent.com/8608855/50261471-98b6ae00-0404-11e9-99cc-3625c2b71823.png)

Now the `Noto color emoji` works on lxterminal,  and everywhere else because `/etc/fonts/local.conf` has this:

```
<fontconfig>
  <match target="pattern">
    <edit name="family" mode="prepend_first">
      <string>Icons</string>
    </edit>
  </match>
    
  <match target="pattern">
    <edit name="family" mode="prepend_first">
      <string>Noto Color Emoji</string>
    </edit>
  </match>

<alias>
  <family>monospace</family>
    <prefer>
      <family>Inconsolata for Powerline</family>
    </prefer>
</alias>

<alias>
  <family>serif</family>
    <prefer>
      <family>Inconsolata for Powerline</family>
    </prefer>
</alias>
</fontconfig>

```

I think Qt terminal is not properly dealing with fonts that have double-width characters. 

Here is the file with the emojis so you can test:
[emojis.txt](https://github.com/equalsraf/neovim-qt/files/2697273/emojis.txt)

You will need to install the `Noto color emoji` font.

# Update
It is working fine on `neovim-gtk`:
![neovim-gtk](https://user-images.githubusercontent.com/8608855/50262005-f3e9a000-0406-11e9-8eee-ace39560af7d.png)

**Comment by jgehrig** [comment]
This should be resolved now in `master`, or available in the next release `v0.2.17`.

A handful of emoji bugs have been fixed. See: #735 #727 #733 #736

Marking as closed. Please re-open, or file a new bug if you still see issues.
