### ISSUE TITLE
Preview window positioning and colors are all weird 

### ISSUE THREAD

**Issue by s-kashif** [equalsraf/neovim-qt#487]
Completion window is not using correct colors on Preview (Using YoucompleteMe)
Also the position is offset

Occurs in 0.2.10 and 0.2.11, Doesn't happen in 0.2.8

![image](https://user-images.githubusercontent.com/9801383/50380524-2c120c80-06ad-11e9-81fc-786395724a87.png)

**Comment by s-kashif** [comment]
But this wasn't happening in v0.2.8  (Refer screenshot of v 0.2.8). 0.2.8 was using correct widget and was respecting the color scheme
Seems like a regression in later versions
![image](https://user-images.githubusercontent.com/9801383/50390351-b0ca5c80-0779-11e9-8cd7-688f8789e671.png)

**Comment by gagbo** [comment]
You can get this behaviour (let Nvim decide the popup stuff) with `:GuiPopupmenu 0`. Adding this in your `ginit.vim` should give you this behaviour.

In the following screenshots, I have 
- Qt theme : Kvantum KvGlass + ArcDark ; 
- Neovim theme : Snow

So anything light is from Neovim, anything dark is a Qt widget

With GuiPopupmenu (the default)  :

![screenshot_guipopupmenu](https://user-images.githubusercontent.com/10496163/50397746-def86e00-0772-11e9-8d40-0b5b5378793d.png)
 

After `:GuiPopupmenu 0` : 

![screenshot_noguipopupmenu](https://user-images.githubusercontent.com/10496163/50397787-f0da1100-0772-11e9-928d-786f5f7e8e36.png)

Note that the position is not the same (above or below text here), but I still have something reasonable (this is done while working on a feature branch that only adds a directory tree view, nothing at all about the Popupmenu).

I'll admit that we can work a little bit on alignment of columns and stuff like that, but the positioning and the theming seem fine to me

**Comment by s-kashif** [comment]
@equalsraf  and @gagbo Thanks a lot. I'll check
