### ISSUE TITLE
white screen when starting

### ISSUE THREAD

**Issue by prabirshrestha** [equalsraf/neovim-qt#489]
On windows I get this white screen and then after few sec goes to my dark solorized theme. Would be good if it could be avoided.

![image](https://user-images.githubusercontent.com/287744/50527353-91df0980-0a9c-11e9-8d3e-967547e26c78.png)

**Comment by justinmk** [comment]
what version of nvim-qt and nvim

**Comment by justinmk** [comment]
Somewhat related to this, @equalsraf  Nvim now [defaults to background=dark](https://github.com/neovim/neovim/pull/9205) so it make sense for Neovim-Qt to default to a dark background at the Qt widget level. That would have the side-effect of "hiding" the effect reported here.

**Comment by gagbo** [comment]
[Related line of code](https://github.com/equalsraf/neovim-qt/blob/7b216b0387da0190cc70a041c8258ea65e602638/src/gui/shell.cpp#L287) @bfredl hinted that the default background should be set when nvim sends -1, so this is probably where the fallback should be "better"

(Or maybe the fallback should be the user's `QPalette`, but that's up for discussion I guess)

**Comment by bfredl** [comment]
What I meant was rather that nvim itself should never send `-1`, instead always send concrete rgb colors for `default_colors_set`. (except perhaps some opt-in flag for remote TUI which needs real `bg=NONE` behavior)

**Comment by equalsraf** [comment]
That comment is pretty old. I can confirm that it should never happen and to my knowledge it only happened a long time ago (think early days of neovim and the ui protocol).

**Comment by gagbo** [comment]
Ok. I suppose most of this issue is at least postponed until `ext_linegrid` is working here.

**Comment by nadya-p** [comment]
I'm also experiencing this issue.
![image](https://user-images.githubusercontent.com/15910645/51990754-fdf0cb00-24a9-11e9-8827-14b6a920bb18.png)

**Comment by jgehrig** [comment]
This issue should be resolved now. I don't see these issues with `v0.2.16` using a light or dark background. 

Most of the fixes discussed in this thread are  implemented: default colors, `ext_linegrid`, `:set background=`, and `:GuiAdaptive*`.

If anyone sees issues like this in a recent release, please file a new bug. Marking as closed.
