### ISSUE TITLE
Input box do not follow cursor

### ISSUE THREAD

**Issue by equalsraf** [equalsraf/neovim-qt#490]
Originally reported in gitter by @wsdjeg, when using sougou in windows, the input box does not follow the cursor.

![image](https://user-images.githubusercontent.com/715238/50550647-4aa77300-0c6c-11e9-9bb3-23cf90ba1185.png)

@bfredl suggested a fix for this,

> I think call to QInputMethod::setInputItemRectangle is needed when cursor is moved.

which I tried to implement in https://github.com/equalsraf/neovim-qt/pull/488.

Sadly Christmas is over so I no longer have windows to test. This should be fixable by checking with Qt docs, I just have no way to test fixes.

**Comment by zhmars** [comment]
hi, equalsraf. 
It seems that  this problem not just happened on windows. I have the same situtation on linux using [ibus](https://github.com/ibus/ibus) 1.5.19 and  gnome 3.30.2

![2019-01-05 00-17-02](https://user-images.githubusercontent.com/18466397/50698298-75843380-107f-11e9-9d2d-b9393fb5ff02.png)

**Comment by equalsraf** [comment]
Ok I can see this in linux - but I'm not entirely sure in which position it should be.

For reference here is the list of IM queries for Qt http://doc.qt.io/qt-5/qt.html#InputMethodQuery-enum, currently we only reply to cursor rect and font.

**Comment by zhmars** [comment]
thanks reply. The candidate window should be right below cursor (as close as possible).

This is it look like in gvim
![2019-01-05 11-51-22](https://user-images.githubusercontent.com/18466397/50720115-dc3a3900-10e1-11e9-91dd-3746c237b068.png)

**Comment by equalsraf** [comment]
@wsdjeg I've merged #488, can you check if that works for you?

**Comment by zhmars** [comment]
confirmed it works on windows 10 1809 with microsoft pinyin and qq wubi :)

**Comment by wsdjeg** [comment]
Thanks, will it merged into neovim master?

________________________________
wsdjeg@outlook.com

**Comment by justinmk** [comment]
@wsdjeg when neovim-qt publishes a [release](https://github.com/equalsraf/neovim-qt/releases) then Neovim will update to that. And we will probably release 0.3.4 so that the stable version has these fixes.

**Comment by equalsraf** [comment]
Closing this then. If I forget to tag a release before then someone poke me in the face about it.
