### ISSUE TITLE
Implement GuiFont *

### ISSUE THREAD

**Issue by gagbo** [equalsraf/neovim-qt#491]
Navigating Qt documentation I found this snippet : 
```cpp
void Notepad::on_actionFont_triggered()
{
    bool fontSelected;
    QFont font = QFontDialog::getFont(&fontSelected, this);
    if (fontSelected)
        ui->textEdit->setFont(font);
}
```

Maybe it could be used to implement a `:GuiFont *` like gvim does.

I'm just leaving this here since I'm trying to do something else, this is probably going to be a small PR soon. I also think it should be easy enough to add/test the snippet

**Comment by equalsraf** [comment]
in vim-qt there is custom widget for this very purpose - mostly to filter monospace fonts https://github.com/equalsraf/vim-qt/blob/master/src/qt/fontdialog.cpp

**Comment by gagbo** [comment]
Is all of this necessary with [FontDialogOptions](http://doc.qt.io/qt-5/qfontdialog.html#FontDialogOption-enum) ?

**Comment by equalsraf** [comment]
Maybe not :D it was way back in Qt4

**Comment by equalsraf** [comment]
Closing duplicate, see https://github.com/equalsraf/neovim-qt/issues/584
