### ISSUE TITLE
Proposal : use QPalette to theme Shell's child widgets

### ISSUE THREAD

**Issue by gagbo** [equalsraf/neovim-qt#496]
Possible relatives : #489 #478 

## Summary
I think that using [QPalette](http://doc.qt.io/qt-5/qpalette.html#ColorRole-enum), and updating its values for each `colorscheme` event would help a lot with Widget consistency in the whole application.

## Illustration
For a basic example, I added a QPalette update in `update_fg` and `update_bg` handlers in 00ad4e7 in order to inherit directly the correct background/foreground for `cmdline` from `Shell::QPalette`.

### When would QPalette update
I don't think we need to change the palette for more events than these 2 (See all the documented color roles in the link above). Which means that eventually QPalette changes would only happens in `update_fg`, `update_bg` and `default_colors_set` I guess.

### What in QPalette would update
I am currently (still in 00ad4e7 ) using only `QPalette::Base` and `QPalette::Text` because it worked well to obtain the correct background in the cmdline widgets I'm implementing. But `QPalette::Tooltip{Base,Text}` can also be modified, and probably `Window` and `WindowText` too if we want to use other widgets than `Shell` like `TreeView`

### How QPalette would update
Also, I think it would be better to group all these methods/calls somewhere, this way we will be able to let the user decide if they want to have Neovim's colorscheme change the QPalette, or if they want to use the QPalette imported from their Qt settings (meaning leaving the QPalette untouched).

Having a single point of entry for Palette modification would also allow to trigger a massive repaint() to make the changes appear (for example to change an already created `TreeView` after having called `:colorscheme`)

## Misc

In any case, it would be nice to be able to render a (Neo)vim colorscheme in a QPalette, so we can see how applying the colorscheme would render for other widgets (I think the 'Application Color Theme' menu in my Plasma system settings app is basically a QPalette viewer)

![screenshot_20190106_120159](https://user-images.githubusercontent.com/10496163/50735196-115e8e00-11ab-11e9-812f-fb5975e2d65b.png)

I think that having this kind of tool to start things would be a nice way to get other opinions on the matter. The code for this section can be found [here](https://cgit.kde.org/plasma-desktop.git/tree/kcms/colors), but it uses `.ui` files for the layout, so translating this in pure cpp might take some time.

**Comment by jgehrig** [comment]
The idea is good. Tracking with Pull #719.

Marking as closed.
