### ISSUE TITLE
is this a bug here? shouldn't we reset the end_row?

### ISSUE THREAD

**Issue by etorth** [equalsraf/neovim-qt#499]
https://github.com/equalsraf/neovim-qt/blob/130baeea8f945cb4b99b81025e5974378aaa1453/src/gui/shellwidget/shellwidget.cpp#L117

**Comment by equalsraf** [comment]
uuuuuuups .... it looks like a bug. Is it possible that we never bumped into this because screens are generally wider than taller?

**Comment by equalsraf** [comment]
Ok the resizing of the widget always resizes the contents https://github.com/equalsraf/neovim-qt/blob/130baeea8f945cb4b99b81025e5974378aaa1453/src/gui/shellwidget/shellwidget.cpp#L227

Which is why this is not noticeable.

Still, good catch, @etorth, starting a PR.
