### ISSUE TITLE
Build instructions for noobs?

### ISSUE THREAD

**Issue by osa1** [equalsraf/neovim-qt#5]
So I'm new at this CMake based build system and I'm failing to build the project.

It says something like not having `Qt5NetworkConfig.cmake`, I'm installing one from the internets and putting it under `$CMAKE_MODULE_PATH` but then it's saying

```
CMake Error at /home/omer/CMAKE_PREFIX_PATH/Qt5NetworkConfig.cmake:15 (message):
  The imported target "Qt5::Network" references the file

     "//include/"

  but this file does not exist.  Possible reasons include:
...
```

etc.

Any ideas?

**Comment by equalsraf** [comment]
That file should definitely be part of Qt5. What version of Qt are you using and where did you get it?

**Comment by equalsraf** [comment]
Maybe missing a qt-devel package or something similar?

**Comment by osa1** [comment]
Oh wow amazing. Now it's failing at this step:

```
Scanning dependencies of target neovim-qt
[ 10%] Building CXX object src/CMakeFiles/neovim-qt.dir/util.cpp.o
/home/omer/opt/neovim-qt/src/util.cpp: In function ‘bool NeovimQt::decodeMsgpack(const msgpack_object&, QVariant&)’:
/home/omer/opt/neovim-qt/src/util.cpp:191:7: error: ‘MSGPACK_OBJECT_DOUBLE’ was not declared in this scope
  case MSGPACK_OBJECT_DOUBLE:
       ^
compilation terminated due to -Wfatal-errors.
src/CMakeFiles/neovim-qt.dir/build.make:54: recipe for target 'src/CMakeFiles/neovim-qt.dir/util.cpp.o' failed
make[2]: *** [src/CMakeFiles/neovim-qt.dir/util.cpp.o] Error 1
CMakeFiles/Makefile2:107: recipe for target 'src/CMakeFiles/neovim-qt.dir/all' failed
make[1]: *** [src/CMakeFiles/neovim-qt.dir/all] Error 2
Makefile:86: recipe for target 'all' failed
make: *** [all] Error 2
```

I guess I'm using wrong version of msgpack? I just compiled it from master branch: https://github.com/msgpack/msgpack-c

**Comment by equalsraf** [comment]
Yeah probably something like that. I'm using the same version as Neovim

    https://github.com/msgpack/msgpack-c/commit/ecf4b09acd29746829b6a02939db91dfdec635b4

It seems MSGPACK_OBJECT_DOUBLE as renamed as MSGPACK_OBJECT_FLOAT in a more recent change.

**Comment by equalsraf** [comment]
(Maybe) this works without changing anything

    cmake -DCMAKE_CXX_FLAGS=-DMSGPACK_USE_LEGACY_NAME_AS_FLOAT=1 ..

**Comment by osa1** [comment]
Cool, more progress. Now I'm stuck at:

```
[ 63%] Building CXX object test/CMakeFiles/tst_connector.dir/tst_connector.cpp.o
/home/omer/opt/neovim-qt/test/tst_connector.cpp: In member function ‘void TestConnector::invalidSocket()’:
/home/omer/opt/neovim-qt/test/tst_connector.cpp:31:29: error: unused variable ‘c’ [-Werror=unused-variable]
  NeovimQt::NeovimConnector *c = new NeovimQt::NeovimConnector(&s);
                             ^
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors
test/CMakeFiles/tst_connector.dir/build.make:54: recipe for target 'test/CMakeFiles/tst_connector.dir/tst_connector.cpp.o' failed
make[2]: *** [test/CMakeFiles/tst_connector.dir/tst_connector.cpp.o] Error 1
CMakeFiles/Makefile2:281: recipe for target 'test/CMakeFiles/tst_connector.dir/all' failed
make[1]: *** [test/CMakeFiles/tst_connector.dir/all] Error 2
Makefile:86: recipe for target 'all' failed
make: *** [all] Error 2
```

I guess I need to disable -Werror?

**Comment by equalsraf** [comment]
Which branch are you building? I think I fixed that in tb-remote-ui.

**Comment by equalsraf** [comment]
If it makes things easier you can find me on IRC freenode, nick is the same. In #neovim or ##vim_qt

**Comment by equalsraf** [comment]
The Werror issue should be fixed in the tb-remote-ui branch now. Werror is still there, but I fixed the unit tests.

**Comment by equalsraf** [comment]
Neovim has updated to the latest version of msgpack, I'm updating to use the new version as well. The MSGPACK_OBJECT_FLOAT errors should now be gone, but we need to build against a recent msgpack version.
