### ISSUE TITLE
Windows 10 starting window position

### ISSUE THREAD

**Issue by stu-b-doo** [equalsraf/neovim-qt#501]
How can we set the default window position on screen when opening Neovim-qt? Whenever it opens it always opens in the same undesired position and I end up moving it with the mouse. I know you can set window size using the -geometry flag when starting neovim-qt. Is there something similar we can do for initial position?

I always want the window to open centered on my screen. Remembering the last window position would also work. I don't want it to start full screen. 

Using Windows 10.

**Comment by equalsraf** [comment]
Cheers,

Does `-qwindowgeometry 100x100+50+50` work for you?

**Comment by stu-b-doo** [comment]
Indeed it does, thanks! Is that documented anywhere? Might be worth including with the `nvim-qt.exe --help` text

**Comment by stu-b-doo** [comment]
-qwindowgeometry has the annoying side effect of undocking the task bar icon from the pinned icon, which means you can't use the win+number shortcuts to switch between your favourite applications
