### ISSUE TITLE
Api6

### ISSUE THREAD

**Issue by sassanh** [equalsraf/neovim-qt#504]
Thanks for this great library.
Could you please add api6 too? I need the `nvim_ui_try_resize_grid` method of version 6 api. I added it for myself and can create a PR for it but it'd be great if it's on master branch of this repo too so that the build instructions of my [plugin](https://github.com/sassanh/qnvim) doesn't get even harder.

**Comment by equalsraf** [comment]
Hi @sassanh. Can you get a PR going? I'll happyly press the merge button.

**Comment by sassanh** [comment]
@equalsraf sure, I just created it.
