### ISSUE TITLE
Window size is abnormal when I open two files in vertical split

### ISSUE THREAD

**Issue by jdhao** [equalsraf/neovim-qt#508]
I have noticed that sometimes nvim-qt will start up with a very small window, similar to #251 . So I add the following setting in `ginit.vim`:

```
call GuiWindowMaximized(1)
```

It works well when I open just one files. But when I open two files side by side:

```
nvim-qt -- -O file1.txt file2.txt
```

nvim-qt will start up with a small window, then resize to maximized window, which will result in uneven window size between the two files. The end result is something like the following image:

![image](https://user-images.githubusercontent.com/16662357/51374401-dca0ee00-1b3d-11e9-88ef-9ff4aba03f8f.png)

**Comment by jgehrig** [comment]
This issue should be resolved by Pull Request #898.

Marking as closed.
