### ISSUE TITLE
Incorrect footer size in full screen mode on Windows 10.

### ISSUE THREAD

**Issue by sprainbrains** [equalsraf/neovim-qt#511]
When i expand the window to full screen so then  part of the footer has disapeared(

![image](https://user-images.githubusercontent.com/10284309/52203653-dd968700-2882-11e9-9cca-da68337c7ec7.png)

**Comment by jjohnson338** [comment]
I found that hiding the tab-bar (in ginit.vim) got the UI to line up correctly:
`GuiTabline 0`

**Comment by sprainbrains** [comment]
> I found that hiding the tab-bar (in ginit.vim) got the UI to line up correctly:
> `GuiTabline 0`

Yep, I knew about it. But i want to solve this trouble with a gui tab)

**Comment by justinmk** [comment]
closed by https://github.com/equalsraf/neovim-qt/pull/516
