### ISSUE TITLE
Cursor shape change does not work when statusline option is set

### ISSUE THREAD

**Issue by Shougo** [equalsraf/neovim-qt#513]
I have tested below minimal vimrc.

```vim
set noshowcmd
set noshowmode
set statusline=foo
```

If you test the vimrc, cursor shape does not change in insert mode.

**Comment by equalsraf** [comment]
Confirmed here, it seems like we are failing to repaint the cursor.

For example changing the focus of the window does cause the cursor to be repainted.

#514 should fix this

**Comment by equalsraf** [comment]
Merged, thanks @Shougo
