### ISSUE TITLE
command line is hided by windows 10 task bar

### ISSUE THREAD

**Issue by ShuguangSun** [equalsraf/neovim-qt#515]
- `nvim --version`: 0.3.4 and 0.4.0
- Operating system/version: Windows 10

### Steps to reproduce 

run nvim-qt.exe and then maximize the window
or nvim-qt --maximized
or put `call GuiWindowMaximized(1)` in ginit.vim

### Actual behaviour
The nvim-qt is really maximized but it fit the whole screen (some kind like of fullscreen). And the windows taskbar (with start menu and those shortcut icons) hide the status/command line. I need to `set cmdheight=2` to make the area above windows task bar.

The fontsize and dpi has some impact.

### Expected behaviour
I expect the bottom of nvim-qt windows fit windows taskbar.

**Comment by sprainbrains** [comment]
I guess, it's the same my [problem](https://github.com/equalsraf/neovim-qt/issues/511)

**Comment by sprainbrains** [comment]
I know how to fix it. I will pull request later.

**Comment by justinmk** [comment]
https://github.com/equalsraf/neovim-qt/pull/516
