### ISSUE TITLE
No visible indicator when window unfocused.

### ISSUE THREAD

**Issue by rsheasby** [equalsraf/neovim-qt#519]
Hi team.

As it is now, there's no way to tell when Neovim-QT is focused or unfocused without looking at the tiny title text to see if it's grey or bold. With terminal Vim/Neovim the cursor block turns hollow and the powerline changes color. Hence if you're looking at another screen and look back at Neovim to start typing, you can instantly see that your input won't be received. As it is now, I find myself starting to type only to be frustrated that my browser is still focused.

**Comment by sprainbrains** [comment]
> Hi team.
> 
> As it is now, there's no way to tell when Neovim-QT is focused or unfocused without looking at the tiny title text to see if it's grey or bold. With terminal Vim/Neovim the cursor block turns hollow and the powerline changes color. Hence if you're looking at another screen and look back at Neovim to start typing, you can instantly see that your input won't be received. As it is now, I find myself starting to type only to be frustrated that my browser is still focused.

Can you add some gifs to show this issue?

**Comment by rsheasby** [comment]
Don't have a screen recorder on my work machine but will add when I get home. It's a pretty simple issue really. If the window(the actual system window) is unfocused(you click on another window) then there's no visual indicator of the fact that Neovim isn't responding to input. With nvim in the terminal, the cursor block goes hollow or disappears or changes color(depending on terminal) to show that it's not receiving input.

**Comment by sprainbrains** [comment]
> Don't have a screen recorder on my work machine but will add when I get home. It's a pretty simple issue really. If the window(the actual system window) is unfocused(you click on another window) then there's no visual indicator of the fact that Neovim isn't responding to input. With nvim in the terminal, the cursor block goes hollow or disappears or changes color(depending on terminal) to show that it's not receiving input.

Please, show it. I didn't repeat it on my system.

**Comment by equalsraf** [comment]
Weird I could swear this was working. Strangely enough I get consistent behaviour between the terminal and nvim-qt.

One way to test this is to simply set autocommands for FocusGained/FocusLost.

There seems to be something going on with the FocusLost autocommand. The UI is supposed to trigger the focus autocommands [here](https://github.com/equalsraf/neovim-qt/blob/bbdead4b1a5093de486d35bf12184796c8e7cf69/src/gui/shell.cpp#L1140). But focus lost gets me a message **No matching autocommands**.

For reference I'm running nvim 0.3.1 in Linux. What are you guys running.

**Comment by equalsraf** [comment]
Ah the terminal behaviour depends on the terminal you are using, gnome-terminal does show a block cursor.

**Comment by equalsraf** [comment]
Well my memories of support for this feature are all messed up - maybe i'm confusing this with vim-qt. Anyway lets add support for this and be done with it.

Pushed a PR for this https://github.com/equalsraf/neovim-qt/pull/521

**Comment by sprainbrains** [comment]
> **Edit** because I was not making sense.
> 
> Weird I could swear this was working. Strangely enough I get consistent behaviour between the terminal and nvim-qt - the cursor does not change.
> 
> The UI is supposed to trigger the focus autocommands [here](https://github.com/equalsraf/neovim-qt/blob/bbdead4b1a5093de486d35bf12184796c8e7cf69/src/gui/shell.cpp#L1140)
> 
> ```viml
> :autocmd FocusGained * echom 'gain NARF'
> :autocmd FocusLost * echom 'lost NARF'
> ```
> 
> Going back and forth shows the message but nothing else happens.
> 
> For reference I'm running nvim 0.3.1 in Linux. What are you guys running.

Can you show me what happening? Because i dont undestand.. Where to look?

**Comment by equalsraf** [comment]
Merged fix into master. Let me know if i missed something.
