### ISSUE TITLE
Accent keys with space work differently than expected

### ISSUE THREAD

**Issue by TheSilvus** [equalsraf/neovim-qt#522]
Pressing the `^` (or any other accent) key and then `Space` causes a space to appear. 

Normal behavior (on Windows at least) is the accent character appearing on its own without a space behind it. Following the accent key with an "accentable" letter (e.g. a) works as expected, as does entering a non-accentable character (e.g. `.`) which causes the second character to appear after the accent (`^.`).

I'm currently only able to test this for Windows.

I'm using the version bundled with NVim 0.3.4 ( https://github.com/neovim/neovim/releases/tag/v0.3.4 ).

**Comment by jgehrig** [comment]
This looks related to Issue #720. We should add some unit tests, and validate this scenario in Pull #721.

**Comment by jgehrig** [comment]
@TheSilvus This issue may be fixed by #713 

If you have the ability to test the proposed fix, it would be greatly appreciated.

I am familiar with keyboard layouts for accented characters...
