### ISSUE TITLE
Maximizing on Windows with tabline on causes clipping 

### ISSUE THREAD

**Issue by TheSilvus** [equalsraf/neovim-qt#523]
Maximizing the Neovim window on Windows with the tabline enabled causes the last line (commands, ...) to clip.

Maximized:

![image](https://user-images.githubusercontent.com/18658672/53685843-54a72a00-3d20-11e9-963a-57fd894b7de9.png)

Non-Maximized:

![image](https://user-images.githubusercontent.com/18658672/53685841-4c4eef00-3d20-11e9-8186-18ec3c263646.png)

Note that this only happens when maximized, i.e. not when the window covers half the screen. A workaround is therefore to force the window on one side (e.g. using Windows-Left) and then stretching it to fill almost the full screen.

Another workaround is to disable the GUI tabline.

I'm using the Nvim-QT version bundled with the latest Nvim version, i.e. 0.3.4 and Windows 10.

**Comment by equalsraf** [comment]
A fix for this was merged in https://github.com/equalsraf/neovim-qt/pull/516 but it is not available in that version.

**Comment by TheSilvus** [comment]
Perfect; thanks!

**Comment by equalsraf** [comment]
If you need to grab a build, there should be one marked as staging in the releases page.

**Comment by youngmit** [comment]
I am on nvim 0.3.8, and still seeing this issue. Has the fix made it into a release yet?

**Comment by equalsraf** [comment]
Yes it did, reopening then.

@youngmit can you provide some more details. OS, nvim and nvim-qt versions?

**Comment by youngmit** [comment]
Apologies! I'm on Windows 10, running version 0.3.8, from the neovim releases page. Not sure how to get the nvim-qt version, but it's the one that came packaged with neovim. Disabling the external tabline seems to clear things up for now.

**Comment by justinmk** [comment]
> from the neovim releases page. Not sure how to get the nvim-qt version, but it's the one that came packaged with neovim

For neovim builds, we are waiting for the next release of nvim-qt, very much hoping that https://github.com/equalsraf/neovim-qt/pull/557 will be included.

**Comment by equalsraf** [comment]
> For neovim builds, we are waiting for the next release of nvim-qt, very much hoping that #557 will be included.

Well let me press the merge button then.

I'm waiting on a couple of fixes, but if neovim is releasing shortly i'm ok with tagging a release.

**Comment by justinmk** [comment]
@equalsraf we are aiming to release Neovim 0.4 in the next 2-3 weeks.

**Comment by ellbur** [comment]
FWIW, I am on Linux using neovim 0.4.3 and neovim-qt 0.2.15 and this issue is fixed for me.

**Comment by jgehrig** [comment]
Marking as closed.

As per comment above, this issue is fixed as of `v0.2.15`.
