### ISSUE TITLE
GUI popup menu location is not honored 

### ISSUE THREAD

**Issue by anasem** [equalsraf/neovim-qt#524]
When using ncm2 autocomplete plugin. The GUI popup menu is misplaced when neovim-qt is not in full screen (using i3 wm). When disabling GUI pop up menu, everything works perfectly. 

Neovim-qt version: 0.2.21-1

![GUI](https://user-images.githubusercontent.com/26265640/54250715-2bb73e00-4545-11e9-9983-6878822478b4.png)

Expected behavior:
![No_GUI](https://user-images.githubusercontent.com/26265640/54250719-2eb22e80-4545-11e9-9e9f-704bb87f351d.png)

**Comment by jgehrig** [comment]
I agree, the current behavior is confusing. We should try to more closely mimic the Terminal UI behavior.

Let me know if you can build, test, or have feedback! :smile:

**Comment by jgehrig** [comment]
FYI, the current behavior looks intentional.

Here is the logic causing the behavior you see:
https://github.com/equalsraf/neovim-qt/blob/663f2b778b730f48b6ed1c29d0faf8db4c668c95/src/gui/shell.cpp#L566-L600

You can see the half-shell re-size, and conditional movement of the anchor position.

**Comment by jgehrig** [comment]
The `:GuiPopupmenu` location improvements are available as of `v0.2.13`

Marking as closed.
