### ISSUE TITLE
Font scaling is different when used under a GTK DE

### ISSUE THREAD

**Issue by YorickPeterse** [equalsraf/neovim-qt#525]
I've been trying various NeoVim GUIs in an attempt to find one with low input latency. So far I've determined what both neovim-qt and neovim-gtk have pretty good latencies (15-20 ms versus 35 ms for GNOME terminal). Unfortunately, it appears that neovim-qt renders fonts wider than they should be when using an HiDPI display (4K in this case). Consider this screenshot:

![Screenshot from 2019-03-21 14-47-49](https://user-images.githubusercontent.com/86065/54756793-39299380-4be9-11e9-99ec-b0e9ab0a1c24.png)

This shows three windows with the following setups:

1. Just `nvim-qt` with `GuiFont Source Code Pro:h8:l`. Without the `:l` option the font is _really_ bold
2. `QT_SCALE_FACTOR=1 nvim-qt` with `GuiFont Source Code Pro:h8`. If I use the `:l` option the fonts are way too light
3. `nvim` running in GNOME terminal. This is displaying fonts as they should be, and neovim-gtk displays them in the same way

I've been toying around with other variables such as `QT_FONT_DPI` and `QT_AUTO_SCREEN_SCALE_FACTOR`, but I have thus far not been able to get the fonts displayed the same way as GTK. 

Is this something neovim-qt could handle, or is this perhaps a system issue?

**Comment by YorickPeterse** [comment]
Based on https://github.com/equalsraf/neovim-qt/issues/221 I think I might be running into the same problem: neovim-qt not supporting the right size to my match my terminal

**Comment by equalsraf** [comment]
I dont think this is related to #221, that issue only prevents the user from specifying a fractional size, which is not the case here.

For the case where QT_SCALE_FACTOR=1 this may be related to the font options (set [here](https://github.com/equalsraf/neovim-qt/blob/master/src/gui/shellwidget/shellwidget.cpp#L43)), namely ForceIntegerMetrics and perhaps fixed pitch.

In windows we are using QT_AUTO_SCREEN_SCALE_FACTOR=1 to address hidpi, but we had some issues in linux [earlier](https://github.com/equalsraf/neovim-qt/blob/master/src/gui/main.cpp#L28).

Cheers

**Comment by YorickPeterse** [comment]
@equalsraf Even with that variable set the fonts are considerably bigger. I played around a bit with changing the code to use fractional point sizes. I managed to get pretty close with a point size of 7.5 (if I remember correctly), but the line heights were still different (= GNOME terminal's lines are a bit taller).

**Comment by equalsraf** [comment]
Line heights are a different matter, ours uses [QFontMetrics::lineSpacing](https://doc.qt.io/qt-5/qfontmetrics.html#lineSpacing) which is the distance between baselines. I'm not sure what gtk uses but I do remember it being different even in other apps. Maybe GTK uses ascent+descent as its line height (wild gues based on a browse of [this](https://github.com/daa84/neovim-gtk/blob/f9a978bd092052da214743bc75b1990b2b09c851/src/render/context.rs#L119)).

**Comment by YorickPeterse** [comment]
@equalsraf Ah, interesting! Would there be a way for neovim-qt to handle it similarly or make configurable? On `master` it feels a bit like lines are squished together too much. We can see this in the following screenshot:

![comparison](https://user-images.githubusercontent.com/86065/54784335-e7522f00-4c23-11e9-9e64-cc7b0b0ff585.png)

The windows displayed from left to right are:

1. nvim in GNOME terminal with a font size of 8 (not sure if GNOME terminal uses pixels or points)
2. neovim-qt using `GuiFont Source Code Pro:h8`
3. neovim-qt using `GuiFont Source Code Pro:h8` and a change to `shellwidget.cpp` to use `f.setPointSizeF(8.5);` for hardcoding the font size

If you look carefully at the image, you'll note two things:

1. The line height of neovim-qt is a bit smaller than GNOME terminal
2. The letters in neovim-qt are a bit wider and appear to be _just_ a little bit bolder (probably causing the increase in width)

Window 3 is just there to illiustrate what happens when we use fractional point sizes

**Comment by equalsraf** [comment]
For the linespace you can use `:set linespace=3` - negative values will cause the line height to be smaller (even if it crops the font).

**Comment by YorickPeterse** [comment]
@equalsraf I played around a bit with that, but I think the spacing I would need is too small. Using `linespace=1` the lines are too tall, and with `linespace=0` they are a tiny bit too narrow.

I took a closer look at the actual width of the characters as well. To do this, I took the text `typesetting, ` from the lorem ipsum example, and took a screenshot of it in both GNOME terminal and nvim-qt. I then drew markers around the GNOME version, and tried to overlay those on the nvim-qt version:

![comparison](https://user-images.githubusercontent.com/86065/54789760-e2957700-4c33-11e9-8c55-dd2666f3b6ea.png)

Left is GNOME terminal, right is nvim-qt. Here we can quite clearly see what the width of characters/words in nvim-qt is quite a bit bigger. This can add up quite easily, resulting in lines being quite a bit wider. One thing I also see is that in nvim-qt the letters appear to be bolder/smoother. Maybe this adds to some of the width. This then brings the question: who is right, GNOME or nvim-qt?

**Comment by YorickPeterse** [comment]
The difference between GNOME terminal and nvim-qt is quite noticeable when comparing them side by side:

![Screenshot from 2019-03-21 23-52-02](https://user-images.githubusercontent.com/86065/54789886-618aaf80-4c34-11e9-883a-459eb8ed669e.png)

Left is GNOME terminal, right is nvim-qt. Both windows are of equal size. On line 30 we can most clearly see the difference, with quite a bit of code not fitting in the window.

**Comment by equalsraf** [comment]
> Left is GNOME terminal, right is nvim-qt. Here we can quite clearly see what the width of characters/words in nvim-qt is quite a bit bigger. This can add up quite easily, resulting in lines being quite a bit wider.

nvim-qt is pretty pedantic when it comes to font width, it

- assumes the font is monospaced and all characters have the same width
- no overlap across letters (and no kerning)
 
The cell width is calculated [here](https://github.com/equalsraf/neovim-qt/blob/6ffdd6d76936d77fc2a796bad89ab7ce83ce08fe/src/gui/shellwidget/shellwidget.cpp#L94)

Maybe the width used by gtk is different, but I have no better estimate for it.

> One thing I also see is that in nvim-qt the letters appear to be bolder/smoother. Maybe this adds to some of the width.

Here my guess would be no, unless there is something weird with the font, nvim-qt usually checks if all font variants have the same width (bold, italic, regular). Perhaps a consequence of the type of hinting being used?

> This then brings the question: who is right, GNOME or nvim-qt?

Not sure there is a right answer - our outcome is a consequence of being very strict about font metrics and drawing chars one by one.

There is one open PR https://github.com/equalsraf/neovim-qt/pull/470 that draws by line, maybe that helps with the thicker fonts.

**Comment by YorickPeterse** [comment]
> Here my guess would be no, unless there is something weird with the font, nvim-qt usually checks if all font variants have the same width (bold, italic, regular). Perhaps a consequence of the type of hinting being used?

I played around with disabling hinting as follows:

```c++
// in ShellWidget::setShellFont()
f.setHintingPreference(QFont::PreferNoHinting);
```

This (or any other `QFont::HintingPreference` value) does not appear to make any difference, assuming I'm applying the setting correctly.

I'll take a look at the cell width calculation next.

**Comment by YorickPeterse** [comment]
I managed to get the width of characters to be the same as GNOME by using the following:

```c++
f.setStretch(95);
```

A value lower than 95 results in the text being too condensed, whereas a higher value results in the text being stretched too much. I suspect this value probably is not portable between configurations.

For the line spacing I tried to use the same approach as neovim-gtk: `ascent() + descent()`. This makes sense since `QFontMetrics::height()` already does this. Toying around with `set linespace`, it seems the height is off by roughly 0.5.

**Comment by YorickPeterse** [comment]
An alternative to the stretching hack is to do this:

```c++
m_cellSize = QSize(fm.width('W') - 1,                       
        qMax(fm.lineSpacing(), fm.height()) + m_lineSpace); 
```

Similar to the stretch hack, this isn't really a final solution. I tried using different characters to calculate the width, but it didn't make a difference.

**Comment by YorickPeterse** [comment]
Using the following hack we can get the line heights to be very close to GNOME terminal:

```c++
m_cellSize = QSize(fm.width('W') - 1,                            
        (qMax(fm.lineSpacing(), fm.height()) + m_lineSpace) + 1);
```

This produces the following:

![Screenshot from 2019-03-22 02-55-33](https://user-images.githubusercontent.com/86065/54795861-0e255b00-4c4e-11e9-9d30-72f8029e7791.png)

The left window is GNOME terminal, the right one (on top of the first one) is nvim-qt with the above hack. Note that we're close, but not exactly the same as the difference appears to be maybe one pixel.

**Comment by YorickPeterse** [comment]
I tested NeoVim in Konsole, and I get very similar (if not identical) rendering compared to nvim-qt. This suggests it might just be that Qt renders fonts in a slightly different way, instead of it being an nvim-qt issue. With this in mind, I'll close this issue.

**Comment by YorickPeterse** [comment]
@equalsraf So after toying around a bit more, I can get nvim-qt to be almost identical by doing the following:

1. Hardcode the font size to 7.5 points (8 is too big apparently)
2. Use `GuiFont Source Code Pro:h8:l`. The size is ignored obviously, but it seems that without using the light option nvim-qt picks the demibold font (or at least something that's way too bold)
3. Use `set linespace=1`

This brings me to the following two questions:

1. I'm not sure if I'd be able to (my C++ knowledge is limited), but would neovim-qt be OK to a patch that adds support for fractional font sizes (e.g. `h7.5`)?
2. Does the font bold issue ring any bells? It seems the only reliable "hack" is to force a light font, which in neovim-qt looks like the regular font.
