### ISSUE TITLE
command mode mapping behaves oddly

### ISSUE THREAD

**Issue by jdhao** [equalsraf/neovim-qt#531]
I am using neovim-qt (neovim version 0.3.4) on Windows 10 (version 1803). It seems that the command mode mapping is a little strange. Here is how to reproduce:

+ Create the following minimal `init.vim`
```
imap <silent> <S-Insert> <C-R>*
cmap <silent> <S-Insert> <C-R>*

set clipboard+=unnamedplus
```

+ open a file `test.txt` with neovim-qt using the above setting:

```
nvim-qt -- -u init.vim test.txt
```

+ Copy a line with `yy`

+ Press `:` to go to command mode and press `<S-Insert>`. Nothing shows on the command line. But if you press a character key, the pasted string will appear before the pressed key.

**Comment by jgehrig** [comment]
@jdhao This looks like an upstream neovim issue. Would you like to file an issue with neovim?

`<S-Insert>` may not reproduce for all terminal emulatores, switching to `<C-Space>` demonstrates the issue with terminal `nvim`.

**minimal.vim:**
imap <silent> <C-Space> <C-R>*
cmap <silent> <C-Space> <C-R>*

set clipboard+=unnamedplus

**Repro Steps:**
1. Command `nvim --version`  reports NVIM v0.5.0-1564-g8b0287805
2. Run `nvim -u minimal.vim`
3. Go to command mode `:` and press Ctrl + Space.
4. Notice, no text appears on-screen.
5. Press space, notice the pasted text appears suddently. Bug.

**Comment by jdhao** [comment]
ok, I will file an issue there.

**Comment by jdhao** [comment]
@jgehrig it seems to be an issue with the argument `<silent>`, if I remove it, this issue disappears.
