### ISSUE TITLE
arbitrary font weights

### ISSUE THREAD

**Issue by nilsbecker** [equalsraf/neovim-qt#532]
#136 added support for the "light" font weight. however, at least on os x there are multiple other font weights, including 'book', 'semibold', etc. in particular there is also the weight 'retina' which designates a font specifically optimized for rendering on a high-res display. it would be great to have some workaround to use all of these. for instance, being able to give the postscript name directly, e.g. `FiraCode-Retina:h12` etc.

**Comment by jgehrig** [comment]
Support for arbitrary font weight was added in `v0.2.16`.

For example Hack; 11pt; 90% weight:
`:GuiFont Hack:h11:w90`

See `:help GuiFont` for more details.
```
The following attributes are available

	hXX - height is XX in points (can be floating-point)
	wXX - weight is XX
	b   - bold weight
	sb  - semibold weight
	l   - light weight
	i   - italic
```

Marking as closed.
