### ISSUE TITLE
256 color terminal in Windows 10?

### ISSUE THREAD

**Issue by moshen** [equalsraf/neovim-qt#537]
When using `:terminal` within the nvim-qt session on Windows 10, 256 color support doesn't seem to work.

When running `nvim-qt - -u NONE`:

![image](https://user-images.githubusercontent.com/168513/56626096-471a6c00-660e-11e9-9572-c316bdf9a3a2.png)

`cat`ing https://github.com/Maximus5/ConEmu/blob/master/Release/ConEmu/Addons/AnsiColors256.ans

Here's what it looks like in fluent terminal:

![image](https://user-images.githubusercontent.com/168513/56626157-8ba60780-660e-11e9-9d99-015fe45f3247.png)

**Comment by moshen** [comment]
This might be an `nvim` thing since I can replicate it in a powershell

**Comment by moshen** [comment]
Created https://github.com/neovim/neovim/issues/9937 to track upstream

**Comment by Kraust** [comment]
Looks like this could be potentially neovim on windows specific. Tried to replicate it with Windows 10 (Client) and Linux (Server) but I got the desired output:
![image](https://user-images.githubusercontent.com/6548135/57181845-de7d8b80-6e66-11e9-9d7d-b69421f56111.png)

**Comment by moshen** [comment]
@Kraust it was confirmed in the ticket on neovim above.  Apparently the windows neovim version does not use conpty at all, only winpty (which only supports 16 colors).

How do you manage it in client/server mode?  I only seem to be able to with another shell open.

**Comment by equalsraf** [comment]
Closing as this can be handled upstream.
