### ISSUE TITLE
Multiple :echom commands in init.vim results in white screen

### ISSUE THREAD

**Issue by NuclearDog** [equalsraf/neovim-qt#538]
Using neovim-qt from the Ubuntu repos (0.2.9-1).

If I create a `init.vim` which contains:

```
:echom 'test'
```

neovim-qt starts and `:messages` shows the message as expected.

If I create a `init.vim` which contains:

```
:echom 'test'
:echom 'test'
```

Starting neovim-qt results only in a white screen. None of the usual suspects (Ctrl+C, for instance) do anything. Eventually I get the message "Neovim is taking too long to respond. [Retry]".

neovim continues to start correctly from the terminal, just outputting my messages on start.

Stumbled across this trying to debug some issues with my init.vim. Let me know if there's any additional information I could provide.

Thanks!

Adam

**Comment by justinmk** [comment]
What version of `nvim` (not nvim-qt) ? https://github.com/neovim/neovim/pull/8754 already fixed the core problem.

@equalsraf there are zillions of open duplicate issues in the neovim-qt project about this.

**Comment by NuclearDog** [comment]
Hi Justin,

Thanks -- I did search the neovim issues but without knowing the background my keywords didn't get me very far. I'm on 0.3.1 which looks like it was released before that PR was merged.

I just tried updating to the 0.4.0-dev package in the Ubuntu PPA and seem to be having the same issue. Should the fix have been included in that release?

Thank you!

**Comment by justinmk** [comment]
@NuclearDog it is unclear from your last comment what version of neovim-qt you are using. I think 0.2.9 is too old.

**Comment by NuclearDog** [comment]
Yeah sorry, 0.2.9. Built nvim-qt from the latest "staging" release and this issue is resolved.

Sorry to waste your time reporting issues with old software. Thanks for taking the time out to work through it!
