### ISSUE TITLE
cursor disappears when opening :version :messages

### ISSUE THREAD

**Issue by prabirshrestha** [equalsraf/neovim-qt#54]
![image](https://cloud.githubusercontent.com/assets/287744/10377616/40722f88-6db9-11e5-987f-83aa859a6929.png)

gvim shows cursor similar to this. 
![image](https://cloud.githubusercontent.com/assets/287744/10377692/aa706f08-6db9-11e5-9685-eac3e5ddd513.png)

**Comment by equalsraf** [comment]
@prabirshrestha seems simple to fix, create a pull request.
