### ISSUE TITLE
switching to full-sreen mode with tabline enabled hides the command line

### ISSUE THREAD

**Issue by Glavnokoman** [equalsraf/neovim-qt#542]
neovim-qt 0.2.12
neovim 0.3.5
arch linux x64, kde.
With tabline enabled (btw I can not disable it somehow, so not sure it that is important) switching to full-screen mode using the kde windows controls hides the bottom of the screen which happens to contain the command line below the screen edge.

**Comment by equalsraf** [comment]
Can you share a screenshot of this. Is KDE doing something strange about the geometry of the window?


> With tabline enabled (btw I can not disable it somehow

mmm, not even if you start with `nvim-qt --no-ext-tabline`? Alternatively you should be able to call `:GuiTabline 0` to disable it at runtime.

Do we need to open a new issue for this?

**Comment by Glavnokoman** [comment]
Sorry, I do not have nvim-qt installed any longer so I can not try your suggestions. I guess I'd rather close this one.
