### ISSUE TITLE
How can I set an alternative font？

### ISSUE THREAD

**Issue by mzr1996** [equalsraf/neovim-qt#544]
- `nvim --version`:
```
NVIM v0.4.0-819-g66d127957
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG -DMIN_LOG_LEVEL=3 /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv +tui
```
- Operating system/version:
Windows Home Basic 1903

I want to set Latin characters' font and Chinese characters' font separately. And in qvim，I can do it by the option `guifontwide`, while that option does not work in nvim-qt. I have also tried Guifont,  but it can't seem to set more than one font. 

I'm wondering if I can set an alternative fonts, just like URxvt's configuration:
```
URxvt.font:xft:Hack Nerd Font Mono:pixelsize=23, xft:Sarasa Mono SC:pixelsize=26
```
It will apply the first font primarily, and apply the second font when the character can't be found in the first font.

Or just like Gvim's configuration:
```
set guifont=Hack\ NF:h14
set guifontwide=等宽更纱黑体\ SC:h16
```
It will apply `guifontwide` to the double-width characters.

**Comment by jgehrig** [comment]
This feature is available in `master` now. It should be included in the `v0.2.17` release.

Marking as closed.
