### ISSUE TITLE
.zshrc is not sourced if I launch neovim-qt.app direclty on MacOS

### ISSUE THREAD

**Issue by AllenDang** [equalsraf/neovim-qt#553]
I'm using zsh on MacOS 10.14.5, I defined lots of environment variables in .zshrc like $GOPATH, $PATH etc...

I found none of them are accessible from neovim-qt if I launch it direclty.

I tried to echo $GOPATH, it returns empty. Echo #SHELL returns /bin/zsh.

If i launch neovim-qt from terminal via nvim, all of the environment variables are good.

How can I solve this problem? 

This makes I cannot launch language servers correctly.

**Comment by shlomif** [comment]
@AllenDang : hi! Did you use `export GOPATH` /etc? See https://stackoverflow.com/questions/7411455/what-does-export-do-in-shell-programming .

**Comment by AllenDang** [comment]
@shlomif Yes, I'm sure I export all the variables in .zshrc.

Here is a small piece of my .zshrc file.
```
# Add flutter to path
export PATH=/Users/allendang/SDK/flutter/bin:$PATH
export NVM_DIR="/Users/allendang/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
export PATH=/usr/local/sbin:$PATH
export PATH=/Library/Frameworks/Python.framework/Versions/3.7/bin:$PATH
export PATH=$HOME/.pub-cache/bin:$PATH
export TERM=xterm-256color
```

**Comment by shlomif** [comment]
@AllenDang : Perhaps the system nvim-qt does not process `.zshrc` and you need to either wrap it inside a zsh script or define these env vars in a system wide location. It is unlikely that nvim-qt nullifies them on its own volition.

**Comment by equalsraf** [comment]
>  Perhaps the system nvim-qt does not process .zshrc

Mac OS X applications do not load the user shell environment variables. What we did to address this was to try and [get the environment](https://github.com/equalsraf/neovim-qt/commit/d5ab18da23e0723bea715cc49bdb01431a5540a4) from $SHELL using 

```
$SHELL -l -c env -i
```

Dont know if this would work for zsh or not.

In debug builds you might get a debug log about this.

So, assuming zsh is your login shell, what happens when you run `zsh -c -c env -i`. Testing here I get a list of environment variables.

**Comment by AllenDang** [comment]
`zsh -c -c env -i` could get all the environment variables.
What should I do next?

**Comment by equalsraf** [comment]
how do you start zsh then?

It sounds like zsh is not you login shell.

What does `:echo $SHELL` show?

**Comment by AllenDang** [comment]
`:echo $SHELL` shows `/bin/zsh`

**Comment by equalsraf** [comment]
Ok I am at a loss then.

Can you try to get some debug logs to see if anything useful pops out?

    $ NVIM_QT_LOG=nvim-qt.log nvim-qt

Thiis should log into nvim-qt.log

**Comment by lgeo3** [comment]
Hi, 
I encoutered similar issue, and found out that zshrc is only sourced in an interactive shell so one solution is to use:

```
zsh -i -c env -i
```
@equalsraf don't know if we should do that in the neovim-qt source code ? Maybee adding a if $SHELL == zsh then use this parameters ?

An other way is just to put the export path in ~/.zshenv file, which is sourced in all situations

for more information see 
https://unix.stackexchange.com/questions/71253/what-should-shouldnt-go-in-zshenv-zshrc-zlogin-zprofile-zlogout


@AllenDang does it solve the issue ?

**Comment by equalsraf** [comment]
I'd rather keep the same behavior across shells to be honest. It seems that either .zshenv or .zshprofile would both since they are loaded by a login shell.

**Comment by jgehrig** [comment]
We have a workaround for this issue above. Marking as closed.

**Comment by dnguyen85** [comment]
@jgehrig: what's the work-around? Do you mind sharing? I recently ran into this exact issue.

**Comment by jgehrig** [comment]
@dnguyen85 

Sorry, I'm not much help here. I don't use zsh and I don't own a Mac...

I closed this because it looks like a zsh config issue, and several workarounds were suggested with no response from the original author.

See:
https://github.com/equalsraf/neovim-qt/issues/553#issuecomment-512231609
https://github.com/equalsraf/neovim-qt/issues/553#issuecomment-712696595
https://github.com/equalsraf/neovim-qt/issues/553#issuecomment-714819874

**Comment by celioreyes** [comment]
Hey @gwerbin super late followup but I'm using Fedora 37 and moved my env variables to be in `~/.zshenv` but still not luck with nvim-qt picking them up. You have any tips to help fix this?

**Comment by gwerbin** [comment]
> Hey @gwerbin super late followup but I'm using Fedora 37 and moved my env variables to be in `~/.zshenv` but still not luck with nvim-qt picking them up. You have any tips to help fix this?

Verify that your shell in Neovim is actually set to Zsh (`:set shell=/usr/bin/zsh` or equivalent), and set a shell parameter like `foo=123` in `~/.zshrc`. Then you should be able to run `!echo "$foo"` in Neovim and see `123` as output.
