### ISSUE TITLE
Is it possible to define a bundle identifier when built on mac?

### ISSUE THREAD

**Issue by svermeulen** [equalsraf/neovim-qt#554]
I'd like to do some special processing for neovim-qt windows on mac.  Unfortunately though the "bundle identifier" is empty so I have to use the application path, which fails easily when changing the nvim-qt install I'm running.  It would be great if a non-empty bundle identifier could be used instead

**Comment by equalsraf** [comment]
I have no problem with this.

This seems to be set in https://github.com/equalsraf/neovim-qt/blob/master/cmake/MacOSXBundleInfo.plist.in#L17 but the variable is not set?

Presumably replacing these

- APPLE_GUI_IDENTIFIER -> CMAKE_PROJECT_NAME
- APPLE_GUI_LONG_VERSION_STRING -> CMAKE_PROJECT_VERSION
- APPLE_GUI_SHORT_VERSION_STRING -> CMAKE_PROJECT_VERSION

would have the intended effect.

Can anyone test?

**Comment by svermeulen** [comment]
Yep that worked . :) . Well, the bundle identifier part at least.  Not sure how to confirm the versiono part.  I'll make a PR

**Comment by svermeulen** [comment]
Oh I actually was able to confirm the version works as well.  PR: https://github.com/equalsraf/neovim-qt/pull/555

**Comment by equalsraf** [comment]
Merged, thanks for this @svermeulen
