### ISSUE TITLE
Followup from reloading clipboard provider & neovim-qt

### ISSUE THREAD

**Issue by Kraust** [equalsraf/neovim-qt#559]
Congrats in getting the PR finally in, I've been using the latest build with the loaded_XXX_provider changes, and managed to get cross-host clipboard working without ssh with the following:

In my init.vim:
```
function ReloadClipboard()
    call GuiClipboard()
    execute 'unlet g:loaded_clipboard_provider'
    execute 'runtime autoload/provider/clipboard.vim'
endfunction()
```
And ginit.vim:
```
call ReloadClipboard()
```
As easy as that. Now every time I open up nvim-qt on my client, I get full clipboard support.

Any plans on getting this integrated with the gui-shim so I don't have to call this in ginit.vim?

**Comment by equalsraf** [comment]
Hi @Kraust thanks for doing the leg work there I missed the final work on that PR.

Concerning you script. `GuiClipboard()` already calls runtime, so this can be simply

```vim
    execute 'unlet g:loaded_clipboard_provider'
    call GuiClipboard()
```

The only difference is really the `unlet g:loaded_clipboard_provider` and any errors can be ignored using `unlet!`.

I've opened https://github.com/equalsraf/neovim-qt/issues/559 lets give it a test and if it works it should be enough to just call GuiClipboard().

**Comment by Kraust** [comment]
Checks out, if I put the following in my ginit.vim I get clipboard support.
```
execute 'unlet g:loaded_clipboard_provider'
call GuiClipboard()
```
You have no idea how much of a quality of life improvement this is for me.

**Comment by equalsraf** [comment]
> You have no idea how much of a quality of life improvement this is for me.

As someone who develops exclusively on remote boxes I think I do :D My $DAYJOB just got a lot better.
