### ISSUE TITLE
neovim with python3 support

### ISSUE THREAD

**Issue by prabirshrestha** [equalsraf/neovim-qt#56]
not sure if this is the right place to ask this since there isn't a place to file a bug for neovim in your repo.

Is it possible to create neovim builds in appveyor with python3 support? https://ci.appveyor.com/project/equalsraf/neovim

**Comment by equalsraf** [comment]
No need, all builds support python2 and 3 as long as the python binary is available and the neovim python module is instaled. However (in windows) some problem in the shell command execution is preventing this from working (shell command escaping) - there is PR in Neovim to gix it

**Comment by prabirshrestha** [comment]
that make sense. I had the neovim python module installed but it still didn't work.

closing since not related to neovim-qt.
