### ISSUE TITLE
Airline rendering issue

### ISSUE THREAD

**Issue by vladimir-didenko** [equalsraf/neovim-qt#561]
I found one rendering issue when airline is used. When you make first change in git repo after ":w" is typed airline has inconsistent state

#
![Screenshot from 2019-08-05 18-54-59](https://user-images.githubusercontent.com/1499142/62478524-f8a36e80-b7b3-11e9-80b6-2ada03c9a69e.png)

As you could see on screenshot there is a garbage symbol "a" between branch name and file name. If you issue "ctrl+l" (or switching back from another buffer) then garbage symbol will be replaced by blackbox

![Screenshot from 2019-08-05 18-55-03](https://user-images.githubusercontent.com/1499142/62478700-5d5ec900-b7b4-11e9-85b5-79785920d9de.png)

If you type ":" and then "Esc" it fixes the issue and airline shows an arrow

![Screenshot from 2019-08-05 18-55-11](https://user-images.githubusercontent.com/1499142/62478743-83846900-b7b4-11e9-9034-df133a9a9db0.png)

**Comment by justinmk** [comment]
Maybe https://github.com/equalsraf/neovim-qt/pull/557 will help with this.

**Comment by vladimir-didenko** [comment]
> Maybe #557 will help with this.

Yes it fixes the bug. I am closing this issue because we already have another one to track this problem.
