### ISSUE TITLE
Default colorscheme is broken

### ISSUE THREAD

**Issue by jgehrig** [equalsraf/neovim-qt#568]
The default colors are not handled well by ext_linegrid.

Both instances are started with `nvim-qt -- -u NONE`.

Symptoms:
![image](https://user-images.githubusercontent.com/11207308/62967136-619f6d80-bdd6-11e9-9947-274f3ab24868.png)

Both instances of nvim-qt are identical (built from master) with ext_linegrid enabled. The Neovim host version is different.

Left: v0.3.7
Right: v0.4.0 (custom build)

I am not sure what the root cause is, but it looks related to light/dark background and default colors. The issues appear for `:colorscheme default`, but not others like `:colorscheme blue`.

I suspect we need more complex logic to pick the correct rendering color when none is provided. The color may need to change depending on version of the neovim host.

**Comment by justinmk** [comment]
in Nvim 0.4 `:help ui-linegrid` note:

```
["default_colors_set", rgb_fg, rgb_bg, rgb_sp, cterm_fg, cterm_bg]      
        The first three arguments set the default foreground, background and
        special colors respectively. cterm_fg and cterm_bg specifies the     
        default color codes to use in a 256-color terminal.
                                                                           
        The RGB values will always be valid colors, by default. If no         
        colors have been set, they will default to black and white, depending 
        on 'background'. By setting the ext_termcolors option, instead       
        -1 will be used for unset colors. This is mostly useful for a TUI
        implementation, where using the terminal builtin ("ANSI") defaults 
        are expected.                                                        
                                                                              
        Note: Unlike the corresponding ui-grid-old events, the screen is not  
        always cleared after sending this event. The UI must repaint the
        screen with changed background color itself.
```

**Comment by bfredl** [comment]
The handling of default colors did not change with `ext_linegrid` in this aspect. The difference is rather that 0.4 will _always_ supply valid colors, while 0.3.x still might use -1 values, which is a backwards compatible change. No extra "complexity" should be needed compared to the previous version, nvim-qt should just be prepared to handle -1 defaults _regardless_ of mode.

**Comment by bfredl** [comment]
More specifically: `handleDefaultColorsSet` needs to check `if (rgb_fg/bg == -1) ` just like `"update_fg/bg"` handler does.

**Comment by jgehrig** [comment]
Just to be clear... Something wrong with my implementation, not `ext_linegrid` itself. 😄

Thanks for the info!

> The difference is rather that 0.4 will always supply valid colors, while 0.3.x still might use -1 values

This sounds like the reason why the bug manifests in 0.3 but not 0.4.

> If no colors have been set, they will default to black and white, depending on 'background'.

I would guess this is the issue in nvim-qt's implementation. I don't think it looks at background before setting the default fg/bg values? They are hard coded to black/white.

> More specifically: handleDefaultColorsSet needs to check if (rgb_fg/bg == -1) just like "update_fg/bg" handler does.

If I understand correctly, this functionality is already in place. In each Cell, QColor::Invalid (-1) is used to mark where the default colors should be used. Re-painting when those defaults change works too.

**Comment by jgehrig** [comment]
This seems related to Issue #390.

I bet that bug also occurs because `background` is not checked before setting the default colors.

**Comment by equalsraf** [comment]
Yup just bumped into this myself, but it is not caused by the ext_linegrid changes. It also happens with the latest release.

**Comment by equalsraf** [comment]
Humorous workaround:

```diff
index 8eea774..ec01236 100644
--- a/src/gui/shell.cpp
+++ b/src/gui/shell.cpp
@@ -852,9 +852,9 @@ void Shell::handleDefaultColorsSet(const QVariantList& opargs)
        const uint64_t rgb_bg = opargs.at(1).toULongLong();
        const uint64_t rgb_sp = opargs.at(2).toULongLong();
 
-       const QColor foregroundColor = color(rgb_fg, QColor::Invalid);
-       const QColor backgroundColor = color(rgb_bg, QColor::Invalid);
-       const QColor specialColor = color(rgb_sp, QColor::Invalid);
+       const QColor foregroundColor = color(rgb_fg, Qt::black);
+       const QColor backgroundColor = color(rgb_bg, Qt::white);
+       const QColor specialColor = color(rgb_sp, Qt::yellow);
 
        // Update shellwidget default colors
        setForeground(foregroundColor);
```

**Comment by bfredl** [comment]
> If I understand correctly, this functionality is already in place. In each Cell, QColor::Invalid (-1) is used to mark where the default colors should be used. Re-painting when those defaults change works too.

No this is not the same thing, -1 in a specific cell means something different. This is about when the the defaults themselves are -1.

`handleDefaultColorsSet` should just do the same same thing as a sequence of "update_bg"/"update_fg"/"update_sp" used to do. The only thing that changed between these is that three events got grouped together into one event. The meaning of -1 in this event did not change.

> Humorous workaround:

Is the second arg used for out-of-range values? I guess this works by accident then when -1 gets underflown to UINT64_MAX value at unsigned conversion.

**Comment by jgehrig** [comment]
I see the distinction, thanks for the clarification bfredl!

Here is the source for color():
```
QColor Shell::color(qint64 color, const QColor& fallback)
{
	if (color == -1) {
		return fallback;
	}
	return QRgb(color);
}
```

Haha, I now see the humor...

**Comment by jgehrig** [comment]
I think the quick fix above is almost correct... We still don't look at `background` for white/black or black/white.

>If no colors have been set, they will default to black and white, depending on 'background'.

**Comment by jgehrig** [comment]
Thanks!
