### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by dlamblin** [equalsraf/neovim-qt#58]
So I thought I might see something interesting for a Windows 10 machine with HiDPI and a scale factor of 250%. Unfortunately, this is my first time out with NeoVim and instead I think I have a non-working installation.

I installed using these instructions https://github.com/neovim/neovim/wiki/Installing-Neovim#windows

The running of nvim-qt.exe results in a small windows barely 3 title bars high and wide enough for an N logo, Maximize, and close button in the title bar. It can be expanded to show a larger N logo hidden within.
It does not appear to be interactive beyond placement and sizing, nor does it contain menus or options.

**Comment by equalsraf** [comment]
Hi @dlamblin, I can't test right away but I think this is related to recent changes in Neovim and #52, but the new build is not available in github yet. Can you try with this binary?

    https://ci.appveyor.com/project/equalsraf/neovim-qt/build/376/artifacts

**Comment by dlamblin** [comment]
I refreshed the files I'd had in vim-qt/ from the zip at that artifact and yes, now the window starts at a normal default size, contains ~ on lines, and behaves like vim.

That said first thing I tried was :terminal
And it gave me the error that openterm was an unknown function. Maybe that's normal for the current state of development.

Thanks.

**Comment by equalsraf** [comment]
> And it gave me the error that openterm was an unknown function.

Correct, `:terminal` is not implemented for windows yet.

Thanks for the report, closing this.
