### ISSUE TITLE
Popup menu SIGSEV on Mac OS X

### ISSUE THREAD

**Issue by equalsraf** [equalsraf/neovim-qt#580]
When running on Mac OS X I was able to reproduce a crash that occurs when trying to run an auto complete (C-N). In my case it was sufficient to open a file, write a few words and trigger completion.

I do not have debug builds in this machine, only a light trace that shows the crash occurring in `NeovimQt::Shell::handlePopupMenuSelect(long long) + 34`

**Comment by eyalk5** [comment]
Maybe it is related to https://github.com/neovim/neovim/issues/10950

**Comment by equalsraf** [comment]
I can no longer reproduce this, resolving.
