### ISSUE TITLE
List available fonts using GuiFont

### ISSUE THREAD

**Issue by nico-abram** [equalsraf/neovim-qt#584]
Similar to `set guifont=*`

**Comment by jgehrig** [comment]
Does the command `:set guifont=*` list fonts with nvim? I don't get a list back (0.4.0 or 0.3.8)...

You could probably use [QFontDatabase](https://doc.qt.io/qt-5/qfontdatabase.html) to look up the available fonts, and return that information to neovim. You could either create a new function to do this in `nvim_gui_shim.vim`, or expand upon `:GuiFont`.

For GuiFont, you could call out the `fdesc == "*"` case in `bool Shell::setGuiFont(const QString& fdesc, bool force)`, and then issue an `:echo` with the list of fonts via `m_nvim->api0()->vim_command(...)` or similar. The approach would be similar for a new function too.

**Comment by justinmk** [comment]
> Does the command `:set guifont=*` list fonts with nvim? I don't get a list back (0.4.0 or 0.3.8)...

I assume that's a gVim feature.

**Comment by jgehrig** [comment]
You are correct, this is a gVim feature.

![image](https://user-images.githubusercontent.com/11207308/65055791-d158c900-d93d-11e9-891d-2302932931c4.png)

**Comment by jgehrig** [comment]
Closing as merged.

See `:set guifont=*` or `:GuiFont *`.
