### ISSUE TITLE
`QCommandLineParser: option not defined: "qwindowgeometry"` when starting nvim-qt 0.2.14

### ISSUE THREAD

**Issue by YorickPeterse** [equalsraf/neovim-qt#587]
As of version 0.2.14, starting `nvim-qt` on Arch Linux produces the the following warning:

    QCommandLineParser: option not defined: "qwindowgeometry"

This does not seem to prevent running of neovim-qt, but it seems to suggest that commandline arguments might not be parsed properly.

**Comment by jgehrig** [comment]
This is probably related to #551. Are you running a Debug or Release build?

It is a harmless message, but we don't want it to display for Release builds.

**Comment by YorickPeterse** [comment]
@jgehrig This is using a release build (see the [PKGBUILD](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/neovim-qt#n22) for Arch Linux).

**Comment by jgehrig** [comment]
Thanks for the confirmation, this should definitely be fixed.

https://github.com/equalsraf/neovim-qt/blob/fc27a4e8bfdc6efa095fa79cc7db6801bc111e50/src/gui/app.cpp#L120-L122

`QCommandlineParser` leaves something to be desired... Only one of the last two options will ever be set. Looking at the Qt source, `isSet` will trigger qWarnings for unkown arguments; we have no control.

I have a few ideas, and will post a fix shortly.

**Comment by jgehrig** [comment]
Fix merged. Marking as closed.
