### ISSUE TITLE
nvim-qt installation instructions on mac os / homebrew

### ISSUE THREAD

**Issue by mwbogucki** [equalsraf/neovim-qt#59]
Hi Everyone. Longtime vim/linux user. Just starting w/ neovim/nvim-qt.

Neovim is built.  ( ~/Code/VIM/NeoVim/build/bin/nvim)
nvim-qt is built (~/Code/VIM/neovim-qt/build/bin/nvim-qt)

I've copied nvim into both neovim-qt  ( and neovim-qt/build/bin/ )
I've copied ~/Code/VIM/NeoVim/runtime/* into neovim-qt  (and neovim-qt/build/bin) 

When I invoke nvim-qt I see the following message on my console:
$> ~/Code/VIM/neovim-qt/build/bin => ./nvim-qt
QWidget::setMinimumSize: (/QDockWidget) Negative sizes (0,-1) are not possible
QWidget::setMaximumSize: (/QDockWidget) Negative sizes (0,-1) are not possible
Neovim fatal error "No such file or directory"

In the popup window I see: "Unable to start nvim: No such file or directory"

Where does nvim-qt expect nvim to exist?

Thank you.

--Mike

**Comment by equalsraf** [comment]
Hi @mwbogucki, and welcome I think you are the first person trying neovim-qt on Mac, so congrats on being a trailblazer :D

    Neovim fatal error "No such file or directory"

nvim-qt expects nvim to be in your $PATH, if nvim is already working from your terminal nvim-qt should also start successfully (at least from the console) - there should be no need to move the runtime/ around if Neovim is already working. How are you launching nvim-qt?

These two messages should me harmless

    QWidget::setMinimumSize: (/QDockWidget) Negative sizes (0,-1) are not possible
    QWidget::setMaximumSize: (/QDockWidget) Negative sizes (0,-1) are not possible

**Comment by mwbogucki** [comment]
Hi Rui Abreu Ferreira,

Thank you for the speedy reply. That certainly fixed the issue. Added nvim
to my PATH ... and it worked.
At this point all I'm seeing is a nvim session in a window.... no menus or
anything. Is that the present state, or do I need to see up something in my
.nvimrc file?

Thanks again.

--mike

**Comment by equalsraf** [comment]
That is the current state. No menus or scrollbars are implemented.

If you get the chance check the following

- i suspect some are not working - Cmd vs Ctrl
- i dont have a mac where to test, maybe there is a way to cook a brew recipe that includes the path to vim
- ping me if you have mac specific tweaks or drop them in the wiki

You can change the font, see the [[GUi]] wiki page.

**Comment by james2doyle** [comment]
Is it possible to disable or hide the little terminal window that pops up with nvim-qt? Do I always need to have a terminal open for the app to run?

**Comment by equalsraf** [comment]
@james2doyle, in Mac OS? What terminal window are you referring to?

**Comment by james2doyle** [comment]
Yeah in OSX. Whenever I run the nvim-qt binary, it pops open a terminal window and starts printing out information

**Comment by equalsraf** [comment]
@mwbogucki I'm closing issue this in favor of #86.

@james2doyle moving this discussion to #93.
