### ISSUE TITLE
Error connecting to remote nvim server running inside a docker container

### ISSUE THREAD

**Issue by tareqsiraj** [equalsraf/neovim-qt#594]
I'm trying to use `nvim-qt` to connect to a `nvim` server running inside a docker container on the same machine. Unfortunately I'm getting errors whether or not I'm using a unix file socket or ip/port. I tried the same locally without the docker container and it works fine.

Versions:
```
nvim-qt: be7051b1cc5b1dbc781c3b07d86d9293ca297d67
nvim: 0.4.2 release
host: Ubuntu 19.04 (5.0.0-29-generic #31-Ubuntu SMP Thu Sep 12 13:05:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux)
```

Reproduce:
Using the `Dockerfile`:
```
FROM ubuntu:19.04

RUN echo "Installing fuse..." \
    && apt update \
    && apt install -y fuse curl

RUN echo "Downloading neovim..." \
    && mkdir -p /usr/local/bin \
    && curl -L https://github.com/neovim/neovim/releases/download/v0.4.2/nvim.appimage > /usr/local/bin/nvim \
    && chmod a+x /usr/local/bin/nvim

ARG NVIM_PORT=8337
EXPOSE ${NVIM_PORT}
ENV NVIM_LISTEN_ADDRESS=/work/nvim.sock

WORKDIR /work
```

Build:
```
docker build -t neovim-bugreport:local .
```

Docker run:
```
docker run --privileged -it -v $PWD:/work -p 127.0.0.1:8337:8337 neovim-bugreport:local /usr/local/bin/nvim
```

Neovim-qt:
```
nvim-qt --server 127.0.0.1:8337
```

Failures:
![nvim-qt-ip](https://user-images.githubusercontent.com/1815868/65842095-fa426c00-e2f6-11e9-89c9-c9c2275ea53b.png)
![nvim-qt_socket](https://user-images.githubusercontent.com/1815868/65842100-ff072000-e2f6-11e9-9b25-61170af5d5e1.png)

Am I missing something? Thanks.

**Comment by justinmk** [comment]
Try connecting with `nc` ?

**Comment by tareqsiraj** [comment]
`nc` seems to connect? I'm not sure what to expect, but after typing `foobar`, it exits with return 0.
```
❯ nc localhost 8337
foobar
Exit code: 0 👍
```

**Comment by tareqsiraj** [comment]
@justinmk You are probably right, docker is doing something fishy. If I launch using:
```

**Comment by tareqsiraj** [comment]
Closing this issue since it looks like its my docker environment that is screwing things up for me.
