### ISSUE TITLE
why the y of the QPoint send first

### ISSUE THREAD

**Issue by zgpio** [equalsraf/neovim-qt#596]
I am using neovim-qt client to build a cpp neovim plugin.
I found the y of the QPoint send first when I use `nvim_win_set_cursor`, but why? 
https://github.com/equalsraf/neovim-qt/blob/9875617f1f471031ee48cb4f51757ba73e08833b/src/msgpackiodevice.cpp#L784-L789

**Comment by equalsraf** [comment]
Neovim defines its own types for use in msgpack. One of those types is a pair **Array(Integer, 2)** which is used in methods that use coordinates. The first item in the array is the row and the second the column so (y, x).

For example see [nvim_win_set_cursor()](https://github.com/neovim/neovim/blob/master/src/nvim/api/window.c#L120) in nvim. This is common in the nvim api and the bindings generator treats occurrences of **Array(Integer, 2)** as QPoint, (in [here](https://github.com/equalsraf/neovim-qt/blob/master/bindings/generate_bindings.py#L88))

So the generated C++ function uses QPoint directly:

https://github.com/equalsraf/neovim-qt/blob/9875617f1f471031ee48cb4f51757ba73e08833b/src/auto/neovimapi1.cpp#L806

**Comment by zgpio** [comment]
Intuitively, I took the first variable of QPoint as row.
