### ISSUE TITLE
<c-/> rings a bell

### ISSUE THREAD

**Issue by eyalk5** [equalsraf/neovim-qt#598]
I want to use <c-/> it in my mapping but it causes a bell to ring every time I press on it, no matter what I mapped it to. 

For example:

    nmap <c-/> y

I have tried all of these and still happens:

    set noerrorbells visualbell t_vb=
    set noeb vb t_vb=
    autocmd GUIEnter * set visualbell t_vb=

Thanks. 

In nvim in iterm with the same settings, it doesn't beep

**Comment by eyalk5** [comment]
I believe it is due to line 427 in src/gui/shell.cpp

	} else if (name == "bell"){
		QApplication::beep();

I guess I will remove it from the compiled version myself. 
But in any case, I suggest to put it in a controllable variable.

**Comment by eyalk5** [comment]
I tried to recompile it, and it is not because of this. I wonder why it happens(not in the terminal, just in nvim-qt)

**Comment by justinmk** [comment]
This is the Nvim default:

    :set belloff=all

**Comment by eyalk5** [comment]
It beeps with this setting and without it under neovim-qt. 
nvim in terminal doesn't recognize <c-/> only ^_ , so it doesn't nothing on <c-/> . 

 on <c-/>, neovim-qt goes to search and beeps with `-u NONE`.

**Comment by justinmk** [comment]
Hmm. So the mapping is invoked? Might be a Nvim bug.

**Comment by eyalk5** [comment]
The mapping is invoked on neovim-qt(only) where it is companied by a beep.  ^_ mappings are invoked on neovim in Iterm2. I will create an issue on neovim repo.
