### ISSUE TITLE
Can't overwrite Cursor color over parenthesis, and can't disable reverse color

### ISSUE THREAD

**Issue by AgentCosmic** [equalsraf/neovim-qt#599]
As you can see on the image, when the cursor in on a parenthesis there is a purple background which I can't disable. The correct color should be white. Another problem is that the guifg will invert everywhere even though I explicitly set a color.

Is there a highlight group or option that I should be adding?

![image](https://user-images.githubusercontent.com/1035714/66758820-a4aeb780-eed1-11e9-8752-7ea43171cdfb.png)

**Comment by equalsraf** [comment]
No. This is currently a limitation in neovim-qt, it always paints the cursor by inverting the colors instead of using the correct color

https://github.com/equalsraf/neovim-qt/blob/9875617f1f471031ee48cb4f51757ba73e08833b/src/gui/shell.cpp#L1038-L1052

**Comment by AgentCosmic** [comment]
Oh, will it ever be supported? Cos I always get confused where my cursor's at, especially without the blinking option. Thanks.

**Comment by jgehrig** [comment]
Maybe Pull Request #520 would resolve (or at least help with) this issue?

![peekV43L9Z](https://user-images.githubusercontent.com/11207308/67357314-e6bba700-f52a-11e9-921c-e62eb24bb724.gif)

Curious... What is the "correct" way to handle bracketing cursor color?

@equalsraf
We now have support for light/dark fg/bg issue last mentioned in the thread. Do you think the feature is worth merging if that code is finished?

**Comment by jgehrig** [comment]
XOR cursor caused this issue. With #640, the logic is no longer present.

With the new `:set guicursor` implementation, this issue is not present.

Marking as closed.
