### ISSUE TITLE
Build fails with error: ‘MSGPACK_OBJECT_BIN’ was not declared in this scope

### ISSUE THREAD

**Issue by equalsraf** [equalsraf/neovim-qt#6]
From [r/neovim](https://www.reddit.com/r/neovim/comments/2sq1dz/current_status_of_guis_for_neovim/co72r7f)

```
$ make
Scanning dependencies of target neovim-qt_automoc
[  3%] Automoc for target neovim-qt
Generating moc_neovimconnector.cpp
Generating moc_neovim.cpp
Generating moc_neovimrequest.cpp
[  3%] Built target neovim-qt_automoc
Scanning dependencies of target neovim-qt
[  7%] Building CXX object src/CMakeFiles/neovim-qt.dir/util.cpp.o
/home/mike/root/projects/neovim-qt/src/util.cpp: In function ‘QByteArray NeovimQt::toByteArray(const msgpack_object&)’:
/home/mike/root/projects/neovim-qt/src/util.cpp:71:19: error: ‘MSGPACK_OBJECT_BIN’ was not declared in this scope
  if ( obj.type != MSGPACK_OBJECT_BIN ) {
                   ^
compilation terminated due to -Wfatal-errors.
make[2]: *** [src/CMakeFiles/neovim-qt.dir/util.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/neovim-qt.dir/all] Error 2
make: *** [all] Error 2
```

The msgpack library seems too old. If you are already building neovim in the same machine you point cmake to the version in the neovim folder .e.g

```
cmake -DMSGPACK_INCLUDE_DIR=../../neovim/.deps/usr/include/ -DMSGPACK_LIBRARY=../../neovim/.deps/usr/lib/libmsgpack.a
```

Related #5. There may also be some errors if the library version is too new, because the API changed.

**Comment by michaeljones** [comment]
Thanks for picking this up. I'll try to give it another shot and report back. Given that I'm running a fairly simple set up and out of practice with configuring C++ related projects, I imagine it is something pretty basic.

**Comment by equalsraf** [comment]
NP. This is a fairly  common issue since msgpack has not made a release since July - but Neovim needs some of the more recent features.

**Comment by michaeljones** [comment]
I've managed to build it with that line. Cheers.

I'm running `build/src/nvim-qt` which loads successfully but I get a white panel with white text. Or I assume it is white text anyway :) The cursor moves as I type but I can't see anything. I'm wondering if I'm missing some qt styles or something.

Great to see anyway! I'm curious what your plans are for the project? It is a test exercise for you, or are you hoping to push it quite far? Are you focussing on creating a fully functional UI or more interested in the library side to allow others to use it as a qt component in other apps?

**Comment by equalsraf** [comment]
Can you attach a screenshot? Github should allow you to drag/drop here.

> I'm running build/src/nvim-qt which loads successfully but I get a white panel with white text. Or I assume it is white text anyway :) The cursor moves as I type but I can't see anything. I'm wondering if 

No qt styles needed, it should be an exact replica of what you get on the terminal.

Which versions of Neovim and neovim-qt are you running? There was an issue with colors that was fixed in 1712e0881dd091d404ffa96d656925606527c54a

> Great to see anyway! I'm curious what your plans are for the project? It is a test exercise for you, or are you hoping to push it quite far? Are you focussing on creating a fully functional UI or more interested in the library side to allow others to use it as a qt component in other apps?

Hard to say, I find myself a bit short on time.

Personally I'm more interested on the GUI side of things, as an alternative to vim-Qt. But there is no reason why the lib/bindings can't be reused by others - e.g. if anyone wants to use it to build a different GUI, it should be reusable enough for that too.

My goals for the GUI are:
- Get a simple GUI going (mostly the editing area as seen in the terminal), altough some facilities already provided by Qt like save/load dialogs can be tied together as well.
- Allow the editor widget to be embeded in third-party Qt apps

I'm not a big user of the more visible Vim GUI features (menus, toolbars etc), what I like in the Vim GUI is

- fonts
- colors, without terminal issues
- desktop integration e.g. fullscreen mode

And of course all this allows me to validate the work in neovim/neovim, and get a portable GUI in the process :D

**Comment by equalsraf** [comment]
A possibility that did no occur to me earlier is that maybe the connection to neovim is failling - can you paste here the console output from neovim-qt, it should show some debug messages. If it does not you can enable Debug builds in cmake with

    cmake -DCMAKE_BUILD_TYPE=Debug (...) ..

**Comment by michaeljones** [comment]
Thanks for the prompt reply. I'll let you know as soon as I've had time to investigate a little further and get the screenshot, etc.

**Comment by michaeljones** [comment]
Here is a couple of screen shots after starting a new session and pressing: `oHello there.<Enter><Esc>` ie. starting a new line and writing 'hellothere.'

Normal mode:
![nvim-qt-normal-mode](https://cloud.githubusercontent.com/assets/5390/6096185/24445512-af7c-11e4-885e-09314a145cc3.png)
 
Visual mode with the text highlighted:
![nvim-qt-visual-mode](https://cloud.githubusercontent.com/assets/5390/6096188/2d61e9e8-af7c-11e4-9286-4d648d63733f.png)

When I try to exit without saving I can see green text saying 'Press ENTER or type command to continue' at the bottom though no other information. If I do a `:q!` then it exits correctly but I don't see those characters appear at the prompt at the bottom.

As for your goals, they sound excellent to me. I'm short on time as well but I love the idea of trying to contribute a little. I use gvim for similar reasons. I disable all the GUI additions but enjoy the fonts, colours and getting it out of my terminal. I'd love something similar for neovim.

**Comment by equalsraf** [comment]
Ok got it! Somehow it seems related to the color scheme, or some other setting in Neovim. Right now I'm using wombat 256, but when I run Neovim with the default colors the exact same thing happens here. I'll have a look in a bit.

Sidenote: With exception to --server all other command line arguments are passed onto Neovim e.g. `nvim-qt -u NONE`

**Comment by equalsraf** [comment]
FYI merged the tb-remote-ui branch into master

**Comment by equalsraf** [comment]
The color scheme issue should be fixed now

**Comment by michaeljones** [comment]
Thanks for the update. I can confirm that it works for me. One initial issue I now notice is that using `<C-[>` instead of `<ESC>` doesn't work. I can register that as another issue if you like.

It is really great to see. I'm hoping to have more time to look into this stuff in mid-March but I'm afraid I can't spend much time at the moment. Very cool to see though! Good job :)

**Comment by equalsraf** [comment]
This should be fixed in Neovim and in upstream msgpack by now.
