### ISSUE TITLE
Cmake warnings about tests

### ISSUE THREAD

**Issue by jpfairbanks** [equalsraf/neovim-qt#60]
I just updated my build from source and noticed these warnings. It looks like these are warnings about libraries necessary for tests. If they are just necessary for tests then I won't worry about it. If not, then it should probably be documented what to do about them.

```
> cmake ..                                                           /h/j/l/n/build (git)-[master] 
-- Downloading Msgpack...
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
-- Could NOT find ZLIB (missing:  ZLIB_LIBRARY ZLIB_INCLUDE_DIR) 
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
```

**Comment by equalsraf** [comment]
@jpfairbanks, no worries, libmsgpack is built as part of of the build process and it looks for those libraries for its tests - but we don't need them. Likewise, Doxygen is only required if you want to generate the documentation.
