### ISSUE TITLE
is there a way to know if nvim-qt is running when sourcing init.vim?

### ISSUE THREAD

**Issue by jdhao** [equalsraf/neovim-qt#604]
Hi, I am aware that the variable `g:GuiLoaded` is used to indicate that nvim-qt is running.  But it seems that this variable is not available when `init.vim` is sourced.

I have a use case where I want to set  `termguicolors` options based on whether I am using nvim-qt or whether TERM is `xterm-256color`:

```
if $TERM == "xterm-256color" || exists('g:GuiLoaded')
    set termguicolors
else
    set notermguicolors
endif
```

Unfortunately, it does not work. Is there a workaround?

**Comment by equalsraf** [comment]
if you have an up to date version of neovim you should have autocommand UIEnter, for whenever the UI attaches to nvim.

However, this specific example got my attention because this option

>    set termguicolors

is already set by neovim-qt when starting up nvim (for compatibility with older nvim versions)

```
$ ps ax | grep nvim
 3676 ?        Sl     0:00 /home/raf/.local/bin/nvim-qt --nofork
 3678 ?        S      0:00 /usr/bin/nvim --embed --cmd let &rtp.=',/home/raf/.local/share/nvim-qt/runtime' 
                            --cmd set termguicolors
```

So you really should not need it.

**Comment by justinmk** [comment]
Yes, see `:help UIEnter` or `:help gvimrc` in Nvim 0.4.2. https://github.com/neovim/neovim/pull/11263 will also enhance UIEnter in Nvim 0.4.3/0.5

**Comment by jdhao** [comment]
@equalsraf , my config is now like:

```
if $TERM == "xterm-256color"
    set termguicolors
else
    set notermguicolors
endif
```

But after launching nvim-qt, the `termguicolors` option is not set.  I am using Windows 10.

**Comment by equalsraf** [comment]
What happens if remove the else statement? The default should be off anyway. And the UI should set it for you, so you only really need to do it for xterm.

```
if $TERM == "xterm-256color"
    set termguicolors
endif
```

**Comment by jdhao** [comment]
@equalsraf  Thanks, it works now. It seems that `set notermguicolors` explicitly will override the nvim-qt setting on `termguicolors`.

**Comment by equalsraf** [comment]
>  It seems that set notermguicolors explicitly will override the nvim-qt setting on termguicolors.

yup nvim-qt sets it through the command line when starting neovim, and the config file unsets it.

Ok, closing this then.
