### ISSUE TITLE
"vnoremap < <gv" doesn't work

### ISSUE THREAD

**Issue by aj3423** [equalsraf/neovim-qt#607]
I use two mapping to keep selection after indenting

    vnoremap > >gv
    vnoremap < <gv

The first line works fine, but the second line doesn't work. I tried the console *nvim.exe*, it works fine for both lines.  

Environment:  win10-64bit  nvim-qt 0.5.0

**Comment by rsheasby** [comment]
Was just about to open a similar issue for this. I'm unable to map `<`.
`nnoremap < <<` doesn't work either. Works perfectly when using nvim directly from terminal though.

**Comment by justinmk** [comment]
Maybe `<` needs to be sent as `<lt>`

**Comment by rsheasby** [comment]
I’ve already tried that. No luck. 

Besides, if that were the case why would it work correctly in regular nvim?

**Comment by justinmk** [comment]
? This is something nvim-qt needs to do in it's input routine.

**Comment by alexeevit** [comment]
ubuntu 18.04, the same problem

**Comment by jhimcras** [comment]
manjaro 18.1.1, KDE 5.17.3, kernel 5.3.12-1
Same problem.
```
void Shell::keyPressEvent(QKeyEvent *ev) {
//...
    QString inp = Input.convertKey(ev->text(), ev->key(), ev->modifiers());
    std::cout << insp.toStdString().c_str() << "\n";
//...
}
```
intput: <
output: <s-lt>

It works with `vnoremap <s-lt> <gv`.

**Comment by jgehrig** [comment]
This looks like a bug in neovim-qt to me...

@justinmk When the user types `<` they are holding down the keys `Shift + ,<`. Should the client send `<S-lt>` or just `<lt>`?

I assume the client is supposed to send only `<lt>`, and neovim-qt needs something like the following:
``` C++
	const auto modNoShift { mod & ~Qt::KeyboardModifier::ShiftModifier };
	return QString{ "<%1%2>"}.arg(GetModifierPrefix(modNoShift)).arg("lt");
```

**Comment by justinmk** [comment]
> @justinmk When the user types `<` they are holding down the keys `Shift + ,<`. Should the client send `<S-lt>` or just `<lt>`?

Just `<lt>`. Otherwise users would need to map `<s-lt>` instead of `<lt>`. Nvim does not alias the two, otherwise the `s-` prefix would be pointless.

You can test it like this (in any Nvim UI, including terminal Nvim):

```
:nn <s-lt> :echo 's-lt'<cr>
:call nvim_input('<lt>')
```

**Comment by jgehrig** [comment]
Working in the latest release, `v0.2.16`. Marking as Closed.
