### ISSUE TITLE
`keymap` russian-jcuken(win/mac) for russian capital BE (Б) does not work

### ISSUE THREAD

**Issue by artkpv** [equalsraf/neovim-qt#608]
When I press '<' with `keymap=russian-jcuken` under nvim-qt it does not print russian capital 'Б' but '<'. Under terminal (kitty) with nvim it prints correct symbol. How to fix for nvim-qt?

```
> pacman -Qs vim
local/neovim-qt 0.2.14-1
    GUI for Neovim
```

- `nvim --version`:
```
NVIM v0.4.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.2/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
- `nvim -u DEFAULTS` (version: ) behaves differently?

YES, it works correctly then, ie it prints 'Б' after `set keymap=russian-jcuken`

- Operating system/version:
```
Linux artpc 5.3.8-arch1-1 #1 SMP PREEMPT @1572357769 x86_64 GNU/Linux
```

### Actual behaviour
Press '<' it prints '<'.

### Expected behaviour
Press '<' it prints 'Б'.

This is the key:
https://github.com/neovim/neovim/blob/cafb92487b308b44f38d004c6d1c540f00656021/runtime/keymap/russian-jcuken.vim#L18

**Comment by jgehrig** [comment]
Hey @artkpv,

This looks like a duplicate of Issue #607; different symptoms for the same issue. We incorrectly send a shift modifier along with `<`, which is not correct.

If you are able to build from source, try Pull Request #612. That should fix your issue.

**Comment by artkpv** [comment]
Hi @jgehrig , Thanks! It is fixed. I've used AUR package (Arch Linux) - https://aur.archlinux.org/packages/neovim-gtk-git/. Won't reproduce now, shows the correct char.

**Comment by jgehrig** [comment]
@artkpv

Yes, the input-layer got an overhaul. Thanks, I'm glad to hear your scenario is working! :smiley:
