### ISSUE TITLE
Failure build if cc linked to clang

### ISSUE THREAD

**Issue by MarrekNozka** [equalsraf/neovim-qt#609]
Hi.
I build neovim-qt on Devuan/Debian Linux. Compilation failed with this message: 

```
/usr/bin/ld: ../../third-party/libmsgpackc.a(unpack.c.o): relocation R_X86_64_32S against `.text' can not be used when making a PIE object; recompile with -fPIC
```

This behavior occurs if `cc` linked to `clang`. If I switch (by `update-alternatives`) cc to gcc complilation is OK. 

Thanks

**Comment by equalsraf** [comment]
It seems the messagepack recipe does not build with PIC on.

https://github.com/equalsraf/neovim-qt/blob/master/third-party/CMakeLists.txt

Perhaps setting a global option works

```
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
```

**Comment by jgehrig** [comment]
As per comments above, resolved.

Marking as closed.
