### ISSUE TITLE
[Windows 8.1] Git fugitive does not work

### ISSUE THREAD

**Issue by aikeru** [equalsraf/neovim-qt#62]
It works fine in gvim, but when run in neovim-qt I get an error when running commands, such as "Gitv" or "Gstatus":
![image](https://cloud.githubusercontent.com/assets/1163405/10657616/cd3393b8-7853-11e5-9c63-50d3956c04f7.png)

Not sure if this is a bug for neovim itself or for neovim-qt. Of course, it could be I am missing something :)

**Comment by equalsraf** [comment]
@aikeru I can't test right now. Likely an issue with Neovim, the system() command is partially broken, but this seems different.

**Comment by equalsraf** [comment]
This might be fixed with a recent neovim build.
