### ISSUE TITLE
Is there any way of Copy and Paste to/from Other Programs like in GVim?

### ISSUE THREAD

**Issue by RockatanskyV8** [equalsraf/neovim-qt#621]
The GVim had the + register that allows the user to copy and paste text outside of vim like the browser, does this exists in neovim-qt?

I can't find any reference to it in the documentation.

**Comment by jgehrig** [comment]
Yes, Cut-Copy-Paste should work in `neovim` and `neovim-qt`.

Cut: `"+x`

Copy: `"+y`

Paste: `"+gp`

There is also an optional context menu that can be mapped in `ginit.vim`:
```
nnoremap <silent><RightMouse> :call GuiShowContextMenu()<CR>
inoremap <silent><RightMouse> <Esc>:call GuiShowContextMenu()<CR>
vnoremap <silent><RightMouse> :call GuiShowContextMenu()<CR>
```

![image](https://user-images.githubusercontent.com/11207308/72034306-a4b91c00-3262-11ea-99fe-0c45fc70154c.png)

**Comment by RockatanskyV8** [comment]
But in this way I'm only allowed to copy and paste text that comes from inside the NeoVim editor. 
What if I want to copy a text from my browser and paste it to NeoVim?

**Comment by jgehrig** [comment]
No, the `"` register should work in `nvim` too for the external clipboard.

What is the output of `:checkhealth`?

For example, I just copied the following from `nvim-qt`:
```
health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xsel
```

You will need that check to pass for external clipboard to work. If that health check fails, you should be able to modify `PATH` so that the correct utility is available to `nvim`. How to do this depends on your platform.

**Comment by RockatanskyV8** [comment]
It says:
```
health#provider#check
========================================================================
## Clipboard (optional)
  -WARNING: No clipboard tool found. Clipboard registers ("+ and "*) will not work.
   -ADVICE:
    -:help clipboard
```
I'm looking on :help but didn't find the solution to this particular problem yet...

**Comment by jgehrig** [comment]
https://neovim.io/doc/user/provider.html

```
 *clipboard-tool*
The presence of a working clipboard tool implicitly enables the '+' and '*'
registers. Nvim looks for these clipboard tools, in order of priority:

  - |g:clipboard|
  - pbcopy, pbpaste (macOS)
  - wl-copy, wl-paste (if $WAYLAND_DISPLAY is set)
  - xclip (if $DISPLAY is set)
  - xsel (if $DISPLAY is set)
  - lemonade (for SSH) https://github.com/pocke/lemonade
 - doitclient for SSH	http://www.chiark.greenend.org.uk/~sgtatham/doit/
  - win32yank (Windows)
  - tmux (if $TMUX is set)
```
You need one of the above utilities available to `nvim` in the install directory or `PATH`. Which utility depends on your platform and configuration.

**Comment by RockatanskyV8** [comment]
I installed one of then, now it works. Thanks!
