### ISSUE TITLE
how to disable GuiTabLine from init.vim?

### ISSUE THREAD

**Issue by avalonv** [equalsraf/neovim-qt#622]
Some settings like `guifont` can be set from init.vim, but `guitabline=0` doesn't seem to work, how can I do that?

**Comment by jgehrig** [comment]
Those settings are not accessible in `init.vim`. You need to use `ginit.vim` to adjust most GUI settings.

Here is a page that provides more information:
https://jdhao.github.io/2019/01/17/nvim_qt_settings_on_windows/
