### ISSUE TITLE
[Windows 8.1] clipboard not available

### ISSUE THREAD

**Issue by aikeru** [equalsraf/neovim-qt#63]
![image](https://cloud.githubusercontent.com/assets/1163405/10960857/e9c22cc4-834d-11e5-9ece-743973656cea.png)

Not sure if this belongs to neovim or neovim-qt. When using ```"*y``` I get this message.

**Comment by poldy** [comment]
I had to copy "winclip.exe" from the [Outwit tools](http://www.dmst.aueb.gr/dds/sw/outwit/) to somewhere on my path, I used C:\Windows

**Comment by equalsraf** [comment]
@poldy yes, there is a commit in neovim/neovim#810 for initial clipboard support using winclip - but I've noticed some issues where it either pastes the wrong text or adds some trailing bytes to the text. Ping me in neovim/neovim#810 if you into issues, or have a solution.

**Comment by equalsraf** [comment]
Closing this, since its being handled upstream.
