### ISSUE TITLE
eslint errors do not show in neovim-qt

### ISSUE THREAD

**Issue by ralvez** [equalsraf/neovim-qt#636]
I'm using neovim-qt in ArchLinux.
If I start the program from a GUI it starts fine but ... eslint errors/warnings do not show.
If I run eslint from the CLI it works and lints as expected.

If I start neovim-qt from a CLI (nvim-qt --no-ext-tabline --nofork) eslint works fine. (!!??)

I cannot figure out a reason for that, although, I spent a week trying different things from re-installing eslint using different versions of pynvim etc. to running the program from the CLI as described above.

Any ideas to solve the problem will be appreciated.

**Comment by ralvez** [comment]
I just did another test. Running neovim-qt from GUI and the issuing the command: Neomake, I get the following response:
Neomake : Exe (eslint) of maker eslint is not executable
Not sure what causes it but it seems reasonable that if eslint is not executable it would not work.

**Comment by ralvez** [comment]
Just noticed that the problem seems related to vue.js files specifically.
If I run neovim-qt from GUI and open a *.javascript program and then purposely add and error, the eslint error shows.
But if I do the same to a *.vim file nothing happens.

**Comment by jgehrig** [comment]
> If I start neovim-qt from a CLI (nvim-qt --no-ext-tabline --nofork) eslint works fine. (!!??)

> Neomake : Exe (eslint) of maker eslint is not executable

Both suggest to me you have a configuration problem with your system. Environment Variables? PATH?

**Comment by ralvez** [comment]
No. I do not think it is a configuration issue because if I run eslint from the CLI it works and lints fine.
Nevertheless, I think the problem was the plugin I was using. I switched to ALE and it works like a charm.

Thanks.
