### ISSUE TITLE
Bump Minimum Qt Version from 5.2

### ISSUE THREAD

**Issue by jgehrig** [equalsraf/neovim-qt#639]
Any thoughts on bumping the minimum Qt version from 5.2?

It would be nice to get rid of `#ifdef`s like the one from Pull #630  for old Qt versions.

There are several other improvements we can make:
- Get rid of `Q_ENUM` vs `Q_ENUMS`
- Fix compiler warnings for `QRegion::rects()` and other deprecations.

Qt 5.8 seems like a good minimum version candidate. It is old enough to be widely available, contains useful performance improvements, and is higher than many of the `#ifdef` checks.

**Comment by equalsraf** [comment]
Preliminaries, trying to track down used versions

- Ubuntu xenial seems to run 5.5 https://packages.ubuntu.com/search?keywords=qt&searchon=names&suite=xenial&section=all
- OpenBSD 6.3 seems to be 5.9
- Appveyor goes from Qt 5.3 to 5.14 https://www.appveyor.com/docs/windows-images-software/#qt
- Void is 5.13 https://voidlinux.org/packages/
- anyone else wants to add more here?

Q_ENUMS was introduced in 5.5 right. I'm tempted to stick with that. What version is required for `QRegion::rects`?

**Comment by jgehrig** [comment]
`QRegion::rects()` has been deprecated in favor of `::begin()/::end()`, which occurred in Qt 5.8.

- https://doc.qt.io/qt-5/qregion-obsolete.html#rects
- https://doc.qt.io/qt-5/qregion.html#begin

Yes, `Q_ENUM` was introduced in Qt5.5 from what I can tell.

#630 has one preprocessor check for >=Qt5.5, and another for >=Qt5.7

There are also some warnings around `QFontMetrics::width()` vs `QFontMetricsF::horizontalAdvance()`, which require Qt 5.11. However, I think Qt5.11 is too aggressive as a minimum version.

**Comment by equalsraf** [comment]
Lets stick with 5.5. We can live with one ifdef, and the enums are the most significant one.

The deprecation warnings are annoying but we will have to deal with them a bit longer.
