### ISSUE TITLE
v:windowid is not defined

### ISSUE THREAD

**Issue by jalvesaq** [equalsraf/neovim-qt#64]
The value of `v:windowid` is not properly defined on Windows. It should be the number corresponding to Neovim-Qt window handle. I am not sure if `GetActiveWindow()` is the correct function to get the window handle in this case, but once you get it you can cast it to `long` (32 bit) or `long long` (64 bit).

On Linux, nvim running in a terminal emulator does not set the value of `v:windowid`, but we can use the value of `$WINDOWID`.

**Comment by equalsraf** [comment]
I can't fiddle with v:windowid from the GUI since it is read only (this deserves an issue request in neovim/neovim), but I think I can provide an alternative workaround for windows, by setting the $WINDOWID inside the Neovim process when the GUI attaches.

**Comment by jalvesaq** [comment]
Thanks! `$WINDOWID` is going to solve my problem.

**Comment by equalsraf** [comment]
`g:GuiWindowId`now holds the window id.

**Comment by justinmk** [comment]
> I can't fiddle with v:windowid from the GUI since it is read only (this deserves an issue request in neovim/neovim)

Oh, didn't realize that--let's fix that.
