### ISSUE TITLE
Remove XOR based gui cursor

### ISSUE THREAD

**Issue by jgehrig** [equalsraf/neovim-qt#640]
With Pull Request #623, the old XOR-based gui cursor is obsolete.

The old cursor should be removed once there is confidence in the new cursor code. For now, a fallback to the old xor cursor still exists when `:set guicursor=` is executed.

See `Shell::paintEvent` and `Shell::handleModeChanged` for the old code.

**Comment by Shatur95** [comment]
It looks like new cursor is not working properly. I have two cursors in FZF and terminal (even without any configuration):

![изображение](https://user-images.githubusercontent.com/22453358/77705352-171adc00-6fc8-11ea-9f56-701a85517b0f.png)

With `:set guicursor=` everything is okay.

**Comment by jgehrig** [comment]
Sorry, I'm not familiar with `FZF`.

Could you please elaborate further on the broken configuration and steps?

A `minimal.vim` (`-- -u NONE` is fine too) along with a set of steps to reach the issue would be very helpful in debugging this issue.

**Comment by Shatur95** [comment]
Of course. `nvim-qt -- -u NONE`:
```vim
:term
anyword <- space here
```
You will see the following:
![изображение](https://user-images.githubusercontent.com/22453358/77710957-42a5c280-6fd8-11ea-96bc-a5c9cd65e42b.png)

**Comment by jgehrig** [comment]
Thanks, I see the issue now. That is some odd behavior...

This issue looks similar in nature to #649. The cursor over `d` above is not real, it is a stale part of the canvas that has not been properly refreshed.

The second cursor goes away when focus is lost or gained. The focus change triggers a re-paint.

**Comment by jgehrig** [comment]
On a semi-related note:

This feature behaves strangely for `nvim` too, I can move a phantom cursor around:

![terminal-phantom-cursor](https://user-images.githubusercontent.com/11207308/77711934-b3cd8180-6fa8-11ea-98b5-ce5faabf4737.gif)

**Comment by Shatur95** [comment]
Yes, and it happens only with new cursor. As a temporary workaround I put `set guicursor=` into my `ginitrc.vim`
