### ISSUE TITLE
vimtex exits visual mode on compiling

### ISSUE THREAD

**Issue by eyalk5** [equalsraf/neovim-qt#645]
Hi,

This only happens on neovim-qt and goneovim. Not on TUI. 

See https://github.com/lervag/vimtex/issues/1597 

I couldn't figure out how to make nvim-qt -u option work. So, if you tell me, I will send you a minimal vimrc. 

Can you make an educated guess as to why it happens?

**Comment by equalsraf** [comment]
> I couldn't figure out how to make nvim-qt -u option work. So, if you tell me, I will send you a minimal vimrc.

nvim arguments can be added after `--` e.g.

```
$ nvim-qt -- -u NONE
```

**Comment by eyalk5** [comment]
nvr bug. Solved. neovim/neovim#12165
