### ISSUE TITLE
How to use -u NONE for nvim-qt?

### ISSUE THREAD

**Issue by BSDxxxx** [equalsraf/neovim-qt#658]
When I type ```nvim-qt -u NONE``` in cmd, It gives me ```Unknow option 'u'``` .

**Comment by shlomif** [comment]
@BSDxxxx : hi! `nvim-qt -- -u NONE` (with the double dash) seems to work for me judging by `:scriptnames`. You can use any other nvim arguments after the double dash.

**Comment by BSDxxxx** [comment]
@shlomif Thank you for the help.

**Comment by shlomif** [comment]
@BSDxxxx : you're welcome.
