### ISSUE TITLE
Spaces between underlined words are not underlined

### ISSUE THREAD

**Issue by Melkster** [equalsraf/neovim-qt#678]
When running Neovim in a terminal the spaces between underlined words are also underlined. However, in neovim-qt this is not the case.
![this is neovim-qt](https://i.gyazo.com/c88d74bfacc6f5ec38640bb1eac4ffb8.png)
![this is terminal neovim](https://i.gyazo.com/1337543b21948f90f9bb06a07c4b3598.png)

Font: DejaVu Sans Mono for Powerline
OS: Antergos Linux x86_64

**Comment by jgehrig** [comment]
@Melkster

A very similar bug was reported and fixed recently, Pull Request #643.

I cannot reproduce this issue in `master`:
![Screenshot_20200412_185450](https://user-images.githubusercontent.com/11207308/79081856-1cc63080-7cef-11ea-9b37-c0a57f7cb6a0.png)

What version are you using? An upgrade should resolve your issue.

**Comment by Melkster** [comment]
@jgehrig Not 100% sure but looks like I'm running 0.2.15-1

`nvim-qt --version` has no output, how do I tell the version?

**Comment by jgehrig** [comment]
> Not 100% sure but looks like I'm running 0.2.15-1
You are probably correct. The latest released version is 0.2.15.

The `--version` option was only added recently. We should release a new version, `0.2.16` at some point soon... However, there are a few fixes that should go in first.

This issue is already resolved in `master`.

**Comment by Melkster** [comment]
Oki gotcha, thanks!
