### ISSUE TITLE
.nvimrc from user profile folder isn't getting loaded

### ISSUE THREAD

**Issue by prabirshrestha** [equalsraf/neovim-qt#68]
`%USERPROFILE%/.nvimrc` file in windows isn't getting loaded. It stopped working after I upgraded to this version:

![image](https://cloud.githubusercontent.com/assets/287744/11696964/0d5ea61a-9e6c-11e5-99e3-5658654dadfd.png)

In the meantime where I temporarily move my `.nvimrc` file?

**Comment by equalsraf** [comment]
Since Neovim added support for XDG the user settings file hould be %LOCALAPPDATA%\nvim\init.vim.

**Comment by halkeye** [comment]
I've been trying out neovim on various platforms. Windows doesn't really like symlinks, so for now I created an init.vim in my nvim directory, this auto loads the .vimrc file, but could easily be swapped out for the old %USERPROFILE%/.nvimrc or whatever if necessary.

```
let $ORIGVIMRC=fnamemodify($MYVIMRC, ':p:h') . '/.vimrc'
source $ORIGVIMRC
```
