### ISSUE TITLE
Mingw, Unable to find the platform plugin.

### ISSUE THREAD

**Issue by saucesaft** [equalsraf/neovim-qt#680]
Hello, i was building neovim-qt from source an at the moment from running: `cmake --build .` i encountered this error:

```[ 44%] Preparing Qt runtime dependencies
C:\Users\eduar\Documents\neovim-qt\build\bin\nvim-qt.exe 64 bit, release executable
Direct dependencies: Qt5Core Qt5Gui Qt5Network Qt5Svg Qt5Widgets
All dependencies   : Qt5Core Qt5Gui Qt5Network Qt5Svg Qt5Widgets
To be deployed     : Qt5Core Qt5Gui Qt5Network Qt5Svg Qt5Widgets
Unable to find the platform plugin.
mingw32-make.exe[2]: *** [src\gui\CMakeFiles\windeployqt.dir\build.make:57: src/
gui/CMakeFiles/windeployqt] Error 1
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:1532: src/gui/CMakeFiles/windeplo
yqt.dir/all] Error 2
mingw32-make.exe: *** [Makefile:162: all] Error 2
```

I've been following the guide from the [wiki](https://github.com/equalsraf/neovim-qt/wiki/Build#windows-10-and-mingw) step by step, and i don't understand the error. Thanks :)

**Comment by jgehrig** [comment]
More context as to exactly what you did would be helpful. Without that, I am just guessing :)

It looks like a `%PATH%` error to me, and CMake is unable to find `windeployqt`. Are you using powershell or cmd?

Did you add the following to your path?
```
> $CMAKE_PATH = "C:\Qt\Tools\CMake_64\bin\"
> $MINGW_PATH = "C:\Qt\Tools\mingw730_64\bin\"
> $QT_PATH = "C:\Qt\5.12.6\mingw73_64\bin\"
> $NVIM_PATH = "C:\Program Files\Neovim\bin"
> $env:Path += "$CMAKE_PATH;$MINGW_PATH;$QT_PATH;$NVIM_PATH;"
```

You may need to adjust some of these values to the specific paths on your machine.

**Comment by saucesaft** [comment]
Hi,
I'm running everything in powershell, set up all the env vars and change them accordingly to my machine. Even tho that, i cam across the same error. One strange thing is that if i go to `C:\tools\neovim\Neovim\bin\` there's a fully functional neovim-qt binary in there, which i don't understand because the compilation failed at 40%.
Some context could be:
- Using windows 10
- Have mingw64 installed and trying to compile neovim-qt for it
- Installed neovim thorough chocolatey package manager

Thanks, if i'm missing anything please tell me. :)

**Comment by jgehrig** [comment]
That is the precompiled neovim-qt, which is bundled with neovim.

With the path modifications made to the current powershell session, is `windeployqt` found? `where windeployqt`

> Have mingw64 installed 
It seems your Qt Install may be 32-bit? Not 100% sure... Make sure your compiler is compatible with the version of Qt you selected. Version (7.x, 8.x), and Architecture (32/64) must match.

Another thing to try is a web search of the error message: "unable to find the platform plugin qt".

**Comment by saucesaft** [comment]
Hey, thanks for the help, its being a rough change from linux into windows and i missed neovim.
I didn't know that a precompiled  neovim-qt was included when installing it from chocolatey/scoop, i've decided to use it instead of compiling it from source.
Thanks!
