### ISSUE TITLE
pressing Shift+Insert in Insert mode freezes neovim-qt

### ISSUE THREAD

**Issue by petRUShka** [equalsraf/neovim-qt#681]
Steps to reproduce:
1. Run `nvim-qt`
2. Press `i` to enter Insert-mode.
3. Press `Shift+Insert`

After these three steps neovim-qt stops to react on any keys or events (like close neovim-qt window for example).

In command mode it work as expected (e.g. insert <S-insert> or paste from clipboard after configuring as in #253).

P.S. Latest neovim-qt from ArchLinux: 0.2.15.

```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by jgehrig** [comment]
I cannot reproduce the issue.

Can you think of anything unique about your system configuration or how you installed neovim-qt?

What is the output of `nvim-qt --version`? Did this happen with previous versions?

Does this issue reproduce with `nvim-qt -- -u NONE` or `nvim-qt -- -u NORC`?

These commands may break <S+Insert>, that is okay for now. Try manually typing `Control + R followed by  Shift + "Key +/="` and `Shift + Insert`.

**Comment by petRUShka** [comment]
> What is the output of nvim-qt --version? Did this happen with previous versions?

```
nvim-qt --version
nvim-qt: Unknown option 'version
```

It's the first version I use.

> Does this issue reproduce with nvim-qt -- -u NONE or nvim-qt -- -u NORC?

No with zero config it inserts `<S-Insert>` instead of freezing.

`Control + R followed by Shift + "Key +/="` works as expected.

I'll try to figure what part of my config related with freezing.

**Comment by petRUShka** [comment]
[glrnvim](https://github.com/beeender/glrnvim) by the way do not freeze by shift+insert and insert clipboard content.

**Comment by jgehrig** [comment]
Okay, `--version` was added recently. Not a problem.

> I'll try to figure what part of my config related with freezing but there is no freezing with gvim (same config).

Yes, this is the next step.

Everything sounds good and thanks for the info about gvim/gnvim/glrnvim. This is helpful.

Let's put together a `minimal.vim` with as few lines as possible: `nvim-qt -- -u minimal.vim`.

> Failed to turn input event into nvim key (keyval: 65505)

This is an interesting error message... Perhaps your system sends unusual key events?

If you can build `neovim-qt`, un-comment the following two lines from `src/gui/shell.cpp`and inspect the `QKeyEvents` when you press `<S-Insert>`:
```C++
void Shell::keyPressEvent(QKeyEvent *ev)
{
	...
	// Uncomment for key input debugging and unit test writing.
	// qDebug() << "QKeyEvent ev:" << ev;
	// qDebug() << "  " << inp;
```

You should see something similar to this for <S-Insert>:
```
QKeyEvent ev: QKeyEvent(KeyPress, Key_Shift, ShiftModifier)
   ""
QKeyEvent ev: QKeyEvent(KeyPress, Key_Insert, ShiftModifier)
   "<S-Insert>"
```

**Comment by petRUShka** [comment]
I've compiled nvim-qt with uncommented lines you suggested but there is no output to console at all. 

```C
	const QString inp{ Input::convertKey(*ev) };

	// Uncomment for key input debugging and unit test writing.
	qDebug() << "QKeyEvent ev:" << ev;
	qDebug() << "  " << inp;
```

nvim-qt was build after uncemmenting lines with 

```bash
$ mkdir build
$ cd build
$ cmake -DCMAKE_BUILD_TYPE=Release ..
$ make
```

And run with `nvim-qt --no-fork`.

P.S. `bin/nvim-qt --version`:
```
NVIM-QT v0.2.16.9999
Build type: Release
Compilation: -Wall -Wextra -Wno-unused-parameter -std=c++11 -Wfatal-errors
Qt Version: 5.14.2
Environment: 
  nvim: nvim
  args: --cmd set termguicolors
  runtime: 

NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by shlomif** [comment]
> I've compiled nvim-qt with uncommented lines you suggested but there is no output to console at all.
> 
> ```c
> 	const QString inp{ Input::convertKey(*ev) };
> 
> 	// Uncomment for key input debugging and unit test writing.
> 	qDebug() << "QKeyEvent ev:" << ev;
> 	qDebug() << "  " << inp;
> ```
> 
> nvim-qt was build after uncemmenting lines with
> 
> ```shell
> $ mkdir build
> $ cd build
> $ cmake -DCMAKE_BUILD_TYPE=Release ..
> $ make
> ```

Try with `-DCMAKE_BUILD_TYPE=Debug`.

> 
> And run with `nvim-qt --no-fork`.
> 

I get an error with `--no-fork` but `--nofork` exists.

> P.S. `bin/nvim-qt --version`:
> 
> ```
> NVIM-QT v0.2.16.9999
> Build type: Release
> Compilation: -Wall -Wextra -Wno-unused-parameter -std=c++11 -Wfatal-errors
> Qt Version: 5.14.2
> Environment: 
>   nvim: nvim
>   args: --cmd set termguicolors
>   runtime: 
> 
> NVIM v0.4.3
> Build type: Release
> LuaJIT 2.0.5
> Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
> Compiled by builduser
> 
> Features: +acl +iconv +tui
> See ":help feature-compile"
> 
>    system vimrc file: "$VIM/sysinit.vim"
>   fall-back for $VIM: "/usr/share/nvim"
> 
> Run :checkhealth for more info
> ```

**Comment by petRUShka** [comment]
I are right it is `--nofork`.

```
-➤  bin/nvim-qt --nofork                                                                                                                                                                                       

Neovim API version compatible with 0 supported 6
Received unknown option "pumblend" QVariant(qulonglong, 0)
Received unknown option "ext_multigrid" QVariant(bool, false)
Received unknown option "ext_hlstate" QVariant(bool, false)
Received unknown option "ext_termcolors" QVariant(bool, false)
Received unknown option "ext_messages" QVariant(bool, false)
Received unknown option "ext_messages" QVariant(bool, false)
Received unknown option "ext_messages" QVariant(bool, false)
QKeyEvent ev: QKeyEvent(KeyPress, Key_I, text="i")
   "i"
QKeyEvent ev: QKeyEvent(KeyPress, Key_A, text="a")
   "a"
QKeyEvent ev: QKeyEvent(KeyPress, Key_D, text="d")
   "d"
QKeyEvent ev: QKeyEvent(KeyPress, Key_S, text="s")
   "s"
QKeyEvent ev: QKeyEvent(KeyPress, Key_A, text="a")
   "a"
QKeyEvent ev: QKeyEvent(KeyPress, Key_D, text="d")
   "d"
QKeyEvent ev: QKeyEvent(KeyPress, Key_S, text="s")
   "s"
QKeyEvent ev: QKeyEvent(KeyPress, Key_Space, text=" ")
   "<Space>"
QKeyEvent ev: QKeyEvent(KeyPress, Key_Shift, ShiftModifier)
   ""
QKeyEvent ev: QKeyEvent(KeyPress, Key_Insert, ShiftModifier)
   "<S-Insert>"
QKeyEvent ev: QKeyEvent(KeyPress, Key_Super_L)
   ""

Neovim API version compatible with 0 supported 6
Received unknown option "pumblend" QVariant(qulonglong, 0)
Received unknown option "ext_multigrid" QVariant(bool, false)
Received unknown option "ext_hlstate" QVariant(bool, false)
Received unknown option "ext_termcolors" QVariant(bool, false)
Received unknown option "ext_messages" QVariant(bool, false)
Received unknown option "ext_messages" QVariant(bool, false)
Received unknown option "ext_messages" QVariant(bool, false)
QKeyEvent ev: QKeyEvent(KeyPress, Key_I, text="i")
   "i"
QKeyEvent ev: QKeyEvent(KeyPress, Key_A, text="a")
   "a"
QKeyEvent ev: QKeyEvent(KeyPress, Key_D, text="d")
   "d"
QKeyEvent ev: QKeyEvent(KeyPress, Key_S, text="s")
   "s"
QKeyEvent ev: QKeyEvent(KeyPress, Key_A, text="a")
   "a"
QKeyEvent ev: QKeyEvent(KeyPress, Key_D, text="d")
   "d"
QKeyEvent ev: QKeyEvent(KeyPress, Key_S, text="s")
   "s"
QKeyEvent ev: QKeyEvent(KeyPress, Key_Space, text=" ")
   "<Space>"
QKeyEvent ev: QKeyEvent(KeyPress, Key_Shift, ShiftModifier)
   ""
QKeyEvent ev: QKeyEvent(KeyPress, Key_Insert, ShiftModifier)
   "<S-Insert>"
```

After freezing it still logs the keys to console.

**Comment by jgehrig** [comment]
Thanks @shlomif! You beat me to it...

Your input looks identical to mine:
`QKeyEvent ev: QKeyEvent(KeyPress, Key_Insert, ShiftModifier)`

Since the input is well formed, I don't think the input layer is responsible for this issue.

**Comment by jgehrig** [comment]
> Let's put together a minimal.vim with as few lines as possible: nvim-qt -- -u minimal.vim.

This is the next step. We need to identify the configuration "problem" causing this issue.

I would recommend systematically commenting out lines until you find a set of options that reproduces the issue. Perform a "binary search" of your vimrc by commenting out half of the file each time.

**Comment by jgehrig** [comment]
Feel free to re-open if you can identify a specific configuration/scenario causing this issue.
