### ISSUE TITLE
Buffers are not reflected as separate tabs in GUI

### ISSUE THREAD

**Issue by f-squirrel** [equalsraf/neovim-qt#684]
**How to reproduce:**
1. Open `neovim-qt`
2. Open two files in separate buffers: `e: file1.txt<CR>`, `e: file2.txt`<CR>

**Actual:**
There is only one tab despite two buffers were open.
**Expected:**
Every buffer to be in a separate tab
**Note:**
There is a possibility to switch between the buffers with regular commands as `:bprev` and `:bnext`.

**Additional information:**
```
bin/nvim-qt.app/Contents/MacOS/nvim-qt --version
NVIM-QT v0.2.16.9999
Build type: Release
Compilation: -Wall -Wextra -Wno-unused-parameter -std=c++11 -Wfatal-errors
Qt Version: 5.14.1
Environment:
  nvim: nvim
  args: --cmd let &rtp.=',/Users/user/neovim-qt/build/bin/nvim-qt.app/Contents/MacOS/../Resources/runtime' --cmd set termguicolors
  runtime: /Users/user/neovim-qt/build/bin/nvim-qt.app/Contents/MacOS/../Resources/runtime

NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/config -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/src -I/usr/local/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/include
Compiled by brew@Catalina.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.3/share/nvim"

Run :checkhealth for more info
```

**Comment by shlomif** [comment]
Hi Dmitry,

On Wed, 22 Apr 2020 05:36:53 -0700
Dmitry <notifications@github.com> wrote:

> **How to reproduce:**
> 1. Open `neovim-qt`
> 2. Open two files in separate buffers: `e: file1.txt<CR>`, `e: file2.txt`<CR>
> 
> **Actual:**
> There is only one tab despite two buffers were open.
> **Expected:**
> Every buffer to be in a separate tab
> **Note:**
> There is a possibility to switch between the buffers with regular commands as
> `:bprev` and `:bnext`.
> 

From what I recall vim, gvim, and nvim don't do it either, and I like it that
way. You can use :tabe or similar to open in a new tab.

> **Additional information:**
> ```
> bin/nvim-qt.app/Contents/MacOS/nvim-qt --version
> NVIM-QT v0.2.16.9999
> Build type: Release
> Compilation: -Wall -Wextra -Wno-unused-parameter -std=c++11 -Wfatal-errors
> Qt Version: 5.14.1
> Environment:
>   nvim: nvim
>   args: --cmd let
> &rtp.=',/Users/user/neovim-qt/build/bin/nvim-qt.app/Contents/MacOS/../Resources/runtime'
> --cmd set termguicolors runtime:
> /Users/user/neovim-qt/build/bin/nvim-qt.app/Contents/MacOS/../Resources/runtime
> 
> NVIM v0.4.3
> Build type: Release
> LuaJIT 2.0.5
> Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang
> -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall
> -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99
> -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla
> -fstack-protector-strong -fdiagnostics-color=auto
> -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32
> -DNVIM_UNIBI_HAS_VAR_FROM
> -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/config
> -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/src -I/usr/local/include
> -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/deps-build/include
> -I/usr/local/opt/gettext/include
> -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include
> -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/src/nvim/auto
> -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/include Compiled by
> brew@Catalina.local
> 
> Features: +acl +iconv +tui
> See ":help feature-compile"
> 
>    system vimrc file: "$VIM/sysinit.vim"
>   fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.3/share/nvim"
> 
> Run :checkhealth for more info
> ```
> 



-- 

Shlomi Fish       https://www.shlomifish.org/
Best Introductory Programming Language - https://shlom.in/intro-lang

Our parents can't be spies! They're not cool enough.
    — https://en.wikipedia.org/wiki/Spy_Kids

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by f-squirrel** [comment]
Hi @shlomif,
Thank you for the quick response.
A far as I see all the mentioned flavors do show buffers as "tabs".
Please see the attached screenshot:
![Screen Shot 2020-04-22 at 16 29 37](https://user-images.githubusercontent.com/1248133/79987950-b7c0c680-84b6-11ea-99bc-cf460758b5f0.png)

Is there any way to configure the desired behavior?

**Comment by shlomif** [comment]
On Wed, 22 Apr 2020 06:32:33 -0700
Dmitry <notifications@github.com> wrote:

> Hi @shlomif,
> Thank you for the quick response.
> A far as I see all the mentioned flavors do show buffers as "tabs".
> Please see the attached screenshot:
> ![Screen Shot 2020-04-22 at 16 29
> 37](https://user-images.githubusercontent.com/1248133/79987950-b7c0c680-84b6-11ea-99bc-cf460758b5f0.png)
> 
> Is there any way to configure the desired behavior?
> 

This seems like a plugin's behaviour because it doesn't happen with gvim here.

-- 

Shlomi Fish       https://www.shlomifish.org/
https://www.shlomifish.org/humour/Summerschool-at-the-NSA/

SGlau: shut up, Mr. Frog! I’m here on a mission from the Grammar God. Herr
Norris and I are loyal servants of Grammar Nazism, which aims to unite Grammar
Europe under the reign of the Third Grammar Reich. Hail Grammar!
    — https://is.gd/htmOCv

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by f-squirrel** [comment]
If you run `gvim file1.txt file2.txt` you'll see 2 buffers:
<img width="742" alt="Screen Shot 2020-04-22 at 16 52 40" src="https://user-images.githubusercontent.com/1248133/79990430-b513a080-84b9-11ea-8330-1a95fedf1e83.png">
The same behavior for macvim.
```
gvim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 13 2020 11:32:00)
Included patches: 1-251
Modified by jonathon.fernyhough@york.ac.uk
Compiled by jonathon.fernyhough@york.ac.uk
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_old_static
+arabic            +file_in_path      +mouse_urxvt       -tag_any_white
+autocmd           +find_in_path      +mouse_xterm       +tcl
+autochdir         +float             +multi_byte        +termguicolors
-autoservername    +folding           +multi_lang        +terminal
+balloon_eval      -footer            -mzscheme          +terminfo
+balloon_eval_term +fork()            +netbeans_intg     +termresponse
+browse            +gettext           +num64             +textobjects
++builtin_terms    -hangul_input      +packages          +textprop
+byte_offset       +iconv             +path_extra        +timers
+channel           +insert_expand     +perl              +title
+cindent           +job               +persistent_undo   +toolbar
+clientserver      +jumplist          +popupwin          +user_commands
+clipboard         +keymap            +postscript        +vartabs
+cmdline_compl     +lambda            +printer           +vertsplit
+cmdline_hist      +langmap           +profile           +virtualedit
+cmdline_info      +libcall           -python            +visual
+comments          +linebreak         +python3           +visualextra
+conceal           +lispindent        +quickfix          +viminfo
+cryptv            +listcmds          +reltime           +vreplace
+cscope            +localmap          +rightleft         +wildignore
+cursorbind        +lua               +ruby              +wildmenu
+cursorshape       +menu              +scrollbind        +windows
+dialog_con_gui    +mksession         +signs             +writebackup
+diff              +modify_fname      +smartindent       +X11
+digraphs          +mouse             +sound             -xfontset
+dnd               +mouseshape        +spell             +xim
-ebcdic            +mouse_dec         +startuptime       +xpm
+emacs_tags        +mouse_gpm         +statusline        +xsmp_interact
+eval              -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-HqR6Bs/vim-8.2.0251=. -fstack-protector-strong -Wformat -Werror=format-security -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lcanberra -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.26/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -lpython3.6m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lm -lruby-2.5 -lpthread -lgmp -ldl -lcrypt -lm
```

**Comment by jgehrig** [comment]
You are misusing vim terminology. The term "tabs" means something different in vim than most editors. Confusing, I know :)

- `buffer` similar to what most editors call tabs. Edit multiple files within the same session.
- `tab` is similar to multiple vim sessions. Configure multiple views for the same set of "buffers". 

It looks like you are using a plugin such as `vim-airline` to display "buffers" at the top of your viewport. This is possible in `neovim-qt` too.

Neovim uses a slightly different configuration scheme than Vim, see `:help vimrc`:
```
The Nvim config file is named "init.vim", located at:
	Unix		~/.config/nvim/init.vim
	Windows		~/AppData/Local/nvim/init.vim
Or if |$XDG_CONFIG_HOME| is defined:
	$XDG_CONFIG_HOME/nvim/init.vim
```

You need to create a `init.vim` file. You can even make it load your existing `vimrc`, simply add:
```
if has('win32')
        source $HOME\_vimrc
else
        source $HOME/.vimrc
endif
```

You may also notice the `ext_tabline` feature of neovim:
![image](https://user-images.githubusercontent.com/11207308/79996984-10786b00-8487-11ea-8721-0534abc00a74.png)

This feature can be disabled with `:GuiTabLine 0`.

Alternatively, you can disable this feature at startup via:
```
[General]
ext_tabline=false
```

The file is located at:
- Linux: `$HOME/.config/nvim-qt/nvim-qt.conf`
- MacOS: `$HOME/Library/Preferences/com.nvim-qt.nvim-qt.plist`
- Windows: HKEY_CURRENT_USER\Software\nvim-qt\nvim-qt
See https://github.com/equalsraf/neovim-qt/issues/589#issuecomment-532760074 for details

**Comment by f-squirrel** [comment]
Thank you for the explanation @jgehrig !
I have one more question regarding this feature.
I've succeeded to turn the feature off locally via `ginit.vim`.
But my main use case is to run `neovim-qt` at MacOS and connect to `nvim` running in server mode at Ubuntu.
In this mode, I cannot turn it off.
I understand that this is probably not a straightforward way of using the application but maybe you know a workaround.

**Comment by jgehrig** [comment]
@f-squirrel

Could you provide a quick example/description of how you are connecting?

The option `:GuiTabLine 0` requires the `nvim-qt` runtime to be loaded.

If I had to guess, I'd say your remote session has not performed this step. There are some simple workarounds, but it depends on how your specific scenario operates.

You could also use `ext_tabline=false`, but I would strongly encourage you to fix the underlying runtime issue too. Other GUI features may not work without the runtime...

**Comment by f-squirrel** [comment]
@jgehrig
I connect via SSH to Ubuntu running on the same machine in the VM and run the following command there: `nvim --listen 172.16.145.128:7778 --headless &`.
Then I run `bin/nvim-qt.app/Contents/MacOS/nvim-qt --server 172.16.145.128:7778` at MacOS.
Btw, this feature is just awesome I really appreciate it!
P.S.
Ideally, I'd like to get rid of the VM and run `nvim` in a docker container and connect to it from `neovim-qt`.

**Comment by jgehrig** [comment]
The easiest way is probably to configure the `vimrc` in your VM to load this plugin:
`Plugin equalsraf/neovim-gui-shim`

That will give you the neovim-qt runtime without having to manually load the script.

You could also manually load the script by sourcing it in your `vimrc`, or at the command line with:
`nvim --listen 172.16.145.128:7778 --headless --cmd "let &rtp.='{RUNTIME_PATH}'"`

Replace `{RUNTIME_PATH}` with your specific runtime path found in `--version`. You could symlink or copy the files from your host. An install of `neovim-qt` on the VM would work too.

On your host, the runtime path is:
`/Users/user/neovim-qt/build/bin/nvim-qt.app/Contents/MacOS/../Resources/runtime`

> Ideally, I'd like to get rid of the VM and run nvim in a docker container and connect to it from nvim-qt.

I'm not very familiar with Docker, but this should be possible. Neovim is hosting a simple TCP/IP socket, so it should be the same as any other web server in Docker.

**Comment by f-squirrel** [comment]
@jgehrig ,
It works like a charm! Thank you so much!
Together with `call GuiClipboard()`it works really smoothly!
