### ISSUE TITLE
neovim-qt does not show vim-airline fonts properly when connected to a remote nvim

### ISSUE THREAD

**Issue by f-squirrel** [equalsraf/neovim-qt#686]
I have Ubuntu 18.04 where I run `nvim` as a server: `nvim --listen <ip>:<port> --headless`.
And MacOS Catalina where I run `neovim-qt` as a client: `nvim-qt --server <IP>:<port>`.

The top and bottom lines are presented incorrectly:
![Screen Shot 2020-04-27 at 19 25 05](https://user-images.githubusercontent.com/1248133/80396731-c09e0780-88bd-11ea-907a-7a995153a35e.png)

However, when I run `neovim-qt` locally they are fine.
Ubuntu:
<img width="567" alt="Screen Shot 2020-04-27 at 19 24 12" src="https://user-images.githubusercontent.com/1248133/80396734-c1cf3480-88bd-11ea-8b26-38266f2ce214.png">

MacOS:
![Screen Shot 2020-04-27 at 19 22 19](https://user-images.githubusercontent.com/1248133/80396695-b0862800-88bd-11ea-95ca-62327cd51eab.png)

Both machines have the same `.vimrc` and `ginit.vim`:
```
"I want to see buffers on top of the screen
GuiTabline 0

"This is a good feature but unfortunately it is not good for the YCM
"Need to check from time to time if it works
GuiPopupmenu 0

Guifont Source Code Pro for Powerline:h16
colorscheme monokai

"Allows yanking to the local clipboard(even from remote!)
call GuiClipboard()
```
I went through `help: nvim-gui-shim` but did not find a command fixing the problem.

Could you please advise?

**Comment by jgehrig** [comment]
What is the output of `:GuiFont`?

It probably displays something other than `Source Code Pro for Powerline:h16`.

You need to escape the spaces, same as `guifont`:

`Guifont Source\ Code\ Pro\ for\ Powerline:h16`

**Comment by jgehrig** [comment]
Would you like to expand the documentation to include a note about this, and an example?

I have seen this before, and I think it would be useful to other users :)

https://github.com/equalsraf/neovim-qt/blob/9c21aef8dbe66298fc833c9615f9e844ffb3090e/src/gui/runtime/doc/nvim_gui_shim.txt#L20-L48

**Comment by f-squirrel** [comment]
@jgehrig ,
Actually, `:GuiFont` returns the font defined in `ginit.vim`.
Nevertheless, I've added the escape symbols but it did not help.

**Comment by jgehrig** [comment]
Sorry, I think I was confused as to what the issue was... What exactly is the problem?

Is this an issue with the coloring of the arrow-like vim-airline characters?

Notice the highlighted characters are white, not yellow:
![image](https://user-images.githubusercontent.com/11207308/80503900-7dd14380-8940-11ea-82b4-a85bbeb94931.png)

**Comment by f-squirrel** [comment]
@jgehrig , the problem is that the highlighted characters are rendered differently when `neovim-qt` running at MacOS is connected to `nvim` running at Ubuntu and when `neovim-qt` is connected to a local `nvim`(for both MacOS and Ubuntu).

**Comment by akiyosi** [comment]
Perhaps it's because the termguicolors configuration for the remote nvim isn't working.
I had a similar problem with goneovim because I didn't set termguicolors at startup (See https://github.com/akiyosi/goneovim/issues/79#issuecomment-611001053).

**Comment by f-squirrel** [comment]
@akiyosi , adding `set termguicolors` to `init.vim` did solve the problem!
Thank you very much!
