### ISSUE TITLE
Can not paste in command mode input window on mac

### ISSUE THREAD

**Issue by ray-x** [equalsraf/neovim-qt#699]
neovim-qt latest version (6e30998)
MacOS 10.15.4 (19E287)
`<CMD>+V`  will insert V
`<CTL>+V`  insert ^
`<Shift+Insert>` does nothing
Only mouse middle key can paste.

**Comment by khalidchawtany** [comment]
Put this in ginit.vim
```cnoremap <D-V> <c-r>+```

However, when searching using / or ? this does not work. I don't know why?
Instead the some characters (```<80><fc><80>v```) are printed

![Screen Shot 2020-05-30 at 2 03 40 PM](https://user-images.githubusercontent.com/1681606/83326650-66a6ae00-a27e-11ea-8855-d38ddce44aca.png)

**Comment by jgehrig** [comment]
What is the output of `:checkhealth'?

Has paste worked before?

What happens when you type `"+gP`?

What do you mean by "command line window"? Specific steps would be helpful.

**Comment by ray-x** [comment]
Thanks for looking into this.
:checkhealth
All check passed with `OK` except python2. Full logs as below at the end of message.

Paste works fine in other neovim client (neovim console mode from iterm, and vimr, macvim with same configure) with < cmd - v >.  But I do not remember it succeed in neovim-qt before. 

What happens when you type "+gP?
I do not think `"+gP` works same way in command mode. 
Also,  I can paste with `<C-r> a` from vim register in command mode. But I can not paste from MacOS clipboard. While in insert mode I can use < C - v > to paste from other applications (e.g. from Chrome)

'command line window' 
I should say `Command Mode` instead
For example, to do a global find and replace type :%s/foo/bar/g.   I would like to use paste to replace foo with string in my clipboard, but I can only use middle mouse button to do that. Both < C - v > < cmd - V > not woking.  `<C-r> *` works

```
health#defx#check
========================================================================
## defx.nvim
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful

health#floaterm#check
========================================================================
  - OK: Terminal feature is OK
  - OK: Floating window feature is OK
  - OK: nvr is OK

health#coc#check
========================================================================
  - OK: Environment check passed

  - OK: Javascript bundle build/index.js found
  - OK: Service started

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy


## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Other python executable: /usr/bin/python3
  - INFO: Python version: 3.7.7
  - INFO: pynvim version: 0.4.1
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v14.3.0
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

```

**Comment by jgehrig** [comment]
The checkhealth output looks good, we were looking for:
```
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy
```

+1 to @khalidchawtany's comment above. That is the map you want.

`<C-V>` is not a standard vim mapping, so neovim-qt does not map it by default.

You should be able to paste from a register with `<C-r>` followed by `+`. If this does not work, we will need to debug further.

**Comment by jgehrig** [comment]
For example, here is a set of steps that works on my system:

1. Copy `echo "Hello World"` outside of neovim.
2. Open neovim-qt, `nvim-qt -- -u NONE`
3. Add the <S-Insert> map, `:cmap <S-Insert> <C-R>+`
4. Go into Command Mode, type `:`
5. Press Shift + Insert
6. Notice the content was pasted, `:echo "Hello World"`

You can use any key combination in place of `<S-Insert>`. For example, Ctrl +V is `<C-v>` on my Linux machine.

Ctrl+V has a default meaning in vim that is not paste. Not to worry though, it safe to override as paste.

**Comment by ray-x** [comment]
I tested and it works with `:cmap <C-V> <C-R>*`
`<S-Insert>` does not work for me. 
I tried both
 `:cmap <S-Insert>  <C-R>*` and  `:cmap <S-Insert> <C-R>+`

**Comment by jgehrig** [comment]
What did you test? Did you try `-- -u NONE`?

If you can map `<C-V>` but not `<S-Insert>`, it sounds like you have a `vimrc` configuration issue...

You can try a non-recursive mapping, `cnoremp`.

**Comment by ray-x** [comment]
From my experiment. Even with `-- -u NONE` option still not works for me for `<CMD-V>` and `<S-Ins>`. Seems macbook handle key differently.   Macbook do not have Ins, I am using a HP keyboard. So I am not sure if it is the ext-keyboard case this defect.
`:cmap <C-V> <C-R>+ ` : this works for me.

neovim does support <M or <D key for `CMD` on mac. But It seems neovim-qt handle this slight differently as khalidchawtany  mentioned.

**Comment by jgehrig** [comment]
Sorry for the confusion, I did not fully understand.

You are correct, MacOS + Qt does not support the `Insert` key.

**Comment by ray-x** [comment]
In that case, I think the issue can be close.
Thanks for the suggestions, I think I have work around for this now.
