### ISSUE TITLE
Control-Windows key combination inserts a quote character

### ISSUE THREAD

**Issue by ryanisaacg** [equalsraf/neovim-qt#700]
**Operating System:** Windows

**Version:** I'm not sure what version of nvim-qt I'm on, but it's whatever came with nvim 0.4.3 on the nvim downloads page.

Whenever I press the key combination Control-Windows nvim-qt types a quote character ("). In Insert mode, this adds a quote character next to the cursor, in command mode it adds a quote character to the command, etc.

(Importantly, this only occurs when hitting Control-Windows not Windows-Control.)

**Comment by jgehrig** [comment]
I cannot reproduce the issue in the latest version of neovim-qt.

> whatever came with nvim 0.4.3

That version is old enough that it does not have some some important input improvements. The input layer has been overhauled to resolve issues like this and make fixing/testing these issues easier.

I think an upgrade will resolve your issues... If you still have issues after an upgrade, let me know and I will help diagnose the issue.

Thanks for the bug report!

**Comment by ryanisaacg** [comment]
Should I build from source, or are there binary versions I should upgrade to?

**Comment by jgehrig** [comment]
Here is a Windows build from `master`:
https://ci.appveyor.com/api/buildjobs/jy0bifl6uyrflhio/artifacts/neovim-qt.zip

It is a build artifact from the automation system on the most recent change.

If the issue still reproduces, we will need to build from source. I haven't gotten around to #683, providing the required input debugging information without building from source.

**Comment by ryanisaacg** [comment]
The master build fixed it! Thanks so much. I really appreciate all the work that goes into neovim-qt!
