### ISSUE TITLE
Generate Release 0.2.16

### ISSUE THREAD

**Issue by jgehrig** [equalsraf/neovim-qt#701]
@equalsraf

Any thoughts on a 0.2.16 release?

The last release was October and there have been some good fixes/improvements since. The current master seems stable and I am not aware of any issues.

There are also a few outstanding Pull Requests:
#682
#689
#694
#695
#697

I don't have any strong opinions on including/excluding any of the above in a release.

Adding `guifontwide` to the release (#690) would be nice, but soak time after merge would be wise. Lots of font-related code was refactored. This seems like a high value (and occasionally requested) feature.

Removing the XOR cursor entirely (#695) should be done after the release.

**Comment by Shatur95** [comment]
I see that you made a lot of contributions, but seems that @equalsraf do not have a time for now :( So, it would be nice to let you rights.

**Comment by Shatur95** [comment]
I see that you made a lot of contributions, but seems that @equalsraf do not have a time for now. It would be nice to add more rights to most active contributors.

**Comment by equalsraf** [comment]
Hi, @jgehrig 

I have merged all PRs, minus the guifontwide and the cursor (actually accidentally merged and reverted that :S ).

The usual TODO list for a release:

- Bump version in CMakeLists.txt - i believe this will be the first release where --version and version.h.in are in use with the 9999 version tweak - so we need a release commit with tweak=0 and later a followup to 9999
- tag v0.2.16 (**git tag -a** with release notes, e.g. see **git show v0.2.14**)
- windows builds are generated by appveyor (https://github.com/equalsraf/neovim-qt/releases) automatically for the new tag
- bump version in https://github.com/equalsraf/homebrew-neovim-qt/blob/master/neovim-qt.rb#L4

Here is a quick draft for the notes:

```
v0.2.16

Features:

- CLI now respects the --version option
- Enable ext_linegrid by default
- Support arbitrary font weight
- guifont=* a modal dialog to select fonts
- initial GUI scrollbar support

Fixes

- Many, many, many keyboard input fixes
- Multiple fixes for highlight attributes and rendering issues
- Fix attribute scroll speed
- Fix GuiFont! for bad monospace fonts
- Fix empty gui tree view
```

Let me know if i'm missing something that needs a call out.

**Comment by equalsraf** [comment]
PR for new release https://github.com/equalsraf/neovim-qt/pull/704

> I see that you made a lot of contributions, but seems that @equalsraf do not have a time for now. It would be nice to add more rights to most active contributors.

I agree, more so since @jgehrig has been the most active contributor for the last year.

**Comment by equalsraf** [comment]
@jgehrig should we attempt to sneak in https://github.com/equalsraf/neovim-qt/pull/702/files as well. Otherwise mode changes would not work with guicursor, right?

**Comment by jgehrig** [comment]
No need to merge that, I would do it after the release. The current code works fine, it is just convoluted. I removed the extra list I accidentally added before calling the lower layers.

It is a subtle class of uniform initialization bug I missed:
```
std::vector<int> foo{ 3 }; // Vector containing [ 3 ], calls initializer list CTOR
std::vector<int> bar( 3 ); // Vector containing [ 0, 0, 0 ], 3 is CTOR size/count parameter
```

There is ambiguity in the CTOR call because `QVariantList` is also a `QVariant`. The C++ standard defaults to list initialization in ambiguous cases.

**Comment by jgehrig** [comment]
> I agree, more so since @jgehrig has been the most active contributor for the last year.

Thanks for the confidence!

I look forward to making more fixes and improvements in `neovim-qt` :smiley:

**Comment by equalsraf** [comment]
The tag is up,

- it will probably take a bit for it to show up in the releases tab with the windows build https://github.com/equalsraf/neovim-qt/issues/701
- homebrew recipe bump in https://github.com/equalsraf/homebrew-neovim-qt/pull/1

**Comment by equalsraf** [comment]
Alright, I think we are all done here, closing this.
