### ISSUE TITLE
Tracking for Release 0.2.16.1

### ISSUE THREAD

**Issue by jgehrig** [equalsraf/neovim-qt#714]
Tracking for any changes that should be included in a `neovim-qt-0.2.16-r1` release.

**Work Item List:**
1. Bump version argument to `0.2.16.1`
2. The `--help` argument should work when no display is set. #707 #709 

We could still do this release from `master`, but that would also include XOR cursor removal #640.

**Comment by equalsraf** [comment]
We might have to do a patch branch for this i.e. cherry pick the fix into a separate branch (created from v0.2.16) and release out of that.

**Comment by jgehrig** [comment]
Agreed.

I don't think there is immediate urgency on the `--help` issue since most Qt GUI applications crash given the same scenario.

I think we should and see if any new issues are reported from users neovim nightly users. The `0.2.16` build was included for Windows users as of yesterday.

**Comment by equalsraf** [comment]
I've added a patch branch https://github.com/equalsraf/neovim-qt/tree/patch-v0.2.16, cherry picked the fix into it and created a commit for a new release. Tagging that commit should be enough.
