### ISSUE TITLE
Feature Request: Add QTouchEvent Scrolling to ShellWidget

### ISSUE THREAD

**Issue by snairolf** [equalsraf/neovim-qt#722]
I'd expect the scrolling to work when swiping up down. Instead it selects the text, i.e. is treated as a touch+hold+swipe.

**Comment by jgehrig** [comment]
Yes, this could definitely be handled better... However, it is not high on my priority list right now.

I think `ShellWidget` would need to be configured to emit the proper events, `Qt::WA_AcceptTouchEvents` or `acceptTouchEvents`. Once the events are distinguishable from regular mouse events, you would have to handle the touch-specific events inside `Shell::neovimMouseEvent` from `Shell.cpp`.

Qt Documentation: https://doc.qt.io/qt-5/qtouchevent.html

If you'd like to try fixing this issue, I would be happy to review your code. Pull Requests are always welcomed :)

**Comment by jgehrig** [comment]
This looks like a duplicate of #229.

Marking this issue as closed in favor of tracking via the original issue.
