### ISSUE TITLE
nvim-qt always throw "Press Enter or type command to continue" when press X

### ISSUE THREAD

**Issue by wsdjeg** [equalsraf/neovim-qt#726]
My neovim version is :

```


NVIM v0.5.0-577-g48ac77a14
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

![float_preview](https://user-images.githubusercontent.com/13142418/87874096-a1fd6780-c9f9-11ea-8453-d32d0bfc20c8.gif)
![float_preview](https://user-images.githubusercontent.com/13142418/87874101-b3df0a80-c9f9-11ea-99a1-6c318a774cf7.gif)

NOTE: there is no unwrite buffer.

**Comment by wsdjeg** [comment]
I want to know what happened when press `X`. which autocmd is running?

**Comment by jgehrig** [comment]
This looks like an issue specific to your configuration.

1. Does the issue reproduce in `nvim` launched from the terminal? Is the issue limited to `neovim-qt`?
2. What version of neovim-qt are you running? Where did it come from? `nvim-qt --version`
3. Your configuration looks non-trivial configuration. You should  systematically disabling parts until the issue is isolated.

Without more information, it is difficult to say what is going wrong...

**Comment by jgehrig** [comment]
> I want to know what happened when press X. which autocmd is running?

We don't bind anything to `X`.

Here is the vim runtime code we use:
https://github.com/equalsraf/neovim-qt/blob/master/src/gui/runtime/plugin/nvim_gui_shim.vim

**Comment by wsdjeg** [comment]
I have debug it out, it is spacevim typescript layer, when enable this layer, I get this issue. but in this layer, only following plugin is used.

```
  call add(plugins, ['leafgarland/typescript-vim'])
  call add(plugins, ['heavenshell/vim-jsdoc', { 'on_cmd': 'JsDoc' }])
  if !SpaceVim#layers#lsp#check_filetype('typescript')
    if has('nvim')
      call add(plugins, ['mhartington/nvim-typescript', {'build': './install.sh'}])
    else
      call add(plugins, ['Quramy/tsuquyomi', {'merged' : 0}])
    endif
  endif
```

**Comment by wsdjeg** [comment]
It is because this line `autocmd VimLeavePre * TSStop`, but `TSStop` has not been difinded! I just search `unknown funtion` key workd in `mhartington/nvim-typescript` repo, too many issue about this, all of them can be fixed by run install script. but I think all this error should be handle without print error message.

cc @mhartington

**Comment by mhartington** [comment]
This is typical of remote plugins. Remote plugins to have `UpdateRemotePlugins` run in order to make sure command or functions that are remote are registered. 

I'd think this would need to be changed in neovim core, correct?
