### ISSUE TITLE
Warning: Font "Consolas" reports bad fixed pitch metrics

### ISSUE THREAD

**Issue by zrsharp** [equalsraf/neovim-qt#732]
- Platform: windows 10
- version:：nvim 0.5.0

It is downloaded from neovim/neovim release, the version is 0.5.0.

When I set guifont=Consolas:h15 or exec GuiFont Consolas:h15, an warning occur: 
**Warining: Font "Consolas" reports bad fixed pitch metrics.**

After switching to other fonts, the problem still exists.

**Comment by jgehrig** [comment]
You can suppress these warnings with `:GuiFont! Consolas:h15`.

See `:help GuiFont`:
```
It warns and fails when an invalid font has specified.
Use a |bang| (!) to forcedly assign an invalid font like:
	:GuiFont! <An invalid font>
```

This message indicates Consolas has some non-monospace features/characteristics.

**Comment by nkta3m** [comment]
neovim 0.82
Windows 10
i set GuiFont! JetBrainsMono\ NF:h12 in ginit.vim
but it shows the same error
Warning: Font "JetBrainsMono NF" reports bad fixed pitch metrics

**Comment by nullptr-deref** [comment]
@nkta3m do you use nvim-qt or launch nvim executable in some terminal?

**Comment by nkta3m** [comment]
alacritty

**Comment by nkta3m** [comment]
I use set guifont=xxx in init.vim replace Guifont! Xxx in ginit.vim now, it is working.

**Comment by nullptr-deref** [comment]
Didn't catch: you use both `set guifont=<fontfamily>` and `GuiFont! <fontfamily>` simultaneously or exchanged the first one to the second one?

**Comment by nkta3m** [comment]
i use set guifont=<fontfamily>

**Comment by nullptr-deref** [comment]
Hmm, actually it's kind of a tricky thing. I still cannot determine tendency when this problem appears.
Nevertheless, it's nice that you've dealt with your problem.

**Comment by pvonmoradi** [comment]
Getting the same error with [Inconsolata](https://github.com/googlefonts/Inconsolata) (tried both OTF and TTF)

```console
$ nvim-qt --version
NVIM-QT v0.2.16.0
Build type: Release
Compilation:-g -O2 -fdebug-prefix-map=/build/neovim-qt-tKBgNt/neovim-qt-0.2.16=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wno-unused-parameter -std=c++11 -Wfatal-errors
Qt Version: 5.12.5
Environment:
  nvim: nvim
  args: --cmd let &rtp.=',/usr/share/nvim-qt/runtime' --cmd set termguicolors
  runtime: /usr/share/nvim-qt/runtime

NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
