### ISSUE TITLE
Color emoji

### ISSUE THREAD

**Issue by nu8** [equalsraf/neovim-qt#733]
With regular Vim:

https://github.com/vim/vim-win32-installer/releases

I can `set renderoptions=type:directx`, and it will produce color emoji:

>![Untitled](https://user-images.githubusercontent.com/61808913/90966346-1e6ee480-e497-11ea-8358-fc8391622869.png)

is this possible with Neovim?

**Comment by jgehrig** [comment]
Yes, this should be supported, but you may find rendering issues.

Your font must support color emojis. My default font `Liberation Mono` does not render emojis in color.
![image](https://user-images.githubusercontent.com/11207308/91664329-753e7480-eabc-11ea-9ce9-1bbd76130d23.png)

With the latest `master` you can provide a `guifontwide` list. This will change the wide-character font.

Here is the same text rendered with `set guifontwide=Noto\ Color\ Emoji:h14`:
![image](https://user-images.githubusercontent.com/11207308/91664370-dbc39280-eabc-11ea-9cc3-55e3066e0983.png)

I don't think either feature is widely used. Please let me know if you see any rendering issues :)

**Comment by nu8** [comment]
With this file:

~~~
C:\Users\Steven\AppData\Local\nvim\init.vim
~~~

As:

~~~
set guifontwide=Segoe\ UI\ Emoji:h14:
~~~

doesnt seem to make any difference. Note I am using this file:

https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip

which has date of 2020-08-30.

**Comment by jgehrig** [comment]
> https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip

That is a nightly neovim release, but it does not contain all of the changes in `master` for neovim-qt.

You should be able to confirm this with `nvim-qt --version`, which I'm guessing will show `v0.2.16.1`.

Here is a download link for the latest neovim-qt commit (available a few months):
https://ci.appveyor.com/project/equalsraf/neovim-qt/build/job/g4lbd7a2kw3jd0td/artifacts

You can find these Windows builds clicking the AppVeyor details for any recent commit.

**Comment by nu8** [comment]
Ok tried again with NVIM-QT v0.2.17.9999 (and previous `init.vim`), still seems
to be black and white.

**Comment by jgehrig** [comment]
It works for me on Windows 10 with or without `guifontwide`.

My default font is `Consolas:h11`, and I can set a secondary font to `Segoe\ UI\ Emoji:h14`.

![image](https://user-images.githubusercontent.com/11207308/91669939-f4e13900-eae6-11ea-8f68-97bf5665b3d5.png)

It do see a cursor rendering issue with `guicursor` and some wide characters:
![image](https://user-images.githubusercontent.com/11207308/91669990-61f4ce80-eae7-11ea-8870-784a33ddffdd.png)

**Comment by jgehrig** [comment]
This is an issue with Qt. You need a more recent version for color emoji support.

I tested with my usual development machine (Qt 5.13.0), where color emojis works. The binary above uses Qt 5.11.3, were emoji are rendered in monotone.

Let me see if I can quickly bump our AppVeyor builds to Qt 5.13...

**Comment by nu8** [comment]
https://github.com/equalsraf/neovim-qt/issues/735

**Comment by jgehrig** [comment]
Here is a Qt 5.15 build:
https://ci.appveyor.com/api/buildjobs/8qekg75h9y15o8cs/artifacts/neovim-qt.zip

**Comment by nu8** [comment]
Ok yes, using the Qt 5.15 fixes it, color is now shown.

I will note that the overlapping issue is still present, but thats to be
expected.

Also should note that Qt 5.15 requires Microsoft Visual C++ 2015:

https://support.microsoft.com/help/2977003

not sure if thats because of some different build flags, but should be mentioned
somewhere.

**Comment by jgehrig** [comment]
> Ok yes, using the Qt 5.15 fixes it, color is now shown.

Excellent, marking the bug as closed.

> Also should note that Qt 5.15 requires Microsoft Visual C++ 2015:
https://support.microsoft.com/help/2977003

Just to be clear, the "Microsoft Visual C++ Redistributable for Visual Studio 2019".

Yes, that is likely because the new link was built with Visual Studio 2019 and MSVC. I think the other build was MinGW and GCC (not working yet, windeployqt issues). Artifacts for both are provided

I will make sure to double-check this, thanks.
