### ISSUE TITLE
[Question] Is it possible to open file from terminal to an existing nvim-qt?

### ISSUE THREAD

**Issue by chocopowwwa** [equalsraf/neovim-qt#734]
Hi, Is it possible to open file from terminal to an existing nvim-qt window?
At first, I thought the --server would do the job but it isn't, it doesn't support file args

The behavior that I'm looking for is like `gvim --remote <file_name>`

Thanks

**Comment by jgehrig** [comment]
The architecture of Neovim is slightly different from Vim. The feature exists, but is different.

Neovim always operates with a separate frontend GUI and backend editor. Whenever you call `nvim-qt`, a corresponding `nvim` server process starts. This is true for all frontends, even the terminal UI.

You may find this project useful:
https://github.com/mhinz/neovim-remote

Here is a basic example:
```
export NVIM_LISTEN_ADDRESS=127.0.0.1:1234
nvim --headless &
nvim-qt --server $NVIM_LISTEN_ADDRESS
nvr File1.txt
```

This also works with an already spawned `nvim-qt`:
1. Open `nvim-qt`
2. Run Neovim command `:echo v:servername`
3. Adds File1.txt to the instance spawned above in Step 1:
`nvr --servername {output from Step 2} File1.txt File2.txt`

There is some basic information about `--server` on the [Wiki](https://github.com/equalsraf/neovim-qt/wiki).

The feature is commonly used to run `nvim` within a Virtual Machine and an instance of `nvim-qt` on the host machine. There should be some examples from other users in the Issue tracker.

If the `:Gui...` commands are missing, you may need to install `Plugin 'equalsraf/neovim-gui-shim'`

**Comment by jgehrig** [comment]
Marking as closed.

**Comment by Shatur95** [comment]
```
export NVIM_LISTEN_ADDRESS=127.0.0.1:1234
nvim --headless &
nvim-qt --server $NVIM_LISTEN_ADDRESS
nvr File1.txt
```

But after last step neovim instance will not be active. I mean, if it is minimized it, it will remain minimized. Usually, text editors, when opening a new file with an instance already running, make it active. Is it possible to make Neovim Qt active on the last action?

**Comment by jgehrig** [comment]
I filed a new bug to track your request, I will try to investigate...

**Comment by Shatur95** [comment]
Thank you!
