### ISSUE TITLE
ginit.vim not sourced.

### ISSUE THREAD

**Issue by lucc** [equalsraf/neovim-qt#74]
When I start neovim-qt my ginit.vim file in ~/.config/nvim is not sourced. I can source it manually with `runtime ginit.vim` so rtp should be ok.

nvim: 0.1.1
nvim-qt: 85dd35b

**Comment by equalsraf** [comment]
Will have a look, I see the references in the Neovim docs, but AFAIK ginit.vim is not implemented in neovim - the original issue is still open neovim/neovim#3656

**Comment by equalsraf** [comment]
Closing this, ginit.vim is now sourced when nvim-qt attaches to Neovim. You should be able to use the commands from the shim plugin to set the font, etc.
