### ISSUE TITLE
concat lines with shift+J causes line invisible

### ISSUE THREAD

**Issue by aj3423** [equalsraf/neovim-qt#743]
To reproduce:
1. create 100 lines of text 'a':
   type 'a' -> yy -> 100p
2. visual select all lines: 
    gg ->  v -> G
3. concat into one line:
    Shift + J

Result:  The line is concated but looks transparent, it's actually there but invisible.

Note: It seems only happens when the length of the concated line is longer than the window width, if 100 lines works normally, try 500 lines, it will happen.
![vim](https://user-images.githubusercontent.com/4710875/93176589-1176a580-f764-11ea-8e93-301c55146476.gif)

**Comment by jgehrig** [comment]
@aj3423 Thanks for the bug report!

I'm stumped... From a quick inspection of the RPC commands, we are painting as instructed by `nvim`. 

On the surface, it looks like a neovim bug. However, I cannot reproduce in `nvim` or other clients. I will need to investigate further.

**NOTES:**
This reproduced with and without `ext_linegrid`.
This reproduces with `nvim-qt -- -u NONE`.
This issue does not reproduce in `nvim`, or other GUI clients (so far).

**Comment by equalsraf** [comment]
Interesting:

- removing the line and then doing an undo does render the line properly
- doing a `redraw!` has no effect, but resizing the window does cause the line to be rendered
- doing and `undo` after the join and then a `redo` renders the line
- there is a slight odity when the issue happens  - the tilde marker on the left side is present in the first line - maybe a scroll operation gone wrong with the text being rendered outside the intended area?

To add more confusion, on a couple of instances i was not able to reproduce the problem.

I was able to reproduce in nvim, but not using -u NONE, so it seems I am missing something here.
My current testing config is

```
silent! call plug#begin('~/.local/share/nvim/plugged')
Plug '~/Code/neovim-qt/src/gui/runtime'
call plug#end()
```
For context, I manually load the shim for remote execution.
So maybe the shim is the cause of this issue.

I reduced the shim to this 

```vim
" Notify Gui of any cursor movement, used by GuiScrollBar
function s:GuiCursorMoved()
	let l:minLineVisible = line('w0')
	let l:bufferSize = line('$')
	let l:windowHeight = winheight(winnr())
	call rpcnotify(0, 'Gui', 'CursorMoved', l:minLineVisible, l:bufferSize, l:windowHeight)
endfunction

autocmd CursorMoved,CursorMovedI,VimResized * call <SID>GuiCursorMoved()
```

and the final reduction leaves this

```vim
" Notify Gui of any cursor movement, used by GuiScrollBar
function s:GuiCursorMoved()
	let l:minLineVisible = line('w0')
endfunction

autocmd CursorMoved,CursorMovedI,VimResized * call <SID>GuiCursorMoved()
```
Commenting that `minLineVisible` line fixes the issue for me, but it is not clear to me what is going on there, or why this would affect rendering.

**Comment by equalsraf** [comment]
Having a second look, after triggering the issue

- line('w0') is 74
- line('w$') is 1

**Comment by equalsraf** [comment]
Staring at nvim's move.c it seems like `line('w0')` -> `var2fpos()` -> `update_topline()` could trigger a redraw.
