### ISSUE TITLE
neovim-qt do not display neovim.svg in the title bar on Windows 10

### ISSUE THREAD

**Issue by VimIcewind** [equalsraf/neovim-qt#745]
I use neovim-qt on Windows 10,  neovim-qt do not display neovim.svg in the title bar. I have to change source code from neovim.svg back to neovim.png then rebuild neovim-qt.exe and the neovim-qt ico works.  I read the git log and I know that the neovim.svg is for High DPI displays, my solution is not a good way.

**Comment by VimIcewind** [comment]
I found the reason: there are no imageformats\qsvg.dll and imageformats\qsvgd.dll in Neovim\bin.  After I put them in the directory, it workes.

**Comment by jgehrig** [comment]
I'm glad to hear you figured this out! Thanks for the detective work.

Where did you install neovim-qt from? Perhaps we need to address this bundling issue somewhere...

**Comment by VimIcewind** [comment]
I install neovim-qt from https://github.com/neovim/neovim/releases/ and I hava wrote a issue https://github.com/neovim/neovim/issues/12928 for this.

**Comment by jgehrig** [comment]
Closing this bug. Tracking upstream in neovim.
