### ISSUE TITLE
CircleCI Coveralls Upload Fails

### ISSUE THREAD

**Issue by jgehrig** [equalsraf/neovim-qt#749]
I see CircleCI failures on all of my Pull Requests. The cause is a failure to upload the coverage report:
https://app.circleci.com/pipelines/github/equalsraf/neovim-qt/215/workflows/88698af7-9c0e-4dea-98a5-9429b6fd58cc/jobs/432

`{u'message': u"Couldn't find a repository matching this job.", u'error': True}`

@equalsraf

It looks like the issue doesn't occur for your PRs. I'm not very familiar with coveralls, but perhaps this is an authorization issue?

Not a big deal, but I figured I would call this out. Maybe there is an easy fix :)

**Comment by equalsraf** [comment]
It seems to be an issue with circle CI - https://github.com/lemurheavy/coveralls-public/issues/1018 - I already used the workaround described in the ticket but it looks like it does not work for your PR. Maybe it is time to switch providers.

**Comment by equalsraf** [comment]
Can you try rebasing something on top of master and see if codecov works?

**Comment by jgehrig** [comment]
Sure, I just created Pull Request #758.

**Comment by equalsraf** [comment]
Circle/Ci failed for the usual reason, but the codecov actually worked https://codecov.io/github/equalsraf/neovim-qt/commit/d7b609ccd517f1dce95c59698be69a2464c367b8

I guess it is time to remove coveralls.

**Comment by jgehrig** [comment]
Awesome! Thanks for taking a look at this :+1:

**Comment by equalsraf** [comment]
Merged, closing.
