### ISSUE TITLE
^K<< doesn’t work, ^K< puts <S-lt>

### ISSUE THREAD

**Issue by unclechu** [equalsraf/neovim-qt#755]
When I’m trying to put `«` symbol by typing `<C-k>` and then `<<` I get `<S-lt><` plain text because just `<C-k><` already resolves to `<S-lt>`.

Version (on NixOS 20.09):
```
λ nix repl <<<'(import <nixpkgs> {}).neovim-qt.version'
Welcome to Nix version 2.3.7. Type :? for help.

"0.2.15"

```

**Comment by unclechu** [comment]
This is actually fixed in `0.2.16.1`, it just didn’t update for quite a while in the NixOS nixpkgs repo.
See https://github.com/NixOS/nixpkgs/pull/98605

**Comment by jgehrig** [comment]
Thank you for the bug report, this is helpful for other users having the same issues. :+1: 

Related: #134, #607, #608, #222, #612

**Comment by unclechu** [comment]
In case someone would come here by “nix” or “nixos” keyword here how I overridden the version to the latest one for myself (until https://github.com/NixOS/nixpkgs/pull/98605 is getting merged):
https://github.com/unclechu/nixos-config/commit/4f3bf5540dc8384c9431f77e8bd4bcb8c579b861
