### ISSUE TITLE
NVR should activate the MainWindow

### ISSUE THREAD

**Issue by jgehrig** [equalsraf/neovim-qt#757]
From Issue #734.

@Shatur95 Wrote:

```
export NVIM_LISTEN_ADDRESS=127.0.0.1:1234
nvim --headless &
nvim-qt --server $NVIM_LISTEN_ADDRESS
nvr File1.txt
```

But after last step neovim instance will not be active. I mean, if it is minimized it, it will remain minimized. Usually, text editors, when opening a new file with an instance already running, make it active. Is it possible to make Neovim Qt active on the last action?

**Comment by equalsraf** [comment]
Sounds like you want to issue a call to `call GuiForeground()` as part of your command.

I'm not familiar with nvr, so there might be a better way, this looks like a start.

```
nvr --servername /tmp/nvim5ANTQk/0 -c 'call GuiForeground()' /tmp/test.txt
```

**Comment by Shatur95** [comment]
I tried id, no effect :(

**Comment by equalsraf** [comment]
Strange. This kind of behaviour depends a bit on the window manager, so we may have to try a couple of things. Which window manager are you using?

What about `call GuiWindowMaximized(1)`?

**Comment by Shatur95** [comment]
> Strange. This kind of behaviour depends a bit on the window manager, so we may have to try a couple of things. Which window manager are you using?

KWin on KDE Plasma. I have another application in Qt that shows correctly. [Here](https://github.com/crow-translate/crow-translate/blob/b378e5dcc7f12d9208568b2f2e1ae39766d71380/src/mainwindow.cpp#L242) is the code.

> What about call GuiWindowMaximized(1)?

Still no effect :(

**Comment by equalsraf** [comment]
Strange, are we failing to do it properly here? https://github.com/equalsraf/neovim-qt/blob/e5841d267229c9066861f453dafda50ebfaeac19/src/gui/shell.cpp#L753

My system is a bit hard to test this, I cant raise the window in my window manager, but I do get a window alert notification.

**Comment by equalsraf** [comment]
Maybe this change helps, https://github.com/equalsraf/neovim-qt/commit/48c490bafbb4a5db51f625a58219bd6119f71942 but in my case i see no difference. Can you build that change and let us know?

**Comment by Shatur95** [comment]
Thanks, I tried, but still not works. Maybe try the following?

```cpp
    setWindowState(windowState() & ~Qt::WindowMinimized);
    show();
    activateWindow();
```

This will always make window active.
