### ISSUE TITLE
Need way to set custom WM_CLASS on startup

### ISSUE THREAD

**Issue by cvincent** [equalsraf/neovim-qt#760]
Currently there doesn't appear to be a way to assign a custom WM_CLASS on startup. This is useful for doing interesting things with window managers, such as setting up specific layouts automatically. With terminal NeoVim, I could do this using my terminal emulator, Kitty:

```
kitty --name dotfiles --title dotfiles bash -c "cd ~/dotfiles && nvim -S Session.vim"
```

Unfortunately there does not appear to be a way to do this with `nvim-qt`.

**Comment by equalsraf** [comment]
Does `nvim-qt --name thewmclassyouwant` work?

Based on [this](https://bugreports.qt.io/browse/QTBUG-29396?focusedCommentId=208874&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel) this should be available in qt 5.1.

**Comment by jgehrig** [comment]
For me, `--name` is an unrecognized argument:
``` bash
$ nvim-qt --name FooBar
nvim-qt: Unknown option 'name'.
```

From latest master and  built with Qt 5.15.0.

**Comment by equalsraf** [comment]
```
$ nvim-qt --name birubirubiru
```

Then used xprop to get the wm class

```
$ xprop
XdndAware(ATOM) = BITMAP
WM_NAME(STRING) = "[No Name] - NVIM"
_NET_WM_NAME(UTF8_STRING) = "[No Name] - NVIM — Neovim"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x3e, 0x7e, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_XEMBED_INFO(_XEMBED_INFO) = 0x0, 0x1
WM_CLIENT_LEADER(WINDOW): window id # 0x2600008
WM_HINTS(WM_HINTS):
                Client accepts input or input focus: True
                window id # of group leader: 0x2600008

_NET_WM_PID(CARDINAL) = 32017
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 39845895
WM_CLASS(STRING) = "birubirubiru", "nvim-qt"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_NORMAL_HINTS(WM_SIZE_HINTS):
                user specified location: 0, 32
                user specified size: 1920 by 1011
                program specified minimum size: 197 by 90
                window gravity: Static
```

nothing fancy here, 

```
$ nvim-qt --version
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-raf'
NVIM-QT v0.2.16.0
(...)
```

But testing from master does not work

```
$ bin/nvim-qt --name whereismyclass
nvim-qt: Unknown option 'name'.
```

**Comment by jgehrig** [comment]
Could the behavior difference be caused by Qt?

Are both `nvim-qt` executables built with the same version of Qt?

**Comment by equalsraf** [comment]
Yes, both running in my Linux laptop and are linked against the same library 5.15.1
