### ISSUE TITLE
Feature Request: Animated cursor movements

### ISSUE THREAD

**Issue by aj3423** [equalsraf/neovim-qt#770]
Hi, I switched to **neovim-qt** from **neovide**, I can't use **neovide** because it has font problem, I reported the bug half year ago but it's still there.

But it has a cool feature [animated-cursor](https://github.com/Kethku/neovide#animated-cursor). This is helpful when working with multiple split windows. I never lost cursor position when switch between windows.

Is it possible to implement this in **neovim-qt**?

Thanks.

**Comment by jgehrig** [comment]
Cool feature!

Unfortunately, I don't think I have the time to work on this feature. I have a handful of higher priority work I'd like to do (startup, argument parsing, ext_cmdline, input handling, ext_messages, etc).

If you'd like to work on implementing feature, I'm happy to guidance and code reviews. :)

**Comment by aj3423** [comment]
Got it, but I don't know much about QT or Rust. This is not a major problem anyway. Thanks for the great and stable **nvim-qt** :)

**Comment by Helguli** [comment]
@jgehrig 
I'm interested in implementing this feature.
