### ISSUE TITLE
Add --cmd command support

### ISSUE THREAD

**Issue by Mte90** [equalsraf/neovim-qt#774]
I am trying to pass a parameter to neovim.  
Vim/Nvim has this parameter `--cmd "let variable=1"` that you can use to pass a command but with nvim-qt I get: `nvim-qt: Unknown option 'cmd 'let variable'.`

I tried also `nvim-qt /var/www/ --cmd='let variable=1'` or `nvim-qt /var/www/ --cmd 'let variable=1'` but `nvim-qt: Unknown option 'cmd'.`.

**Comment by jgehrig** [comment]
Here is the command you're looking for:
`nvim-qt /var/www/ -- --cmd 'let variable=42'`

See `nvim-qt --help`:
```
Usage: nvim-qt [options] [file...] [-- ...]

Options:
  --nvim <nvim_path>           nvim executable path
  --timeout <ms>               Error if nvim does not responde after count
                               milliseconds
  --geometry <width>x<height>  Set initial window geometry
  --stylesheet <stylesheet>    Apply qss stylesheet from file
  --maximized                  Maximize the window on startup
  --no-ext-tabline             Disable the external GUI tabline
  --no-ext-popupmenu           Disable the external GUI popup menu
  --fullscreen                 Open the window in fullscreen on startup
  --embed                      Communicate with Neovim over stdin/out
  --server <addr>              Connect to existing Neovim instance
  --spawn                      Treat positional arguments as the nvim argv
  -v, --version                Displays version information.
  -h, --help                   Displays help on commandline options.
  --help-all                   Displays help including Qt specific options.
  --nofork                     Run in foreground

Arguments:
  file                         Edit specified file(s)
  ...                          Additional arguments are forwarded to Neovim           **<== SEE HERE**
```

You need to use `--` to forward arguments to Neovim. Confusing and strange I know, it is on my TODO list of things to address :)

**Related Issues:**
#172
#449

**Comment by Mte90** [comment]
Thanks, it wasn't clear `...` that is just arguments, I was thinking that was other files because with others parameter it wasn't working.

So `--` usage wasn't clear, at least for me.

Anyway thanks!

**Comment by jgehrig** [comment]
Agreed, I don't think this behavior is obvious. It is a non-standard useage of `--`.

If you have any suggestions as to how this can be improved, the code responsible for the help message is:
https://github.com/equalsraf/neovim-qt/blob/2c3c7c292bb6fc7701bda76343458ec0d1a9bbd4/src/gui/app.cpp#L152-L209

Perhaps this could be made more discoverable in the Wiki or README?

**Comment by Mte90** [comment]
Maybe it should be enough to change the message in help, because I looked there without any hints about it:
```
-- [command]                      Additional arguments are forwarded to Neovim, ex: `-- --cmd 'let variable=42'`
```

**Comment by jgehrig** [comment]
I like the idea.

Perhaps:
```
Usage: nvim-qt [options] [file...] [-- nvim_args ]
...
-- [nvim_args]                      Additional arguments are forwarded to Neovim: "nvim-qt -- -u NONE"
```

If you'd like to create a Pull Request, feel free. Otherwise I will try to get to this at some point in the next few days.

**Comment by Mte90** [comment]
You asked and I did the pr :-)
