### ISSUE TITLE
Unused Oxygen icon resources

### ISSUE THREAD

**Issue by alebastr** [equalsraf/neovim-qt#777]
Hi,

I was working on the package for Fedora and license checker script alerted me that there are several LGPLv3-licensed items in the source tree.
After a short investigation I found these Oxygen icons that are actually compiled into the nvim-qt binary but never used:
https://github.com/equalsraf/neovim-qt/blob/b813471ec04afb391c34921dd27fea5c169323e7/src/gui/data.qrc#L5-L7
It appears to be a leftover from early revisions of #349 and the code that displays the icons was never merged to master branch.

Is there a plan to use these icons? If no, would it make sense to remove them both from the resource file and from the source tree?

**Comment by jgehrig** [comment]
Good catch!

From the context, I would assume these icons were intended as `GuiPopupmenu` icons.

They are not used anywhere and there isn't an active plan to use them. I agree, they should be removed.

**Comment by jgehrig** [comment]
Merged.

The removed files and license changes should be available in the next release, v0.2.17.
