### ISSUE TITLE
When neovim gets stuck while initializing neovim-qt does not respond

### ISSUE THREAD

**Issue by RedX2501** [equalsraf/neovim-qt#78]
I am testing out my .vimrc with neovim.

First i transferred it to the new XDG_CONFIG_HOME location and renamed it.

Now when i tried to start neovim-qt it would just state that neovim was not responding.

After some fiddling in the command line i was able to start neovim and it printed:

```
Error detected while processing C:\Users\uidw8099\AppData\Roaming\nvim\init.vim:
line   90:
E484: Can't open file d:\Playground\neovim\Neovim\bin\syntax\syntax.vim
line  563:
E185: Cannot find color scheme 'zenburn'
Press ENTER or type command to continue
```

Well now it is clear why neovim-qt said it was stuck but there was no indication on neovim-qt's window.

Is there any way to forward this console information from neovim to the user?

**Comment by equalsraf** [comment]
Not much that can be done for this right now, its being fixed upstream (https://github.com/equalsraf/neovim-qt/issues/50#issuecomment-144577335,  neovim/neovim#3646)

**Comment by equalsraf** [comment]
ref https://github.com/neovim/neovim/issues/3901

**Comment by shlomif** [comment]
I'm just subscribing to this bug based on https://github.com/equalsraf/neovim-qt/issues/333 being closed as a dup of this one.

**Comment by equalsraf** [comment]
> I'm just subscribing to this bug based on #333 being closed as a dup of this one.

:D FYI there should be a subscribe button on the right sidebar.

**Comment by dumblob** [comment]
I've just reported a "subissue" of this one on https://github.com/neovim/neovim/issues/8038#issuecomment-367348125 . But it seems it's a more general issue and fits exactly here.

Any news on this?

**Comment by equalsraf** [comment]
Added a patch for this in https://github.com/equalsraf/neovim-qt/pull/463. The only way I found to handle this case was to insert a `<C-c>` in the input.
