### ISSUE TITLE
Signature/Documentation Popup in wrong position

### ISSUE THREAD

**Issue by matheusfillipe** [equalsraf/neovim-qt#780]
I am facing an annoying issue with neovim-qt. The popups for documentation (in my case with the coc plugin) appear behind the autocomplete list popup but attached to the left:

![image](https://user-images.githubusercontent.com/24435787/96507272-4d070280-122f-11eb-9e85-f9ba2475ae3a.png)

While from a shell  they work just fine in a nice position:

![image](https://user-images.githubusercontent.com/24435787/96507328-6314c300-122f-11eb-92ba-0ec7571515ae.png)

Both clients use the same init.vim evidently. So what can be wrong?

**Comment by matheusfillipe** [comment]
oh it also happens with neovim-gtk:

![image](https://user-images.githubusercontent.com/24435787/96508044-66f51500-1230-11eb-9479-1efbca93ed0c.png)

Doesn't happen on neovide:

![image](https://user-images.githubusercontent.com/24435787/96510938-acb3dc80-1234-11eb-9b0b-b940247f791a.png)

Happens in Fvim;

![image](https://user-images.githubusercontent.com/24435787/96510997-cce39b80-1234-11eb-9699-38143318a5fc.png)

Could this be lack of a feature (Thus this would be a feature request i guess), or could I just have another problem on my configs?

**Comment by jgehrig** [comment]
I'd guess `coc.vim` implements that feature with a floating window. I think this requires `ext_multigrid`, and neovim-qt does not support it yet.

You could also try `:GuiPopupmenu 0` to disable the GUI popupmenu. Based on the `Fvim` and `neovim-gtk` screenshots, `coc.vim` doesn't work well with a gui popupmenu. Note, `:GuiPopupmenu 0` is a neovim-qt specific configuration and still won't fix the lack of floating window support.

**Comment by jgehrig** [comment]
Amendment... `:GuiPopupmenu 0` may be all that is required.

I thought the floating window was your file content and not a floating window in the first screenshot.

**Comment by matheusfillipe** [comment]
![image](https://user-images.githubusercontent.com/24435787/96521892-ad566e00-1248-11eb-8e55-0ce6134d5390.png)

`:GuiPopupmenu 0` did it!!! Thanks @jgehrig ! I almost left neovim-qt but I have everything I wanted on it now :P (Well just waiting for transparent background though ;) )

**Comment by jgehrig** [comment]
@matheusfillipe Glad to hear that, thanks!

Have you seen Pull Request #737? It sounds like we should get that merged :smile:

I would recommend you quickly file an issue for the `coc.vim` folks. It looks like the plugin is making some invalid assumptions regarding `ext_popupmenu`...

**Comment by matheusfillipe** [comment]
I saw #737 ! is what I'm waiting for! I'll tell coc.vim folks.

**Comment by jgehrig** [comment]
Merged 737 :)
