### ISSUE TITLE
App icon not showing on Neovim 0.5.0 on Windows 10

### ISSUE THREAD

**Issue by ggandor** [equalsraf/neovim-qt#782]
On nightly versions the app icon has been missing for a while:
![nightly](https://user-images.githubusercontent.com/17800844/97367914-3e14f580-18aa-11eb-9c72-1e2e35e06bd1.JPG)

The nvim-qt.exe bundled with 0.4.x looks fine:
![stable](https://user-images.githubusercontent.com/17800844/97367938-4836f400-18aa-11eb-90a4-08424c9858a1.JPG)

**Comment by jdhao** [comment]
@ggandor  This is a standing that has not been resolved, see https://github.com/neovim/neovim/issues/12928 .

**Comment by jgehrig** [comment]
Duplicate #745

The CMake logic in `neovim` is incorrect, and does not copy all of the `windeployqt` output.
