### ISSUE TITLE
Serious lag when entering or writing a buffer on Windows

### ISSUE THREAD

**Issue by ggandor** [equalsraf/neovim-qt#783]
Now this is a curious issue. Sometimes there's a 1-3 second lag when writing a particular buffer, and a shorter but still considerable lag when entering it. For any file type, even when no change has been done. I have noticed it for a while, on random occasions, but couldn't pinpoint the exact cases. My first thought was obviously that some autocommand or plugin could be behind this, but the issue is present even with an emtpy `init.vim`.

After a lot of experimenting, it seems this lag arises only when the given file's location is on the desktop, _and_ the desktop is set to be the current working directory. If I move the file to somewhere else, even to a subfolder `C:\Users\Username\Desktop\foo\`, everything works flawlessly again. If the file stays on the desktop, but I `cd` to somewhere else, the lag also disappears. There's no lag when switching between windows if both files opened are on the desktop (but `:write` still lags).

I could not reproduce this either in terminal or other GUI frontends (I tried GoNeovim and FVim).

**Comment by jgehrig** [comment]
Does this issue reproduce with `nvim-qt -- -u NONE`?

Could you also provide the output `nvim-qt --version`?

We're just a front end for `nvim`, so these scenarios are generally outside our control. You correctly noted `init.vim` is one of the few differences we have with other front ends. It is still possible this is a `nvim-qt` bug.

I cannot reproduce this issue on Windows.

**Comment by ggandor** [comment]
It's the same with `nvim-qt -- -u NONE`, although only the writing lags (not the window switching).

`nvim-qt --version`:
![version](https://user-images.githubusercontent.com/17800844/97478205-ea111c00-1950-11eb-8744-58e1cb3872d3.JPG)

**Comment by jgehrig** [comment]
It looks like you are running a nightly release of `neovim`. Can you quickly update to the latest nightly?

The latest versions as of today are: `NVIM v0.5.0-782-gb6897ebc0` and `NVIM-QT v0.2.16.1`.

You may also want to try the latest stable releases of `nvim-qt` and `nvim` together:

- https://github.com/neovim/neovim/releases/tag/v0.4.4
- https://github.com/equalsraf/neovim-qt/releases/tag/v0.2.16.1

Install both, but launch `nvim-qt` from the source above. The version packaged with `v0.4.4` is older. An upgrade will help us quickly rule out any already-fixed issues.

If those updates don't help, we can debug further...

**Comment by ggandor** [comment]
The pre-compiled `nvim-win64.zip` file among the release assets contains this `-773` build with the `0.2.16.0` QT version, I don't have the toolchain ready to compile it on Windows from source, but might try that later. That being said, I downloaded the latest `NVIM-QT v0.2.16.1` separately, and tried it both with the nightly and the latest stable version `v0.4.4`, with no luck.

**Comment by swag-lab** [comment]
+1. I do have lags but not "Serious". Might be due to plugins(?) as I disabled loading `init.vim` and sorts with `nvim-qt -- -u NONE` and the lag disappeared quite a bit...

**Comment by ggandor** [comment]
Update: I have recently installed the nightly `nvim-qt` from the latest Windows AppVeyor build, and the problem seems to be resolved in the meantime. With the current stable release, I still experience the same kind of lags. So I think we can close this issue, if you agree.

**Comment by jgehrig** [comment]
@ggandor

Thanks for following up!

I was never able to reproduce this issue myself.

Given you no-longer see issues with the latest build, I agree. Let's close the issue.

If anyone sees this issue again with a recent build, we can re-open.
