### ISSUE TITLE
crash when scrolling using mouse

### ISSUE THREAD

**Issue by jdhao** [equalsraf/neovim-qt#784]
I have experienced a lot of crash lately with nvim-qt on Windows.

nvim-qt version: 0.2.17.9999
nvim version:  v0.5.0-705-g9f704c88a

Steps to reproduce:

+ Open nvim-qt: `nvim-qt -- -u NORC some_file.py`
+ Set it to use mouse: `:set mouse=a`
+ Scroll the screen using middle mouse button right after the above step (do not click using the mouse or anything).

Then nvim-qt crashed with the message:

> The Neovim process has crashed.

If we click the window, then start scroll using mouse. It may not crash. I don't know why.

**Comment by jgehrig** [comment]
This is very likely related to bad mouse handling in `shell.cpp`.

You can see an example of the bad input in #696:
```
QWheelEvent
   QWheelEvent(Qt::ScrollMomentum, pixelDelta=QPoint(58,0), angleDelta=QPoint(116,0))
   "<ScrollWheelRight><86.25,28.8667>"
```

I think I broke this with a combination of Qt Version Bump, 3a59d6bd6e24a0935272a87e4300f97472e40d13, and 6e309981c3fdedd2a09dcfd8c203c3667f54bf1f.
