### ISSUE TITLE
AppVeyor version of neovim is built without python support

### ISSUE THREAD

**Issue by RedX2501** [equalsraf/neovim-qt#79]
This is about your neovim build at AppVeyor. I would have liked to create an issue in your neovim repository but there you have Issues disabled.

it seems that neovim is build without python2 support. i have not checked for Python3 as i don't use it.

It is very convient being able to download ready built versions and yours seem to be the only one available for windows. Thank you.

With python support enabled i'd be able to test many more things under windows as that is my only development platform.

**Comment by equalsraf** [comment]
In neovim python support is enabled as long as
- Python is in path
- The neovim python module is installed (i.e. pip install neovim)

There is not build time check to enable/disable python2 or python3, just install python and the module and has('python') should work.

I realize you currently can't check the help files in Windows, but you can check {online](https://neovim.io/doc/user/nvim.html), here is [:h nvim-python](https://neovim.io/doc/user/nvim_python.html#nvim-python)

**Comment by RedX2501** [comment]
I have installed the neovim module (they should have a  message stating that it is missing).

![2015-12-16_16-16-31](https://cloud.githubusercontent.com/assets/929932/11839000/962be76a-a410-11e5-9ade-045a6551e745.png)

The 0 at the last line is from `echo has('python')`.

**Comment by equalsraf** [comment]
> I have installed the neovim module (they should have a message stating that it is missing).

Mmmm I was under the impression it had one, try calling an actual python expression instead of has('python') e.g. `:py 42`

**Comment by RedX2501** [comment]
Ok, something strange is going on. I am starting neovim-qt through a batch file:
```
rem cd D:\Playground\neovim\Neovim\share\nvim\runtime\
set XDG_CONFIG_HOME=%APPDATA%\
set NVIM_QT_LOG=D:\Playground\neovim\neovim-qt\nvim-qt.log
set PATH=%PATH%;D:\Playground\neovim\Neovim\bin;C:\Python27;D:\Playground\neovim\Neovim\share\nvim\runtime;C:\Program Files\Git\bin

rem D:\Playground\neovim\neovim-qt\nvim-qt.exe --server 127.0.0.1:7777
D:\Playground\neovim\neovim-qt\nvim-qt.exe
```
When using it, python was definitely not working.

Now I set the remote version, commented the nvim-qt.exe without arguments added Python to the PATH where i'm invoking nvim.exe and it is kind of working.

Now i get
```
2015-12-16 18:56:07,934 [ERROR @ base_events.py:default_exception_handler:1053] 15040 - Fatal read error on pipe transport
protocol: <neovim.msgpack_rpc.event_loop.asyncio.AsyncioEventLoop object at 0x02862510>
transport: <_ProactorReadPipeTransport fd=0>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\trollius\proactor_events.py", line 195, in _loop_reading
    self._read_fut = self._loop._proactor.recv(self._sock, 4096)
  File "C:\Python27\lib\site-packages\trollius\windows_events.py", line 428, in recv
    self._register_with_iocp(conn)
  File "C:\Python27\lib\site-packages\trollius\windows_events.py", line 609, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
WindowsError: [Error 6] Das Handle ist ungültig
```
but that is from python which should mean the support is installed...

But somehow something seems to be left open. When i try to execute neovim-qt without startin neovim remotely it just states that neovim is taking too long to start...

**Comment by RedX2501** [comment]
Neovim seems to be stuck here:

![2015-12-16_19-14-43](https://cloud.githubusercontent.com/assets/929932/11842464/c823b112-a429-11e5-89f6-2ebd76281608.png)

**Comment by equalsraf** [comment]
Lets take it one step back first. also you can do some simpler tests without all the hassle of starting nvim and nvim-qt for example

    nvim --cmd "echo has('python'); q"

Command arguments passed to nvim-qt are forwarded to nvim (except --server). Try to skip loading your vimrc

    nvim-qt -u NONE

Can your runt it like this? If yes can you call `:py 42`

A while back there an error message similar to yours being discussed in giter, at the time it seemed to be related to deoplete. Most likely neovim called a python plugin while loading vimrc and its waiting for a keypress (like #78)

**Comment by RedX2501** [comment]
```nvim --cmd "echo has('python'); q"``` has earned 
```
1
Error detected while processing pre-vimrc command line:
E15: Invalid expression: ; q
E15: Invalid expression: ; q
Press ENTER or type command to continue
```
comment from nvim.

```nvim-qt -u NONE``` allows me to start nvim from nvim-qt (so this probably means that loading my vimrc with python dependent plugins might be bad). When i try to do ```:py 42``` that gets me:
```
E117: Unknown function provider#python#Call
```

BUT! as i discovered in the other bug i reported in neovim, i have to set VIMRUNTIME because of some path issues.

Then it seems to load python and ```:py 42``` gets me again the:
```
Failed to load python host... set env var...
```

And if i set the env var the contents are again:
```
2015-12-16 19:30:08,586 [ERROR @ base_events.py:default_exception_handler:1053] 16700 - Fatal read error on pipe transport
protocol: <neovim.msgpack_rpc.event_loop.asyncio.AsyncioEventLoop object at 0x027314B0>
transport: <_ProactorReadPipeTransport fd=0>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\trollius\proactor_events.py", line 195, in _loop_reading
    self._read_fut = self._loop._proactor.recv(self._sock, 4096)
  File "C:\Python27\lib\site-packages\trollius\windows_events.py", line 428, in recv
    self._register_with_iocp(conn)
  File "C:\Python27\lib\site-packages\trollius\windows_events.py", line 609, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
WindowsError: [Error 6] Das Handle ist ungültig
```

Is there any way to see the handle it is trying to use?

**Comment by equalsraf** [comment]
> nvim --cmd "echo has('python'); q" has earned 

My mistake should be a `|` e.g. `nvim --cmd "echo has('python') | q"`

Is there a $HOME/.nvimlog file?

**Comment by RedX2501** [comment]
You can see there a `1` on the output. That is from the `has('python')` which means it thinks it's working. Your new version outputs a `1` and nothing else.

The contents of nvimlog when i start nvim-qt.exe and issue `:py 42` are:

```
2015/12/16 20:39:47 [info @ main:533] 9036 - Starting Neovim main loop.
2015/12/16 20:40:10 [info @ main:533] 17500 - Starting Neovim main loop.
2015/12/16 20:40:22 [error @ forward_stderr:333] 17500 - Channel 2 stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\site-packages\neovim\__init__.py", line 64, in start_host
    session = stdio_session()
  File "C:\Python27\lib\site-packages\neovim\msgpack_rpc\__init__
2015/12/16 20:40:22 [error @ forward_stderr:333] 17500 - Channel 2 stderr: .py", line 36, in stdio_session
    return session('stdio')
  File "C:\Python27\lib\site-packages\neovim\msgpack_rpc\__init__.py", line 17, in session
    loop = EventLoop(transport_type, *args, **kwargs)
  File "C:\Python27\lib\site-packages\neovim\m
2015/12/16 20:40:23 [error @ forward_stderr:333] 17500 - Channel 2 stderr: sgpack_rpc\event_loop\base.py", line 88, in __init__
    getattr(self, '_connect_{0}'.format(transport_type))(*args)
  File "C:\Python27\lib\site-packages\neovim\msgpack_rpc\event_loop\asyncio.py", line 90, in _connect_stdio
    self._loop.run_until_co
2015/12/16 20:40:23 [error @ forward_stderr:333] 17500 - Channel 2 stderr: mplete(coroutine)
  File "C:\Python27\lib\site-packages\trollius\base_events.py", line 348, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.

2015/12/16 20:40:24 [error @ call_set_error:743] 17500 - msgpack-rpc: Channel was closed by the client
```
