### ISSUE TITLE
Unable to map < key in nvim-qt. But works on terminal nvim

### ISSUE THREAD

**Issue by lygamac** [equalsraf/neovim-qt#790]
`<` key cannot be mapped in nvim-qt. Even with an empty `init.vim`.

Terminal vim does not have this issue.

nvim version: 0.4.4

**Comment by jgehrig** [comment]
You're running an old version of `nvim-qt`, this issue has been resolved as of the latest release.

You can download nvim-qt separately and run it with nvim 0.4.4, or download the latest nvim nightly.

See #612
