### ISSUE TITLE
nvim-qt doesn't recognize monospaced fonts

### ISSUE THREAD

**Issue by ndavidpsi** [equalsraf/neovim-qt#792]
- `nvim --version`: 0.5.0
- Operating system/version: Windows 10

I am using UbuntuMono NF (from the NerdFont official website).
(set guifont=UbuntuMono\ NF:h12)

I get the following error when I enter nvim-qt:
Warning: Font "UbuntuMono NF" reports bad fixed pitch metrics

Is there a way to fix this or just to suppress it? (I read in other issue  #732 to use something called bang but GuiFont isn't recognized as a command, at least in nvim 0.5.0)

**Comment by jgehrig** [comment]
You can suppress these warnings with `:GuiFont! UbuntuMono\ NF:h12` in `ginit.vim`.

See `:help GuiFont`:
```
It warns and fails when an invalid font has specified.
Use a |bang| (!) to forcedly assign an invalid font like:
	:GuiFont! <An invalid font>
```

This message indicates your don't has some non-monospace features/characteristics.

**Comment by ndavidpsi** [comment]
is ginit.vim supposed to be in the same folder as init.vim? It doesn't seem to have any effect

**Comment by jgehrig** [comment]
Here is an example on my machine:
```
" Render programming font ligatures if available
if exists(':GuiRenderLigatures')
	GuiRenderLigatures 1
	GuiFont! FiraCode\ Nerd\ Font:h13 " <-- Here
endif
```

The `ginit.vim` file is located at `~/.config/nvim/ginit.vim`.
On Windows, this file is found at `%LOCALAPPDATA%\nvim\ginit.vim`.

If you want to set the option for the current session, use `:GuiFont!`. In `ginit.vim`, the `:` is not required.

You can ignore the `GuiRenderLigature` stuff, the feature is likely unavailable in your build.

**Comment by ndavidpsi** [comment]
Did exactly like you said. I am using windows 10 right now.
In ~/AppData/Local/nvim/ginit.vim I put the following line `GuiFont! UbuntuMono\ NF:h12`

**Comment by jgehrig** [comment]
The only way for that message to appear is if you set a font with bad mono space metrics without the `!` option. The error will appear for `:set guifont=...` and `:GuiFont ...`.

Try `nvim-qt --u NONE` and manually call `:GuiFont! UbuntuMono\ NF:h12`. Does the error still appear?

**Comment by ndavidpsi** [comment]
It says `unknown option 'u'` (on the terminal version it allows me to do `nvim -u NONE` but it doesn't let me do that in the GUI version, Idk why)

**Comment by jgehrig** [comment]
Sorry, auto-correct typo: `nvim-qt -- -u NONE`. Edited above too.

**Comment by ndavidpsi** [comment]
I mean yeah it works fine there

**Comment by ndavidpsi** [comment]
Thanks for the help.
I was setting the guifont in my init.vim

What I did in my ginit.vim was:
```
GuiFont! UbuntuMono\ NF:h12
set guifont=UbuntuMono\ NF:h12
```

It works fine now, thanks!!

**Comment by jgehrig** [comment]
Glad to hear the issue is resolved.

This is worth noting:
```
GuiFont! UbuntuMono\ NF:h12
set guifont=UbuntuMono\ NF:h12 " This line isn't strictly necessary, would error if called first
```

**Comment by sp1n0r** [comment]
Alright thanks. I'll remove it then

**Comment by ndavidpsi** [comment]
Alright thanks. I'll remove it then

**Comment by nkta3m** [comment]
nepvim 0.82
Windows 10
i set GuiFont! JetBrainsMono\ NF:h12 in ginit.vim
but it shows the same error 
Warning: Font "JetBrainsMono NF" reports bad fixed pitch metrics
