### ISSUE TITLE
neovim-qt built from source doesn't recognize GuiFont command

### ISSUE THREAD

**Issue by ndavidpsi** [equalsraf/neovim-qt#798]
**nvim-qt version:**
![nvimqtversion](https://user-images.githubusercontent.com/73792104/101200223-e82c2e00-365d-11eb-9388-b8acc7278578.PNG)
### Steps to reproduce the issue
- **Build neovim from source**
```
-- open msys2 mingw32-64 as admin
cd (...)/neovim(-nightly)
-- install packages:
pacman -S \
    mingw-w64-x86_64-{gcc,libtool,cmake,make,perl,python2,pkg-config,unibilium} \
    gperf

-- build:
mkdir .deps
cd .deps
cmake  -G "MinGW Makefiles" ../third-party/
mingw32-make
cd ..
mkdir build
cd build
cmake -G "MinGW Makefiles" -DCMAKE_INSTALL_PREFIX="C:\Program Files\nvim" -DGPERF_PRG="C:\msys64\usr\bin\gperf.exe" -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
mingw32-make
```
- **Run nvim-qt -- -u NONE**
- **type :GuiFont _somefont_**
### Expected result
nvim should recognize the command and change the font (using the latest official build that is what happens)
### Actual Result
**E492: Not an editor command GuiFont! UbuntuMono\ NF:h12**

**Comment by jgehrig** [comment]
See the Wiki for more details:
https://github.com/equalsraf/neovim-qt/wiki#guifontguiforegroundetc-dont-exist

This looks like a configuration error with your machine.

There is a vim script that routes those commands to RPC events. The script probably isn't loaded on your machine.

These days you can also use `:set guifont=...` for all cases except the non-mono-space-font override `:GuiFont!`.

Also, `v0.2.16` is an old version. You should probably want `v0.2.16.1` (or perhaps `master`).

**Comment by ndavidpsi** [comment]
> for all cases except the non-mono-space-font override `:GuiFont!`.
This is exactly why I want it.
> Also, `v0.2.16` is an old version. You should probably want `v0.2.16.1` (or perhaps `master`).
Oh I did not realize that...

**Comment by ndavidpsi** [comment]
So what I should do is
`git clone https://github.com/neovim/neovim/ -b master`
?

**Comment by ndavidpsi** [comment]
Yes I forgot to mention that what I did was `git clone https://github.com/neovim/neovim/`.
I did not clone from this repo, were you talking about this repo?

**Comment by jgehrig** [comment]
All of this depends... What are you trying to accomplish?

I ask because there may be an easier way to get at what you need. If you're just experimenting, that's fine too.

A simple `git clone https://github.com/equalsraf/neovim-qt.git` should put you on the tip of `master`.

You can validate this with `git branch`, which will display the active branch:
```
...
  jg-version-arg
  jg-win_viewport
* master
  tb-411
```

You can change the active branch/tag with `git checkout {tag_here}`:
`git checkout master` or `git checkout v0.2.16.1`

It looks like you're on Windows... You can resolve the bug above with:
```
 set NVIM_QT_RUNTIME_PATH=C:\Path\To\NvimQT\Runtime
nvim-qt
```

> If so is there a way to "join" the two builds? nvim from nvim repo and nvim-qt from equalsraf repo

Sure, releases of `nvim` on Windows usually contain a version of `neovim-qt`.

If you build neovim, it will download and build `neovim-qt` in the `third-party` directory.

**Comment by jgehrig** [comment]
Closing this, since it is a config issue on your machine.

Feel free to keep asking questions here though :)

**Comment by ndavidpsi** [comment]
Oh how cool, thanks for the clarification. To solve the issue I actually installed the plugin mentioned in the link you sent me, but I'll do that instead in a second

**Comment by jgehrig** [comment]
Using the plugin is a perfectly valid solution.

The plugin's primarily target is folks who connect `nvim-qt` to an already spawned instance of `nvim`. Usually WSL, Virtual Machines, etc.

There are a handful of new commands available in `master`, but not yet in a release. These commands won't appear with the plugin yet. Probably not an issue for you in this case.

**Comment by ndavidpsi** [comment]
Alright sounds great.

The thing is, I finished the build now, and I can't find the neovim-qt runtime, I know the neovim one and I usually just move the folder into the default path but I don't know where the neovim-qt one is located

**Comment by jgehrig** [comment]
This is the file:
https://github.com/equalsraf/neovim-qt/blob/master/src/gui/runtime/plugin/nvim_gui_shim.vim

You should set `NVIM_QT_RUNTIME_PATH` to point to the `runtime` folder (I think). The specific location depends on what CMake has decided to do. Generally, there is a `bin` folder somewhere in your `build` directory. You want to point to that file.

However, any path to a `runtime` directory will work.

**Comment by ndavidpsi** [comment]
I guess I'll stick to the plugin, I am not sure where the nvim-qt runtime folder is
