### ISSUE TITLE
Changing Neovim font

### ISSUE THREAD

**Issue by equalsraf** [equalsraf/neovim-qt#8]
A font changing dialog would be nice, but how do we trigger without risking shadowing a neovim mapping.

Otherwise if neovim/neovim#2203 is implemented we can wait for a notification for a predefined variable.

**Comment by aikeru** [comment]
If we're stuck with just one font, could you switch it to be a powerline font?
https://github.com/powerline/fonts/tree/master/DejaVuSansMono

Or even better, the font with the file icons, too, for those that want them:
https://github.com/ryanoasis/font-nerd-icons/tree/master/patched-fonts/DejaVuSansMono

That would be really sweet.

**Comment by equalsraf** [comment]
@aikeru, PR #16 seems ready to be merged, and should allow you to change your fonts.

But requires the following nvimrc snippet.
```
" Neovim-qt Guifont command, to change the font
command -nargs=? Guifont call rpcnotify(0, 'Gui', 'SetFont', "<args>")
" Set font on start
let g:Guifont="DejaVu Sans Mono for Powerline:h13"
```

**Comment by yngwin** [comment]
neovim-qt should not ship a copy of dejavu, but should simply use the default monospace font as defined by fontconfig, in case no Guifont is set.

**Comment by equalsraf** [comment]
@yngwin yup the bundled DejaVu will be removed when #16 is merged. It just defaults to Monospace.

**Comment by vityafx** [comment]
I still don't understand what should I do to change font in neovim-qt, can you guys please enlight me?

When I do

    :Guifont Monaco:h12

Neovim says:

> E116: Invalid arguments for function rpcnotify

**Comment by equalsraf** [comment]
Hi @vityafx.

I'm assuming you are using the branch from #16.

> > E116: Invalid arguments for function rpcnotify

It seems Neovim is not happy about the Guifont command, what do you have in your .nvimrc? Mine looks like this.

    command -nargs=? Guifont call rpcnotify(0, 'Gui', 'SetFont', "\<args\>") | let g:Guifont="<args>"

**Comment by vityafx** [comment]
Yes, had a problems with it while pasting from here.
I've changed it to your one and it does not throw any error anymore. But the font still does not change.

**Comment by equalsraf** [comment]
Strange did you build neovim-qt from the branch in #16? Also does `:messages` show any messages about the font?

**Comment by vityafx** [comment]
`:messages` say:

> Unknown font: <args>

**Comment by equalsraf** [comment]
#16 has been merged into master, and the builds should be up shortly. I'm aware some of the items in #16 are not fixed yet but we can discuss those in separate issues.

**Comment by equalsraf** [comment]
https://github.com/equalsraf/neovim-qt/wiki/GUI
