### ISSUE TITLE
Undercurl is a bit random

### ISSUE THREAD

**Issue by statiolake** [equalsraf/neovim-qt#802]
![image](https://user-images.githubusercontent.com/20490597/102804218-c9b78800-43fc-11eb-959c-11e5ddb6f414.png)

This is current undercurl. It's OK, but I feel this a bit random.

I fixed it for my personal use (https://github.com/statiolake/neovim-qt/commit/78c1129b854ac0bc982c0fc620083b9e9b4d3921) and now undercurl looks like this:

![image](https://user-images.githubusercontent.com/20490597/102806862-fa99bc00-4400-11eb-87cd-bcd7bbd727b0.png)

I think it is more clean and I'd be happy to open PR if it's worth.

**Comment by jgehrig** [comment]
That looks *much* better!

Definitely worth it, please open a PR.

From a quick read of the code above, this looks merge-able as written. I may or may not have a few minor comments after testing.
