### ISSUE TITLE
Unexpected runtime path C:\projects\neovim-qt\INSTALL\share\nvim-qt

### ISSUE THREAD

**Issue by statiolake** [equalsraf/neovim-qt#806]
In Windows, if a folder exists at `C:\projects\neovim-qt\INSTALL\share\nvim-qt`, Neovim-qt registers the directory to the runtimepath. If this folder is empty then Neovim fails to load neovim-gui-shim. In my personal case, there was an old neovim-gui-shim so I sometimes had unexpected behavior, e.g. my exit status improvement (#644) didn't work correctly as it required modified version of neovim-gui-shim.

The path is the INSTALL directory used inside CI like AppVayor.

I suspect following codes are the cause (and so I also suspect this is not Windows-specific but also affects other platforms except for macOS):

https://github.com/equalsraf/neovim-qt/blob/e8b37f069511ea7d7aa62b8ffbec17d3dc8689ef/src/gui/app_runtime.cpp#L16-L18

and `NVIM_QT_RUNTIME_PATH` is defined automatically by CMake at compile-time:

https://github.com/equalsraf/neovim-qt/blob/e8b37f069511ea7d7aa62b8ffbec17d3dc8689ef/src/gui/CMakeLists.txt#L58-L61

I think the paths only related to the build environment shouldn't be appear outside of the environment, but seeing it's disabled for macOS, it also appears to be intentional.

Anyway, I don't think hard-coding a path which is not related to the runtime environment is a good idea...

**Comment by jgehrig** [comment]
Pull Request: #807
Edit + Merge: 8e167e1

Thanks!
