### ISSUE TITLE
Welcome message doesn't appear in nvim-qt

### ISSUE THREAD

**Issue by ndavidpsi** [equalsraf/neovim-qt#808]
The welcome message that shows the version of nvim, etc. doesn't appear in nvim-qt. Taking a closer look it seems that it briefly appears when nvim-qt is opened but then the screen clears right away.

**Comment by jgehrig** [comment]
Personally, I like this behavior. I prefer the clean screen when I open my editor.

I'd guess the lack of welcome screen is a side effect of our current startup logic:
1. Start blank Qt MainWindow
2. Spawn `nvim`, initiate connection.
3. Once connected resize Neovim canvas to fit.

>Taking a closer look it seems that it briefly appears when nvim-qt is opened but then the screen clears right away.

How did you observe this? Do you see an empty screen flickering or a quick flash of the welcome message?

**Comment by ndavidpsi** [comment]
I saw a quick flash of the welcome message. It's not even noticeable all the time but I have seen it a few times. So is it possible to make it show the welcome message or is it too much trouble?

**Comment by jgehrig** [comment]
Okay. I don't think I can't see the flash, empty screen only.

Unfortunately, I don't currently have the time to investigate. For me, this is low priority.

If you'd like to investigate yourself, I'm open to a merge/fix and am happy to answer any questions you have about the code.

**Comment by ndavidpsi** [comment]
Yes I understand, thanks. I'll look into it

**Comment by jgehrig** [comment]
#197
