### ISSUE TITLE
Problem with coc.nvim

### ISSUE THREAD

**Issue by gamardzoba** [equalsraf/neovim-qt#810]
How it works in a terminal and should work correctly:
![terminal](https://user-images.githubusercontent.com/3626876/103437886-6ec03500-4c35-11eb-942f-8a9d9ea5e644.png)

How it works in the neovim-qt:
![neovim-qt](https://user-images.githubusercontent.com/3626876/103437887-754eac80-4c35-11eb-8584-870c24e3f0de.png)

Seems this bug is not caused by https://github.com/neoclide/coc.nvim. It was tested in the first top-five GUIs for nvim and only neovim-qt had the issue. 

The bug has occurred on Ubuntu 20.10 with the very init nvim config and with a blank one. Easy reproducible.

**Comment by jgehrig** [comment]
See: #780 and https://github.com/neoclide/coc.nvim/issues/2478

This is a known issue. The workaround is to disable the gui popupmenu `:GuiPopupmenu 0`.

As I understand this is an upstream Neovim issue, and there is no Neovim API to support reporting the popup size. Without this COC cannot position the documentation pop-up properly.
