### ISSUE TITLE
Control shift mappings do not work with latest neovim

### ISSUE THREAD

**Issue by svermeulen** [equalsraf/neovim-qt#817]
Adding a vim rc with a `<c-s-k>` map works correctly when building neovim from commit e62beab71, but as of commit a88bc4d95, this mapping stops working.  Related neovim changes:  https://github.com/neovim/neovim/issues/12037 and https://github.com/neovim/neovim/pull/13279

Moved over from neovim repo issue here:  https://github.com/neovim/neovim/issues/13421 (which contains more detailed repro steps)

I also noticed that `c-s` mappings work as expected with [neovide](https://github.com/Kethku/neovide) so I suspect it's a nvim-qt issue

**Comment by jgehrig** [comment]
Thanks for the bug report! A long-term goal of mine is to fix input layer issues like this...

You're triggering this block of code in `input.cpp`:
```c++
// Remove Ctrl empty characters at the start of the ASCII range
if (c.unicode() < 0x20) {
	mod &= ~ControlModifier();
}
```

That block removes the control modifiers from non-printing characters (tab, newline, etc).

For example, on Linux in an en-us keyboard layout, you can insert a newline by typing `CTRL + J`. Without this block, `nvim-qt` would send `CTRL + \n`, incorrect.

I have mixed feelings on this issue... A good argument can be made for this being "by-design", the sequence can also be interpreted as `SHIFT + TAB`. On my machine,  CTRL + K is a tab. 

Looking at git blame, this is how input.cpp was originally designed.

Which interpretation is correct?

**Comment by jgehrig** [comment]
It is also worth noting, MacOS has a "Hex Input" keyboard layout.

I would guess this issue does not occur in that layout, where key combinations are not overloaded.

**Comment by svermeulen** [comment]
I should mention that I'm experiencing this problem on MacOS.  Thanks for explaining that.  Since I'm very used to CTRL+SHIFT mappings, I'll try just commenting that out and see if that at least fixes it for me locally

**Comment by jgehrig** [comment]
Since you're compiling from source... Can you quickly provide some debug output?

The following snippet from `shell.cpp` is useful for understanding input bugs:
```c++
// Uncomment for key input debugging and unit test writing.
// qDebug() << "QKeyEvent ev:" << ev;
// qDebug() << "  " << inp;
```

The output shows Qt event info and the input we send to nvim:
```
QKeyEvent ev: QKeyEvent(KeyPress, Key_J, ShiftModifier|ControlModifier, text="\n")
   "<S-\n>"
```

For MacOS you can also try the alternative layout (Unicode Hex Input?). I don't have access to a Mac at the moment...

I'm open to a fix, but will probably move slowly. I've seen similar bugs in the past where users are evenly split on what the "correct" behavior should be. We may be able narrow the control modifier removal conditional, `< 0x20`.

**Comment by svermeulen** [comment]
Ok so I tried it again after uncommenting those debug lines.  I used this as my init.vim:

```
nnoremap <c-b> :echo 'hi1'<cr>
nnoremap <c-s-b> :echo 'hi2'<cr>
```

If I execute terminal nvim, and hit `<c-b>` then I get `hi1` as I would expect.  If I open nvim-qt and hit `<c-b>`, I get `hi2` for some reason.

Here's the nvim-qt log:
```
Neovim API version compatible with 0 supported 6
Received unknown option "pumblend" QVariant(qulonglong, 0)
Received unknown option "ext_multigrid" QVariant(bool, false)
Received unknown option "ext_hlstate" QVariant(bool, false)
Received unknown option "ext_termcolors" QVariant(bool, false)
Received unknown option "ext_messages" QVariant(bool, false)
Received unknown redraw notification "update_menu" ()
Received unknown redraw notification "update_menu" ()
Received unknown redraw notification "update_menu" ()
Received unknown option "ext_messages" QVariant(bool, false)
Received unknown option "ext_messages" QVariant(bool, false)
QKeyEvent ev: QKeyEvent(KeyPress, Key_Meta, MetaModifier)
   ""
QKeyEvent ev: QKeyEvent(KeyPress, Key_B, MetaModifier)
   "<C-b>"
Neovim requested a GUI close
```

**Comment by svermeulen** [comment]
Oh, one thing I did notice is that if I use `<C-b>` in init.vim instead, then I get the same behaviour in terminal vim.  So I guess capitalizing the `C` does it

**Comment by jgehrig** [comment]
> Oh, one thing I did notice is that if I use <C-b> in init.vim instead, then I get the same behaviour in terminal vim. So I guess capitalizing the C does it

What you describe here sounds like `nvim` behavior. We don't have control over paring `init.vim` from `nvim-qt`.

From the client perspective, we can only control the key events sent to `nvim`.

We map input received from QTt (`QKeyEvent ev: ...`) and map it to sequences nvim understands (`<C-b>`).

**Comment by jgehrig** [comment]
I'm not 100% sure I follow the key sequences you're using...

From my read of the debug output, you're only pressing CTRL + B. This confuses me, and I would like to understand what is going on.

For reference, here is my debug output on Linux.
CTRL + B:
```
QKeyEvent ev: QKeyEvent(KeyPress, Key_B, ControlModifier, text="\u0002")
   "\u0002"
```

CTRL + SHIFT + B:
```
QKeyEvent ev: QKeyEvent(KeyPress, Key_B, ShiftModifier|ControlModifier, text="\u0002")
   "<S-\u0002>"
```

There will be differences in input based on keyboard localization and platform.

Also, `MetaModifier` on MacOS and `ControlModifier` are equivalent from an nvim perspective.

**Comment by svermeulen** [comment]
Sorry, I should clarify that the nvim-qt log I posted above was with me hitting CTRL+B and not CTRL+SHIFT+B.  In this case it seems nvim-qt sends the following:

```
QKeyEvent ev: QKeyEvent(KeyPress, Key_Meta, MetaModifier)
   ""
QKeyEvent ev: QKeyEvent(KeyPress, Key_B, MetaModifier)
   "<C-b>"
Neovim requested a GUI close
```

If I hit CTRL+SHIFT+B then I get this:

```
QKeyEvent ev: QKeyEvent(KeyPress, Key_Meta, MetaModifier)
   ""
QKeyEvent ev: QKeyEvent(KeyPress, Key_Shift, ShiftModifier|MetaModifier)
   ""
QKeyEvent ev: QKeyEvent(KeyPress, Key_B, ShiftModifier|MetaModifier)
   "<C-B>"
```

What I'm saying is that I think this problem would be fixed if nvim-qt passes `<c-b>` instead of `<C-b>` in the first case here.  I think this because I noticed that if I create a map using `<C-b>` instead of `<c-b>` then I get similar problems with terminal vim (that is - hitting CTRL+B is interpreted as CTRL+SHIFT+B).

**Comment by svermeulen** [comment]
This is probably a neovim bug though I'm guessing, since I would not expect neovim to change behaviour when capitalizing the C in `<C-b>`

**Comment by svermeulen** [comment]
Ok so I tried playing with it some more and learned the following:

If I use the following init.vim with neovide:

```
nnoremap <c-b> :echo 'foo'<cr>
nnoremap <c-s-b> :echo 'bar'<cr>
```

Then CTRL+B and CTRL+SHIFT+B both print the corresponding text as expected.

If I use it with nvim-qt, then both CTRL+B and CTRL+SHIFT+B print 'foo'.

I also noticed that if I use the following init.vim instead:

```
nnoremap <C-b> :echo 'foo'<cr>
nnoremap <C-B> :echo 'bar'<cr>
```

Then neovide prints 'bar' when hitting CTRL+B.  And hitting CTRL+SHIFT+B prints nothing.  So it seems that the `<C-B>` map overrides the `<C-b>` map.

And based on the nvim-qt logs I posted above, nvim-qt seems to send `<C-b>` to neovim when I press CTRL+B and `<C-B>` when I press CTRL+SHIFT+B.

I wonder if nvim-qt could send `<c-s-b>` instead of `<C-B>` for these cases?

**Comment by jgehrig** [comment]
Okay, I see what is happening on your machine. Thanks for the clarifying repro steps.

In the case of `CTRL + SHIFT + B`, we're sending `<C-B>`.
In the case of `CTRL + B`, we're sending `<C-b>`.

We're removing the shift because the letter is capitalized. This is an API contract issue.

What is the correct format for `CTRL + SHIFT + KEY_LETTER`?

Should we use: `<C-B>`, `<C-S-B>`, `<C-S-b>`? Which parts are case sensitive?

We need to hand off whatever `nvim` expects.

**Comment by jgehrig** [comment]
@jamessan

Can you provide any guidance on how CTRL + SHIFT should be handled?

I see you've recently done some worth with modifier keys in `nvim`:
https://github.com/jamessan/neovim/commit/0cdd4652d07bcba10209d6bbea50e86ca682d9b5
https://github.com/neovim/neovim/issues/12037

I would like to make sure we send the correct format, as expected by `nvim`. See comment above.

Thanks! :smiley:

**Comment by svermeulen** [comment]
Just want to say that your PR fixes the issue for me :D Thanks!

**Comment by jgehrig** [comment]
Sorry for the long delay!

The changes have been merged, and this issue should be resolved.
