### ISSUE TITLE
Is GuiRenderLigatures command supported on Windows?

### ISSUE THREAD

**Issue by swag-lab** [equalsraf/neovim-qt#823]
### Environment:
- nvim-qt version: Latest release
- nvim version: v0.4.4
- OS: Windows 7 x64
- Font: Victor Mono Nerd Font

From #166, I got to know that the ligatures are supported in the `nvim-qt` GUI Client for Neovim. I tried using `:GuiRenderLigatures 1` as stated in the thread, but it shows an error: `E492: Not an editor command: GuiRenderLigatures`.

My question is, is there any support for ligatures in nvim-qt (on Windows at least), or is there some other way?

**Comment by jgehrig** [comment]
> Is GuiRenderLigatures command supported on Windows?

Yes!

It looks like you are either:
1. Running an unsupported version, `master` is required.
2. Have shim-loading issues, `:Gui...` commands aren't working.

I would guess issue 1. If you have `:GuiFont` available, we can rule out issue 2.

You can confirm your version with `nvim-qt --version`, you should see a `NVIM-QT v0.2.17.9999` or similar.

On Windows, you can download our AppVeyor build artifacts to get the latest changes:
1. Go to https://github.com/equalsraf/neovim-qt
2. Look for the latest commit banner. Click the small red `X` to show a CI dialog.
3. Click 'Details` for AppVeyor, small teal + white icon.
4. Click one of the builds (MSVC or GCC). Click `Artifacts`.

![image](https://user-images.githubusercontent.com/11207308/109321569-4b71ca80-781f-11eb-9192-b55fefe7bec2.png)

Here is a link:
https://ci.appveyor.com/api/buildjobs/g34g565if746j4k9/artifacts/neovim-qt.zip

**Comment by swag-lab** [comment]
Yes. I do have access to GuiFont and other Gui... commands like GuiScrollBar, GuiPopupmenu, etc...
Will update after downloading the zip from the link.

**Comment by swag-lab** [comment]
Update: This works! Thanks!
Then, is the latest release from "Releases" on GitHub not the version? Because I previously had the latest release build.

**Comment by jgehrig** [comment]
Ligatures isn't supported yet by a released version. The changes are only available in nightly builds from `master`.

Once I do the next release, it will be available on the page you reference. I have some known issues before the next release...

The `Gui...` commands not working is usually a result of a "shim" loading issue. Under the hood, we load a vim plugin for these commands. If you see issues, that plugin could be stale, missing, etc.

More details on Gui commands:
https://github.com/equalsraf/neovim-qt/wiki#guifontguiforegroundetc-dont-exist

**Comment by jgehrig** [comment]
Marking as closed, since this is resolved. Feel free to keep commenting.

If you notice any issues with ligatures, please let me know. I will do my best to fix them.

**Comment by Acejoy** [comment]
Hey , I just installed neovim on windows 10 . I too am experiencing the same problems.I am using Fira Code Font, it is working fine in vscode, but not in neovim-qt. Some Gui options are showing but nor GuiRenderLigatures. Will this feature will be updated to the main github repo and we can directly update from there or do i need to reinstall neovim?

**Comment by Acejoy** [comment]
Thanks for the reply. sorry, i overlooked the above reply.

**Comment by siddhi** [comment]
Looks like AppVeyor only retains build artifacts for a month, and the last build was over a month ago. Is it possible to trigger a new build to get the download?

**Comment by WenLinkis** [comment]
> Looks like AppVeyor only retains build artifacts for a month, and the last build was over a month ago. Is it possible to trigger a new build to get the download?

I have the same question. The last build is invalid and the "realease" is too older to experience new features. :-(
