### ISSUE TITLE
First keypress not interpreted after switching virtual desktop on Windows

### ISSUE THREAD

**Issue by rjurga** [equalsraf/neovim-qt#826]
I often switch virtual desktops on Windows (using the keyboard shortcuts ctrl+windows+left or right). Here's a bug that occurs with nvim-qt when doing so:

* Open nvim-qt in a desktop, with its window having the focus, and start editing some document
* Switch to another desktop (ctrl+windows+right)
* Come back to the desktop with nvim-qt (ctrl+window+left)
* Continue to edit document. For example, attempt to save it with `:w`. The very first keypress is not interpreted by nvim-qt, hence instead of saving, the cursor will move forward by one word (`:` is ignored but `w` taken into account).

It looks like there might be some focus stealing issue of some kind, but in general switching desktops in Windows seems to give the focus back to the correct window automatically. For example, if I switch to a desktop where notepad is open, I can type text directly.

I use the prebuilt binary shipped with nvim 0.4.4.

EDIT: I might have found another clue.

While in insert mode, pressing ctrl+windows inserts a `"` character in nvim-qt. And this key combination is part of the combination to switch desktops.

**Comment by jgehrig** [comment]
> I use the prebuilt binary shipped with nvim 0.4.4.

This is a very old version of both nvim and nvim-qt. Neovim has not done a release in some time.

Can you test with the latest Neovim release candidate, 0.5.0?

Better yet, you could test with the latest nvim-qt from master:
https://ci.appveyor.com/api/buildjobs/nqdg8fp65pcki9kq/artifacts/neovim-qt.zip

The version of nvim should not have any impact beyond letting me know what version of nvim-qt you have.

**Comment by rjurga** [comment]
It works correctly with the nvim-qt from master.

My bad for not testing earlier, I apologize. I didn't realize 0.4.4 was so far behind.

**Comment by jgehrig** [comment]
No problem! It is definitely not obvious.

A new nvim release is coming soon.

Marking as closed.
