### ISSUE TITLE
Feature request: Set fallback font

### ISSUE THREAD

**Issue by WieeRd** [equalsraf/neovim-qt#827]
If I set English-only fonts like `:GuiFont Hack`, texts in other languages just use system default.  
Would be cool if I can change fallback fonts for other languages.  
Is it already possible to set alternative/fallback font in Neovim-qt?

**Comment by jgehrig** [comment]
Yes, this is possible with `:set guifontwide=`.

That option will set a fallback don't if a character is unavailable in the regular font. The idea being you can set a CJK font with that option to render non-english wide characters. It is simply a coma separated list of fallback fonts using the same markup as `GuiFont`.

It can also be used for Emoji.

**Comment by WieeRd** [comment]
But in my case 'other language' is Korean, which is not wide character.  
Do you mean non-ascii char by 'wide' char?  

Also what if the main font supports other language but I want to change font for specific language?  
I actually already solved this issue by merging 2 font files, but it was quite laborious work.  
So I'm still curious if it's possible to set different font for each language

**Comment by jgehrig** [comment]
In this context "wide" means a character consuming two cells. It is a term used by Neovim.

Here is an example of `:set guifontwide`:
![GuiFont-GuiFontWide](https://user-images.githubusercontent.com/11207308/111034393-6463a980-83e3-11eb-802c-d366c98186d6.gif)

`Hello World` is rendered with `!GuiFont! Fira\ Code:h11`.

The feature was added recently. I'm not sure offhand which release of neovim-qt `guifontwide` is first available in. `0.2.16`?

If the option doesn't work for you, I recommend quickly testing with latest `master` build from AppVeyor:
https://ci.appveyor.com/project/equalsraf/neovim-qt/builds/38103132/job/nqdg8fp65pcki9kq/artifacts
https://ci.appveyor.com/api/buildjobs/nqdg8fp65pcki9kq/artifacts/neovim-qt.zip

**Comment by WieeRd** [comment]
Didn't work for my nvim, but it did on latest build from your link!  
Thanks a lot :)
