### ISSUE TITLE
CTRL-C kill job and terminal only in neovim-qt

### ISSUE THREAD

**Issue by grimgort** [equalsraf/neovim-qt#828]
When I use the CTRL-C key in nvim-qt, the job and the terminal are closed as in the picture below. In a powershell console or other, my vim config doesn't do that. 
![image](https://user-images.githubusercontent.com/44238325/111789981-042ca600-88c2-11eb-9790-116e1fb3bfd5.png)

**Comment by jgehrig** [comment]
I don't understand what is going wrong. Can you please provide more details?

What version of nvim-qt: `nvim-qt --version`?
What specific steps are you performing?

It sounds like you're running this on Windows. I quickly checked `<C-c>` in normal, insert, and `:terminal` modes. I didn't see any behavior differences from `nvim`.

**Comment by swag-lab** [comment]
Running latest AppVeyor build (commit 9dbd99dfaccd52a8b24b2c914831e5c7b9de6e28). No issues here (both terminal and GUI).

**Comment by jgehrig** [comment]
Marking as closed.
