### ISSUE TITLE
Oddities while using NERDTree (vim-devicons ~ WebDevIcons) when ligatures is enabled

### ISSUE THREAD

**Issue by swag-lab** [equalsraf/neovim-qt#830]
When ligatures is turned on, some characters don't seem to render well. The characters(icons) are cut off from ends or from the beginning, some simply don't render, and some render weird characters when the cursor is on them. Here's an example:

https://user-images.githubusercontent.com/79488680/112283119-ceb2fe80-8cad-11eb-8ff8-4673ea96debc.mp4

There are some issues regarding ligatures and rendering issues, ref-ing them: #809 #771 #735 #412

**Comment by tan-wei** [comment]
Hmm, this issue should not closed. If enable ligatures, these issues exists now.
