### ISSUE TITLE
White line on the top of window

### ISSUE THREAD

**Issue by fuelen** [equalsraf/neovim-qt#84]
I use `subtle` tiling WM. First screen - `vim-qt`, Second - `neovim-qt`
![28 12 15-19 56 25-184495924](https://cloud.githubusercontent.com/assets/588762/12023011/d5c8dd2e-ad9d-11e5-9af6-b5ce6d27a4e8.png)
![28 12 15-20 00 13-444656766](https://cloud.githubusercontent.com/assets/588762/12023010/d5c6db00-ad9d-11e5-9c38-9745593b7318.png)
There is white line on the top of second screen. When I click right mouse button on it, then I can see small popup with inactive checkbox.
Also `nvim-qt` starts not fullscreen (left, top and bottom). Only reloading subtle's config makes `neovim-qt` fullscreen (but other programs starts fullscreen without reloading).

Arch Linux. latest neovim and neovim-qt

**Comment by equalsraf** [comment]
Cheers, thanks for reporting these.

The white line is basically padding from the dock widget (see #75). The maximized windows are likely covered in #83 and #4.

**Comment by agauniyal** [comment]
bspwm does have that white padding on top too. Other than this, I find it the best nvim gui for linux.

**Comment by osa1** [comment]
I'm having this same problem. Old GTK-based vim GUIs also had this same problem and this is why I had switched to vim-qt years ago.

**Comment by ivegotasthma** [comment]
I'm experiencing this on i3.

**Comment by osa1** [comment]
FWIW, I'm on i3 too.

**Comment by equalsraf** [comment]
I've pushed an alternative fix for this into #109. Can anyone have a look with i3?

ping @nowrep,  c1ba8a0, similar to your fix but it uses a stacked widget instead of a custom layout.

**Comment by osa1** [comment]
Just tried it, it looks great. No more white lines around the window in i3.

**Comment by equalsraf** [comment]
Thanks @osa1, let me know if see something else, its likely I've added a fair share of bugs in the process.

**Comment by agauniyal** [comment]
```QWidget::setMinimumSize: (/QDockWidget) Negative sizes (0,-1) are not possible
QWidget::setMaximumSize: (/QDockWidget) Negative sizes (0,-1) are not possible```
