### ISSUE TITLE
Bring to front

### ISSUE THREAD

**Issue by MartyLake** [equalsraf/neovim-qt#843]
Hello,

First, sorry if this option exists and I did not find it in the manual.

I am using "nvr" ( https://github.com/mhinz/neovim-remote/issues/164 ) to quickly open files from the terminal "tig" to the already open neovim-qt instance. I am on win32. It works well.

I would like to know if it is possible to bring neovim window to front too.

Thanks for creating and maintaining neovim-qt, using it everyday for work and at home.
Best,

**Comment by jgehrig** [comment]
Yes, this should be possible with `:call GuiForeground()`.

Here is an `nvr` example:
https://github.com/equalsraf/neovim-qt/issues/757#issuecomment-699455023

If you come up with any clever `nvr` workflow improvements, let me know. It would be nice to have a solution that skips the `-c` argument.

It might help others to add an example workflow with NVR to the Wiki:
https://github.com/equalsraf/neovim-qt/wiki/Remote-attachment

> Thanks for creating and maintaining neovim-qt, using it everyday for work and at home.

I'm glad to hear this! :smile:

**Comment by jgehrig** [comment]
Marking this as closed.

Feel free to continue the thread with comments/questions.

**Comment by MartyLake** [comment]
I am curious, why is it called `GuiForeground` instead of `foreground` as described in the documentation ?
