### ISSUE TITLE
Highlight does not respect guisp for underline

### ISSUE THREAD

**Issue by YorickPeterse** [equalsraf/neovim-qt#851]
Support for the undercurl setting was added back in https://github.com/equalsraf/neovim-qt/commit/1d9c076e2992705c860f094433b704bae9ef177e. At the time the value for `guisp` was hard coded. It seems this may have been solved in https://github.com/neovim/neovim/pull/4633. I believe at least goneovim and neovide support this setting, though I could be mistaken.

If possible, it would be nice for neovim-qt to support this setting.

**Comment by jgehrig** [comment]
How is this supposed to behave? Do you have a non-working example?

From what I can tell, we are correctly processing the colors as sent by `nvim`.

For example:
`:hi FooBar guisp=Blue`
`QMap(("special", QVariant(qulonglong, 255)))`

We received and register the correct `guisp` value.

Interestingly, I'm not able to generate a `:hi` with property `undercurl`:
`:hi FooBar cterm=undercurl guisp=Blue`
`QMap(("special", QVariant(qulonglong, 255)))`

**Comment by YorickPeterse** [comment]
@jgehrig The `guisp` parameter specifies the color for just the underline/undercurl that is drawn. For example, this is using the TUI:

![Screenshot from 2021-05-14 15-54-20](https://user-images.githubusercontent.com/86065/118280646-b3ee5080-b4cc-11eb-82d3-7d85a840b296.png)

Here the highlight group is `SpellBad       xxx ctermbg=224 gui=bold,underline guifg=#cc3e28 guisp=blue`.

Here is what that currently looks like in neovim-qt:

![Screenshot from 2021-05-14 15-56-05](https://user-images.githubusercontent.com/86065/118280889-eac46680-b4cc-11eb-95b2-2ef9fd7bcf8a.png)

This is using the same highlight group, except neovim-qt seems to ignore the `guisp` setting, always rendering the underline using the text color.

**Comment by jgehrig** [comment]
@YorickPeterse

Okay, I see the issue...

The value for `undercurl` is correct:
![image](https://user-images.githubusercontent.com/11207308/118861217-41a1b580-b8aa-11eb-9d9c-bd0628a0efc1.png)
`:hi SpellBad ctermbg=224 gui=bold,undercurl guifg=#cc3e28 guisp=blue`

The value for `underline` is incorrect:
![image](https://user-images.githubusercontent.com/11207308/118861440-7f9ed980-b8aa-11eb-92cb-14a205aa8a69.png)
`:hi SpellBad ctermbg=224 gui=bold,underline guifg=#cc3e28 guisp=blue`

**Comment by jgehrig** [comment]
Changes merged, marking as closed.

I tested this quickly myself, but let me know if you still see issues
