### ISSUE TITLE
Bold font weight not applying on italic font

### ISSUE THREAD

**Issue by AnsonH** [equalsraf/neovim-qt#854]
I'm using the [MesloLGS NF][1] font with font weight of bold (`:b`) as configured in `ginit.vim`:
```
" Set Editor Font
if exists(':GuiFont')
    GuiFont MesloLGS NF:h10:b
endif
```

However, it seems like the bold font weight is not applying to the italicized font (pay attention to the italicized text in light blue):

![italic font not bolded](https://user-images.githubusercontent.com/57580593/118644262-3732dd80-b810-11eb-871f-c97dc655b03c.png)

However, I already got the bold italic font-face installed ([download link][2]). Here's a screenshot from **Windows Terminal** proving that I got the italic font-face properly installed:

![image](https://user-images.githubusercontent.com/57580593/118644868-d526a800-b810-11eb-8a07-e8e4ac51cc1f.png)

Here's some useful information about my environment:
- OS: Windows 10 version 20H2
- neovim-qt version: v0.2.16.1
- neovim version: v0.5.0-dev+1325-gdab6b08a1
- Color scheme: [vim-monokai-pro][3]

[1]: https://github.com/romkatv/powerlevel10k#manual-font-installation
[2]: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf
[3]: https://github.com/phanviet/vim-monokai-pro

**Comment by jgehrig** [comment]
@AnsonH 

Thanks for the bug report!

Yes, this is an issue with our logic. The fix should be easy and safe...

**Comment by jgehrig** [comment]
@AnsonH 

Fix merged, marking as closed. I tested this quickly myself and everything looks good.

Let me know if you still see issues with the latest build from `master`.
