### ISSUE TITLE
mac homebrew formula?

### ISSUE THREAD

**Issue by rkitover** [equalsraf/neovim-qt#86]
Hi, I noticed there is no mac homebrew formula for this project, I was thinking we could do something like [this](https://github.com/neovim/homebrew-neovim).

I am happy to write the formula for you guys if you are interested.

**Comment by equalsraf** [comment]
Go for it :D

I don't have a Mac where I can test though, I suspect there will be some issues with the keyboard Ctrl/Cmd keys.

**Comment by rkitover** [comment]
The cmd key is not really used in vim, the ctrl key is indeed borked.

The other issue is that the default font on mac is terrible, here is a screenshot:

![screenshot](https://www.dropbox.com/s/eynldi1k11e21rs/Screenshot%202016-01-24%2002.59.03.png?dl=1)

I'll try to send you a PR for these two things over the next few days.

**Comment by equalsraf** [comment]
> The cmd key is not really used in vim, the ctrl key is indeed borked.

According to the [Qt docs](http://doc.qt.io/qt-5/qt.html#Key-enum) the Qt::Key_Control is Cmd and Qt::Key_Meta is Ctrl. So its likely Cmd is being accepted as Ctrl key.

> The other issue is that the default font on mac is terrible, here is a screenshot:

We just set Monospace 10pt by default in shell.cpp.

**Comment by rkitover** [comment]
Just checked and cmd key does not function as a ctrl, but then cmd is a system key on macs so likely not mappable by applications, except for combos.

**Comment by rkitover** [comment]
I noticed you have no tags, the way homebrew formulae that get their sources from git work is that they reference a specific tag, and are constantly updated for new tags. The reason for this is so that when you do a `brew upgrade` you won't always rebuild the same thing needlessly and for stability reasons of course.

Would you be willing to push version tags occasionally? This would of course also help packagers for other systems.

**Comment by equalsraf** [comment]
Sure, just tagged v0.1.0

**Comment by gwerbin** [comment]
For those following this issue: I just wrote a formula

https://github.com/equalsraf/neovim-qt/issues/135

**Comment by equalsraf** [comment]
Closing for #135
