### ISSUE TITLE
Text is being vertically cut off, and shifted upwards

### ISSUE THREAD

**Issue by K4LCIFER** [equalsraf/neovim-qt#861]
![image](https://user-images.githubusercontent.com/7829231/119905863-8aa5d980-bf3c-11eb-9be5-1df9fed5edd3.png)
![image](https://user-images.githubusercontent.com/7829231/119905873-92fe1480-bf3c-11eb-802e-7cbf7081cbbc.png)
![image](https://user-images.githubusercontent.com/7829231/119905900-a315f400-bf3c-11eb-9da4-5b6338aae5fb.png)
![image](https://user-images.githubusercontent.com/7829231/119906387-a5c51900-bf3d-11eb-9d0e-063815e57d41.png)
 As you can see in these images, some of the text/characters are being shifted upwards, so they end up being cut off. As seen below, the issue doesn't present when running nvim in the terminal.
![image](https://user-images.githubusercontent.com/7829231/119906049-fa1bc900-bf3c-11eb-90f6-2c414c2ddf52.png)
![image](https://user-images.githubusercontent.com/7829231/119906064-fee07d00-bf3c-11eb-809d-5fd3c35083bf.png)
![image](https://user-images.githubusercontent.com/7829231/119906075-03a53100-bf3d-11eb-970b-5f4cd5cf416f.png)

**Comment by K4LCIFER** [comment]
Turns out the issue has to do with the Monospace font. I changed it to Source Code Pro, and the problem seems to be fixed now. Not sure whats up with the monospace font, but it seems that it has the same issue in the regular terminal as well if I change the font there. Must be a bug with the font in the system.

**Comment by jgehrig** [comment]
@K4LCIFER

Glad you found a workaround!

Yes, it looks like those characters are not monospace; the special characters extend beyond the bounds of their respective cells.

It sounds like this is an issue with the specific font... Can we close this bug?
