### ISSUE TITLE
undercurl doesn't render smoothly

### ISSUE THREAD

**Issue by YorickPeterse** [equalsraf/neovim-qt#870]
This is a bit nit picky, but here's how undercurls are rendered in GNOME terminal:

![terminal](https://user-images.githubusercontent.com/86065/123429856-bf529280-d5c7-11eb-9410-e8181ee4254d.png)

Note how the undercurl is rendered smoothly. nvim-qt on the other hand renders it in a more messy way:

![nvim-qt](https://user-images.githubusercontent.com/86065/123429909-cd081800-d5c7-11eb-9cb2-c1e6e952084e.png)

It looks like each character is given it's own undercurl, with the spacing in between caused by the spacing between characters; instead of there being a single smooth line below all the characters.

nvim version: `NVIM v0.5.0-dev+1405-g2f0e5e7e6`
nvim-qt version: `NVIM-QT v0.2.17.9999`
OS: Arch Linux

**Comment by jgehrig** [comment]
Thanks for the bug report!

I thought these issues were resolved with #803...

A few questions:
1. What is the output of `nvim-qt --version`?
2. Is this the latest release from `master`?
3. Does the rendering vary with `:GuiRenderLigatures?
4. Do you have display scaling enabled?

Here is what I see:
![image](https://user-images.githubusercontent.com/11207308/123445663-1d6e7e00-d5a6-11eb-992e-abc2dfb9516c.png)

Related: #802

**Comment by YorickPeterse** [comment]
@jgehrig 

> What is the output of nvim-qt --version?

```
NVIM-QT v0.2.17.9999
Build type: Release
Compilation:-D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Wno-unused-parameter -Wunused-variable -std=c++11
Qt Version: 5.15.2
Environment: 
  nvim: nvim
  args: --cmd set termguicolors
  runtime: 

NVIM v0.5.0-dev+1405-g2f0e5e7e6
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/yorickpeterse/.cache/yay/neovim-git/src/build/config -I/home/yorickpeterse/.cache/yay/neovim-git/src/neovim-git/src -I/usr/include -I/home/yorickpeterse/.cache/yay/neovim-git/src/build/src/nvim/auto -I/home/yorickpeterse/.cache/yay/neovim-git/src/build/include
Compiled by yorickpeterse@sharkie

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

> Is this the latest release from master?

I'm running commit https://github.com/equalsraf/neovim-qt/commit/3eb6f51918ebd7eb1f3d97af84cc2a599b5988c7

> Does the rendering vary with :GuiRenderLigatures?

Enabling it improves the rendering a tiny bit, but not much:

![Screenshot from 2021-06-25 19-20-22](https://user-images.githubusercontent.com/86065/123462301-6cd69d80-d5ea-11eb-8cdd-bb7e49c86a3a.png)

> Do you have display scaling enabled?

Yes, I use a HiDPI display. Not sure what the exact scaling factor is, probably just 2x.

**Comment by jgehrig** [comment]
@YorickPeterse

Does #871 resolve your undercurl rendering issues?

**Comment by YorickPeterse** [comment]
@jgehrig That looks much better, thanks! :smile:
