### ISSUE TITLE
Render of mêlée is not ideal with `GuiRenderLigature 1`

### ISSUE THREAD

**Issue by kierun** [equalsraf/neovim-qt#872]
Using nvim-qt, I get this:

![screenshot](https://user-images.githubusercontent.com/3079575/124256316-10f8a100-db23-11eb-9be0-ff67c8191ff6.png)

Using the console nvim, I get this:

![screenshot-console](https://user-images.githubusercontent.com/3079575/124256423-2f5e9c80-db23-11eb-9bfd-b5501df36136.png)

Note that the font is the same in both instances so it should render fine. 

Setting `GuiRenderLigature 0` instead of 1 makes the problem vanish.

```bash
NVIM-QT v0.2.17.9999
Build type:
Compilation: -Wall -Wextra -Wno-unused-parameter -Wunused-variable -std=c++11
Qt Version: 5.15.2
Environment:
  nvim: nvim
  args: --cmd let &rtp.=',/home/yann/bin/../share/nvim-qt/runtime' --cmd set termguicolors
  runtime: /home/yann/bin/../share/nvim-qt/runtime

NVIM v0.5.0-dev+1455-gf83c25942
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/home/yann/src/neovim/build/config -I/home/yann/src/neovim/src -I/home/yann/src/neovim/.deps/usr/include -I/usr/include -I/home/yann/src/neovim/build/src/nvim/auto -I/home/yann/src/neovim/build/include
Compiled by yann@nightwatch.neverness.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/yann/nvim/share/nvim"

Run :checkhealth for more info
```

**Comment by jgehrig** [comment]
I cannot reproduce this issue.

What platform? (MacOS or Linux)
What font?
Does this issue appear for all fonts?

This looks like another rendering scenario that may be fixed by #781.

Sorry, I've procrastinated on that change... I don't like the code.

That PR essentially adds yet-another rendering code path. Ligatures are tricky!

**Comment by kierun** [comment]
> What platform? (MacOS or Linux)

Fedora 34. `5.12.13-300.fc34.x86_64 #1 SMP Wed Jun 23 16:18:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

> What font?

Pragmata Pro

> Does this issue appear for all fonts?

Of course not… Stupid font I use… It works fine on `Monoid Nerd Font`.

Yeah, we can close this. Apologies for the noise.

**Comment by jgehrig** [comment]
No worries!

Sorry for the delays with PR 781... I need to finish that work.
