### ISSUE TITLE
VimLeave(Pre) not triggered on Windows

### ISSUE THREAD

**Issue by MIvanchev** [equalsraf/neovim-qt#874]
Hi, I'm using the pre-built binaries. The following is never executed (file not created):

```
au VimLeave * mksession!
au VimLeavePre * mksession!
au VimLeave * mksession! $USERPROFILE/session.vim
au VimLeavePre * mksession! $USERPROFILE/session.vim
```

In general, I cannot get any indication that VimLeave is ever triggered.

```
NVIM v0.5.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 -DNVIM_TS_HAS_SET_MATCH_LIMIT /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compiled by runneradmin@fv-az152-786

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

**Comment by jgehrig** [comment]
I cannot reproduce this issue:

1. Open `nvim-qt`
2. Enter vim command `:au VimLeave * mksession! $USERPROFILE/session.vim`
3. Exit `:q`
4. New file `$USERPROFILE/session.vim`

For me, the file exists...

I'm assuming `session.vim` is never created on your machine.

> I'm using the pre-built binaries.

Can you elaborate further?

How did you install neovim and neovim-qt?

Are commands like `:call GuiClose()` or `:GuiFont` present?

**Comment by MIvanchev** [comment]
Hey! You are correct, the file is never created!

I got the binaries from here https://github.com/neovim/neovim/releases/download/v0.5.0/nvim-win64.zip. Just unpacked it on my test machine (Windows 7). `au VimLeave` gives me `call GuiClose()`. My `ginit.vim` is:

```
" Set Editor Font
if exists(':GuiFont')
    " Use GuiFont! to ignore font errors
    GuiFont! LiterationMono NF:h11
endif

" Disable GUI Tabline
if exists(':GuiTabline')
    GuiTabline 0
endif
```

**Comment by jgehrig** [comment]
Okay, good. I'm assuming two things:
1. `GuiFont` is present (indicates the shim commands are properly loaded).
2. Your install is good (Sometimes people try to install from strange sources).

Interesting...

I just downloaded and extracted from that link, and the file is created. No repro with Win10.

Can you be more explicit about what you are trying?

Usually, it helps to provide a `minimal.vim` that demonstrates the issues. `nvim-qt -- -u minimal.vim`

**Comment by MIvanchev** [comment]
Hi, again, thanks for your support, I started disabling my plugins one by one and eventually traced the issue to https://github.com/preservim/nerdtree/issues/1108. All good now :) Thanks again.

**Comment by jgehrig** [comment]
No problem! :)

I'm glad to hear you solved the issue.

**Comment by MIvanchev** [comment]
Yes, I'm always quick to pin the blame on others :)
