### ISSUE TITLE
Neovim QT does not have an option to change default font

### ISSUE THREAD

**Issue by duytrung** [equalsraf/neovim-qt#877]
Hello,
Please consider this issue,
```
    nvim --version: v0.6.0-dev+3-gd791274a9
    vim -u DEFAULTS (version: ) behaves differently? No
    Operating system/version: Windows 10
    Terminal name/version: Windows 10 CMD - or Neovim Qt
    $TERM:

#Actual behaviour

Neovim Qt GUI does not have a right-click menu to allow changing default font from Consolas to the other fonts

#Expected behaviour

I'm not sure whether this is a bug of Neovim-Qt so I would like to request for this feature in Neovim-qt GUI.
```
Thanks for considering the issue

**Comment by jgehrig** [comment]
Are you asking specifically for the ability to set the gui font from a right click menu?

Why do you want this feature? Is there an equivalent feature in gVim?

---

Just for the sake of being explicitly clear:

The default font can be changed. There are `:set guifont=*` and `:GuiFont *` which pop a font selection dialogs or allow the user to specify a font.

**Comment by duytrung** [comment]
Hi @jgehrig ,

I forgot to run the nvim.exe instead of Neovim-qt.exe. Nvim.exe did have a function to change the font as vim.exe.

Sorry for not considering the problem thoroughly.

![image](https://user-images.githubusercontent.com/2046672/125187704-14510280-e270-11eb-92f5-0b27ed2f7e08.png)

![image](https://user-images.githubusercontent.com/2046672/125187712-1fa42e00-e270-11eb-8ae8-b1e5221573d5.png)

Here is the nvim.exe with default font changed.

![image](https://user-images.githubusercontent.com/2046672/125187761-45313780-e270-11eb-8c27-ce65a4c62d07.png)

I haven't used all of the functionality of neovim. My apology :-)
