### ISSUE TITLE
:Gui commands missing even with NeovimQt runtime

### ISSUE THREAD

**Issue by dave-kennedy** [equalsraf/neovim-qt#879]
When I run the app, it is extremely barebones and missing most of the :Gui commands listed on [this page](https://github.com/equalsraf/neovim-qt/wiki/Configuration-Options):

![image](https://user-images.githubusercontent.com/13735532/125205184-42b5ea00-e23e-11eb-8aac-f8ec9ea709e4.png)

You can see the runtime listed in the output of `nvim-qt --version` in the terminal window behind the app. The contents of that directory are:

```
% tree -a /usr/local/Cellar/neovim-qt/0.2.16/nvim-qt.app/Contents/MacOS/../Resources/runtime
/usr/local/Cellar/neovim-qt/0.2.16/nvim-qt.app/Contents/MacOS/../Resources/runtime
├── doc/
│   ├── nvim_gui_shim.txt
│   └── tags
├── plugin/
│   └── nvim_gui_shim.vim
└── README.md

2 directories, 4 files
```

Here's my `runtimepath` with newlines inserted for readability:

```
runtimepath=~/.config/nvim,
/etc/xdg/nvim,
~/.local/share/nvim/site,
/usr/local/share/nvim/site,
/usr/share/nvim/site,
/usr/local/Cellar/neovim/0.5.0/share/nvim/runtime,
/usr/local/Cellar/neovim/0.5.0/share/nvim/runtime/pack/dist/opt/matchit,
/usr/local/Cellar/neovim/0.5.0/lib/nvim,
/usr/share/nvim/site/after,
/usr/local/share/nvim/site/after,
~/.local/share/nvim/site/after,
/etc/xdg/nvim/after,
~/.config/nvim/after,
/usr/local/Cellar/neovim-qt/0.2.16/nvim-qt.app/Contents/MacOS/../Resources/runtime
```

Nothin in .config/nvim or .local/share/nvim except a swap file for the empty buffer.

**Comment by jgehrig** [comment]
You're not on the latest release.

You'll need to update to get some of the more recent `:Gui...` commands. Some of those commands are only available in the latest version from `master`.

See https://github.com/equalsraf/neovim-qt#macos:
```
$ brew tap equalsraf/neovim-qt
$ brew install --HEAD neovim-qt
```

Note: I just updated that README, `--HEAD` was missing.
