### ISSUE TITLE
Travis MacOS CI Down

### ISSUE THREAD

**Issue by jgehrig** [equalsraf/neovim-qt#881]
@equalsraf

It looks like the Travis CI is down. I don't have access to investigate.

Examples:
https://github.com/equalsraf/neovim-qt/commit/84721b6d5935bbd1b747e5d0aae31ba046883ded
https://github.com/equalsraf/neovim-qt/pull/875

It looks like a domain change:
> Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.

Banner pulled from an older commit :
https://github.com/equalsraf/neovim-qt/commit/09ba8f8eda6261ba18a0577b07edee5fdc169126

Maybe we should use this as an opportunity to move our MacOS CI over to GitHub Actions?

**Comment by equalsraf** [comment]
> Maybe we should use this as an opportunity to move our MacOS CI over to GitHub Actions?

+1

It seems like the domain was not the only thing changing. I tried to quickly re-enable it but there are some new issues in there to enable github repos.
