### ISSUE TITLE
Request to add support for ginit.lua

### ISSUE THREAD

**Issue by peppermilldetective** [equalsraf/neovim-qt#883]
Since base Neovim now supports both init.vim and init.lua, it would be great if Neovim-qt could also support either ginit.vim or ginit.lua as a configuration file.

**Comment by jgehrig** [comment]
Are there any functional differences between `init.vim` vs `init.lua`?

Can a user have `init.vim` and `init.lua`? What is the conflict behavior?

If there is no functional difference... I'm hesitant to add this feature.

It would be one more thing to test and maintain, and I don't see a big advantage other than the ability to use a different filename.

**Comment by peppermilldetective** [comment]
Functional differences depend on use case. In my experience, I've enjoyed and had an easier time using lua than I ever did with vimscript, but YMMV. Typically, if your config is 90% keybinds then vimscript is okay. However, settings, functions, and basically everything else has been improved in lua with the introduction of modularity via `require(<lua file>)` as well as Neovim's change to putting all options behind `vim.opt` (e.g. `vim.opt.tabstop = 4`). Further, lua has been faster as a config for me for startup purposes, and more and more neovim plugins have been migrating to lua and supporting lua first.

**However**, functionally speaking you can achieve an "init.lua" effect with "init.vim" via:
```
lua <<< EOF
-- STUFF
EOF
```

I am not sure of the performance differences of doing it this way vs raw `init.lua`. While it allows us to make use of lua, it has to start in Vimscript land, and I do not know how much of a hit it takes to do that.

For the questions:

> Are there any functional differences between `init.vim` vs `init.lua`?

Performance wise, yes. Functionality wise, maybe (modularity is _way_ easier). Overall, maybe. It's mostly a "keep things consistent" change since with Vim going from `vim` to `vim-qt` is migrating from `init.vim` to `ginit.vim`, so migrating from `nvim` to `nvim-qt` would imply `init.lua` -> `ginit.lua`. I still need to find the time to see the performance difference, if any, between `init.lua` and an `init.vim` with `lua <<< EOF`.

Beyond that, with `init.vim` with `lua <<< EOF`, a lua lsp doesn't work in the file since it's a vim file (nvim-lspconfig does have support for vimscript, treesitter does not, lspconfig does not support lua inside vimscript from what I can see), but that's one file and not a big deal.

> Can a user have `init.vim` and `init.lua? What is the conflict behavior?

No. According to `:h init.lua`:

> It can be a Vimscript or Lua file named "init.vim" or "init.lua" respectively. It is an error to use both at the same time.

To me, "Adding support for ginit.lua" vs "Another thing to test and maintain" comes out even with a little in favor to "Adding support for ginit.lua", but that's because I favor UX and consistency and have enjoyed lua _way more_ than vimscript. At the end of the day, however, I'm neither a contributor nor have the time to be one, so I understand and won't complain if this gets shelved/closed.

**Comment by jgehrig** [comment]
@peppermilldetective 

Thank you for the detailed write-up. This is helpful.

It sounds like this will be a non-trivial change. We'll need a mechanism to only load one configuration file. There is also the potential forcompatibility issues with the current shim layer written in vimscript.

I'm not opposed this feature, but I don't have any immediate plans to implement this myself. If enough folks want this, maybe I will re-evaluate in the future.

To anyone else interested in this feature: Pull Requests welcomed :)

**Comment by pidgeon777** [comment]
This seems to be a good idea. A `ginit.lua` feature.

**Comment by j-xella** [comment]
> there's no need for this. You can call any Lua function or module from a UIEnter handler:
> 
> ```
> au UIAttach * lua require('ginit')
> ```
> 
> Put ginit.lua anywhere on 'runtimepath', in a lua/ directory.

To make this solution even better, add `++once` to remove this event after the first run - there is no point running it again, because `require` works once anyway :

```
au UIAttach * ++once lua require('ginit')
```

and, as a bonus, the same in pure lua  :

```
vim.api.nvim_create_autocmd( "UIEnter", {
    once = true,
    callback = function() require "ginit" end
  } )
```

**Comment by hinell** [comment]
The feature is undocumented in wiki. This should be fixed!

**Comment by przepompownia** [comment]
neovim/neovim#22382 could be useful when ready.
