### ISSUE TITLE
[Bug] Setting MYGVIMRC has no effect when loading Neovim

### ISSUE THREAD

**Issue by pidgeon777** [equalsraf/neovim-qt#887]
`:version`:

````log
NVIM v0.6.0-dev+14-gdf33f30e8
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 -DNVIM_TS_HAS_SET_MATCH_LIMIT /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compilato da runneradmin@fv-az152-786

Features: -acl +iconv +tui
See ":help feature-compile"

   file vimrc di sistema: "$VIM\sysinit.vim"
         $VIM di riserva: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
````

`sysinit.vim`:

````
if has('win32')
    let $MYGVIMRC = fnamemodify(expand("$VIM"), ':h:h') . '\ginit.vim'                             " Set $MYGVIMRC to point to the ginit.vim file
endif
````

The issue is that setting `$MYGVIMRC` doesn't seem to produce any effect (checked for example by adding random strings to the specified `ginit.vim`: no error is generated when starting Neovim).

**Comment by jgehrig** [comment]
I think `$MYGVIMRC` is a Vim-only option.

[Vim Documentation](https://github.com/vim/vim/blob/90df4b9d423485f7db16e3a65cab4f14edc815ae/runtime/doc/gui.txt)
[Neovim Documentation](https://github.com/neovim/neovim/blame/bd7a0b46a9daefe36e914136d6ce347a76efc57d/runtime/doc/gui.txt)

I can't follow the steps you've provided. Can you add more detail? What are you trying to accomplish?

On Windows, `ginit.vim` should be placed in `%LOCALAPPDATA%\nvim\ginit.vim`. It is loaded without any special configuration.

**Comment by jgehrig** [comment]
Marking as closed, since Neovim does not support `MYGVIMRC`.

Feel free to keep commenting, or re-open if this is still an issue.

**Comment by pidgeon777** [comment]
What I wanted to accomplish, is a way to specify a different location for the `ginit.vim` file, instead of the default Windows location (`%LOCALAPPDATA%\nvim\ginit.vim`).

How could this be accomplished?
