### ISSUE TITLE
Window title doesn't follow `titlestring`

### ISSUE THREAD

**Issue by zoumi** [equalsraf/neovim-qt#904]
I had
```
set titlestring=%F%m%r%=%l/%L-%P
```
But neovim-qt always add ' - Neovim' at the end of window title.

**Comment by jgehrig** [comment]
Good point!

The `:set title` behavior is somewhat odd:
![image](https://user-images.githubusercontent.com/11207308/127596629-cd34bc17-ed09-48d1-8517-efed84506933.png)

This is the root-cause:
https://doc.qt.io/qt-5/qwidget.html#windowTitle-prop

> On some desktop platforms (including Windows and Unix), the application name (from QGuiApplication::applicationDisplayName) is added at the end of the window title, if set. This is done by the QPA plugin, so it is shown to the user, but isn't part of the windowTitle string.

It looks like the behavior can be changed by removing this line:
```C++
setApplicationDisplayName("Neovim");
```

However, removing that line will impact the `:set notitle case`:
![image](https://user-images.githubusercontent.com/11207308/127596845-741495a2-3a84-47a0-b46c-e704b17c8a81.png) 
![image](https://user-images.githubusercontent.com/11207308/127596972-d770d95e-080c-4717-864b-c932b6b7cf48.png)


A git-blame suggests that line is from the original implementation.

**Comment by jgehrig** [comment]
I think we can fix this... However, we will need to be careful about how this is done.

Simply removing the line is not enough.

I'd like to see:
-  `Neovim` for the `:set notitle` case.
- `{titlestring}` for the `:set title` case
