### ISSUE TITLE
[Feature Request]Set font by windows registry

### ISSUE THREAD

**Issue by zoumi** [equalsraf/neovim-qt#905]
When neovim-qt starts up, I can see that it's font switch from default font to the one I specified in ginit.vim.
It will be perfect that neovim-qt can load desired font directly.

**Comment by jgehrig** [comment]
Already done in cafc9ca9f03e7f4104cc81c0330ae220e5f23497 :)

It also works on MacOS/Linux with config files, we use `QSettings`.

You can download an "Actions" build of the latest `master` commit:
https://github.com/equalsraf/neovim-qt/actions/runs/1069804006

**Comment by zoumi** [comment]
@jgehrig Sorry, I can't find any option like "ext_guifont", so what exactly is that option for Windows OS?
