### ISSUE TITLE
[FEATURE REQUEST] File name of an active file on a title bar

### ISSUE THREAD

**Issue by grappas** [equalsraf/neovim-qt#914]
For an easier recognition of opened file on a taskbar (even instead of "Neovim" name).
![obraz](https://user-images.githubusercontent.com/1036957/128091474-c55cbc72-26eb-44dd-aadc-9ce219d4d5d9.png)

**Comment by jgehrig** [comment]
Already supported, try adding `:set title` to your init.vim :)

**Comment by grappas** [comment]
Posting issues here is actually better than googling it 🤔
