### ISSUE TITLE
Ninja build failed: usr/bin/ld: error: lto-wrapper failed due to lto1: internal compiler error: Segmentation fault

### ISSUE THREAD

**Issue by kierun** [equalsraf/neovim-qt#915]
I just pulled `main` at `commit 69d2246bacbb7137be329413fd55ebab837e2aaa` and ran `ninja` which I use to build. It crashed with:

```bash
√ (master|…56); ninja
[1/3] Linking CXX executable bin/nvim-qt
FAILED: bin/nvim-qt
: && /usr/bin/c++ -Wall -Wextra -Wno-unused-parameter -Wunused-variable -std=c++11 -flto -fno-fat-lto-objects -rdynamic src/gui/CMakeFiles/nvim-qt.dir/nvim-qt_autogen/mocs_compilation.cpp.o src/gui/CMakeFiles/nvim-qt.dir/main.cpp.o src/gui/CMakeFiles/nvim-qt.dir/qrc_data.cpp.o -o bin/nvim-qt  third-party/libmsgpackc.a  lib/libneovim-qt-gui.a  /usr/lib64/libQt5Svg.so.5.15.2  lib/libqshellwidget.a  /usr/lib64/libQt5Widgets.so.5.15.2  /usr/lib64/libQt5Gui.so.5.15.2  lib/libneovim-qt.a  /usr/lib64/libQt5Network.so.5.15.2  /usr/lib64/libQt5Core.so.5.15.2  third-party/libmsgpackc.a && :
lto1: internal compiler error: Segmentation fault
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
lto-wrapper: fatal error: /usr/bin/c++ returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
[3/3] Linking CXX executable bin/tst_shell
ninja: build stopped: subcommand failed.
```

In the "old" version I have running, (`v0.2.17.9999`), I get a warning when I start it: `Qt: Session management error: Could not open network socket` which I did not used to get. this might or might not be related…

I am running Fedora 34 (`5.13.7-200.fc34.x86_64`). It is possible some packages got updates as I ran a `dnf upgrade` today.

Anything else you need from me?

**Comment by jgehrig** [comment]
@kierun That is an interesting bug!

I think the combination of our source code and your environment crash the compiler itself...

69d2246bacbb7137be329413fd55ebab837e2aaa is rather innocuous, it doesn't pull in any new dependencies.

Which compiler are you using? 
What is the compiler version?
What version of cmake?

---

**Ideas for working around this issue**

- Update all packages and reboot (probably won't do anything)
- Disable LTO (b813471ec04afb391c34921dd27fea5c169323e7)
- Upgrade your compiler version
- Switch between GCC and Clang

Here is how our CI changes the compiler:
https://github.com/equalsraf/neovim-qt/blob/69d2246bacbb7137be329413fd55ebab837e2aaa/.github/workflows/build-test.yml#L131-L134

**Comment by kierun** [comment]
> @jgehrig That is an interesting bug!

De nada. I aim to please! :grin:

Versions:

```bash
√ (master|…56); /usr/bin/c++ --version
c++ (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1)
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

√ (master|…56); cmake --version
cmake version 3.20.5

CMake suite maintained and supported by Kitware (kitware.com/cmake).
√ (master|…56); ninja --version
1.10.2
```

> I think the combination of our source code and your environment crash the compiler itself...

Even stranger than that: I did the following:

```bash
mv build build.bak
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=$HOME -G Ninja ..
ninja
NVIM_QT_RUNTIME_PATH=../src/gui/runtime ./bin/nvim-qt
```

It worked just fine apart from the `Qt: Session management error: Could not open network socket` line which does not seem to make any difference to anything. My apologies, I should have tried that first! Been a while since I deleted `build` at all.

So yeah, weird. Still, feel free to close this.

**Comment by jgehrig** [comment]
> It worked just fine apart from the Qt: Session management error: Could not open network socket line which does not seem to make any difference to anything.

I searched this error, and this error looks related to general Qt configuration:
https://stackoverflow.com/questions/986964/qt-session-management-error

I'd try (temporarily) clearing your Desktop Manager settings...

> My apologies, I should have tried that first! Been a while since I deleted build at all.

No apology required! Your bug reports are greatly appreciated :smiley:

Side note: I still need to fix the ligature issues still... I'm avoiding the hard problem :/

**Comment by jgehrig** [comment]
Marking as closed.

Feel free to keep commenting about `Qt: Session management error: Could not open network socket`

**Comment by kierun** [comment]
> Side note: I still need to fix the ligature issues still... I'm avoiding the hard problem :/

:grin: I know that feeling well… 

Thank you!
