### ISSUE TITLE
Cannot map <C-Space>

### ISSUE THREAD

**Issue by przepompownia** [equalsraf/neovim-qt#917]
For example
```vim
nmap <C-space> <Cmd>echom tempname()<CR>
```
works on pure nvim (`nvim -u NONE`), doesn't work on nvim-qt d9c9aa4 (`nvim-qt -- -u NONE`).

Using `git bisect` I found that the regression comes from 85ade6728307645a22491d3673af06e82d2ee909.

**Comment by jgehrig** [comment]
@przepompownia 

You are correct. Thank you for the bug report and debug work!

I will put out a fix for this issue shortly.

I will also add test coverage for `<C-Space>`, so this isn't regressed again in the future.

**Comment by jgehrig** [comment]
This issue only impacts Linux:
```
QKeyEvent ev: QKeyEvent(KeyPress, Key_Space, ControlModifier, text="\u0000")
   "<C-\u0000>"
```

Other platforms work fine.

---

MacOS is working correctly:
```
QKeyEvent ev: QKeyEvent(KeyPress, Key_Space, MetaModifier)
   "<C-Space>"
```

Windows is working correctly:
```
QKeyEvent ev: QKeyEvent(KeyPress, Key_Space, ControlModifier, text=" ")
   "<C-Space>"
```

**Comment by jgehrig** [comment]
@przepompownia 

Please let me know if the Pull Request above fixes this issue on your machine.

You can download a Linux AppImage here:
https://github.com/equalsraf/neovim-qt/actions/runs/1126435432

**Comment by przepompownia** [comment]
I built it from source in the same way as I do it usually. It seems to fix the bug :+1:

**Comment by przepompownia** [comment]
> This issue only impacts Linux:

That's right: I did not add that it occurred on Debian.

**Comment by jgehrig** [comment]
Thanks for the bug report!

I've merged the fix, marking as closed.

**Comment by przepompownia** [comment]
@jgehrig thank you for fixing!
