### ISSUE TITLE
nvim crash when quitting nvim-qt in insert mode

### ISSUE THREAD

**Issue by kwon-young** [equalsraf/neovim-qt#92]
I have installed latest neovim and and neovim-qt on fedora.
I want to use on instance of neovim as a server and connect multiple neovim-qt client.
so i did:
```
NVIM_LISTEN_SERVER=/tmp/nvim nvim --embed -u -None
```
Then start multiple time neovim-qt:
```
nvim-qt --server /tmp/nvim
```
If if quit neovim-qt with the quit button while on normal mode, everything is fine.
But when i quit while on insert mode, nvim crash:
```
13548 abort (core dumped)  nvim --embed -u -None
```

**Comment by equalsraf** [comment]
Cheers @kwon-young, I've reported this in Neovim.

**Comment by kwon-young** [comment]
I have redone a test of this issue with the latest neovim-qt and neovim 0.1.4 and neovim doesn't crash anymore.
Do i close this issue ?

**Comment by equalsraf** [comment]
Sure but the issue as reported in neovim/neovim#4163 (without --embed) still happens in 0.1.4 and with the current master.

**Comment by justinmk** [comment]
@equalsraf Did you get a chance to try https://github.com/neovim/neovim/issues/4163#issuecomment-228359833 ?
