### ISSUE TITLE
Allow changing font size via hotkey

### ISSUE THREAD

**Issue by savchenko** [equalsraf/neovim-qt#921]
Having something like `GuiFontIncrease` and `GuiFontDecrease` would be handy when one needs to change the font size on the fly.

These can be mapped by a user to any arbitrary key combination.

**Comment by jgehrig** [comment]
This should be easy to accomplish with VimScript. I don't think it makes sense to support this feature in the GUI.

See #913, for some details on how you can implement this behavior in your personal vimrc.

Marking as closed.
