### ISSUE TITLE
GuiShowContextMenu is incompatible with mswin.vim

### ISSUE THREAD

**Issue by fekir** [equalsraf/neovim-qt#922]
# Additional information

````
nvim --version
NVIM v0.4.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-eK2ojg/neovim-0.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-eK2ojg/neovim-0.4.4/build/config -I/build/neovim-eK2ojg/neovim-0.4.4/src -I/usr/include -I/usr/include/lua5.1 -I/build/neovim-eK2ojg/neovim-0.4.4/build/src/nvim/auto -I/build/neovim-eK2ojg/neovim-0.4.4/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
````

Output of checkhealth

````
health#nvim#check
========================================================================
## Configuration
  - WARNING: Missing user config file: /home/df0/.config/nvim/init.vim
    - ADVICE:
      - :help |nvim-from-vim|

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='6203'
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 10ms
  - INFO: $TERM: screen-256color
  - WARNING: Neither Tc nor RGB capability set. True colors are disabled. |'termguicolors'| won't work properly.
    - ADVICE:
      - Put this in your ~/.tmux.conf and replace XXX by your $TERM outside of tmux:
          set-option -sa terminal-overrides ',XXX:RGB'
      - For older tmux versions use this instead:
          set-option -ga terminal-overrides ',XXX:Tc'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/bin/python does not have the "neovim" module. :help |provider-python|
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/bin/python3
  - INFO: Other python executable: /bin/python3
  - INFO: Python version: 3.9.2
  - INFO: pynvim version: 0.4.2 (outdated; from /usr/lib/python3/dist-packages/neovim)
  - WARNING: Latest pynvim is NOT installed: 0.4.3

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-gnu]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - WARNING: `node` and `npm` (or `yarn`) must be in $PATH.
    - ADVICE:
      - Install Node.js and verify that `node` and `npm` (or `yarn`) commands work.
````

````
nvim-qt --version
NVIM-QT v0.2.16.0
Build type: Release
Compilation:-g -O2 -fdebug-prefix-map=/build/neovim-qt-tKBgNt/neovim-qt-0.2.16=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wno-unused-parameter -std=c++11 -Wfatal-errors
Qt Version: 5.12.5
Environment: 
  nvim: nvim
  args: --cmd let &rtp.=',/usr/share/nvim-qt/runtime' --cmd set termguicolors
  runtime: /usr/share/nvim-qt/runtime

NVIM v0.4.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-eK2ojg/neovim-0.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-eK2ojg/neovim-0.4.4/build/config -I/build/neovim-eK2ojg/neovim-0.4.4/src -I/usr/include -I/usr/include/lua5.1 -I/build/neovim-eK2ojg/neovim-0.4.4/build/src/nvim/auto -I/build/neovim-eK2ojg/neovim-0.4.4/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

````

### cut
1) remove all configuration files (or put only the content of step 3 in a config file)
2) start nvim-qt
3) write `:source $VIMRUNTIME/mswin.vim`, `:set mouse=a` and `:inoremap <silent><RightMouse> <Esc>:call GuiShowContextMenu()<CR>`
4) add some text in insert mode
5) `ctrl+A` to select everything and enter insert mode
6) left mouse click
7) click on cut
8) selected text is replaced by `"+x`

### copy
1) remove all configuration files (or put only the content of step 3 in a config file)
2) start nvim-qt
3) write `:source $VIMRUNTIME/mswin.vim`, `:set mouse=a` and `:inoremap <silent><RightMouse> <Esc>:call GuiShowContextMenu()<CR>`
4) add some text in insert mode
5) `ctrl+A` to select everything and enter insert mode
6) left mouse click
7) click on copy
8) selected text is replaced by `"+y`

### paste
1) remove all configuration files (or put only the content of step 3 in a config file)
2) start nvim-qt
3) write `:source $VIMRUNTIME/mswin.vim`, `:set mouse=a` and `:inoremap <silent><RightMouse> <Esc>:call GuiShowContextMenu()<CR>`
4) add some text (different that `"+gP`) in insert mode, then delete it (for example with `dd`, or with the context menu by selecting cut)
5) `ctrl+A` to select everything and enter insert mode
6) left mouse click
7) click on paste
8) the text `"+gP` is inserted, not what has been cutted (with `dd` or context menu)

## expected behavior

Cut to work like when using `ctrl+x`, copy to work like `ctrl+c` and paste to work like `ctrl+v` (since I've `source $VIMRUNTIME/mswin.vim`).
The mentioned keyboard shortcuts do work as expected (I've also used those for posting here the output of `:checkhealth`)

**Comment by jgehrig** [comment]
I cannot reproduce this issue. I've tried the steps you provided, and Copy/Paste/Cut/SelectAll all work for me.

This looks like a configuration issue to me...

---
**A few comments:**

You're on two old releases, I'd recommend updating both `nvim` and `nvim-qt`.
 - https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip (Nighly)
 - https://github.com/equalsraf/neovim-qt/suites/3497863946/artifacts/83338097 (Latest Commit)

Each context menu entry inserts keystrokes for the respective command. For example paste does `"+gP`. It looks like the keystrokes are inserted before returning to `Normal` mode in your configuration.

I don't think `dd` will work, that will put content into the wrong register, `"` not `+`. 

You only mapped for insert mode. (I assume for bug-demo purposes only)

The following lines should be in you `%LOCALAPPDATA%\nvim\ginit.vim` file:
```
nnoremap <silent><RightMouse> :call GuiShowContextMenu()<CR>
inoremap <silent><RightMouse> <Esc>:call GuiShowContextMenu()<CR>
vnoremap <silent><RightMouse> :call GuiShowContextMenu()<CR>gv
set mouse=a
```

**Comment by fekir** [comment]
Thank you for the fast response.

As you gave me links for Windows, I've tested it now on it:

https://github.com/equalsraf/neovim-qt/suites/3497863946/artifacts/83338097 the installer works, but nvim-qt fails to start (it cannot find VCRUNTIME140_1D.dll, and then other libraries)

So I've installed nvim with chocolatey, as I know that it bundles together nvim-qt.


My `%LOCALAPPDATA%\nvim\ginit.vim` is

````
nnoremap <silent><RightMouse> :call GuiShowContextMenu()<CR>
inoremap <silent><RightMouse> <Esc>:call GuiShowContextMenu()<CR>
vnoremap <silent><RightMouse> :call GuiShowContextMenu()<CR>gv
set mouse=a
source $VIMRUNTIME/mswin.vim
````

there are no other config files in my user environment.

(yes, before I did write only `inoremap` to reduce the scope)


Unfortunately I have exactly the same behavior (and this time on Windows, before I tested only on Debian.):

* cut writes `"+x`
* copy writes `"+y`
* paste writes `"+gP`

version of nvim

````
:version                                                                                                                NVIM v0.5.0                                                                                                             Build type: RelWithDebInfo                                                                                              LuaJIT 2.1.0-beta3                                                                                                      Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 -DNVIM_TS_HAS_SET_MATCH_LIMIT /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include                           Compiled by runneradmin@fv-az152-786                                                                                                                                                                                                            Features: -acl +iconv +tui                                                                                              See ":help feature-compile"                                                                                                                                                                                                                        system vimrc file: "$VIM\sysinit.vim"                                                                                  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"                                                                                                                                                                                        Run :checkhealth for more info                                                                                          Press ENTER or type command to continue         
````


nvim-qt is 2.16.1 (I do not know how to copy the content from the dialog)

**Comment by fekir** [comment]
As both on Debian and Windows I do not have any customization/user-provided configuration, what could I do to find the root cause?

**Comment by jgehrig** [comment]
> As you gave me links for Windows, I've tested it now on it:

Sorry, I saw the `mswin.vim` and (incorrectly) guessed Windows. Please feel free to test on your preferred platform...

You should be able to download MacOS/Linux binaries just as easily.

  - https://github.com/equalsraf/neovim-qt/actions/runs/1129608908
  - https://github.com/neovim/neovim/releases

When you select a context menu entry, it is equivalent to typing the following:
- Cut: `+x`
- Copy: `+y`
- Paste: `+gP`
- Select All: `:normal! ggVG`

If you're seeing any of these sequences, it suggests you're in `Insert` mode when the command executes. You need to be in `Normal` mode. On my machine, the `<Esc>` in the mapping prevents this from occurring.

---

Let's make sure we're both testing with the same environment from a clean state...

For setup:
1. Install the latest versions of `nvim` and `nvim-qt`
2. `nvim --version` should report `NVIM v0.6.0`
3. `nvim-qt --version` should report `NVIM-QT v0.2.17.9999`
4. Ensure there is no `~/config/nvim/init.vim` or `~/.config/nvim/ginit.vim` or `~/.vimrc`

Paste the following into `ginit.vim`:
```
nnoremap <silent><RightMouse> :call GuiShowContextMenu()<CR>
inoremap <silent><RightMouse> <Esc>:call GuiShowContextMenu()<CR>
vnoremap <silent><RightMouse> :call GuiShowContextMenu()<CR>gv
set mouse=a
```

Create a `minimal.vim` file:
```
{ Any config options we want to test go here }
```

For testing:
1. Run `nvim-qt -- -u minimal.vim`
2. { Do test steps here, describe, be explicit }

**Comment by jgehrig** [comment]
Does removing `source $VIMRUNTIME/mswin.vim` have any effect?

**Comment by fekir** [comment]
> Does removing source $VIMRUNTIME/mswin.vim have any effect?

Yes, commands work as expected, both on Windows and GNU/Linux.

**Comment by fekir** [comment]
1) nvim-qt -- -u minimal.vim
2) type some text
3) select text with the mouse
4) left click, select copy


if `minimal.vim` has `source $VIMRUNTIME/mswin.vim`, then `"+y` is inserted
if `minimal.vim` does not have `source $VIMRUNTIME/mswin.vim`, then it works as expected

**Comment by fekir** [comment]
From `source $VIMRUNTIME/mswin.vim`:

`noremap <C-A> gggH<C-O>G`

If I write some text, then do `gggH<C-O>G` for selecting everything, then left click, select copy -> `"+y` is inserted

**Comment by jgehrig** [comment]
Excellent! We're getting closer to understanding this issue...

Here is my `minimal.vim`:
```
nnoremap <silent><RightMouse> :call GuiShowContextMenu()<CR>
inoremap <silent><RightMouse> <Esc>:call GuiShowContextMenu()<CR>
vnoremap <silent><RightMouse> :call GuiShowContextMenu()<CR>gv
set mouse=a

source $VIMRUNTIME/mswin.vim
```

On my system:
- `Paste` works.
- `Copy`, `Cut`, and `Select All` DO NOT work. They insert the underlying command literally.

I will experiment with`mswin.vim`, we need to understand which options trigger this issue.

**Comment by jgehrig** [comment]
Here is an absolute minimal `minimal.vim`:
```
nnoremap <silent><RightMouse> :call GuiShowContextMenu()<CR>
inoremap <silent><RightMouse> <Esc>:call GuiShowContextMenu()<CR>
vnoremap <silent><RightMouse> :call GuiShowContextMenu()<CR>gv
set mouse=a

behave mswin
```

We'll need one of two solutions:
1. The ability to detect `behave mswin` and modify the commands accordingly.
2. Alternatives to commands like `"+y` that work in both modes.

**Comment by fekir** [comment]
I do not know what `behave mswin` does, but isn't 

````
nnoremap <silent><RightMouse> :call GuiShowContextMenu()<CR>
inoremap <silent><RightMouse> <Esc>:call GuiShowContextMenu()<CR>
vnoremap <silent><RightMouse> :call GuiShowContextMenu()<CR>gv
set mouse=a
````

more minimal?

The type in command mode `gggH<C-O>G` (which should select everything, at least it is how ctrl+A is defined in `mswin.vim
`) and select copy from the menu.

**Comment by fekir** [comment]
Which, correct me I'm wrong

* `gg`: go to begin of file
* `gH`: start select mode, which apparently is different from Visual mode
* <C-O>: switches to Visual mode for the duration of one command.
* `G`: go at end of file

thus at the end of the command the editor is in select mode

**Comment by fekir** [comment]
In fact, it can be simplified to:

Type in command mode `gH` (which enters in select mode) and select copy from the menu.

**Comment by jgehrig** [comment]
> I do not know what behave mswin does

`behave mswin` is the part of `$VIMRUNTIME/mswin.vim` that causes the issues.

It changes several options, the important one being how selection operates. See `:help behave`.

> Which, correct me if I'm wrong

You are correct!

Sorry, I did not understand your steps fully from the first post.

Two different paths to the same result...

> thus at the end of the command the editor is in select mode

Yes, I think this is the key issue here.

**Comment by jgehrig** [comment]
I'm not very familiar with this mode...

We'll need one of two solutions:
1. The ability to detect "selection mode" and modify the commands accordingly.
2. Alternatives to commands like "+y that work in all modes.

Code in question:
https://github.com/equalsraf/neovim-qt/blob/56ad7e54a27f1bed2fcbe9e3bf22f9394360c722/src/gui/contextmenu.cpp#L35-L53

**Comment by fekir** [comment]
For the record, I tried adding `snoremap <silent><RightMouse> <Esc>:call GuiShowContextMenu()<CR>`, but it does not make any difference

**Comment by jgehrig** [comment]
> snoremap <silent><RightMouse> <Esc>:call GuiShowContextMenu()<CR>

Conceptually that makes sense to me.

This code modification doesn't work either:
```
m_nvim->api0()->vim_command(R"(normal! <C-G>"+y)");
```

If you manually run the commands, `<C-G>` followed by `"+y` works.

However, I'm not sure how to programmatically accomplish this from the Neovim API.

**Comment by jgehrig** [comment]
Give this VimScript fix a try:
```
nnoremap <silent><RightMouse> :call GuiShowContextMenu()<CR>
inoremap <silent><RightMouse> <Esc>:call GuiShowContextMenu()<CR>
xnoremap <silent><RightMouse> :call GuiShowContextMenu()<CR>gv
snoremap <silent><RightMouse> <C-G>:call GuiShowContextMenu()<CR>gv
```

I suppose making this the new recommended configuration is a reasonable solution...

**Comment by fekir** [comment]
@jgehrig  ,your last VimScript seems to work correctly

**Comment by jgehrig** [comment]
@fekir

Thanks for the bug report and your assistance in debugging this issue!

I've merged a new recommended configuration into the README.
