### ISSUE TITLE
Change guitreeview size on opening?

### ISSUE THREAD

**Issue by qazip** [equalsraf/neovim-qt#927]
Is there a command I can coppy to ginit.vim to have GUITreeview a certain size? Something like:

`GUITreeview 10%`

**Comment by jgehrig** [comment]
@qazip 

Unfortunately, there is not way to set the `GuiTreeview` size on startup.

However, I plan on adding size "memory" to the panel on startup for #898 #866. On startup, the window size and panel size will be the same as the previous instance when it was closed. It is necessary to prevent startup flicker, and properly size split panes. No explicit configuration required.

Would that work well for your use case?

**Comment by qazip** [comment]
Yes, that would be great. Possibly even better for using the same config in different setups!

**Comment by jgehrig** [comment]
@qazip 

I'm marking this as closed by #939. The last-used width for the GuiTreeView should persist across sessions.

Let me know if you see any issues, or if there is a use-case that this solution does not adequately solve.
