### ISSUE TITLE
Thread panic when do  ":redir @+" in Windows OS.

### ISSUE THREAD

**Issue by zoumi** [equalsraf/neovim-qt#930]
OS: Windows 10 64bit
NVIM: NVIM v0.6.0-dev+218-g3f526feeb

Steps:
1,:redir @+
2,:version
3,:redir END

**Comment by zoumi** [comment]
![Snipaste_2021-09-09_09-03-51](https://user-images.githubusercontent.com/5162901/132605287-f0c66093-615d-49f3-86e0-fb23439c6cde.jpg)

**Comment by jgehrig** [comment]
Interesting bug!

It looks like this reproduces with Neovim too. It looks like they already have a bug filed to track the issue: https://github.com/neovim/neovim/issues/11053

From the callstack, it looks like the underlying issue might be in `win32yank.exe`. The issue looks like an unhandled exception from https://github.com/equalsraf/win32yank.

The Win32 error is `ERROR_CLIPBOARD_NOT_OPEN`:
https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--1300-1699-

It looks like this is related to threading and the way `redir` changes the `win32yank` call. I'll try to attach a debugger at some point...

Perhaps @equalsraf can provide some insight?

**Comment by jgehrig** [comment]
I'm going to mark this issue as Closed (Duplicate).

Your bug reports are appreciated! Don't hesitate to post more :)
