### ISSUE TITLE
Neovim-Qt has been submitted to Homebrew Core

### ISSUE THREAD

**Issue by gwerbin** [equalsraf/neovim-qt#933]
After who-knows-how-long, I've finally submitted Neovim-Qt to Homebrew Core: https://github.com/Homebrew/homebrew-core/pull/85526

This would obviate the need for a separate Homebrew "tap" (https://github.com/equalsraf/homebrew-neovim-qt), and would allow users to simply run `brew install neovim-qt`.

Version bumps would be submitted to Homebrew as PRs; there's a guide for doing so [here](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md#to-submit-a-version-upgrade-for-the-foo-formula). It mostly amounts to changing the SHA256 and the tarball URL, and then making a PR with a specific title and commit message.

Once this is accepted, it might make sense to start directing Mac Homebrew (and Linuxbrew) users to Homebrew instead of your Tap.

**Comment by jgehrig** [comment]
@gwerbin

Thanks this is AWESOME! :+1:  :tada:

We should update the README accordingly. I'm assuming we can just remove the two `$ brew tap equalsraf/neovim-qt` lines.

Does the following look correct to you? (Limited ability to test on MacOS)

---

MacOS
You can use HomeBrew to install Neovim Qt:

To install the latest release:
$ brew install neovim-qt

To install the latest development version:
$ brew install --HEAD neovim-qt

**Comment by gwerbin** [comment]
It has been accepted! 🎉 

The updated wording looks good. Feel free to change the README and delete/archive <https://github.com/equalsraf/homebrew-neovim-qt>.

Note that the `.app` bundle is *not* installed to `/Applications` or `~/Applications` because of limitations in how Brew works. You would need to distribute the pre-built app bundles somewhere (eg uploading it to Github for every release) in order to support that (as a "cask" instead of a "formula").

Now that some Macs are x86 and some are ARM, that might be trickier than in the past. Supporting only x86 is probably good enough for now, since M1 machines are still relatively uncommon.

**Comment by jgehrig** [comment]
Thanks again @gwerbin!

This will make it easier for MacOS users to install Neovim Qt. Most appreciated :+1:
