### ISSUE TITLE
Add support for emoji picker in macOS

### ISSUE THREAD

**Issue by ronisbr** [equalsraf/neovim-qt#943]
Hi!

In macOS, you can use CMD + CTRL + Space to open a nice dialog to pick emojis and symbols. Like this in iTerm2:

<img width="795" alt="Captura de Tela 2021-10-23 às 14 48 45" src="https://user-images.githubusercontent.com/1068295/138566618-c39a04bd-5e5a-43c9-bfb8-02ed7c2af0f0.png">

It would be very nice to have a similar functionality in neovim-qt for macOS.

**Comment by jgehrig** [comment]
While this would be a nice feature, I don't see a way to easily implement it.

We don't have a maintainable way to write MacOS-only code for such things. It looks like Qt does not support this dialog.

I'm going to close this issue as 'Won't Fix', unless someone can find a way to implement this in a Qt/cross-platform manner...
