### ISSUE TITLE
nvim-qt seems not load runtime 

### ISSUE THREAD

**Issue by mhusmann** [equalsraf/neovim-qt#949]
Running nvim-qt --version shows:

```console
{
NVIM-QT v0.2.16.1
Build type: Release
Compilation:-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wno-unused-parameter -std=c++11 -Wfatal-errors
Qt Version: 5.15.0
Environment: 
  nvim: nvim
  args: --cmd let &rtp.=',/usr/share/nvim-qt/runtime' --cmd set termguicolors
  runtime: /usr/share/nvim-qt/runtime

NVIM v0.5.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim/src/neovim-0.5.1/build/config -I/build/neovim/src/neovim-0.5.1/src -I/usr/include -I/build/neovim/src/neovim-0.5.1/build/src/nvim/auto -I/build/neovim/src/neovim-0.5.1/build/include
Übersetzt von builduser

Features: +acl +iconv +tui
See ":help feature-compile"

          System-vimrc-Datei: "$VIM/sysinit.vim"
     Voreinstellung für $VIM: "/usr/share/nvim"

Run :checkhealth for more info
}
```

The runtime under runtime: /usr/share/nvim-qt/runtime seems not to be active. I can't set the font by :GuiFont also there is no :help nvim_gui_shim available.

Any hint?

**Comment by jgehrig** [comment]
What is the output of `find  /usr/share/nvim-qt/runtime/`?

You should see something like:
```
/usr/share/nvim-qt/runtime/
/usr/share/nvim-qt/runtime/plugin
/usr/share/nvim-qt/runtime/plugin/nvim_gui_shim.vim
/usr/share/nvim-qt/runtime/doc
/usr/share/nvim-qt/runtime/doc/tags
/usr/share/nvim-qt/runtime/doc/nvim_gui_shim.txt
```

How did you install neovim-qt? Usually amissing `:GuiFont` is caused by a missing or incorrectly placed `nvim_gui_shim.vim`.

**Comment by mhusmann** [comment]
nvim-qt still does not load the runtime

**Comment by jgehrig** [comment]
Sorry for closing this. I didn't see a response, and this is usually a local configuration issue.

Did you try the above `find` command? What is the output?

How did you install `neovim-qt`?

**Comment by mhusmann** [comment]
Dear John,

I'm sure that it must be a configuration issue.
I installed neovim-qt with pacman (running arch linux). Unfortunately
without success. So I removed that and installed it with git from your
repo. The same issue makes no difference.

Running find /usr/share/nvim-qt shows:
/usr/share/nvim-qt
/usr/share/nvim-qt/runtime
/usr/share/nvim-qt/runtime/doc
/usr/share/nvim-qt/runtime/doc/nvim_gui_shim.txt
/usr/share/nvim-qt/runtime/doc/tags
/usr/share/nvim-qt/runtime/plugin
/usr/share/nvim-qt/runtime/plugin/nvim_gui_shim.vim
/usr/share/nvim-qt/runtime/README.md

So everything looks fine but it does not load the runtime.
Any hint would be helpful

Kind regards
Michael

Am Fr., 19. Nov. 2021 um 10:30 Uhr schrieb John Gehrig <
***@***.***>:

**Comment by mhusmann** [comment]
John,

I installed now the plugin directly:

"Alternatively, you can install the Neovim Qt plugin separately: Plugin
'equalsraf/neovim-gui-shim"

Now it works
Kind regards
Michael

Am Fr., 19. Nov. 2021 um 11:57 Uhr schrieb Michael Husmann <
***@***.***>:
