### ISSUE TITLE
Cannot Set Fallback Font Using `:set guifontwide`

### ISSUE THREAD

**Issue by Floaterest** [equalsraf/neovim-qt#950]
# Issue
I want to set a fallback font for non-latin languages (in my case, Japanese). I tried the suggested solution in #827 and #832, but it did not work (as shown in [demo](#demontration)):

# Steps to Reproduce
1. start nvim-qt with empty config: `nvim-qt -- -u NONE`
2. type something in English and in wide characters 
   ```
   This is an example in English
   これは日本語のサンプルです
   ```
3. call `:GuiFont! monospace` to set the font
4. call `:set gfw=Noto\ Sans\ JP` to set the font for wide characters

Result: nothing changes for the wide characters

# Demonstration
![gif](https://user-images.githubusercontent.com/56704092/144112820-f5230f42-7248-4fca-9843-cf6be297ace0.gif)

The gif above shows that
- I can
  - set a monospace font using `GuiFont`
  - set a CJK font using `GuiFont`
- But I cannot
  -  set a CJK font as a fallback font using `set guifontwide`

# Version
nvim-qt version: v0.2.16.1 (newest)
neovim version: 0.6.0 (newest)

**Comment by jgehrig** [comment]
@Floaterest 

The option `guifontwide` is not available in `v0.2.16.1`, you would need to update to a build from `master`.

I'm behind on doing a release...

Marking as closed. Feel free to keep commenting if you have questions.

**Comment by Floaterest** [comment]
Sorry, I didn't realise the releases by Github Actions.

**Comment by jgehrig** [comment]
No need to apologize! This was not obvious :)

I'm behind on generating a release (there are a few bugs I would like to address)....

I'm glad you found the AppVeyor builds. Builds are also available on GitHub Actions (Linux, Windows, Mac).

**Comment by bosbyj** [comment]
Someone from other corner of the world is also waiting for `:set guifontwide`
Greetings!

**Comment by Floaterest** [comment]
@bosbyj no need to wait, you can find the newest build on AppVeyor (details instructions are on the [wiki](https://github.com/equalsraf/neovim-qt/wiki/Windows-AppVeyor-Builds) from this repo)
