### ISSUE TITLE
Please Create a new Release, or I should to build it use the lastest source code with Qt environment.

### ISSUE THREAD

**Issue by VimIcewind** [equalsraf/neovim-qt#952]

**Comment by bosbyj** [comment]
Please check this link
https://github.com/equalsraf/neovim-qt/wiki/Windows-AppVeyor-Builds

**Comment by jgehrig** [comment]
Sorry, life is crazy right now... Yes, a release is on my TODO list. However, there are a few minor issues that should be fixed first.

You can also find the latest builds for any platform on GitHub Actions:
https://github.com/equalsraf/neovim-qt/actions/runs/1423736936
