### ISSUE TITLE
Support winkey mappings in windows env

### ISSUE THREAD

**Issue by eyalk11** [equalsraf/neovim-qt#953]
Hi,

`nvim qt` doesn't recognize  winkey mapping at all.  . They don't appear when doing `<c-v>` in insert mode , and `<D-key>` mappings don't work.

I admit that many of the mapping are occupied by the OS. However, there seem to be several free mapping. 

Thanks!

**Comment by jgehrig** [comment]
> I admit that many of the mapping are occupied by the OS. However, there seem to be several free mapping.

I am guessing this is the issue... Windows doesn't usually pass these occupied key event to the application layer.

To debug and fix this, I will need some diagnostic data.

For instructions, see: https://github.com/equalsraf/neovim-qt/issues/181#issuecomment-990296513

On Windows, you'll need an additional step:
https://github.com/equalsraf/neovim-qt/wiki#i-cant-see-debug-messages-in-windows
```
set NVIM_QT_LOG=log.txt
nvim-qt
```
