### ISSUE TITLE
[Question] neovim-qt frameless

### ISSUE THREAD

**Issue by yyancy** [equalsraf/neovim-qt#954]
Hi, I want to know if there is a way to make neovim-qt frameless. 
Thanks.

**Comment by jgehrig** [comment]
Are you looking for something like `:call GuiWindowMaximized(1)`.

Or are you looking for a non-maximized window without the border/frame?

If you can put together a PR for this, I am willing to review and merge. See the implementation of `GuiWindowMaximized` in `/src/gui/runtime/plugin/nvim_gui_shim.vim`.

That would need to call a new function in `src/gui/mainwindow.cpp`, which sets and un-sets the flag `Qt::FramelessWindowHint`.

See:
https://doc.qt.io/qt-5/qwindow.html#setFlag
https://doc.qt.io/qt-5/qt.html#WindowType-enum

**Comment by yyancy** [comment]
Thanks for your reply, I will give it a try!

**Comment by khalidchawtany** [comment]
I am using this patch https://github.com/khalidchawtany/neovim-qt/commit/a99fa3cb392e327b27d15220b5e6bc7cec9a4728 to allow FrameLess windows in macOS. It works great. Everything works from dragging to resizing etc. 

![2020-01-28 09 45 00](https://user-images.githubusercontent.com/1681606/73241465-1f66be80-41b3-11ea-937a-35e49f527a68.gif)

**Comment by yyancy** [comment]
Thanks your advice. but I I'm not very good at C++，so I may not be able to implement it.
