### ISSUE TITLE
Feature: Allow click-and-drag to arrange tabs

### ISSUE THREAD

**Issue by joeljose350** [equalsraf/neovim-qt#955]
### Feature description

Allow the user to click and drag tabs to arrange them in the GUI client of Neovim.

### Information

- Neovim: v0.6.0
- OS: Windows 11 Home

**Comment by jgehrig** [comment]
Tab order is controlled by Neovim. We don't have the ability to control tab ordering in the GUI.

Arguably the feature could be supported with Neovim's `ext_multigrid`:
https://neovim.io/doc/user/ui.html#ui-multigrid

However, I don't have any immediate plans to add `ext_multigrid` support...
