### ISSUE TITLE
Feature: Open files in new tab when neovim-qt is already open

### ISSUE THREAD

**Issue by joeljose350** [equalsraf/neovim-qt#956]
### Feature description

When a file is opened with another file already open with neovim-qt, the second file is opened in a new instance of neovim-qt. Opening multiple files with neovim-qt will result in the creation of multiple windows which can be difficult to manage. Opening those files as separate tabs in the same instance will make them easier to manage.

### Information

- Neovim: v0.6.0
- OS: Windows 11 Home

**Comment by jgehrig** [comment]
You can achieve this behavior with `nvr`: https://github.com/mhinz/neovim-remote.

```
NVIM_LISTEN_ADDRESS=/tmp/nvimsocket nvim-qt
nvr file1.txt
nvr file2.txt
```

I'd like to avoid duplicated effort, so I'm going to mark this as "Won't Fix".

Feel free to keep commenting if you have questions about `nvr`.
