### ISSUE TITLE
Color emojis are not rendered correctly

### ISSUE THREAD

**Issue by bugnano** [equalsraf/neovim-qt#958]
I'm using color emojis to provide easy to follow debug information to my programs.
To be more specific, I'm using the same emoji but with different colors (📕, 📙, 📗, 📘).

With GVIM, if I insert a color emoji in my source file, it's rendered with the correct color, so I can distinguish the emojis while I'm editing the source code.

With Neovim Qt the color emojis are rendered without color, so I can't distinguish the emojis while editing the code, and that's very annoying.

In the attached screenshot you can see what I mean by that.

![screenshot](https://user-images.githubusercontent.com/299634/149343499-3fab8255-ffb1-42a5-a065-d20bc61db129.png)

By the way, I'm using the standard FreeMono font that you find in all the Linux distros, and I understand that Neovim Qt renders the emojis with the FreeMono font that I selected in my ginit.vim file. However I think that color emojis should be an exception to the font that I selected in my ginit.vim file, and use the OS provided font for color emojis instead.

**Comment by jgehrig** [comment]
Interesting, on my system (Linux running a build from master) I can't even get these emojis to render. I've tried a few different fonts. I either get a blank spaces, or `(closed_book, orange_book, green_book, blue_book).`

> By the way, I'm using the standard FreeMono font that you find in all the Linux distros, and I understand that Neovim Qt renders the emojis with the FreeMono font that I selected in my ginit.vim file. However I think that color emojis should be an exception to the font that I selected in my ginit.vim file, and use the OS provided font for color emojis instead.

I am not aware of  a "system default" emoji font that we can access through Qt.

Fortunately, Vim provides an option for this scenario. Check out `:help guifontwide`, you should be able to set an alternative font list for use with emoji and CJK characters.

Example: `:set guifontwide=Noto\ Color\ Emoji:h11`.

**Comment by bugnano** [comment]
Nope, setting guifontwide didn't change anything unfortunately.

**Comment by jgehrig** [comment]
@bugnano 

More details required :)

Please try the latest build:
https://github.com/equalsraf/neovim-qt/actions/runs/1423736936

The option should impact the rendering of all wide characters, so you could also test it with Chinese (CJK) characters. The option is only available in recent builds, your version may not support `guifontwide`.

I'd also recommend checking `nvim-qt --version` to ensure your copy of neovim-qt is built with a recent version of Qt. Qt has improved their emoji rendering in recent builds (> 5.12 ?), and some issues like this were fixed library-side.

**Comment by bugnano** [comment]
The latest build works like a charm, thank you 😀

**Comment by jgehrig** [comment]
Excellent! :)

Closing this issue.
