### ISSUE TITLE
Focus events are not triggered

### ISSUE THREAD

**Issue by mschulkind** [equalsraf/neovim-qt#96]
Events like `FocusGained` are not triggered when the window regains focus. 

This is a show stopper for me personally because this means that `autoread` does not work, as it is normally triggered by focus events.

**Comment by equalsraf** [comment]
@mschulkind, thanks for pointing those out, completely missed them. The changes in #97 should add support for both events.

**Comment by mschulkind** [comment]
now that's service :)

**Comment by equalsraf** [comment]
Let me know if it works ok. I can't merge right away, but it looks simple enough to be merged later.
