### ISSUE TITLE
[Misc]: I just want to say thanks!

### ISSUE THREAD

**Issue by MIvanchev** [equalsraf/neovim-qt#961]
I'm just dropping by to express my very sincere gratitude for neovim-qt. It's works great on Windows and Linux, great performance, very responsive and friendly dev team and I really appreciate we get neovim-qt (and neovim and all the plugins of course) for free. Thanks, your work is greatly appreciated!

**Comment by equalsraf** [comment]
All credit goes to @jgehrig. Do buy him a beer if you get a chance.

**Comment by MIvanchev** [comment]
If I knew how would definitely do it!!!
