### ISSUE TITLE
Launch in diff mode

### ISSUE THREAD

**Issue by augustebaum** [equalsraf/neovim-qt#965]
I'd like to open files in diff mode. With nvim I can use the `-d` flag, but with nvim-qt the flag is not recognised. From the help message for nvim-qt it seems that it's possible to pass arguments down to nvim, but I don't see how to do that.

Is anyone able to help me with this?

Loving nvim-qt apart from that. Thanks!

**Comment by equalsraf** [comment]
Do you mean something like this

```
 nvim-qt -- -d /tmp/a /tmp/b
```

Positional arguments after `--` are passed straight to nvim.

**Comment by augustebaum** [comment]
Wonderful, thanks! Even after looking at the help again, it took me a while to figure out that this is what `[-- ...]` meant.
I think perhaps I would have used `--nvim` to do what `--` does, and the path option would be given through a `--path` flag instead.
Thanks again!
