### ISSUE TITLE
Transparency

### ISSUE THREAD

**Issue by lilheart** [equalsraf/neovim-qt#974]
How do I make neovim transparent  in windows? I've added this to my init.lua but it just makes the background pure black
highlight Normal ctermbg=none
highlight NonText ctermbg=none

**Comment by jgehrig** [comment]
@lilheart 

Unfortunately, `none` does not have the effect you're looking for. It causes the background color to render as the default background color.

You could try `:GuiWindowOpacity 0.X`, but that is not exactly the same as what you're looking for. That will make the entire window transparent. You will also need a recent build, https://github.com/equalsraf/neovim-qt/suites/5690080170/artifacts/187160467.

There is an outstanding Feature Request for this, #815.
