### ISSUE TITLE
:GuiNewWindow on Linux

### ISSUE THREAD

**Issue by jonathantorres** [equalsraf/neovim-qt#975]
Thanks for creating this GUI, it looks fantastic!

I'm currently using a Debian machine, and I don't see the command :GuiNewWindow. 

Is this command supported on Linux? Is there a technical reason as to why? If not, I can step in to help include it.

**Comment by jgehrig** [comment]
Thanks for the kind words! Yes, Linux is supported :)

What build/version are you running?

I'd guess you're not running a recent enough version of neovim-qt. That command is not yet included in any of our releases. You will need to find a build from a recent commit.

Here is an AppImage for Linux:
https://github.com/equalsraf/neovim-qt/actions/runs/1995530020
https://github.com/equalsraf/neovim-qt/suites/5690080170/artifacts/187160465

Marking as closed. Feel free to keep commenting, and I will help get this working.

**Comment by jonathantorres** [comment]
I'm running 0.2.16-1 it's the version that comes with Debian 11.2 (bullseye)

I'll install one of the updated builds that you provided. Thanks!
