### ISSUE TITLE
Input is Laggy on Windows

### ISSUE THREAD

**Issue by zovt** [equalsraf/neovim-qt#98]
Basically what the title says. The UI is not as smooth as gVim.

**Comment by equalsraf** [comment]
Can you provide some more details. Are there any operations that are specially slow. Windows version, graphics card?

If you have the chance, can you test against this build? https://ci.appveyor.com/project/equalsraf/neovim-qt/build/504/artifacts - (just for speed, I'm sure there are other bugs in there).

**Comment by zovt** [comment]
Sure, Windows 10 pro with a GTX 970, so specs shouldn't be the issue. Specifically, while typing it feels like there is a noticeable delay between when I press a key and when the letter appears in the buffer, especially when typing quickly. Also, when, for example, holding 'j', the cursor moves in a choppy fashion, unlike in gVim. I'll give the new build a shot and report back.

**Comment by zovt** [comment]
Just tested with the newer build. Feels _slightly_ better, but could be just a placebo and is still not very smooth.

**Comment by zovt** [comment]
I looked through the code and since I'm not very well-versed in Qt I didn't see anything blatantly obvious. However, to me it feels like the window is only repainting after a set interval, since the cursor (when holding j or k) moves what looks like a fixed number of lines. Not sure if you can force Qt to redraw faster, but I think you can call update() on a QWidget to have the widget update itself. If I had a build env set up I would try adding a QWidget::update() call after every event sent to or received from neovim.

This is all in theory of course. If you implement this and rebuild it I'll give it a shot and let you know how it goes

**Comment by equalsraf** [comment]
> If I had a build env set up I would try adding a QWidget::update() (EDIT: and maybe QCoreApplication::processEvents) call after every event sent to or received from neovim.

In practice this is what happens already for most events (exception made to resizes):

1. e.g you press a key
2. A call is made to Neovim passing the input forward
3. We get a notification from Neovim with the screen updates
4. We update the window contents and make one (or more) call to update()
5. The Qt event loop sees the update() events and calls paintEvent() to update the screen contents.

**Comment by zovt** [comment]
Yeah I figured something like that would happen automatically. Nevertheless, the problem still persists.

**Comment by equalsraf** [comment]
Part of the problem is that its hard to get consistent results. For me the performance is not that much different from GVim on windows (but both seem slow when compared with Linux).

How about this one, does it make a difference? https://ci.appveyor.com/project/equalsraf/neovim-qt/build/525/artifacts

**Comment by zovt** [comment]
Bingo! That looks much smoother now.

**Comment by zovt** [comment]
Just out of curiosity, what do you think fixed it?

**Comment by equalsraf** [comment]
> Just out of curiosity, what do you think fixed it?

Errr, I just changed the automated builds in Appveyor to use Qt 5.5 (previously using 5.4) and MinGW instead of MSVC. Its possible 5.5 does have significant performance improvements. Its unclear to me which backend is used for MinGW (but I think its OpenGL as well).

**Comment by equalsraf** [comment]
Ok one last check to clear this up and then we should be able to close this, can you try this one?

https://ci.appveyor.com/project/equalsraf/neovim-qt/build/job/cnjvwa4renrich6h/artifacts

**Comment by zovt** [comment]
Sorry, I'm not seeing an artifacts tab like on the last one to download the zip

**Comment by zovt** [comment]
Everything is still smooth. I'll close this now

**Comment by equalsraf** [comment]
Ok, then its a consequence of Qt 5.5. I'll merge this now.

**Comment by justinmk** [comment]
**Wow**. The improvement is incredible. Thank you @equalsraf !

**Comment by brcolow** [comment]
Yes...with the new build my Neovim-QT on Windows 7 feels as fast as any vim (be it in a terminal emulator on nix, or Windows, or gvim) I've dealt with. Great work.
