### ISSUE TITLE
Create a package for Guix

### ISSUE THREAD

**Issue by cassio-tav** [equalsraf/neovim-qt#980]
### Problem

There is no viable way to install `neovim-qt` in Guix. It can't be simply built manually, because Guix configuration is declarative (similar to NixOS, but easier because done in Guile Scheme) — if one would try that, the next time they ran `guix home reconfigure /path/to/config.scm` to update their user's environment, their installation could be broken. And even if it didn't, no one would go to the trouble of having a declarative-configuration (functional) OS just to then renounce its consistency and reprodutibilty features.

Unfortunately, I do not have the technical knowledge to package anything myself — I'm just a teacher in the humanities  (I would do it if I could)…

### Solution

Well, you guys will know better than me how to solve this issue… (sorry)  :(

**Comment by jgehrig** [comment]
The best place to get that issue resolved is with your distro. You need the maintainers to create a package.

I'd guess you want to file a bug here:
https://issues.guix.gnu.org/

In the meantime, you can consume our AppImage. Our CI builds binaries for every commit on Windows/Mac/Linux.

Here is the latest Linux AppImage at the time of writing:
https://github.com/equalsraf/neovim-qt/suites/5980912193/artifacts/205950506
https://github.com/equalsraf/neovim-qt/actions/runs/2112528016

Marking as closed. Feel free to keep commenting if you need further help.

**Comment by equalsraf** [comment]
This is as far as I got. The tests are disabled in this recipe because tests involving the clipboard could not work in the build environment. Not sure how to solve that one, maybe best to skip the one failing test instead.

```
(define-module (gnu packages neovim-qt)
  #:use-module ((guix licenses) #:prefix license:)
  #:use-module (guix utils)
  #:use-module (guix download)
  #:use-module (guix packages)
  #:use-module (guix build-system cmake)
  #:use-module (gnu packages qt)
  #:use-module (gnu packages serialization)
  #:use-module (gnu packages vim)
  )

(define-public neovim-qt
    (package
      (name "neovim-qt")
      (version "0.2.17")
      (source (origin
                (method url-fetch)
                (uri "https://github.com/equalsraf/neovim-qt/archive/refs/tags/v0.2.17.tar.gz")
                (sha256
                 (base32
                  "18fdmar6b2d6rmzlcxm6iq96g3j29pxzl4rwak82smv3blp8qlxc"))))
      (build-system cmake-build-system)
      (arguments
	`(#:configure-flags '("-DUSE_SYSTEM_MSGPACK=1")
	  #:tests? #f
	  #:phases
           (modify-phases %standard-phases
             (add-before 'check 'check-setup
               (lambda _
                 ;; make Qt render "offscreen", required for tests
                 (setenv "QT_QPA_PLATFORM" "offscreen")
                 #t)))))
      (inputs
	(list qtbase-5 qtsvg msgpack neovim qtx11extras))
      
      (home-page "https://github.com/equalsraf/neovim-qt/")
      (synopsis "Qt GUI for neovim")
      (description "GUI frontend for the Neovim editor")
      (license license:isc)))

neovim-qt

```

**Comment by kkremitzki** [comment]
I've submitted a package: https://issues.guix.gnu.org/78362
