### ISSUE TITLE
Can't set negative linespace

### ISSUE THREAD

**Issue by damanis** [equalsraf/neovim-qt#981]
The commit 2c3c7c29 made impossible to set negative linespace.
Seems, there is no reason to prevent negative value, 'GuiLinespace -1' works properly (after disable checking in code).

**Comment by jgehrig** [comment]
@damanis

Good catch! I (incorrectly) assumed a negative linespace value was invalid. Based on the docs, it is an expected case that we should handle.

From `:help linespace`:
```
'linespace' 'lsp'	number	(default 0)
			global
			{only in the GUI}
	Number of pixel lines inserted between characters.  Useful if the font
	uses the full character cell height, making lines touch each other.
	When non-zero there is room for underlining.
	With some fonts there can be too much room between lines (to have
	space for ascents and descents).  Then it makes sense to set
	'linespace' to a negative value.  This may cause display problems
	though!
```

I'll put together a fix.

**Comment by jgehrig** [comment]
Merged. This issue should be fixed, marking as Closed.
