### ISSUE TITLE
Ability to disable buffers in GuiTabline

### ISSUE THREAD

**Issue by harjotgill** [equalsraf/neovim-qt#982]
Looks like a change was merged a while back to enable buffers in Tabline. It would be nice to have an option to disable buffers and switch to Tabs only setting. 
For some people (like me) buffers are just too noisy of an abstraction to show up in the tab line. There are better ways to switch buffers than to pollute the tabline by default -- key mappings, fzf and so on.

**Comment by jgehrig** [comment]
I hear what you're saying... We should provide an option of some kind.

However, I also feel strongly that the 'out-of-the-box' behavior should be roughly what you find today in master.

Most users expect the `:GuiTabline` feature to display their buffers as gui-tabs and are frustrated when they are unable to achieve this behavior. The vast majority simply disable GuiTabline, and use a TUI plugin such as vim-airline. We get lots of bugs filed for this reason.

Let's brainstorm a solution! What behavior are you looking for? How would you like a configuration option to behave?

Do you want the behavior before #739 back? Ex `:GuiTabline 1` that displays tabs (the vim concept) graphically but not buffers.

Related: #973

**Comment by harjotgill** [comment]
Thanks for your prompt response. 
Another UX datapoint is to look at how VimR treats tabs/buffers on macOS. Attaching screenshot from VimR, the tabline shows tabs and buffers are available as part of drawer style tools. 

On the other hand, I believe the default behavior of showing buffers is also acceptable as long as there is an option to disable buffers in tabline, just like vim-airline has done it. 

<img width="257" alt="Screen Shot 2022-04-30 at 10 53 00 PM" src="https://user-images.githubusercontent.com/18579817/166134103-b18a8af1-b342-48d3-aa1d-0ccd0116afed.png">
