### ISSUE TITLE
Generate Neovim-Qt Release

### ISSUE THREAD

**Issue by jgehrig** [equalsraf/neovim-qt#988]
Hey @equalsraf 

I think it is time for a new release... What do you think?

We've got lots of fixes and features present in `master` that are not available in the latest version. We may also get less issues filed if we update the bundled-with-Neovim version.

While there are some things I would have liked to address before the next release, time is limited right now. The code is reasonably stable, and I am not aware of any major bugs... Good enough!

Should we do a `0.2.17` release? Can you walk me though the process?

Should we stage a preliminary release before officially deploying the `0.2.17` release?

Thanks!

**Comment by gregflynn** [comment]
I spent an hour debugging why settings on the wiki didn't exist in my install. Turns out the commit to add those settings was pushed 2 years ago but 3 months after the current release so thus not in my package on Arch.

Either ship a release or update the README to instruct folks that the project should be built from source.

Or defer folks to [neovide](https://github.com/neovide/neovide)

(For reference, [the commit](https://github.com/equalsraf/neovim-qt/commit/05885bad617fcd9b9c9ef3c72069b497b0b28592))

**Comment by jgehrig** [comment]
> Either ship a release or update the README to instruct folks that the project should be built from source.

Well... That's why this issue is open :)

Yes, we will try to put out a release shortly. Sorry for the aggravation, hopefully we can get a more regular release schedule going in the future!

**Comment by gregflynn** [comment]
> > Either ship a release or update the README to instruct folks that the project should be built from source.
> 
> Well... That's why this issue is open :)
> 
> Yes, we will try to put out a release shortly. Sorry for the aggravation, hopefully we can get a more regular release schedule going in the future!

Absolutely, just wanted to throw my 2 cents in from the perspective that the Wiki's docs have outpaced the release cadence and that creates a less than desirable user experience

**Comment by equalsraf** [comment]
Its been a while, it should be enough to tag the version and change the source where needed.

For testing the staging tag also generates a release.

The windows build comes from appveyor but the build is failing ATM https://ci.appveyor.com/project/equalsraf/neovim-qt/builds/43830538/job/wuq74kfn0rqsi9h9

**Comment by equalsraf** [comment]
A staging release is now available under the releases page

https://github.com/equalsraf/neovim-qt/releases

I'll test this tomorrow, and if there are no issues with the artifacts, that will be tagged as v0.2.17

**Comment by equalsraf** [comment]
Looks good here, I'll be tagging shortly, just grabbing some release notes.

**Comment by equalsraf** [comment]
Release is up, happy sunday everyone.
