### ISSUE TITLE
Popups on Startup are Not Shown

### ISSUE THREAD

**Issue by zovt** [equalsraf/neovim-qt#99]
This can be seen when adding a new plugin with NeoBundle, which on gVim presents a popup on startup when detecting a new plugin to install

**Comment by equalsraf** [comment]
I don't think there is an API in Neovim for this yet. The support for popup dialogs was likely removed along with the GUI code. Likely will have to wait before some other fixes upstream before we can have this.

The other alternative would be to have something like a Vim plugin that intercepts the error messages and forwards them to the GUI.

**Comment by zovt** [comment]
Gotcha, thanks. Maybe I will open an issue on the Neobundle repo about this
