### ISSUE TITLE
Small icons when using nerd font with guifontwide

### ISSUE THREAD

**Issue by vanarok** [equalsraf/neovim-qt#995]
Is it possible to achieve the same enlargement of icons as in neovide?

**Nvim-qt**
![2022-06-15T15:39:41,269809126+04:00](https://user-images.githubusercontent.com/6105977/173818735-6d0dc585-6867-4ab1-83fd-f3482e2e0f9e.png)
![2022-06-15T15:39:04,252242717+04:00](https://user-images.githubusercontent.com/6105977/173818740-ec276deb-9be6-45e8-8aec-8883c41d3b38.png)

**Neovide**
![2022-06-15T15:32:34,360330606+04:00](https://user-images.githubusercontent.com/6105977/173818742-93e95be2-2be9-403d-8982-7f53f8fb5860.png)
![2022-06-15T15:32:09,909238728+04:00](https://user-images.githubusercontent.com/6105977/173818744-1813d172-39c8-4445-9027-66a2767650c4.png)

**Comment by jgehrig** [comment]
@vanarok 

The `guifontwide` option is also available in neovim-qt, but you will need to either grab a nightly image from the CI or wait for the upcoming 0.2.17 release.

`:set guifontwide=...`

Here is the latest CI image:
https://github.com/equalsraf/neovim-qt/actions/runs/2462609650

**Comment by vanarok** [comment]
I tried the CI version and it still doesn't work like it should.

**Comment by jgehrig** [comment]
> I tried the CI version and that doesn't work as well.

Can you be more specific?

If something isn't working as expected, I am happy to help fix it.

Here is an example of `guifontwide` on my machine:
![image](https://user-images.githubusercontent.com/11207308/174485105-7c8442b1-f4d7-42a9-8f05-bed1b836219e.png)
![image](https://user-images.githubusercontent.com/11207308/174485123-7ddc3b48-7312-4959-8b6d-c9cc4a202476.png)

`:set guifontwide=Noto\ Color\ Emoji:h12`

**Comment by vanarok** [comment]
![2022-06-19T19:49:14,292051782+04:00](https://user-images.githubusercontent.com/6105977/174489490-7e4098ca-db67-4696-ab75-91980b7d98c9.png)
I think I figured out what the problem is. It seems that the existing characters are not reassigned to the wide font. Other programs: kitty terminal, neovide, goneovim solve this problem in their own way.  They provide the ability to reassign individual unicodes or set a range of unicode icons to reassign from a backup font. But I haven't found how neovovim-qt solves this.
